import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

// Applied only by the desktop editor; phone and native picker styles stay independent.
export const desktopModelOptions = stylex.create({
  dropdownOptions: { height: 'auto', flex: '0 1 auto', minHeight: 0 },
  dropdownChoices: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,minmax(0,1fr))',
    alignContent: 'start',
    alignItems: 'start',
    gap: 6,
    flex: '0 1 auto',
    minHeight: 40,
    maxHeight: 224,
  },
  dropdownGroup: {
    marginBottom: { default: 0, '@media (min-width: 1024px)': 0 },
    borderRadius: 10,
    backgroundColor: colors.stripe,
  },
  dropdownExpandedGroup: { gridColumn: '1 / -1' },
  dropdownChildren: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,minmax(0,1fr))',
    gap: 4,
    paddingTop: 4,
    paddingInline: 8,
    paddingBottom: 8,
  },
  dropdownRow: { minHeight: { default: 40, '@media (min-width: 1024px)': 40 } },
  dropdownChild: { minHeight: { default: 36, '@media (min-width: 1024px)': 36 } },
  dropdownExtras: {
    width: 'min(340px, 100%)',
    alignSelf: 'center',
    flexShrink: 1,
    minHeight: 40,
    maxHeight: 'min(192px, calc(var(--filter-height, 600px) - 128px))',
  },
  dropdownSummary: { minHeight: 40 },
  dropdownFields: { gap: 8, paddingTop: 8, paddingBottom: 8 },
  dropdownEmpty: {
    gridColumn: '1 / -1',
    margin: 0,
    padding: '16px 12px',
    fontSize: 14,
    lineHeight: '22px',
  },
  dropdownExclude: { minHeight: 40, fontSize: 14, lineHeight: '22px' },
  dropdownVariant: {
    minHeight: 40,
    paddingBlock: 8,
    borderRadius: 10,
    fontSize: 14,
    lineHeight: '22px',
  },
  group: { borderBottomWidth: 0, marginBottom: { default: 0, '@media (min-width: 1024px)': 4 } },
  choice: {
    minHeight: { default: 48, '@media (min-width: 1024px)': 54 },
    paddingInline: { default: 8, '@media (min-width: 1024px)': 12 },
    gap: { default: 4, '@media (min-width: 1024px)': 8 },
    borderRadius: 10,
    fontSize: { default: 16, '@media (min-width: 1024px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '22px' },
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.stripe,
      ':active': colors.controlSurface,
    },
  },
  selected: {
    backgroundColor: { default: colors.controlSurface, ':hover': colors.controlSurface },
  },
  childChoice: { paddingLeft: { default: 24, '@media (min-width: 1024px)': 32 } },
  checkTarget: {
    order: -1,
    width: { default: 32, '@media (min-width: 1024px)': 24 },
    minHeight: { default: 48, '@media (min-width: 1024px)': 54 },
  },
  checkbox: {
    width: { default: 20, '@media (min-width: 1024px)': 18 },
    height: { default: 20, '@media (min-width: 1024px)': 18 },
    borderColor: { default: colors.muted, ':checked': colors.text },
    backgroundColor: { default: colors.background, ':checked': colors.text },
  },
  mixed: { borderColor: colors.text, backgroundColor: colors.text },
  familyRow: {
    paddingInline: { default: 8, '@media (min-width: 1024px)': 12 },
    gap: { default: 4, '@media (min-width: 1024px)': 8 },
    minHeight: { default: 48, '@media (min-width: 1024px)': 54 },
    borderRadius: 10,
    backgroundColor: { default: 'transparent', ':hover': colors.stripe },
  },
  familyButton: {
    minHeight: { default: 48, '@media (min-width: 1024px)': 54 },
    paddingLeft: 0,
    paddingRight: 8,
    fontSize: { default: 16, '@media (min-width: 1024px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '22px' },
  },
  extras: { marginTop: 8, borderTopWidth: 0, maxHeight: '72%' },
  summary: {
    position: 'sticky',
    top: 0,
    zIndex: 1,
    minHeight: 48,
    fontSize: { default: 16, '@media (min-width: 1024px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '22px' },
    borderRadius: 10,
    backgroundColor: { default: colors.stripe, ':active': colors.controlSurface },
  },
  optionFields: { paddingTop: 12 },
  excludeRow: { fontSize: 16, lineHeight: '24px' },
});
