import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';
export const pickerStyles = stylex.create({
  embedded: { display: 'flex', flexDirection: 'column', flex: '1', minHeight: 0, minWidth: 0 },
  embeddedInput: {
    fontSize: 16,
    lineHeight: '24px',
    height: { default: 'auto', '@media (max-width: 699px)': 44 },
    minHeight: { default: 48, '@media (max-width: 699px)': 44 },
    paddingBlock: { default: null, '@media (max-width: 699px)': 8 },
    borderRadius: 12,
    borderColor: colors.line,
  },
  embeddedSearchBox: { marginTop: 12, marginBottom: 8 },
  embeddedSearch: { paddingLeft: 40, backgroundColor: colors.controlSurface },
  searchIcon: {
    position: 'absolute',
    left: 12,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    color: colors.muted,
  },
  embeddedClear: {
    width: { default: 48, '@media (max-width: 699px)': 44 },
    height: { default: 48, '@media (max-width: 699px)': 44 },
    top: '50%',
    transform: 'translateY(-50%)',
  },
  embeddedList: {
    marginInline: 0,
    paddingInline: 16,
    paddingBottom: 12,
    scrollbarWidth: 'thin',
    scrollbarGutter: 'stable',
  },
  embeddedMake: {
    minHeight: 56,
    paddingLeft: 8,
    paddingRight: 12,
    gap: 12,
    borderWidth: 0,
    borderBottomWidth: 0,
    minWidth: 0,
    flex: '1',
    backgroundColor: {
      default: colors.background,
      '@media (min-width: 700px)': { default: colors.background, ':hover': colors.stripe },
      ':active': colors.controlSurface,
    },
    borderRadius: { default: 0, '@media (min-width: 700px)': 8 },
  },
  makeOption: {
    display: 'flex',
    alignItems: 'center',
    borderBottomWidth: { default: 0, '@media (min-width: 700px)': 1 },
    borderBottomStyle: 'solid',
    borderBottomColor: colors.stripe,
  },
  allMakes: {
    minHeight: { default: 52, '@media (max-width: 699px)': 44 },
    marginBottom: { default: 8, '@media (max-width: 699px)': 4 },
    paddingLeft: 8,
    paddingRight: 12,
    borderRadius: 10,
    backgroundColor: { default: 'transparent', ':active': colors.controlSurface },
    fontSize: 16,
    fontWeight: 400,
  },
  selectionMark: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: colors.muted,
    borderRadius: '50%',
    backgroundColor: 'transparent',
    color: '#fff',
    flexShrink: 0,
  },
  selectedMark: { borderColor: colors.accent, backgroundColor: colors.accent },
  makeTrailing: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    flexShrink: 0,
  },
  makeName: { flex: '1', minWidth: 0 },
  optionCopy: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    flex: '1',
    overflowWrap: 'anywhere',
  },
  allMakesCopy: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'baseline', gap: 6 },
  selectionSummary: { fontSize: 14, lineHeight: '20px', fontWeight: 400, color: colors.muted },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 64,
    paddingInline: 16,
    paddingTop: 16,
    flexShrink: 0,
  },
  title: {
    fontFamily: 'var(--font-base)',
    fontSize: 20,
    lineHeight: '28px',
    fontWeight: 700,
    flex: '1',
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  toggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: colors.muted,
    fontSize: 12,
    lineHeight: '20px',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  switch: {
    width: 52,
    height: 32,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: '#818592',
    borderRadius: 20,
    padding: 5,
    display: 'flex',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  switchOn: {
    justifyContent: 'flex-end',
    borderColor: colors.deepPurple,
    backgroundColor: colors.deepPurple,
    padding: 3,
  },
  dot: { width: 16, height: 16, borderRadius: '50%', backgroundColor: '#818592' },
  dotOn: { width: 24, height: 24, backgroundColor: '#fff' },
  searchBox: {
    position: 'relative',
    marginInline: 16,
    marginTop: 16,
    marginBottom: 8,
    flexShrink: 0,
  },
  modelSearch: { marginTop: 24, marginBottom: 4 },
  search: {
    height: 44,
    width: '100%',
    fontSize: 14,
    lineHeight: '20px',
    fontWeight: 400,
    paddingRight: 40,
    '::placeholder': { color: colors.muted, opacity: 1 },
    outlineStyle: 'none',
    borderColor: { default: '#818592', ':focus': colors.deepPurple },
  },
  clear: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 44,
    height: 44,
    borderWidth: 0,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.text,
  },
  viewport: { position: 'relative', flex: '1', minHeight: 0 },
  list: {
    height: '100%',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarWidth: 'none',
    position: 'relative',
  },
  makeList: { marginInline: 16, paddingRight: 8 },
  mixed: {
    borderColor: colors.deepPurple,
    backgroundColor: colors.deepPurple,
    backgroundImage: 'linear-gradient(white,white)',
    backgroundSize: '9px 2px',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
  },
  group: {
    fontSize: 14,
    fontWeight: 500,
    color: colors.muted,
    paddingTop: 31,
    paddingInline: 16,
    paddingBottom: 1,
    lineHeight: '20px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.line,
  },
  lastMake: { borderBottomWidth: 0 },
  make: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 65,
    paddingInline: 16,
    textAlign: 'left',
    fontSize: 16,
    fontWeight: 500,
    color: colors.text,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.line,
  },
  block: {
    position: 'relative',
    marginLeft: 16,
    '::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 1,
      backgroundColor: colors.line,
      pointerEvents: 'none',
    },
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    minHeight: 48,
    lineHeight: '24px',
    fontSize: 16,
    fontWeight: 500,
  },
  family: { minHeight: 56 },
  arrow: {
    width: 48,
    height: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.muted,
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    flexShrink: 0,
  },
  choice: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flex: '1',
    minWidth: 0,
    minHeight: 48,
    cursor: 'pointer',
  },
  checkTarget: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    height: 48,
    marginRight: 4,
    flexShrink: 0,
  },
  variantBox: { position: 'relative', marginLeft: 48, marginRight: 16, paddingBottom: 9 },
  variant: {
    height: 44,
    fontSize: 14,
    lineHeight: '20px',
    paddingRight: 32,
    fontWeight: 400,
    '::placeholder': { color: colors.muted, opacity: 1 },
    outlineStyle: 'none',
    borderColor: { default: '#818592', ':focus': colors.deepPurple },
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 0,
    paddingBlock: 14,
    paddingRight: 24,
    minHeight: 76,
    flexShrink: 0,
  },
  action: {
    height: 48,
    minWidth: 88,
    borderWidth: 0,
    backgroundColor: 'transparent',
    fontSize: 14,
    fontWeight: 500,
    color: colors.accent,
  },
  empty: { padding: 24, fontSize: 14, color: colors.muted },
  logo: (size: number) => ({ width: size, height: size, objectFit: 'contain', flexShrink: 0 }),
  fallback: { width: 40, flexShrink: 0 },
});
