import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

export const modelOptionStyles = stylex.create({
  desktopOptions: { display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 },
  phoneChoices: { display: 'contents' },
  desktopChoices: {
    flex: '1',
    minHeight: 0,
    overflowY: 'auto',
    scrollbarGutter: 'stable',
    overscrollBehaviorY: 'contain',
  },
  desktopExtras: {
    flexShrink: 0,
    marginTop: 8,
    maxHeight: '100%',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.stripe,
  },
  group: {
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: { default: colors.line, '@media (min-width: 700px)': colors.stripe },
  },
  choice: {
    display: 'flex',
    alignItems: 'center',
    minHeight: { default: 52, '@media (min-width: 700px)': 44 },
    paddingLeft: 8,
    fontSize: { default: 16, '@media (min-width: 700px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 700px)': '22px' },
    color: colors.text,
    cursor: 'pointer',
    borderRadius: { default: 0, '@media (min-width: 700px)': 8 },
    backgroundColor: {
      default: 'transparent',
      '@media (min-width: 700px)': { default: 'transparent', ':hover': colors.stripe },
      ':active': colors.controlSurface,
    },
  },
  childChoice: { paddingLeft: 24, fontWeight: 400 },
  name: { flex: '1', minWidth: 0, overflowWrap: 'anywhere', textAlign: 'left' },
  checkTarget: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    minHeight: { default: 52, '@media (min-width: 700px)': 44 },
    flexShrink: 0,
    cursor: 'pointer',
  },
  checkbox: {
    borderColor: { default: colors.muted, ':checked': colors.accent },
    backgroundColor: { default: colors.background, ':checked': colors.accent },
  },
  mixed: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
    backgroundImage: 'linear-gradient(white,white)',
    backgroundSize: '9px 2px',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
  },
  familyRow: {
    display: 'flex',
    alignItems: 'center',
    minHeight: { default: 52, '@media (min-width: 700px)': 44 },
    borderRadius: { default: 0, '@media (min-width: 700px)': 8 },
    backgroundColor: {
      default: 'transparent',
      '@media (min-width: 700px)': { default: 'transparent', ':hover': colors.stripe },
    },
  },
  familyButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flex: '1',
    minWidth: 0,
    minHeight: { default: 52, '@media (min-width: 700px)': 44 },
    paddingLeft: 8,
    paddingRight: 4,
    borderWidth: 0,
    backgroundColor: { default: 'transparent', ':active': colors.controlSurface },
    color: colors.text,
    fontSize: { default: 16, '@media (min-width: 700px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 700px)': '22px' },
    textAlign: 'left',
  },
  chevron: { display: 'flex', color: colors.muted, flexShrink: 0 },
  children: { paddingBottom: 4 },
  options: { marginTop: 12 },
  summary: {
    display: { default: 'flex', '::-webkit-details-marker': 'none' },
    listStyleType: 'none',
    alignItems: 'center',
    gap: 8,
    minHeight: { default: 52, '@media (min-width: 700px)': 44 },
    paddingInline: 8,
    fontSize: { default: 16, '@media (min-width: 700px)': 14 },
    lineHeight: { default: '24px', '@media (min-width: 700px)': '22px' },
    color: colors.text,
    cursor: 'pointer',
    backgroundColor: { default: 'transparent', ':active': colors.controlSurface },
  },
  activeCount: { fontSize: 13, lineHeight: '20px', color: colors.accent, flexShrink: 0 },
  optionFields: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    paddingInline: 8,
    paddingBottom: 12,
  },
  excludeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minHeight: 48,
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    fontSize: 14,
    lineHeight: '22px',
  },
  switch: {
    display: 'flex',
    alignItems: 'center',
    width: 36,
    height: 22,
    padding: 3,
    borderRadius: 12,
    backgroundColor: colors.muted,
    flexShrink: 0,
  },
  switchOn: { justifyContent: 'flex-end', backgroundColor: colors.accent },
  thumb: { width: 16, height: 16, borderRadius: '50%', backgroundColor: '#fff' },
  variantField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 14,
    lineHeight: '22px',
    color: colors.muted,
  },
  variantInput: {
    fontSize: 16,
    lineHeight: '24px',
    height: 'auto',
    minHeight: 48,
    paddingBlock: 10,
    borderRadius: 12,
    borderColor: colors.line,
  },
  empty: { padding: 24, fontSize: 14, color: colors.muted },
});
