import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

export const showroomFilterSheetStyles = stylex.create({
  desktopDialog: {
    maxWidth: { default: 640, '@media (min-width: 700px)': 820, '@media (min-width: 1024px)': 980 },
    height: {
      default: '100dvh',
      '@media (min-width: 700px)': 'min(680px, calc(100dvh - 48px))',
      '@media (min-width: 1024px)': 'min(620px, calc(100dvh - 64px))',
    },
    maxHeight: {
      default: '100dvh',
      '@media (min-width: 700px)': 'min(680px, calc(100dvh - 48px))',
      '@media (min-width: 1024px)': 'calc(100dvh - 64px)',
    },
    borderRadius: { default: 0, '@media (min-width: 700px)': 20, '@media (min-width: 1024px)': 20 },
    boxShadow: {
      default: '0 16px 60px #0004',
      '@media (min-width: 1024px)': '0 24px 64px rgba(20, 24, 32, .18)',
    },
  },
  editor: {
    display: { default: 'flex', '@media (min-width: 1024px)': 'grid' },
    flexDirection: 'column',
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    gridTemplateColumns: '180px minmax(0,1fr)',
    gridTemplateRows: 'auto minmax(0,1fr) auto',
    gridTemplateAreas: '"heading heading" "tabs panel" "footer footer"',
  },
  heading: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0,1fr) auto minmax(0,1fr)',
      '@media (min-width: 1024px)': 'minmax(0,1fr) auto auto',
    },
    alignItems: 'center',
    gap: 8,
    paddingInline: {
      default: 12,
      '@media (min-width: 700px)': 16,
      '@media (min-width: 1024px)': 24,
    },
    paddingTop: { default: 'max(8px, env(safe-area-inset-top))', '@media (min-width: 1024px)': 16 },
    paddingBottom: { default: 0, '@media (min-width: 1024px)': 16 },
    flexShrink: 0,
    gridArea: 'heading',
    borderBottomWidth: { default: 0, '@media (min-width: 1024px)': 1 },
    borderBottomStyle: 'solid',
    borderBottomColor: colors.line,
  },
  title: {
    fontSize: { default: 20, '@media (max-width: 699px)': 16 },
    fontWeight: { default: 700, '@media (max-width: 699px)': 400 },
    lineHeight: {
      default: '28px',
      '@media (max-width: 699px)': '24px',
      '@media (min-width: 1024px)': '32px',
    },
    color: { default: colors.text, '@media (max-width: 699px)': colors.muted },
    minWidth: 0,
    textAlign: { default: 'center', '@media (min-width: 1024px)': 'left' },
    gridColumn: { default: null, '@media (min-width: 1024px)': 1 },
    gridRow: { default: null, '@media (min-width: 1024px)': 1 },
  },
  closeAction: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'block' },
    gridColumn: { default: null, '@media (min-width: 1024px)': 3 },
    gridRow: { default: null, '@media (min-width: 1024px)': 1 },
  },
  clearFilters: {
    display: { default: 'inline-block', '@media (max-width: 699px)': 'inline-flex' },
    alignItems: 'center',
    justifyContent: 'center',
    justifySelf: 'end',
    width: { default: 'auto', '@media (max-width: 699px)': 48 },
    minHeight: { default: 48, '@media (min-width: 1024px)': 40 },
    paddingInline: { default: 8, '@media (max-width: 699px)': 0, '@media (min-width: 1024px)': 12 },
    borderWidth: 0,
    borderRadius: { default: 8, '@media (max-width: 699px)': 24 },
    backgroundColor: {
      default: 'transparent',
      '@media (min-width: 1024px)': { default: 'transparent', ':hover': colors.stripe },
    },
    color: {
      default: colors.muted,
      ':hover': colors.text,
      '@media (max-width: 699px)': colors.text,
    },
    fontSize: { default: 14, '@media (min-width: 700px)': 15 },
    fontWeight: 600,
    lineHeight: '20px',
    gridColumn: { default: null, '@media (min-width: 1024px)': 2 },
    gridRow: { default: null, '@media (min-width: 1024px)': 1 },
  },
  clearLabel: { display: { default: 'inline', '@media (max-width: 699px)': 'none' } },
  clearIcon: { display: { default: 'none', '@media (max-width: 699px)': 'inline-flex' } },
  tabs: { flexShrink: 0, minHeight: 0, gridArea: 'tabs' },
  panel: {
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gridArea: 'panel',
  },
  makePanel: {
    display: 'flex',
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
    marginInline: 'auto',
  },
  mobileMakePicker: {
    display: { default: 'flex', '@media (min-width: 700px)': 'none' },
    flex: '1',
    minHeight: 0,
    minWidth: 0,
  },
  hidden: { display: 'none' },
  fields: {
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    padding: { default: 20, '@media (min-width: 700px)': 24 },
    display: 'flex',
    flexDirection: 'column',
    gap: { default: 28, '@media (min-width: 1024px)': 24 },
    backgroundColor: { default: 'transparent', '@media (min-width: 1024px)': colors.background },
  },
  readableFields: {
    width: '100%',
    marginInline: 'auto',
  },
  moreFields: {
    display: { default: 'flex', '@media (min-width: 700px)': 'grid' },
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    alignContent: { default: 'normal', '@media (min-width: 700px)': 'start' },
  },
  moreRange: {
    minWidth: 0,
    gridColumn: {
      default: 'auto',
      '@media (min-width: 700px)': '1 / -1',
    },
  },
  group: {
    borderWidth: 0,
    padding: 0,
    minWidth: 0,
    maxWidth: { default: 'none', '@media (min-width: 1024px)': 560 },
    borderRadius: { default: 0, '@media (min-width: 1024px)': 16 },
    backgroundColor: { default: 'transparent', '@media (min-width: 1024px)': colors.background },
  },
  rangeCard: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'block' },
    padding: { default: 0, '@media (min-width: 1024px)': 20 },
    borderRadius: { default: 0, '@media (min-width: 1024px)': 16 },
    backgroundColor: { default: 'transparent', '@media (min-width: 1024px)': colors.stripe },
  },
  mileageCard: {
    padding: { default: 0, '@media (min-width: 1024px)': 20 },
    borderRadius: { default: 0, '@media (min-width: 1024px)': 16 },
    backgroundColor: { default: 'transparent', '@media (min-width: 1024px)': colors.stripe },
  },
  choiceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: { default: 0, '@media (min-width: 700px)': 8 },
  },
  desktopChoice: {
    paddingInline: { default: 0, '@media (min-width: 700px)': 12 },
    borderRadius: { default: 0, '@media (min-width: 700px)': 12 },
    backgroundColor: {
      default: 'transparent',
      '@media (min-width: 700px)': { default: colors.stripe, ':hover': colors.controlSurface },
      '@media (min-width: 1024px)': { default: colors.background, ':hover': colors.stripe },
    },
    borderWidth: { default: 0, '@media (min-width: 1024px)': 1 },
    borderStyle: 'solid',
    borderColor: colors.line,
    fontSize: { default: 16, '@media (min-width: 1024px)': 15 },
  },
  desktopChoiceSelected: {
    backgroundColor: {
      default: 'transparent',
      '@media (min-width: 700px)': colors.controlSurface,
      '@media (min-width: 1024px)': colors.activeSurface,
    },
    borderColor: { default: colors.line, '@media (min-width: 1024px)': colors.accent },
  },
  desktopCheckbox: {
    borderColor: {
      default: '#808592',
      ':checked': colors.deepPurple,
      '@media (min-width: 700px)': { default: colors.muted, ':checked': colors.text },
    },
    backgroundColor: {
      default: colors.background,
      ':checked': colors.deepPurple,
      '@media (min-width: 700px)': { default: colors.background, ':checked': colors.text },
    },
  },
  fieldTitle: { fontSize: 18, fontWeight: 600, lineHeight: '26px', marginBottom: 12 },
  copy: { color: colors.muted, fontSize: 14, lineHeight: '22px' },
  budgetPresets: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2,minmax(0,1fr))',
      '@media (min-width: 700px)': 'repeat(4,minmax(0,1fr))',
    },
    gap: 8,
    paddingInline: { default: 4, '@media (min-width: 1024px)': 0 },
  },
  budgetPreset: {
    minWidth: 0,
    minHeight: 48,
    paddingInline: 8,
    paddingBlock: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: 12,
    backgroundColor: { default: colors.controlSurface, ':hover': colors.stripe },
    color: colors.text,
    fontSize: {
      default: 14,
      '@media (min-width: 700px)': 16,
      '@media (min-width: 1024px)': 14,
    },
    fontWeight: 500,
    lineHeight: '20px',
  },
  budgetPresetSelected: {
    backgroundColor: {
      default: colors.text,
      ':hover': colors.text,
      '@media (min-width: 1024px)': {
        default: colors.activeSurface,
        ':hover': colors.activeSurface,
      },
    },
    borderColor: { default: colors.text, '@media (min-width: 1024px)': colors.accent },
    color: { default: colors.background, '@media (min-width: 1024px)': colors.accent },
  },
  searchPanel: { gap: 16 },
  suggestions: { display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 },
  suggestion: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 48,
    minWidth: 0,
    paddingInline: 12,
    paddingBlock: 10,
    borderWidth: 0,
    borderRadius: 12,
    backgroundColor: { default: 'transparent', ':hover': colors.controlSurface },
    color: colors.text,
    textAlign: 'left',
    outlineColor: colors.accent,
    fontSize: { default: 15, '@media (max-width: 699px)': 16 },
    lineHeight: { default: '22px', '@media (max-width: 699px)': '24px' },
  },
  suggestionName: { flex: '1', minWidth: 0, overflowWrap: 'anywhere', fontWeight: 500 },
  suggestionTail: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  suggestionArrow: { display: 'flex', color: colors.muted },
  suggestionPrice: {
    flexShrink: 0,
    color: colors.muted,
    fontSize: { default: 13, '@media (max-width: 699px)': 14 },
    lineHeight: '20px',
  },
  footer: {
    gridArea: 'footer',
    flexShrink: 0,
    paddingInline: { default: 16, '@media (min-width: 700px)': 24 },
    paddingTop: { default: 12, '@media (max-width: 699px)': 8 },
    paddingBottom: {
      default: 'max(16px, env(safe-area-inset-bottom))',
      '@media (max-width: 699px)': 'max(12px, env(safe-area-inset-bottom))',
    },
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.line,
    display: { default: 'block', '@media (min-width: 700px)': 'flex' },
    justifyContent: 'flex-end',
  },
  footerAction: { width: { default: '100%', '@media (min-width: 700px)': 240 } },
  footerButton: {
    minHeight: { default: 48, '@media (max-width: 699px)': 44 },
    paddingBlock: 10,
    borderRadius: {
      default: 24,
      '@media (max-width: 699px)': 22,
      '@media (min-width: 1024px)': 12,
    },
    fontSize: {
      default: 14,
      '@media (max-width: 699px)': 16,
      '@media (min-width: 700px)': 16,
    },
    fontWeight: { default: 700, '@media (max-width: 699px)': 500 },
    lineHeight: { default: '20px', '@media (min-width: 700px)': '24px' },
    paddingInline: { default: 24, '@media (min-width: 700px)': 16 },
    transition: {
      default: 'filter 120ms, transform 120ms',
      '@media (min-width: 700px)': 'none',
    },
    transform: {
      default: 'none',
      ':active': { default: 'translateY(1px)', '@media (min-width: 700px)': 'none' },
      '@media (min-width: 700px)': 'none',
    },
  },
});
