import * as stylex from '@stylexjs/stylex';
import { controlShape } from '@/styles/control-tokens.stylex';
import { colors } from '@/styles/tokens.stylex';
import { showroomDesktop } from '@/styles/showroom-desktop-tokens.stylex';

export const s = stylex.create({
  page: {
    padding: { default: 16, '@media (min-width: 1024px)': showroomDesktop.gutter },
    paddingBottom: 32,
    backgroundColor: colors.background,
    minHeight: 'calc(100dvh - 124px)',
  },
  servicesPage: {
    minHeight: { default: 'calc(100dvh - 242px)', '@media (min-width: 1024px)': 0 },
    paddingTop: { default: 16, '@media (max-width: 699px)': 4, '@media (min-width: 1024px)': 20 },
    paddingInline: { default: 16, '@media (min-width: 1024px)': 0 },
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    boxShadow: 'none',
  },
  head: { paddingBlock: 12, marginBottom: 20, display: 'flex', flexDirection: 'column', gap: 8 },
  title: { fontSize: 28, lineHeight: '36px', fontWeight: 700 },
  intro: { fontSize: 16, lineHeight: '24px', color: colors.muted },
  subTitle: {
    fontSize: { default: 18, '@media (min-width: 1024px)': 20 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '26px' },
    fontWeight: { default: 700, '@media (min-width: 1024px)': 500 },
  },
  search: {
    position: { default: 'relative', '@media (min-width: 1024px)': 'static' },
    zIndex: { default: 26, '@media (min-width: 1024px)': 'auto' },
    backgroundColor: { default: colors.background, '@media (min-width: 1024px)': 'transparent' },
    paddingTop: { default: 4, '@media (min-width: 1024px)': 0 },
    width: '100%',
    maxWidth: { default: 'none', '@media (min-width: 1024px)': 620 },
  },
  tabs: {
    position: { default: 'sticky', '@media (min-width: 1024px)': 'static' },
    top: 0,
    zIndex: 25,
    display: { default: 'flow-root', '@media (min-width: 1024px)': 'flex' },
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    minWidth: 0,
    backgroundColor: colors.background,
  },
  phoneServiceControls: {
    display: {
      default: 'contents',
      '@media (max-width: 699px)': 'flow-root',
      '@media (min-width: 1024px)': 'none',
    },
    clipPath: { default: 'none', '@media (max-width: 699px)': 'inset(0 -16px -16px)' },
  },
  desktopServiceControls: {
    display: { default: 'none', '@media (min-width: 1024px)': 'block' },
    minWidth: 0,
    maxWidth: '100%',
  },
  serviceHeroControls: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'flex' },
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    gap: 12,
  },
  serviceFlow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr)',
    alignItems: 'start',
    gap: 20,
    maxWidth: { default: 1040, '@media (min-width: 1024px)': 'none' },
    marginInline: 'auto',
  },
  saleFlow: { gridTemplateColumns: 'minmax(0,1fr)', maxWidth: 720 },
  importFlow: {
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 1024px)': 'minmax(0,.85fr) minmax(0,1.15fr)',
    },
    gap: { default: 20, '@media (min-width: 1024px)': showroomDesktop.sectionGap },
  },
  serviceGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 700px)': 'repeat(2,minmax(0,1fr))',
      '@media (min-width: 1024px)': 'repeat(3,minmax(0,1fr))',
    },
    alignItems: 'stretch',
    columnGap: { default: 8, '@media (min-width: 1024px)': showroomDesktop.sectionGap },
    rowGap: { default: 8, '@media (min-width: 1024px)': 32 },
    maxWidth: { default: 1040, '@media (min-width: 1024px)': 'none' },
    marginInline: 'auto',
  },
  serviceCard: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr) auto',
    alignItems: 'start',
    columnGap: 8,
    rowGap: { default: 4, '@media (min-width: 1024px)': 12 },
    backgroundColor: colors.background,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: colors.line,
      '@media (max-width: 699px)': colors.cardLine,
      '@media (min-width: 1024px)': colors.cardLine,
    },
    borderRadius: { default: 12, '@media (min-width: 1024px)': 16 },
    paddingBlock: { default: 12, '@media (min-width: 1024px)': 20 },
    paddingInline: { default: 14, '@media (min-width: 1024px)': 20 },
    minWidth: 0,
    boxShadow: {
      default: 'none',
      '@media (max-width: 699px)': '0 3px 12px rgba(27, 27, 33, 0.035)',
    },
  },
  serviceCardLink: {
    gridTemplateColumns: 'minmax(0,1fr) auto',
    gridTemplateRows: { default: 'auto', '@media (min-width: 1024px)': 'auto auto 1fr' },
    paddingBlock: { default: 12, '@media (min-width: 1024px)': 0 },
    paddingInline: { default: 14, '@media (min-width: 1024px)': 0 },
    rowGap: { default: 4, '@media (min-width: 1024px)': 0 },
    borderWidth: { default: 1, '@media (min-width: 1024px)': 0 },
    borderRadius: { default: 12, '@media (max-width: 699px)': 16, '@media (min-width: 1024px)': 0 },
    overflow: 'visible',
    color: colors.text,
    textDecoration: 'none',
    backgroundColor: {
      default: colors.background,
      ':hover': colors.controlSurface,
      ':active': colors.controlSurface,
      '@media (min-width: 1024px)': {
        default: 'transparent',
        ':hover': 'transparent',
        ':active': 'transparent',
      },
    },
    outlineColor: colors.accent,
    outlineOffset: 3,
  },
  serviceCardCopy: {
    gridColumn: '1 / -1',
    paddingInline: 0,
    paddingTop: { default: 0, '@media (min-width: 1024px)': 8 },
    paddingBottom: 0,
  },
  serviceCardHeading: {
    display: { default: 'flex', '@media (min-width: 1024px)': 'contents' },
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  serviceCardText: {
    display: { default: 'flex', '@media (min-width: 1024px)': 'contents' },
    flexDirection: 'column',
    flexGrow: 1,
    gap: 4,
    minWidth: 0,
  },
  serviceCardTitle: {
    paddingTop: { default: 0, '@media (min-width: 1024px)': 14 },
    paddingBottom: 0,
  },
  serviceCardLine: {
    minWidth: 0,
    overflow: { default: 'hidden', '@media (min-width: 1024px)': 'visible' },
    whiteSpace: { default: 'nowrap', '@media (min-width: 1024px)': 'normal' },
    textOverflow: { default: 'ellipsis', '@media (min-width: 1024px)': 'clip' },
  },
  serviceMobileCopy: { display: { default: 'inline', '@media (min-width: 1024px)': 'none' } },
  serviceDesktopCopy: { display: { default: 'none', '@media (min-width: 1024px)': 'inline' } },
  serviceIcon: {
    display: { default: 'none', '@media (min-width: 1024px)': 'inline-flex' },
    alignItems: 'center',
    justifyContent: 'center',
    gridColumn: 1,
    gridRow: 1,
    width: 44,
    height: 44,
    borderRadius: 12,
    color: colors.muted,
    backgroundColor: colors.stripe,
    margin: { default: 0, '@media (min-width: 1024px)': 18 },
  },
  serviceCardCue: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    justifySelf: 'end',
    alignSelf: 'start',
    gridColumn: 2,
    gridRow: { default: 1, '@media (min-width: 1024px)': 2 },
    gap: 3,
    minHeight: { default: 24, '@media (min-width: 1024px)': 26 },
    width: { default: 24, '@media (min-width: 1024px)': 32 },
    paddingBlock: 0,
    paddingInline: 0,
    marginTop: { default: 0, '@media (min-width: 360px)': 4, '@media (min-width: 1024px)': 14 },
    marginRight: 0,
    backgroundColor: 'transparent',
    color: colors.text,
    fontSize: { default: 12, '@media (min-width: 1024px)': 14 },
    fontWeight: 500,
    lineHeight: '20px',
    whiteSpace: 'nowrap',
  },
  serviceCardChevron: {
    flexShrink: 0,
    color: colors.muted,
    width: { default: 16, '@media (min-width: 1024px)': 20 },
    height: { default: 16, '@media (min-width: 1024px)': 20 },
  },
  serviceCardViewCue: { width: { default: 24, '@media (min-width: 1024px)': 'auto' }, gap: 4 },
  serviceCardCueText: { display: { default: 'none', '@media (min-width: 1024px)': 'inline' } },
  serviceDetail: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 1024px)': 'minmax(0,.85fr) minmax(0,1.15fr)',
    },
    alignItems: 'start',
    gap: { default: 12, '@media (min-width: 1024px)': 28 },
    borderRadius: 16,
    padding: { default: 20, '@media (min-width: 1024px)': 28 },
  },
  singleCategory: {
    gridTemplateColumns: '1fr',
    maxWidth: { default: 620, '@media (min-width: 1024px)': 840 },
    marginInline: 'auto',
  },
  serviceBody: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    minWidth: 0,
  },
  serviceTitle: {
    paddingTop: { default: 3, '@media (min-width: 1024px)': 14 },
    paddingBottom: { default: 3, '@media (min-width: 1024px)': 0 },
    paddingLeft: 0,
    gridColumn: { default: 'auto', '@media (min-width: 1024px)': 1 },
    gridRow: { default: 'auto', '@media (min-width: 1024px)': 2 },
    fontSize: { default: 16, '@media (min-width: 1024px)': 20 },
    lineHeight: { default: '22px', '@media (min-width: 1024px)': '28px' },
    fontWeight: 500,
    overflowWrap: 'anywhere',
  },
  serviceCopy: {
    fontSize: { default: 14, '@media (min-width: 1024px)': 16 },
    lineHeight: { default: '20px', '@media (min-width: 1024px)': '24px' },
    color: colors.muted,
    overflowWrap: 'anywhere',
  },
  serviceAction: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    flexShrink: 0,
    padding: 0,
    borderRadius: controlShape.pill,
    textDecoration: 'none',
    outlineColor: colors.accent,
  },
  serviceActionFace: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: { default: 36, '@media (min-width: 1024px)': 40 },
    paddingBlock: 7,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: controlShape.pill,
    backgroundColor: { default: colors.controlSurface, ':hover': colors.surface },
    color: colors.text,
    fontSize: { default: 14, '@media (min-width: 1024px)': 16 },
    fontWeight: 500,
    lineHeight: '20px',
  },
  serviceActionPrimary: {
    backgroundColor: { default: colors.accent, ':hover': colors.accent },
    borderColor: colors.accent,
    color: '#fff',
    fontWeight: 600,
  },
  serviceDetailAction: {
    gridColumn: { default: '1 / -1', '@media (min-width: 1024px)': 1 },
    marginTop: 4,
  },
  serviceDetails: {
    gridColumn: { default: '1 / -1', '@media (min-width: 1024px)': 2 },
    gridRow: { default: 'auto', '@media (min-width: 1024px)': '1 / span 2' },
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginTop: 4,
  },
  detailTitle: {
    fontSize: { default: 14, '@media (min-width: 1024px)': 16 },
    lineHeight: { default: '20px', '@media (min-width: 1024px)': '24px' },
    fontWeight: 500,
  },
  detailCopy: {
    fontSize: { default: 14, '@media (min-width: 1024px)': 16 },
    lineHeight: { default: '20px', '@media (min-width: 1024px)': '24px' },
    color: colors.muted,
  },
  contactGrid: {
    display: { default: 'grid', '@media (min-width: 1024px)': 'contents' },
    gridTemplateColumns: 'minmax(0,1fr)',
    alignItems: 'start',
    gap: 12,
  },
  contactPage: {
    display: { default: 'flex', '@media (min-width: 1024px)': 'grid' },
    flexDirection: 'column',
    gridTemplateColumns: 'minmax(0,.85fr) minmax(0,1.15fr)',
    gap: { default: 0, '@media (min-width: 1024px)': showroomDesktop.sectionGap },
    alignItems: 'stretch',
    paddingBlock: { default: 0, '@media (min-width: 1024px)': 12 },
    minHeight: { default: 'calc(100dvh - 124px)', '@media (min-width: 1024px)': 0 },
  },
  contactIntro: {
    display: { default: 'block', '@media (max-width: 699px)': 'none' },
    backgroundColor: colors.background,
    paddingInline: { default: 16, '@media (min-width: 1024px)': 0 },
    paddingBlock: { default: 12, '@media (min-width: 1024px)': 0 },
    borderWidth: { default: 0, '@media (min-width: 1024px)': 1 },
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: { default: 0, '@media (min-width: 1024px)': showroomDesktop.panelRadius },
    gridColumn: 1,
    gridRow: { default: 1, '@media (min-width: 1024px)': '1 / span 2' },
  },
  contactBody: {
    flex: '1',
    minHeight: 0,
    display: { default: 'block', '@media (min-width: 1024px)': 'contents' },
    paddingTop: 16,
  },
  contactContainer: {
    maxWidth: 620,
    marginInline: 'auto',
    minWidth: 0,
    display: { default: 'block', '@media (min-width: 1024px)': 'contents' },
  },
  phoneContact: { display: { default: 'contents', '@media (min-width: 1024px)': 'none' } },
  contactHeroAction: {
    display: { default: 'none', '@media (min-width: 1024px)': 'inline-flex' },
    minHeight: 44,
    paddingInline: 22,
    borderRadius: controlShape.pill,
    borderColor: '#fff',
    backgroundColor: { default: '#fff', ':hover': colors.controlSurface },
    color: colors.text,
    fontWeight: 500,
    outlineColor: '#fff',
    outlineOffset: 4,
  },
  messageLabel: { flexGrow: { default: 0, '@media (min-width: 1024px)': 1 } },
  enquiryCard: {
    gridColumn: { default: 'auto', '@media (min-width: 1024px)': 2 },
    gridRow: { default: 'auto', '@media (min-width: 1024px)': '1 / span 2' },
  },
  inlineEnquiry: { display: { default: 'none', '@media (min-width: 700px)': 'flex' } },
  detailsCard: {
    display: { default: 'flex', '@media (min-width: 1024px)': 'none' },
    gridColumn: { default: 'auto', '@media (min-width: 1024px)': 1 },
    gridRow: { default: 'auto', '@media (min-width: 1024px)': 2 },
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 700px)': 'repeat(2,minmax(0,1fr))',
      '@media (min-width: 1024px)': showroomDesktop.inventoryColumns,
      '@media (min-width: 1600px)': showroomDesktop.wideInventoryColumns,
    },
    gap: { default: 20, '@media (min-width: 1024px)': showroomDesktop.cardGap },
  },
  card: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: { default: colors.line, '@media (min-width: 1024px)': colors.cardLine },
    borderRadius: { default: 16, '@media (min-width: 1024px)': showroomDesktop.panelRadius },
    padding: { default: 16, '@media (min-width: 1024px)': 24 },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: { default: 14, '@media (min-width: 1024px)': showroomDesktop.cardGap },
    minWidth: 0,
  },
  body: {
    fontSize: { default: 15, '@media (min-width: 1024px)': 16 },
    lineHeight: { default: '22px', '@media (min-width: 1024px)': '24px' },
    color: colors.muted,
  },
  contactActions: {
    display: { default: 'grid', '@media (max-width: 699px)': 'none' },
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    gap: { default: 12, '@media (max-width: 699px)': 8 },
  },
  contactAction: {
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 48,
    minWidth: 0,
    padding: 0,
    borderWidth: 0,
    borderRadius: controlShape.pill,
    backgroundColor: 'transparent',
    textDecoration: 'none',
    outlineColor: colors.accent,
    cursor: { default: 'pointer', ':disabled': 'default' },
  },
  contactActionFace: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    minHeight: 44,
    paddingBlock: 10,
    paddingInline: { default: 12, '@media (max-width: 699px)': 10 },
    borderRadius: controlShape.pill,
    backgroundColor: { default: colors.controlSurface, ':hover': colors.surface },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    color: colors.text,
    fontSize: { default: 14, '@media (max-width: 699px)': 16, '@media (min-width: 1024px)': 16 },
    fontWeight: 500,
    lineHeight: '20px',
    overflowWrap: 'anywhere',
  },
  contactActionUnavailable: {
    backgroundColor: { default: colors.controlSurface, ':hover': colors.controlSurface },
    color: colors.muted,
  },
  contactExtraAction: { gridColumn: '1 / -1', justifySelf: 'center', minWidth: 144 },
  contactAvailability: {
    marginTop: 8,
    display: { default: 'block', '@media (max-width: 699px)': 'none' },
  },
  contactPreviewCopy: { display: { default: 'block', '@media (max-width: 699px)': 'none' } },
  contactSubmit: {
    alignSelf: 'flex-start',
    borderWidth: 0,
    backgroundColor: 'transparent',
    borderRadius: controlShape.pill,
  },
  contactSubmitFace: {
    minHeight: {
      default: 36,
      '@media (max-width: 699px)': 44,
      '@media (min-width: 1024px)': 40,
    },
    borderRadius: controlShape.pill,
    fontSize: { default: 14, '@media (max-width: 699px)': 16, '@media (min-width: 1024px)': 16 },
  },
  info: { display: 'flex', flexDirection: 'column', gap: 12 },
  infoRow: { display: 'flex', alignItems: 'flex-start', gap: 10 },
  infoIcon: { display: 'inline-flex', color: colors.muted, flexShrink: 0, marginTop: 2 },
  context: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    paddingInline: 12,
    paddingBlock: 8,
    borderRadius: 10,
    backgroundColor: colors.stripe,
  },
  contextText: { flex: '1 1 160px', minWidth: 0, overflowWrap: 'anywhere' },
  contextTitle: { fontSize: 15, lineHeight: '22px', fontWeight: 500 },
  contextLink: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 44,
    flexShrink: 0,
    color: colors.accent,
    fontSize: 14,
    fontWeight: 500,
    textDecoration: 'none',
  },
  note: {
    fontSize: 12,
    lineHeight: '20px',
    color: colors.muted,
    textAlign: 'center',
    paddingTop: 24,
  },
  textArea: {
    width: '100%',
    minHeight: {
      default: 120,
      '@media (max-width: 699px)': 144,
      '@media (min-width: 1024px)': 180,
    },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: controlShape.field,
    padding: 12,
    backgroundColor: {
      default: colors.controlSurface,
      '@media (min-width: 1024px)': colors.stripe,
    },
    color: colors.text,
    fontSize: 16,
    lineHeight: '24px',
    '::placeholder': {
      color: { default: null, '@media (max-width: 699px)': colors.muted },
      opacity: { default: null, '@media (max-width: 699px)': 1 },
    },
    resize: 'vertical',
    flexGrow: { default: 0, '@media (min-width: 1024px)': 1 },
  },
  form: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    flexGrow: { default: 0, '@media (min-width: 1024px)': 1 },
  },
  saved: { color: colors.green, fontSize: 14, lineHeight: '22px' },
  saveUnavailable: { color: colors.text },
});
