import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

export const desktopMakeModelStyles = stylex.create({
  layout: {
    display: { default: 'none', '@media (min-width: 700px)': 'grid' },
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: { default: 16, '@media (min-width: 1024px)': 24 },
    paddingInline: 24,
    paddingBlock: { default: 24, '@media (max-height: 600px)': 16 },
  },
  pane: {
    display: 'flex',
    flexDirection: 'column',
    gap: { default: 12, '@media (max-height: 600px)': 8 },
    minWidth: 0,
    minHeight: 0,
    padding: { default: 16, '@media (min-width: 1024px)': 0 },
    borderRadius: { default: 16, '@media (min-width: 1024px)': 0 },
    backgroundColor: { default: colors.stripe, '@media (min-width: 1024px)': colors.background },
  },
  heading: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    height: 40,
    flexShrink: 0,
  },
  title: {
    flex: '1',
    minWidth: 0,
    fontSize: { default: 18, '@media (min-width: 1024px)': 16 },
    fontWeight: 600,
    lineHeight: '26px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  search: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    height: 44,
    minWidth: 0,
    flexShrink: 0,
    paddingInline: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    backgroundColor: colors.background,
  },
  searchIcon: { display: 'flex', flexShrink: 0, color: colors.muted },
  searchInput: {
    flex: '1',
    width: '100%',
    minWidth: 0,
    height: '100%',
    padding: 0,
    fontSize: 16,
    lineHeight: '24px',
    borderWidth: 0,
    borderRadius: 0,
    outlineStyle: 'none',
    backgroundColor: 'transparent',
  },
  disabledSearch: { color: colors.muted, backgroundColor: colors.stripe },
  clearSearch: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 24,
    height: 32,
    padding: 0,
    borderWidth: 0,
    borderRadius: 6,
    color: colors.muted,
    backgroundColor: { default: 'transparent', ':hover': colors.background },
    outlineColor: colors.accent,
  },
  makeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    flex: '1',
    minHeight: 0,
    overflowY: 'auto',
    scrollbarGutter: 'stable',
    overscrollBehaviorY: 'contain',
  },
  makeRow: {
    display: 'flex',
    alignItems: 'center',
    minHeight: { default: 64, '@media (min-width: 1024px)': 54 },
    borderRadius: 12,
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
  },
  activeRow: {
    backgroundColor: { default: colors.controlSurface, '@media (min-width: 1024px)': '#fff0eb' },
  },
  makeChoice: {
    display: 'flex',
    alignItems: 'center',
    flex: '1',
    minWidth: 0,
    minHeight: { default: 64, '@media (min-width: 1024px)': 54 },
    gap: 8,
    paddingLeft: 8,
    cursor: 'pointer',
  },
  makeName: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    fontSize: { default: 16, '@media (min-width: 1024px)': 14 },
    fontWeight: 500,
    lineHeight: '24px',
  },
  selectionSummary: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 13,
    fontWeight: 400,
    lineHeight: '20px',
    color: colors.muted,
  },
  excluded: { display: 'block', fontSize: 12, lineHeight: '18px', color: colors.muted },
  checkbox: {
    width: 20,
    height: 20,
    borderColor: { default: colors.muted, ':checked': colors.text },
    backgroundColor: { default: colors.background, ':checked': colors.text },
  },
  edit: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 40,
    height: 44,
    padding: 0,
    borderWidth: 0,
    borderRadius: 8,
    color: colors.muted,
    backgroundColor: { default: 'transparent', ':hover': colors.background },
    outlineColor: colors.accent,
  },
  remove: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    gap: 4,
    height: 40,
    paddingInline: 8,
    borderWidth: 0,
    borderRadius: 8,
    color: colors.text,
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
    outlineColor: colors.accent,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
  },
  invisible: { visibility: 'hidden' },
  modelContent: {
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    borderRadius: { default: 12, '@media (min-width: 1024px)': 0 },
    padding: { default: 8, '@media (min-width: 1024px)': 0 },
    backgroundColor: colors.background,
  },
  empty: {
    paddingBlock: 20,
    paddingInline: 8,
    fontSize: 16,
    lineHeight: '24px',
    color: colors.muted,
  },
});
