import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

export const desktopMakeModelStyles = stylex.create({
  layout: {
    display: { default: 'none', '@media (min-width: 700px)': 'grid' },
    flex: '1',
    minHeight: 0,
    minWidth: 0,
    gridTemplateColumns: 'minmax(200px, .85fr) minmax(0, 1.65fr)',
    gap: 24,
    paddingInline: 24,
    paddingBlock: { default: 24, '@media (max-height: 600px)': 16 },
  },
  pane: {
    display: 'flex',
    flexDirection: 'column',
    gap: { default: 12, '@media (max-height: 600px)': 8 },
    minWidth: 0,
    minHeight: 0,
  },
  modelPane: {
    borderLeftWidth: 1,
    borderLeftStyle: 'solid',
    borderLeftColor: colors.stripe,
    paddingLeft: 24,
  },
  heading: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    height: { default: 36, '@media (max-height: 600px)': 32 },
    flexShrink: 0,
  },
  title: {
    flex: '1',
    minWidth: 0,
    fontSize: 15,
    fontWeight: 600,
    lineHeight: '22px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  search: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    height: 44,
    minWidth: 0,
    flexShrink: 0,
    paddingInline: 12,
    borderRadius: 10,
    backgroundColor: colors.controlSurface,
  },
  searchIcon: { display: 'flex', flexShrink: 0, color: colors.muted },
  searchInput: {
    flex: '1',
    width: '100%',
    minWidth: 0,
    height: 44,
    padding: 0,
    fontSize: 14,
    lineHeight: '22px',
    borderWidth: 0,
    borderRadius: 0,
    outlineStyle: 'none',
    backgroundColor: 'transparent',
  },
  disabledSearch: { color: colors.muted, backgroundColor: colors.stripe },
  clearSearch: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 24,
    height: 32,
    padding: 0,
    borderWidth: 0,
    borderRadius: 6,
    color: colors.muted,
    backgroundColor: { default: 'transparent', ':hover': colors.background },
    outlineColor: colors.accent,
  },
  makeList: {
    flex: '1',
    minHeight: 0,
    overflowY: 'auto',
    scrollbarGutter: 'stable',
    overscrollBehaviorY: 'contain',
  },
  makeRow: {
    display: 'flex',
    alignItems: 'center',
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: { default: 'transparent', ':hover': colors.stripe },
  },
  activeRow: { backgroundColor: colors.controlSurface },
  makeChoice: {
    display: 'flex',
    alignItems: 'center',
    flex: '1',
    minWidth: 0,
    minHeight: 52,
    gap: 10,
    paddingLeft: 8,
    cursor: 'pointer',
  },
  makeName: { minWidth: 0, overflowWrap: 'anywhere', fontSize: 14, lineHeight: '22px' },
  excluded: { display: 'block', fontSize: 12, lineHeight: '18px', color: colors.muted },
  checkbox: {
    width: 18,
    height: 18,
    borderColor: { default: colors.muted, ':checked': colors.accent },
    backgroundColor: { default: colors.background, ':checked': colors.accent },
  },
  edit: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 40,
    height: 44,
    padding: 0,
    borderWidth: 0,
    borderRadius: 8,
    color: colors.muted,
    backgroundColor: { default: 'transparent', ':hover': colors.background },
    outlineColor: colors.accent,
  },
  remove: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    gap: 4,
    height: 36,
    paddingInline: 8,
    borderWidth: 0,
    borderRadius: 8,
    color: colors.muted,
    backgroundColor: { default: 'transparent', ':hover': colors.controlSurface },
    outlineColor: colors.accent,
    fontSize: 13,
    lineHeight: '20px',
  },
  invisible: { visibility: 'hidden' },
  modelContent: { flex: '1', minHeight: 0, minWidth: 0 },
  empty: {
    paddingBlock: 20,
    paddingInline: 8,
    fontSize: 14,
    lineHeight: '22px',
    color: colors.muted,
  },
});
