import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';

export const desktopFilterStyles = stylex.create({
  smallSheet: { width: 'min(640px, calc(100vw - 64px))', height: 'fit-content' },
  autoEditor: { height: 'auto', flex: '0 1 auto' },
  popover: {
    display: 'flex',
    flexDirection: 'column',
    zIndex: 80,
    position: 'fixed',
    inset: 'auto',
    top: 'var(--filter-top, 260px)',
    left: 'var(--filter-left, 24px)',
    visibility: 'hidden',
    margin: 0,
    width: 'min(480px, calc(100vw - 32px))',
    maxWidth: 'calc(100vw - 32px)',
    height: 'auto',
    maxHeight: 'min(480px, var(--filter-height, calc(100dvh - 32px)))',
    padding: 0,
    overflow: 'hidden',
    outlineStyle: 'none',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    backgroundColor: colors.background,
    color: colors.text,
    borderRadius: 18,
    boxShadow: '0 16px 48px rgba(20,24,32,.16), 0 2px 8px rgba(20,24,32,.06)',
  },
  choicePopover: { width: 360 },
  pickerPopover: { width: 'var(--filter-width, 600px)' },
  hiddenHeader: { display: 'none' },
  popupHeader: { padding: '16px 20px 12px', borderBottomWidth: 0 },
  popupTitle: { fontSize: 18, lineHeight: '26px' },
  popupContent: { padding: '8px 20px 20px', flex: '0 1 auto' },
  popupFooter: {
    padding: { default: '10px 12px', '@media (max-height: 700px)': '6px 12px' },
    gap: 12,
  },
  pickerFooter: {
    padding: { default: '8px 12px', '@media (max-height: 700px)': '6px 8px' },
    paddingInline: { default: 12, '@media (max-height: 700px)': 8 },
  },
  footerWithAction: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr) auto minmax(0,1fr)',
  },
  footerClear: { justifySelf: 'start' },
  footerAction: { display: 'flex', justifyContent: 'center', minWidth: 0 },
  footerApply: { justifySelf: 'end' },
  popupClear: { minHeight: 40, paddingInline: 8 },
  popupApply: {
    minHeight: 40,
    minWidth: 140,
    paddingInline: 16,
    paddingBlock: 8,
    borderRadius: 10,
  },
  overview: { display: 'flex', flexDirection: 'column', gap: 16 },
  overviewPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 8,
    borderRadius: 16,
    backgroundColor: colors.stripe,
    minWidth: 0,
  },
  overviewOptions: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4,minmax(0,1fr))',
    gap: 8,
    alignItems: 'stretch',
  },
  optionPanel: {
    padding: 7,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  makeModelSummary: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    gap: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  singleSummary: { gridTemplateColumns: 'minmax(0,1fr)' },
  disabledSummary: { opacity: 0.6, cursor: 'not-allowed' },
  pickerSheet: { width: 'min(560px, calc(100vw - 64px))', borderRadius: 22 },
  modelSheet: { height: 'min(640px, calc(100dvh - 64px))' },
  focusedModelSheet: {
    width: 'min(880px, calc(100vw - 64px))',
    height: 'min(656px, calc(100dvh - 64px))',
  },
  focusedHeader: { padding: '18px 24px' },
  focusedFooter: { padding: '12px 24px' },
  overviewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,minmax(0,1fr))',
    gap: 8,
    alignItems: 'stretch',
  },
  fieldGroup: { display: 'flex', flexDirection: 'column', gap: 8, minWidth: 0 },
  fieldTitle: { fontSize: 15, fontWeight: 600, lineHeight: '22px' },
  makeSummary: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 16px',
    minHeight: 64,
    borderWidth: 0,
    borderInlineStartWidth: { default: 0, ':not(:first-child)': 1 },
    borderInlineStartStyle: 'solid',
    borderInlineStartColor: colors.cardLine,
    borderStartStartRadius: { default: 0, ':first-child': 11 },
    borderEndStartRadius: { default: 0, ':first-child': 11 },
    borderStartEndRadius: { default: 0, ':last-child': 11 },
    borderEndEndRadius: { default: 0, ':last-child': 11 },
    backgroundColor: { default: 'transparent', ':hover': colors.controlSurface },
    color: colors.text,
    textAlign: 'left',
  },
  makeSummaryCopy: { flex: '1', minWidth: 0, display: 'flex', flexDirection: 'column', gap: 4 },
  dialog: {
    display: { default: 'flex', ':not([open])': 'none' },
    flexDirection: 'column',
    position: 'fixed',
    inset: 0,
    margin: 'auto',
    outlineStyle: 'none',
    width: 'min(960px, calc(100vw - 64px))',
    maxWidth: 'calc(100vw - 64px)',
    height: 'min(760px, calc(100dvh - 64px))',
    maxHeight: 'calc(100dvh - 64px)',
    padding: 0,
    borderRadius: 24,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    overflow: 'hidden',
    boxShadow: '0 24px 80px rgba(20,24,32,.22), 0 4px 16px rgba(20,24,32,.08)',
    '::backdrop': { backgroundColor: 'rgba(20,24,32,.28)', backdropFilter: 'blur(4px)' },
  },
  editor: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    maxHeight: 'inherit',
    height: '100%',
    flex: '1',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '20px 24px',
    flexShrink: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.cardLine,
  },
  title: {
    flex: '1',
    minWidth: 0,
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
    outlineStyle: 'none',
  },
  close: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderWidth: 0,
    borderRadius: '50%',
    color: colors.text,
    backgroundColor: { default: colors.controlSurface, ':hover': colors.surface },
  },
  content: {
    flex: '1',
    padding: 24,
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    minHeight: 0,
    minWidth: 0,
  },
  makeContent: { display: 'flex', padding: 0, overflowY: 'hidden', overflowX: 'hidden' },
  footer: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.cardLine,
    backgroundColor: colors.background,
    flexShrink: 0,
  },
  clear: {
    minHeight: 44,
    padding: 0,
    borderWidth: 0,
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
    color: colors.muted,
    backgroundColor: 'transparent',
    textDecoration: { default: 'none', ':hover': 'underline' },
  },
  apply: { minHeight: 44, minWidth: 200, borderRadius: 12, paddingInline: 24, fontSize: 14 },
  group: { borderWidth: 0, padding: 0, margin: 0, minWidth: 0 },
  choices: { display: 'grid', gap: 8, gridTemplateColumns: 'repeat(2,minmax(0,1fr))' },
  choice: {
    minHeight: 48,
    padding: '10px 12px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: 12,
    gap: 10,
    fontSize: 14,
    lineHeight: '20px',
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
  },
  selected: { borderColor: colors.text, backgroundColor: colors.controlSurface },
  checkbox: {
    borderColor: { default: colors.muted, ':checked': colors.text },
    backgroundColor: { default: colors.background, ':checked': colors.text },
  },
  flatChoices: { gridTemplateColumns: 'minmax(0,1fr)', gap: 0 },
  flatChoice: {
    minHeight: 40,
    padding: '8px 6px',
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: { default: 'transparent', ':hover': colors.surface },
  },
  flatSelected: { backgroundColor: colors.background },
  presets: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    gap: 8,
    marginTop: 16,
  },
  preset: {
    minHeight: 40,
    padding: '8px 12px',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.line,
    borderRadius: 10,
    color: colors.text,
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
  },
  presetSelected: {
    borderColor: colors.text,
    color: colors.background,
    backgroundColor: { default: colors.text, ':hover': colors.text },
  },
  copy: { color: colors.muted, fontSize: 14, lineHeight: '22px' },
  suggestions: { display: 'flex', flexDirection: 'column', gap: 4, marginTop: 16 },
  suggestion: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    minHeight: 48,
    padding: '8px 12px',
    borderWidth: 0,
    borderRadius: 10,
    fontSize: 14,
    lineHeight: '22px',
    color: colors.text,
    backgroundColor: { default: 'transparent', ':hover': colors.controlSurface },
    textAlign: 'left',
  },
  suggestionName: { flex: '1', minWidth: 0, fontWeight: 500 },
});
