import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';
import { showroomDesktop } from '@/styles/showroom-desktop-tokens.stylex';

// These new layout boxes exist only from the showroom's desktop breakpoint.
export const vehicleDesktop = stylex.create({
  layout: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'grid' },
    gridTemplateColumns: 'minmax(0,1fr) 360px',
    gridTemplateAreas: '"overview summary" "media summary" "details summary"',
    alignItems: 'start',
    gap: showroomDesktop.sectionGap,
    rowGap: 16,
    fontFamily: {
      default: 'inherit',
      '@media (min-width: 1024px)': '"Mobile UI", Arial, sans-serif',
    },
    padding: 24,
    paddingInline: showroomDesktop.gutter,
  },
  overview: {
    display: { default: 'none', '@media (min-width: 1024px)': 'block' },
    gridArea: 'overview',
    minWidth: 0,
  },
  media: { gridArea: 'media', minWidth: 0 },
  photoFrame: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'block' },
    position: 'relative',
  },
  photoControls: {
    display: { default: 'none', '@media (min-width: 1024px)': 'flex' },
    position: 'absolute',
    insetInline: 16,
    top: '50%',
    transform: 'translateY(-50%)',
    justifyContent: 'space-between',
    pointerEvents: 'none',
  },
  photoButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
    height: 44,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: '50%',
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
    color: colors.text,
    boxShadow: '0 2px 12px #00000012',
    pointerEvents: 'auto',
    cursor: 'pointer',
    outlineColor: colors.accent,
    outlineOffset: 3,
  },
  photoRail: {
    display: { default: 'none', '@media (min-width: 1024px)': 'flex' },
    gap: 10,
    marginTop: 12,
  },
  thumbnail: {
    position: 'relative',
    flex: '1',
    minWidth: 0,
    height: 76,
    padding: 0,
    overflow: 'hidden',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: { default: 'transparent', ':hover': colors.muted },
    borderRadius: 12,
    backgroundColor: colors.controlSurface,
    cursor: 'pointer',
    outlineColor: colors.accent,
    outlineOffset: 2,
  },
  selectedThumbnail: { borderColor: colors.text },
  thumbnailImage: { objectFit: 'cover' },
  photosLink: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    color: colors.text,
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 500,
    lineHeight: '18px',
    backgroundColor: { default: colors.controlSurface, ':hover': colors.surface },
  },
  summary: {
    display: { default: 'none', '@media (min-width: 1024px)': 'block' },
    gridArea: 'summary',
    minWidth: 0,
    alignSelf: 'start',
    position: {
      default: 'static',
      '@media (min-width: 1024px)': 'sticky',
      '@media (min-width: 1024px) and (max-height: 760px)': 'static',
    },
    top: 96,
    maxHeight: {
      default: 'none',
      '@media (min-width: 1024px)': 'calc(100dvh - 120px)',
      '@media (min-width: 1024px) and (max-height: 760px)': 'none',
    },
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarWidth: 'thin',
  },
  content: {
    display: { default: 'contents', '@media (min-width: 1024px)': 'block' },
    gridArea: 'details',
    minWidth: 0,
  },
});
