'use client';
import * as stylex from '@stylexjs/stylex';
import {media, tokens as $} from '@/app/tokens.stylex';

export const filterPaneStyles = stylex.create({
  desktopOnly: {display: {[media.desktop]: 'block', default: 'none'}},
  desktopHidden: {display: {[media.desktop]: 'none', default: 'flex'}},
  desktopChoices: {display: {[media.desktop]: 'grid', default: null}, gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 10},
  desktopPresets: {display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 8},
  desktopPreset: {minWidth: 0, minHeight: 44, paddingInline: 10, color: $.ink, fontFamily: $.fontSans, fontSize: $.desktopTextSize, fontWeight: $.desktopTextWeight, lineHeight: $.desktopTextLineHeight, whiteSpace: 'nowrap', borderWidth: 1, borderStyle: 'solid', borderColor: $.surfaceBorder, borderRadius: 10, backgroundColor: {default: $.surface, ':hover': $.surfaceAlt}, cursor: 'pointer'},
  desktopPresetSelected: {borderColor: $.ink, backgroundColor: {default: $.surfaceAlt, ':hover': $.line}},
  desktopPanel: {minWidth: {[media.desktop]: 0, default: null}, padding: {[media.desktop]: 20, default: null}, borderWidth: {[media.desktop]: 1, default: null}, borderStyle: {[media.desktop]: 'solid', default: null}, borderColor: {[media.desktop]: $.line, default: null}, borderRadius: {[media.desktop]: 12, default: null}, backgroundColor: {[media.desktop]: $.surfaceAlt, default: null}},
  desktopPanelCompact: {padding: {[media.desktop]: 14, default: null}},
  desktopRangeTitle: {marginBottom: 14, color: $.ink, fontSize: $.desktopTextSize, fontWeight: $.desktopEmphasisWeight, lineHeight: $.desktopTextLineHeight},
  desktopRangeSuggestions: {marginTop: 20, marginBottom: 10, color: $.ink, fontSize: $.desktopTextSize, fontWeight: $.desktopEmphasisWeight, lineHeight: $.desktopTextLineHeight},
  desktopFinanceCard: {display: 'flex', alignItems: 'center', gap: 12, minHeight: 52, marginTop: 16, padding: '10px 14px', color: $.ink, fontSize: $.desktopTextSize, fontWeight: $.desktopTextWeight, lineHeight: $.desktopTextLineHeight, textDecoration: 'none', borderWidth: 1, borderStyle: 'solid', borderColor: $.line, borderRadius: 10, backgroundColor: {default: $.surface, ':hover': $.surfaceAlt}, outlineOffset: 3},
  desktopFinanceLabel: {flexGrow: 1, minWidth: 0},
  tabletOnly: {display: {[media.tablet]: 'contents', default: 'none'}},
  phoneTabletContents: {display: {[media.desktop]: 'none', default: 'contents'}},
  desktopPayment: {display: 'block', maxWidth: 320},
  phoneTabletOnly: {display: {[media.desktop]: 'none', default: 'block'}},
  desktopModelSearch: {position: {[media.desktop]: 'sticky', default: null}, top: {[media.desktop]: 0, default: null}, zIndex: {[media.desktop]: 1, default: null}},
  // Keep 16px make names readable; narrower panes fit fewer cards per row.
  brandGrid: {display: {[media.desktop]: 'grid', default: 'contents'}, gridTemplateColumns: {[media.desktop]: 'repeat(auto-fill,minmax(min(100%,222px),1fr))', default: 'repeat(3,minmax(0,1fr))'}, alignItems: 'start', gap: 10},
  wideBrandGrid: {gridTemplateColumns: {[media.desktop]: 'repeat(2,minmax(0,1fr))', default: null}},
  brandGroup: {minWidth: 0, padding: {[media.desktop]: '4px 6px', default: 0}, borderWidth: {[media.desktop]: 1, default: 0}, borderStyle: 'solid', borderColor: {[media.desktop]: {default: $.line, ':hover': $.surfaceBorder}, default: $.line}, borderRadius: {[media.desktop]: 10, default: 0}, backgroundColor: {[media.desktop]: {default: $.surface, ':hover': $.surfaceAlt}, default: 'transparent'}},
  brandGroupExpanded: {backgroundColor: {[media.desktop]: $.surfaceAlt, default: null}},
  brandGroupExpandedWide: {gridColumn: {[media.desktop]: 'span 2', default: null}},
  brandGroupSelected: {borderColor: {[media.desktop]: $.surfaceBorder, default: null}, backgroundColor: {[media.desktop]: $.surfaceAlt, default: null}},
  modelDisclosure: {display: 'contents'},
  brandModels: {display: {[media.desktop]: 'grid', default: 'none'}, gridTemplateColumns: 'minmax(0,1fr)', gap: '6px 8px', marginTop: 4, marginBottom: 4, paddingTop: 10, borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: $.line},
  brandModelsWide: {gridTemplateColumns: 'repeat(2,minmax(0,1fr))'},
  desktopModelOption: {display: 'flex', alignItems: 'center', gap: 10, minWidth: 0, minHeight: 44, padding: '6px 10px', color: $.ink, fontSize: $.desktopTextSize, fontWeight: $.desktopTextWeight, lineHeight: $.desktopTextLineHeight, borderWidth: 1, borderStyle: 'solid', borderColor: {default: $.line, ':hover': $.surfaceBorder}, borderRadius: 8, backgroundColor: {default: $.surface, ':hover': $.surfaceAlt}, cursor: 'pointer'},
  desktopModelOptionSelected: {borderColor: $.surfaceBorder, backgroundColor: {default: $.violetSoft, ':hover': $.line}},
  desktopModelLabel: {minWidth: 0, overflowWrap: 'anywhere'},
  brandName: {display: {[media.desktop]: 'flex', default: null}, alignItems: {[media.desktop]: 'center', default: null}, minWidth: 0, color: {[media.desktop]: $.ink, default: null}, fontSize: {[media.desktop]: $.desktopTextSize, default: null}, fontWeight: {[media.desktop]: $.desktopTextWeight, default: null}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: null}, whiteSpace: {[media.desktop]: 'nowrap', default: null}},
  desktopBrandText: {minWidth: {[media.desktop]: 0, default: null}, overflow: {[media.desktop]: 'hidden', default: null}, textOverflow: {[media.desktop]: 'ellipsis', default: null}},
  desktopBrandLogo: {display: {[media.desktop]: 'block', default: 'none'}, flexShrink: 0, width: 22, height: 22},
  unstockedBrand: {display: {[media.desktop]: 'none', default: 'block'}},
  stockCount: {display: {[media.desktop]: 'inline', default: 'none'}, flexShrink: 0, marginLeft: 'auto', color: $.muted, fontSize: $.desktopLabelSize, fontWeight: {[media.desktop]: $.desktopTextWeight, default: null}, lineHeight: {[media.desktop]: $.desktopLabelLineHeight, default: null}, fontVariantNumeric: 'tabular-nums'},
  brandCount: {marginLeft: {[media.desktop]: 4, default: null}},
  desktopEngineRanges: {display: {[media.desktop]: 'grid', default: 'none'}, gridTemplateColumns: 'minmax(0,1fr)', gap: 16},
  phoneOnly: {display: {[media.mobile]: 'block', default: 'none'}},
  wideOnly: {display: {[media.mobile]: 'none', default: 'contents'}},
  mobileRangeTitle: {marginTop: 18, color: $.ink, fontSize: 14, fontWeight: 600, lineHeight: '21px'},
  mobileSuggestions: {marginTop: 18, marginBottom: 8, color: $.ink, fontSize: 14, fontWeight: 600, lineHeight: '21px'},
  mobilePresets: {display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 6},
  mobileLegacy: {display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 16},
  mobilePreset: {minWidth: 0, minHeight: 44, paddingInline: 4, color: $.ink, fontFamily: $.fontSans, fontSize: 13, fontWeight: 400, whiteSpace: 'nowrap', borderWidth: 0, borderRadius: $.radiusPill, backgroundColor: {default: $.surfaceAlt, ':hover': $.line}, cursor: 'pointer'},
  mobilePresetSelected: {color: '#fff', backgroundColor: {default: $.ink, ':hover': $.violetDark}},
  mobileOptions: {display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', columnGap: 12},
  pane: {maxWidth: {[media.desktop]: 720, default: null}, color: '#535353', fontFamily: $.fontSans},
  firstTitle: {marginTop: 8, marginBottom: 8, color: '#202024', fontSize: 14, fontWeight: 600, lineHeight: '21px'},
  brandTitle: {marginTop: {[media.desktop]: 20, default: 26}, marginBottom: {[media.desktop]: 10, default: 8}, color: '#202024', fontSize: {[media.desktop]: $.desktopTextSize, default: 14}, fontWeight: {[media.desktop]: $.desktopEmphasisWeight, default: 600}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '21px'}},
  brandRow: {display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 44px', columnGap: {[media.desktop]: 0, default: null}, minHeight: 44,},
  brandLabel: {display: 'flex', alignItems: 'center', gap: {[media.desktop]: 4, default: 9}, minWidth: 0, paddingLeft: {[media.desktop]: 7, default: null}, color: '#535353', fontSize: {[media.desktop]: $.desktopTextSize, default: 15}, fontWeight: {[media.desktop]: $.desktopTextWeight, default: null}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '23px'}, cursor: 'pointer'},
  expand: {display: 'grid', alignItems: 'center', justifyItems: {[media.desktop]: 'end', default: 'center'}, width: 44, minHeight: 44, padding: 0, color: $.ink, borderWidth: 0, borderRadius: {[media.desktop]: 8, default: null}, backgroundColor: 'transparent', cursor: 'pointer'},
  expandContent: {display: {[media.desktop]: 'grid', default: 'contents'}, placeItems: 'center', width: {[media.desktop]: 32, default: null}, height: {[media.desktop]: 32, default: null}, borderRadius: {[media.desktop]: 8, default: null}, backgroundColor: {[media.desktop]: {default: 'transparent', ':hover': $.line}, default: null}},
  expandChevron: {width: {[media.desktop]: 18, default: null}, height: {[media.desktop]: 18, default: null}},
  expandOpen: {backgroundColor: {[media.desktop]: {default: $.surface, ':hover': $.line}, default: 'transparent'}},
  rotate: {transform: 'rotate(180deg)'},
  models: {paddingLeft: 26,},
  emptyModels: {paddingBlock: 12, color: '#727272', fontSize: {[media.desktop]: $.desktopSupportSize, default: 12}, lineHeight: {[media.desktop]: '20px', default: '18px'}},
  option: {display: 'flex', alignItems: 'center', gap: 10, minHeight: {[media.desktop]: 48, default: 44}, padding: {[media.desktop]: '8px 12px', default: null}, color: {[media.desktop]: $.ink, default: '#535353'}, fontSize: {[media.desktop]: $.desktopTextSize, default: 14}, fontWeight: {[media.desktop]: $.desktopTextWeight, default: 400}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '22px'}, borderWidth: {[media.desktop]: 1, default: 0}, borderStyle: 'solid', borderColor: {[media.desktop]: {default: $.line, ':hover': $.controlBorder}, default: 'transparent'}, borderRadius: {[media.desktop]: 10, default: 0}, backgroundColor: {[media.desktop]: {default: $.surface, ':hover': $.surfaceAlt}, default: 'transparent'}, cursor: 'pointer'},
  optionLabel: {minWidth: {[media.desktop]: 0, default: null}},
  optionSelected: {borderColor: {[media.desktop]: $.ink, default: null}, backgroundColor: {[media.desktop]: $.surfaceAlt, default: null}},
  optionLarge: {minHeight: {[media.desktop]: 48, default: 49}, fontSize: {[media.desktop]: $.desktopTextSize, default: 15}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '26px'}},
  optionMultiline: {alignItems: {[media.desktop]: 'center', default: 'flex-start'}, minHeight: {[media.desktop]: 48, default: 65}, paddingTop: {[media.desktop]: 8, default: 12}, fontSize: {[media.desktop]: $.desktopTextSize, default: 15}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '25px'}},
  loan: {display: 'flex', alignItems: 'center', gap: 8, minHeight: 51, paddingInline: 11, color: '#101010', fontSize: 12, lineHeight: '17px', borderColor: '#e7e7e7', borderStyle: 'solid', borderWidth: 1, borderRadius: 9, backgroundColor: '#f8f8f8'},
  suggestions: {marginTop: 18, marginBottom: 8, color: '#202024', fontSize: 14, fontWeight: 600, lineHeight: '21px'},
  rangeTitle: {marginTop: 26, color: '#202024', fontSize: 14, fontWeight: 600, lineHeight: '21px'},
  desktopMileageChoices: {display: {[media.desktop]: 'grid', default: 'none'}, gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 8},
  phoneTabletMileage: {display: {[media.desktop]: 'none', default: 'contents'}},
  emiInput: {display: 'flex', alignItems: 'center', gap: 8, width: 164, height: 51, marginTop: 18, paddingLeft: 14, color: '#5f5f5f', fontSize: 15, borderColor: '#c4c4c4', borderStyle: 'solid', borderWidth: 1, borderRadius: {[media.desktop]: 10, default: 4}, outline: {default: 'none', ':focus-within': {[media.desktop]: '2px solid #202024', default: 'none'}}, outlineOffset: 2},
  emiNumber: {width: '100%', minWidth: 0, height: 43, marginLeft: 5, paddingLeft: 10, color: '#535353', fontSize: {[media.mobile]: 16, default: 15}, borderWidth: 0, outline: {default: 'none', ':focus-visible': {[media.desktop]: 'none', default: '2px solid #202024'}}, outlineOffset: 3, backgroundColor: 'transparent'},
  bodies: {display: 'grid', gridTemplateColumns: {[media.desktop]: 'repeat(3,minmax(0,1fr))', default: 'repeat(2,minmax(0,1fr))'}, gap: {[media.desktop]: 10, default: '12px 20px'}, marginTop: {[media.desktop]: 0, default: 8}, marginLeft: {[media.desktop]: 0, default: -4}, marginRight: {[media.desktop]: 0, default: -4}},
  wideBodies: {gridTemplateColumns: {[media.desktop]: 'repeat(2,minmax(0,1fr))', default: null}},
  bodyCount: {display: {[media.desktop]: 'block', default: 'none'}, color: $.muted, fontSize: $.desktopLabelSize, fontWeight: $.desktopTextWeight, lineHeight: $.desktopLabelLineHeight},
  body: {display: 'flex', alignItems: 'center', justifyContent: 'flex-start', flexDirection: 'column', gap: 4, minHeight: 91, padding: '8px 6px', color: '#202024', fontSize: {[media.desktop]: $.desktopTextSize, default: 13}, fontWeight: {[media.desktop]: $.desktopTextWeight, default: 500}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: '17px'}, textAlign: 'center', borderColor: {[media.desktop]: $.surfaceBorder, default: '#c6c6c6'}, borderStyle: 'solid', borderWidth: 1, borderRadius: 12, backgroundColor: '#fff', cursor: 'pointer'},
  bodyActive: {color: {[media.desktop]: $.ink, default: $.violet}, borderColor: {[media.desktop]: $.ink, default: $.violet}, backgroundColor: {[media.desktop]: $.surfaceAlt, default: $.violetSoft}},
  // Blend the captured white image canvas into the selected card.
  bodyImage: {width: 82, maxWidth: '100%', height: 43, objectFit: 'contain', mixBlendMode: 'multiply'},
  types: {display: {[media.desktop]: 'grid', default: null}, gap: 10, paddingInline: {[media.desktop]: 0, default: 2}},
  type: {display: 'grid', gridTemplateColumns: {[media.desktop]: '19px minmax(0,1fr) auto', default: '19px minmax(0,1fr)'}, alignItems: {[media.desktop]: 'center', default: 'start'}, gap: 9, minHeight: {[media.desktop]: 48, default: null}, padding: {[media.desktop]: '10px 12px', default: '18px 6px 22px'}, color: {[media.desktop]: $.ink, default: null}, fontSize: {[media.desktop]: $.desktopTextSize, default: null}, lineHeight: {[media.desktop]: $.desktopTextLineHeight, default: null}, borderWidth: {[media.desktop]: 1, default: 0}, borderStyle: 'solid', borderColor: $.line, borderRadius: {[media.desktop]: 10, default: 0}, backgroundColor: {[media.desktop]: {default: $.surface, ':hover': $.surfaceAlt}, default: null}, cursor: 'pointer'},
  typeTitle: {fontSize: {[media.desktop]: $.desktopTextSize, default: null}, fontWeight: {[media.desktop]: $.desktopTextWeight, default: null}},
  typeCopy: {display: {[media.desktop]: 'none', default: 'block'}, marginTop: {[media.desktop]: 4, default: 9}, color: {[media.desktop]: $.muted, default: '#202024'}, fontSize: 12, fontWeight: 400, lineHeight: '18px'},
  engineHint: {marginTop: 6, color: $.muted, fontSize: 12, fontWeight: 400, lineHeight: '18px'},
});
