// Generated by Cars native configuration adapter; change dealer.json, not this file.
export const carsLocale = {
  "schemaVersion": 1,
  "dealerId": "stockport-broadbent-car-and-servicing",
  "defaultLocale": "en",
  "enabledLocales": [
    "en",
    "bg"
  ],
  "dealerCountry": "GB",
  "inventoryCurrency": "GBP"
} as const;
