import {chromium} from 'playwright';import fs from 'node:fs/promises';import crypto from 'node:crypto';import {load} from 'cheerio';
const browser=await chromium.connectOverCDP(process.argv[2]);const ctx=browser.contexts()[0];const page=ctx.pages()[0];const base='https://shop.creativemox.com/nusavo/';
const assets=JSON.parse(await fs.readFile('reference/assets.json','utf8'));const wanted=new Set();
function want(url,from=base){if(!url||url.startsWith('data:')||url.startsWith('#')||url.startsWith('%23'))return;try{wanted.add(new URL(url,from).href.replace(/^http:/,'https:'))}catch{}}
for(const f of await fs.readdir('reference/pages')){if(!f.endsWith('.html')||f.includes('.rendered.'))continue;const $=load(await fs.readFile('reference/pages/'+f,'utf8'));$('link[rel=stylesheet]').each((i,e)=>want($(e).attr('href')));$('img').each((i,e)=>want($(e).attr('src')));$('style,[style]').each((i,e)=>{const css=e.name==='style'?$(e).text():$(e).attr('style');for(const m of css.matchAll(/url\(["']?([^)'"\s]+)["']?\)/g))want(m[1])});}
async function download(url){if(assets[url])return;try{const r=await ctx.request.get(url,{timeout:20000});if(!r.ok())throw Error(r.status());const name=decodeURIComponent(new URL(url).pathname.split('/').pop()).replace(/[^a-zA-Z0-9._-]/g,'-');const local='/assets/'+crypto.createHash('sha1').update(url).digest('hex').slice(0,10)+'-'+name;await fs.writeFile('public'+local,await r.body());assets[url]=local;}catch(e){console.log('missing',url,e.message)}}
for(let pass=0;pass<3;pass++){for(const [url,local] of Object.entries(assets)){if(local.endsWith('.css')||url.includes('fonts.googleapis.com')){const css=await fs.readFile('public'+local,'utf8');for(const m of css.matchAll(/url\(["']?([^)'"\s]+)["']?\)/g))want(m[1],url)}}const list=[...wanted].filter(u=>!assets[u]);console.log('pass',pass,'fetch',list.length);let idx=0;await Promise.all(Array.from({length:8},async()=>{while(idx<list.length)await download(list[idx++])}));}
await fs.writeFile('reference/assets.json',JSON.stringify(assets,null,2));console.log('saved',Object.keys(assets).length);await browser.close();

