import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const browser=process.argv[2]==="standalone"?await chromium.launch({headless:true,channel:"chrome"}):await chromium.connectOverCDP(process.argv[2]);
const context=browser.contexts()[0]||await browser.newContext();
const base='https://shop.creativemox.com/nusavo/';
await fs.mkdir('reference/pages',{recursive:true});await fs.mkdir('public/assets',{recursive:true});
const assets=JSON.parse(await fs.readFile("reference/assets.json","utf8").catch(()=>"{}"));const pending=[];
function assetPath(url){let u=new URL(url);let name=decodeURIComponent(u.pathname.split('/').pop()).replace(/[^a-zA-Z0-9._-]/g,'-');return '/assets/'+crypto.createHash('sha1').update(url).digest('hex').slice(0,10)+'-'+name;}
context.on('response',r=>{const type=r.request().resourceType();if(!['stylesheet','image','font','media'].includes(type)||!r.ok())return;const url=r.url();if(assets[url])return;const local=assetPath(url);assets[url]=local;pending.push(r.body().then(b=>fs.writeFile('public'+local,b)).catch(()=>{delete assets[url]}));});
const routes=[['home',''],['about-us','about-us/'],['our-team','our-team/'],['services','services/'],['car-listing','?elementor_library=nusavo-listing-car'],['contact-us','contact-us/'],['faq','faq/'],['blog','?elementor_library=nusavo-blog-archive'],['single-post','self-drive-or-chauffeur-rental-which-is-better/'],['404','?elementor_library=nusavo-error-404'],['my-account','my-account/'],...['urbango-hatchback','evolve-electric-suv','prestige-executive','terrax-suv','grandis-mpv','veloce-sedan','voyager-minivan','trailmark-4x4'].map(s=>[s,'car-listing/'+s+'/']),['cart','cart/'],['checkout','checkout/'],['purchase-summary','?elementor_library=nusavo-purchase-summary']];
routes.push(...["airport-car-rental-guide-for-international-travelers","best-car-rental-options-for-family-vacations","car-rental-requirements-for-foreign-tourists-in-indonesia","best-cars-to-rent-for-a-bali-road-trip","how-to-rent-a-car-in-indonesia-easily"].map(s=>[s,s+"/"]));routes.push(...["airport-rental","family-travel","bali-travel","driving-guide","rental-guide","rental-tips"].map(s=>[s,"category/"+s+"/"]),["babyhepi","author/babyhepi/"],["date-archive","2026/07/27/"],["lost-password","my-account/lost-password/"]);const results=JSON.parse(await fs.readFile("reference/routes.json","utf8").catch(()=>"[]")); if(process.argv[3]){const keep=process.argv[3].split(",");routes.splice(0,routes.length,...routes.filter(r=>keep.includes(r[0])))};let index=0;
async function worker(){const page=await context.newPage();await page.setViewportSize({width:1440,height:1000});while(index<routes.length){const [slug,route]=routes[index++];try{const r=await page.goto(base+route,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(2000);await page.evaluate(async()=>{await document.fonts.ready;for(const el of document.querySelectorAll('img'))el.loading='eager';window.scrollTo(0,document.body.scrollHeight)});await page.waitForTimeout(650);await page.evaluate(()=>window.scrollTo(0,0));await fs.writeFile(`reference/pages/${slug}.html`,await r.text());await fs.writeFile(`reference/pages/${slug}.rendered.html`,await page.content());await page.screenshot({path:`reference/pages/${slug}-desktop.png`,fullPage:true});const data=await page.evaluate(()=>({title:document.title,headings:[...document.querySelectorAll('h1,h2,h3')].map(e=>e.textContent.trim()),links:[...new Set([...document.links].map(a=>a.href))],bodyClass:document.body.className}));results.push({slug,source:base+route,url:page.url(),status:r.status(),...data});console.log(slug,r.status(),data.title);}catch(e){console.log('ERROR',slug,e.message)} }await page.close();}
await Promise.all([worker(),worker(),worker()]);await Promise.all(pending);await fs.writeFile('reference/assets.json',JSON.stringify(assets,null,2));await fs.writeFile('reference/routes.json',JSON.stringify(results,null,2));console.log('assets',Object.keys(assets).length);await browser.close();




