import {chromium} from 'playwright';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
function check(ok,name){if(!ok)throw Error(name);checks.push(name);console.log('PASS',name)}
async function open(path){await page.goto('http://127.0.0.1:6420'+path,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready)}
try{
await open('/');const toggle=page.locator('.elementor-menu-toggle');await toggle.click();check(await page.locator('.elementor-nav-menu--dropdown.elementor-nav-menu__container').getAttribute('aria-hidden')==='false','Mobile menu opens accessibly');await page.screenshot({path:'reference/qa/mobile-menu.png'});await page.keyboard.press('Escape');check(await toggle.getAttribute('aria-expanded')==='false','Escape closes menu');await toggle.focus();await page.keyboard.press('Enter');check(await toggle.getAttribute('aria-expanded')==='true','Keyboard opens menu');await page.keyboard.press('Escape');
check(await page.locator('.elementor-widget-loop-carousel .swiper').evaluate(el=>!!el.swiper),'Fleet carousel initialized');
check(await page.locator('.elementor-widget-image-carousel img').first().evaluate(el=>el.getBoundingClientRect().width>0),'Partner logos visible');
await open('/car-listing/');await page.locator('[data-filter="electric"]').click();check(await page.locator('.elementor-widget-loop-grid .e-loop-item:visible').count()===1,'Fleet category filters to one electric car');await page.locator('[data-filter="__all"]').click();check(await page.locator('.elementor-widget-loop-grid .e-loop-item:visible').count()===8,'All filter restores eight cars');
await open('/faq/');const second=page.locator('details').nth(1);await second.locator('summary').click();check(await second.getAttribute('open')!==null,'FAQ expands');await second.locator('summary').click();check(await second.getAttribute('open')===null,'FAQ collapses');
await open('/car-listing/urbango-hatchback/');await page.locator('.woocommerce-product-gallery a').first().click();check(await page.locator('.image-viewer img').isVisible(),'Vehicle image opens');await page.keyboard.press('Escape');check(await page.locator('.image-viewer').count()===0,'Image closes with Escape');
await open('/cart/?add=802');check((await page.locator('.cart_item').textContent()).includes('Evolve Electric SUV'),'Book action adds correct vehicle');await page.locator('.qty').fill('2');await page.locator('.qty').blur();check((await page.locator('.order-total').textContent()).includes('194.00'),'Quantity recalculates total');await page.reload({waitUntil:'networkidle'});check(await page.locator('.qty').inputValue()==='2','Cart survives reload');await page.locator('button.remove').click();check(await page.locator('.cart-empty').isVisible(),'Remove restores empty cart');
await open('/cart/?add=746');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'reference/qa/cart-filled-1440.png',fullPage:true});await page.locator('.checkout-button').click();await page.waitForURL('**/checkout/');await page.screenshot({path:'reference/qa/checkout-filled-1440.png',fullPage:true});await page.locator('#place_order').click();check(page.url().endsWith('/checkout/'),'Checkout prevents empty required fields');
for(const [id,value] of Object.entries({billing_first_name:'Preview',billing_last_name:'Guest',billing_address_1:'1 Example Street',billing_city:'Los Angeles',billing_postcode:'90001',billing_email:'preview@example.com'}))await page.locator('#'+id).fill(value);
await page.locator('#place_order').click();await page.waitForURL('**/purchase-summary/');await page.locator('.woocommerce-thankyou-order-received').waitFor();check((await page.locator('body').textContent()).includes('No reservation or payment has been submitted'),'Checkout reaches honest local summary');
await open('/contact-us/');const form=page.locator('form.elementor-form').first();await form.locator('input[type=email]').fill('preview@example.com');for(const input of await form.locator('input[type=text][required]').all())await input.fill('Preview request');await form.locator('button[type=submit]').click();await page.locator('.preview-notice').waitFor();check(await page.locator('.preview-notice').isVisible(),'Contact form provides local feedback');
check(errors.length===0,'No JavaScript errors during flows');
}catch(e){console.log('FAIL',e.message);await page.screenshot({path:'reference/qa/flow-failure.png',fullPage:true});errors.push(e.message);process.exitCode=1}finally{await fs.writeFile('reference/qa/flows.json',JSON.stringify({checks,errors},null,2));await browser.close()}


