import {chromium} from 'playwright';import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext();
const routes=[...new Map(JSON.parse(await fs.readFile('reference/routes.json','utf8')).map(r=>[r.slug,r])).values()].filter(r=>r.status===200);
await fs.mkdir('reference/qa',{recursive:true});const result=[];let index=0;
let tasks=routes.flatMap(r=>[1440,390].map(width=>({r,width})));
if(process.argv[2]){const slugs=process.argv[2].split(',');tasks=tasks.filter(t=>slugs.includes(t.r.slug));}
async function worker(){const page=await context.newPage();while(index<tasks.length){const {r,width}=tasks[index++];let errors=[],failed=[];const error=e=>errors.push(e.message);const response=r=>{if(r.status()>=400)failed.push(r.url()+' '+r.status())};page.on('pageerror',error);page.on('response',response);await page.setViewportSize({width,height:1000});const route=r.slug==='home'?'':r.slug;try{await page.goto('http://127.0.0.1:6420/'+route+'/',{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>[...document.images].every(i=>i.complete),{timeout:15000});await page.waitForTimeout(250);const metrics=await page.evaluate(()=>({title:document.title,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,h1:[...document.querySelectorAll('h1')].map(e=>({text:e.textContent,box:{x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}})),brokenImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),external:[...document.querySelectorAll('img,link[rel=stylesheet]')].map(e=>e.src||e.href).filter(u=>u?.startsWith('https:'))}));await page.screenshot({path:`reference/qa/${r.slug}-${width}.png`,fullPage:true});result.push({slug:r.slug,...metrics,errors,failed});console.log(r.slug,width,metrics.scrollWidth>width?'OVERFLOW':'OK','images',metrics.brokenImages.length,'errors',errors.length,'failed',failed.length)}catch(e){result.push({slug:r.slug,width,error:e.message});console.log('FAIL',r.slug,width,e.message)}page.off('pageerror',error);page.off('response',response)}await page.close()}
await Promise.all([worker(),worker(),worker()]);const prior=JSON.parse(await fs.readFile('reference/qa/results.json','utf8').catch(()=>'[]'));const combined=process.argv[2]?[...prior.filter(p=>!result.some(r=>r.slug===p.slug&&r.width===p.width)),...result]:result;await fs.writeFile('reference/qa/results.json',JSON.stringify(combined,null,2));await browser.close();


