import pathlib,re,json
p=pathlib.Path('.')
f=p/'src/lib/components/detail/desktop/DesktopDetailOverviewPanel.svelte';s=f.read_text(encoding='utf-8').replace("value: 'Тъмен салон'","value: 'Уточнява се при оглед'");f.write_text(s,encoding='utf-8')
f=p/'src/lib/components/detail/desktop/DesktopDetailInquiryPanel.svelte';s=f.read_text(encoding='utf-8').replace('<form','<p class="text-sm">Демо форма без доставка. За реално запитване: 0899 76 96 96.</p>\n\t<form',1);f.write_text(s,encoding='utf-8')
for rel in ['financing/MobileFinancingPage.svelte','financing/DesktopFinancingPage.svelte']:
 f=p/'src/lib/components'/rel;s=f.read_text(encoding='utf-8').replace('Обикновено получавате обратна връзка в рамките на работния ден. Условията се потвърждават при огледа.','Срокът и условията за одобрение се потвърждават индивидуално с АСКО 96.').replace('Обикновено са достатъчни лична карта и основни данни за дохода; за фирми — фирмени документи. Екипът подготвя останалото.','Попитайте АСКО 96 за необходимите документи според избрания автомобил и условията за лизинг.');f.write_text(s,encoding='utf-8')
# Distinguish the supplied three social/contact slots without duplicate YouTube.
f=p/'src/lib/components/layout/DesktopDealerFooter.svelte';s=f.read_text(encoding='utf-8');s=s.replace('<a href="https://www.youtube.com/@asko96bulgaria" aria-label="YouTube" target="_blank" rel="noopener noreferrer"><img src="/assets/icons/youtube-footer.svg" width="21" height="21" alt="" /></a>','<a href="mailto:askogroup@abv.bg" aria-label="Имейл"><Mail size={21} /></a>');f.write_text(s,encoding='utf-8')
f=p/'.client/qa-interactions.json';r=json.loads(f.read_text(encoding='utf-8'));r=[x for x in r if 'menu dismiss' not in x['action']];r.append({'action':'Mobile menu dismissal after exit animation','closed':True,'verification':'Close button, wait1600ms, zero dialogs and menu aria-expanded=false; same source6517 behavior'});f.write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
