import { nativeContract, nativeText, nativeWrite, sealNativeAdoption } from '../lib/native-localization.mjs';

// These are configuration adapters, not URL/proxy/HTML translation transforms.
// Every application continues to own its request handling and rendered catalogs.
export const NATIVE_MOUNTS = Object.freeze({
  'auto-best': { base: '', environment: null },
  modern: { base: '/variant-2', environment: 'NEXT_PUBLIC_BASE_PATH' },
  import: { base: '/variant-2', environment: 'TEMPLATE_BASE_PATH' },
  carwow: { base: '/variant-3', environment: 'DAY_LOCALE_BASE' }
});
function objectSegments(text, from) {
  const stack = ['{'], parts = []; let start = from + 1;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if ('\'"`'.includes(ch)) {
      const quote = ch; let closed = false;
      for (++i; i < text.length; i++) {
        if (text[i] === '\\') { i++; continue; }
        if (quote === '`' && text.slice(i, i + 2) === '${') throw new Error('Computed configuration requires an upstream adapter review');
        if (text[i] === quote) { closed = true; break; }
      }
      if (!closed) throw new Error('Unterminated configuration string');
    } else if (text.slice(i, i + 2) === '//') { i = text.indexOf('\n', i); if (i < 0) break; }
    else if (text.slice(i, i + 2) === '/*') { i = text.indexOf('*/', i + 2); if (i < 0) break; i++; }
    else if ('{[('.includes(ch)) stack.push(ch);
    else if ('}])'.includes(ch)) {
      if ('}])'['{[('.indexOf(stack.pop())] !== ch) throw new Error('Unbalanced configuration');
      if (!stack.length) { parts.push([start, i]); return { parts, close: i }; }
    } else if (ch === ',' && stack.length === 1) { parts.push([start, i]); start = i + 1; }
  }
  throw new Error('Unterminated native configuration object');
}
export function configureObject(text, exported, replacements) {
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(exported)) throw new Error('Invalid configuration binding');
  const headers = [...text.matchAll(new RegExp(`export const ${exported}(?:\\s*:[^=]+)?\\s*=\\s*\\{`, 'g'))];
  if (headers.length !== 1) throw new Error(`Expected one native configuration export: ${exported}`);
  const header = headers[0], open = header.index + header[0].length - 1;
  const edits = [], found = new Set();
  for (const [start, end] of objectSegments(text, open).parts) {
    const segment = text.slice(start, end);
    if (/^\s*\.\.\./.test(segment)) throw new Error('Spread configuration requires an upstream adapter review');
    const field = segment.match(/^(?:(?:\s+)|(?:\/\/[^\n]*\n)|(?:\/\*[\s\S]*?\*\/))*([A-Za-z][A-Za-z0-9]*)\s*:\s*/);
    if (!field || !Object.hasOwn(replacements, field[1])) continue;
    if (found.has(field[1])) throw new Error(`Duplicate native configuration field: ${field[1]}`);
    found.add(field[1]);
    const last = end - (segment.match(/\s*$/)?.[0].length || 0);
    edits.push({ start: start + field[0].length, end: last, value: replacements[field[1]] });
  }
  for (const name of Object.keys(replacements)) if (!found.has(name)) throw new Error(`Missing native configuration field ${exported}.${name}; return this incompatibility to the template owner`);
  for (const edit of edits.reverse()) text = text.slice(0, edit.start) + edit.value + text.slice(edit.end);
  return text;
}
const generatedContract = contract => '// Generated by Cars native configuration adapter; change dealer.json, not this file.\nexport const carsLocale = ' + JSON.stringify(contract, null, 2) + ' as const;\n';
const contractFields = ['schemaVersion', 'dealerId', 'defaultLocale', 'enabledLocales', 'dealerCountry', 'inventoryCurrency'];
const contractMap = Object.fromEntries(contractFields.map(key => [key, `carsLocale.${key}`]));
function bindConfiguration(files, name, exported, replacements, contract) {
  let text = nativeText(files, name);
  const generated = name.slice(0, name.lastIndexOf('/') + 1) + 'cars-locale.ts';
  const statement = "import { carsLocale } from './cars-locale';";
  if (files.has(generated) && !nativeText(files, generated).startsWith('// Generated by Cars native configuration adapter;')) throw new Error(`Occupied configuration module: ${generated}`);
  if (!text.includes(statement)) {
    if (/\bcarsLocale\b/.test(text)) throw new Error(`Unknown native configuration binding in ${name}`);
    text = statement + '\n' + text;
  }
  nativeWrite(files, name, configureObject(text, exported, replacements));
  nativeWrite(files, generated, generatedContract(contract));
}
function headSwitcher(files, name, jsx = false) {
  let text = nativeText(files, name);
  if (text.includes('preview-switcher.js')) {
    if ((text.match(/preview-switcher\.js/g) || []).length !== 1 || !text.includes('src="/preview-switcher.js"')) throw new Error(`Unknown design switcher in ${name}`);
    return;
  }
  const before = jsx ? '<head>' : '</head>';
  if (text.split(before).length !== 2) throw new Error(`Missing native head boundary: ${name}`);
  const after = jsx ? '<head>\n        <script defer src="/preview-switcher.js" />' : '  <script defer src="/preview-switcher.js"></script>\n</head>';
  nativeWrite(files, name, text.replace(before, after));
}
export function applyNativeMounts(inputFiles, manifest) {
  const files = new Map(inputFiles);
  const contract = nativeContract(manifest);
  for (const { key, base } of manifest.variants) {
    if (NATIVE_MOUNTS[key]?.base !== base) throw new Error(`Unsupported native mount: ${key}`);
    if (files.has(`${key}/src/lib/preview-paths.ts`)) throw new Error(`${key}: legacy mounting helper cannot be mixed with native v2`);
    if (key === 'modern') {
      if (!nativeText(files, 'modern/apps/web/next.config.ts').includes('nextConfig.basePath = publicBasePath') ||
          !nativeText(files, 'modern/packages/internationalization/paths.ts').includes('NEXT_PUBLIC_BASE_PATH')) throw new Error('Modern lacks its native build-time basePath contract');
      const proxy = nativeText(files, 'modern/apps/web/proxy.ts');
      if (proxy.includes('x-dealer-locale-rewrite') || !proxy.includes('createLocaleRequestHandler')) throw new Error('Modern native request handling is missing or was replaced by legacy mounting');
      bindConfiguration(files, 'modern/apps/web/lib/locale-configuration.ts', 'localeConfiguration', contractMap, contract);
      bindConfiguration(files, 'modern/packages/marketplace/lead-site.ts', 'leadSite', {
        publicDefaultLocale: 'carsLocale.defaultLocale', publicLocales: 'carsLocale.enabledLocales',
        countryCode: 'carsLocale.dealerCountry', currency: 'carsLocale.inventoryCurrency'
      }, contract);
      bindInternationalizationDefaults(files, contract);
      headSwitcher(files, 'modern/apps/web/app/[locale]/layout.tsx', true);
    } else {
      if (key !== 'auto-best' && !nativeText(files, `${key}/svelte.config.js`).includes(NATIVE_MOUNTS[key].environment)) throw new Error(`${key}: native build-time mount configuration is missing`);
      if (key === 'auto-best') bindConfiguration(files, 'auto-best/src/lib/config/locale.ts', 'dealerLocaleConfiguration', contractMap, contract);
      if (key === 'carwow') bindConfiguration(files, 'carwow/src/lib/locale/config.ts', 'dealerLocaleConfiguration', contractMap, contract);
      if (key === 'import') {
        bindConfiguration(files, 'import/src/lib/locale/core.ts', 'localeConfiguration', { dealerId: 'carsLocale.dealerId' }, contract);
        bindConfiguration(files, 'import/src/lib/config/dealer.ts', 'dealerLocaleSettings', {
          default: 'carsLocale.defaultLocale', supported: 'carsLocale.enabledLocales',
          country: 'carsLocale.dealerCountry', currency: 'carsLocale.inventoryCurrency'
        }, contract);
      }
      headSwitcher(files, `${key}/src/app.html`);
    }
  }
  return files;
}
function bindInternationalizationDefaults(files, contract) {
  const name = 'modern/packages/internationalization/config.ts';
  let text = nativeText(files, name);
  const statement = "import { carsLocale } from './cars-locale';";
  const locales = /export const locales\s*=\s*(?:\[[^\]]+\]\s+as const|carsLocale\.enabledLocales)\s*;/g;
  const defaultLocale = /export const defaultLocale\s*=\s*(?:["'](?:en|bg)["']|carsLocale\.defaultLocale)\s+satisfies Locale\s*;/g;
  if ([locales, defaultLocale].some(pattern => [...text.matchAll(pattern)].length !== 1)) throw new Error('Modern internationalization defaults require a reviewed configuration adapter');
  if (!text.includes(statement)) {
    if (/\bcarsLocale\b/.test(text)) throw new Error('Unknown Modern internationalization configuration binding');
    text = statement + '\n' + text;
  }
  text = text.replace(locales, 'export const locales = carsLocale.enabledLocales;')
    .replace(defaultLocale, 'export const defaultLocale = carsLocale.defaultLocale satisfies Locale;');
  const generated = 'modern/packages/internationalization/cars-locale.ts';
  if (files.has(generated) && !nativeText(files, generated).startsWith('// Generated by Cars native configuration adapter;')) throw new Error('Occupied Modern locale configuration module');
  nativeWrite(files, name, text);
  nativeWrite(files, generated, generatedContract(contract));
}
export function adoptNativeSource(files, manifest, releases) {
  const adopted = applyNativeMounts(files, manifest);
  sealNativeAdoption(adopted, manifest, releases);
  return adopted;
}
