// Generated by Cars native configuration adapter; change dealer.json, not this file.
export const carsLocale = {
  "schemaVersion": 1,
  "dealerId": "us-tx-dallas-texas-drive-auto",
  "defaultLocale": "en",
  "enabledLocales": [
    "en",
    "bg"
  ],
  "dealerCountry": "US",
  "inventoryCurrency": "USD"
} as const;
