import fs from 'node:fs/promises';import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const root='J:/cars/clients/astracar';const cards=JSON.parse(await fs.readFile(root+'/evidence/cards.json')).filter(c=>c.title&&!/части|ударен|продаден/i.test(c.title)).slice(0,16);const stock=[];const provenance=[];
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();
async function download(url,name){const r=await fetch(url);if(!r.ok)throw Error(`${r.status} ${url}`);await fs.writeFile(root+'/assets/'+name,Buffer.from(await r.arrayBuffer()));provenance.push({file:name,url,capturedAt:new Date().toISOString(),modification:'none; source watermarks retained'});return '/assets/astracar/'+name;}
for(let i=0;i<cards.length;i++){const c=cards[i];const raw=c.parts.find(x=>x.cls==='params').text;const price=Number(c.parts[0].text.match(/([\d ]+)\s*€/)[1].replaceAll(' ',''));const id=c.url.match(/obiava-(\d+)/)[1];
await p.goto(c.url,{waitUntil:'domcontentloaded',timeout:40000});const detail=await p.evaluate(()=>({url:location.href,text:document.body.innerText,images:[...document.images].map(i=>i.src).filter(u=>u.includes('photosorg'))}));await fs.writeFile(root+'/evidence/detail-'+id+'.json',JSON.stringify(detail,null,2));
const images=[];for(const [n,url] of [...new Set([...c.images,...detail.images])].slice(0,5).entries())images.push(await download(url,`vehicle-${String(i+1).padStart(2,'0')}-${n+1}.webp`));
const make=c.title.startsWith('Mercedes-Benz')?'Mercedes-Benz':c.title.split(' ')[0];const fuel=raw.includes('Дизелов')?'Дизел':raw.includes('Хибриден')?'Хибрид':raw.includes('Електрически')?'Електрически':'Бензин';const year=Number(raw.match(/(20\d\d|19\d\d) г\./)[1]);const mileageKm=Number(raw.match(/г\.\s*([\d ]+) км/)[1].replaceAll(' ',''));const bodyBg=raw.match(/(Хечбек|Джип|Седан|Комби|Купе|Кабрио|Ван|Пикап)$/)?.[1]||'Друг';
stock.push({id,title:c.title,fullTitle:c.title,make,model:c.title.slice(make.length).trim(),year,mileageKm,priceEur:price,fuel,transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',body:({Хечбек:'Hatchback',Джип:'SUV',Седан:'Sedan',Комби:'Wagon',Купе:'Coupe',Кабрио:'Convertible',Ван:'Minivan',Пикап:'Pickup Truck'})[bodyBg]||'Other',bodyBg,powerHp:Number(raw.match(/(\d+) к\.с\./)?.[1]||0),engineCc:Number(raw.match(/(\d+) куб\.см/)?.[1]||0),color:raw.match(/км\s+(.*?)\s+(?:Дизелов|Бензинов|Хибриден|Електрически)/)?.[1]||'Не е посочен',date:raw.split('г.')[0]+'г.',vat:c.parts[0].text.includes('включено ДДС')?'Цената е с включено ДДС':'ДДС: виж оригиналната обява',sourceUrl:c.url,images,features:(c.parts.find(x=>x.cls==='info')?.text||'').split('Особености - ')[1]?.split(',').map(x=>x.trim())||[],description:`${c.title}, ${year} г., ${fuel.toLowerCase()}, ${mileageKm.toLocaleString('bg-BG')} км. Публикувана обява на Астракар. Наличността, оборудването и условията се потвърждават по телефона.`,rawFacts:raw});console.log(i+1,c.title,price,images.length);}
await download('https://cdn2.focus.bg/mobile/images/houseslogos/h10303657271230948.pic','astracar-logo.png');await download('https://cdn2.focus.bg/mobile/images/housespicts/h10303657271230948.pic','astracar-cover.jpg');
await fs.writeFile(root+'/stock.json',JSON.stringify(stock,null,2));await fs.writeFile(root+'/assets/provenance.json',JSON.stringify(provenance,null,2));await b.close();

