import fs from 'node:fs/promises';import path from 'node:path';const root='J:/cars/clients/astracar';const f=JSON.parse(await fs.readFile(root+'/business-facts.json'));const stock=JSON.parse(await fs.readFile(root+'/stock.json'));async function edit(p,fn){const s=await fs.readFile(p,'utf8');await fs.writeFile(p,fn(s));}async function walk(d,fn){for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isDirectory())await walk(d+'/'+e.name,fn);else if(/\.(svelte|tsx?|css|html)$/.test(e.name))await edit(d+'/'+e.name,fn);}}
for(const v of ['auto-best','carwow']){await edit(root+'/'+v+'/src/app.html',s=>s.replace(/href="(?:\/favicon.ico|%sveltekit.assets%\/brand\/daynight-favicon.png)"/g,'href="/assets/astracar/astracar-logo.png"'));}
await edit(root+'/auto-best/src/app.css',s=>s.replace('--dn-red: #c40101','--dn-red: #30343b').replace('--dn-red-hover: #a90000','--dn-red-hover: #171a20')+'\n/* Original monochrome dealer logo on light surfaces. */\n.dn-header .dn-logo img, .dn-mobile-menu__brand img { filter: invert(1); }\n');
await edit(root+'/auto-best/src/lib/data/demo-content.ts',s=>s.replace(/export const demoTeamIntro =\s*'[^']*';/,"export const demoTeamIntro = 'Продажба, бартер, лизинг и сервизно обслужване. Уточнете условията с екипа.';").replace(/export const demoPartners: DemoPartner\[\] = \[[\s\S]*?\];/,`export const demoPartners: DemoPartner[] = [{id:'bmw',name:'BMW',image:'/assets/images/partner/parner12.png'},{id:'audi',name:'Audi',image:'/assets/images/partner/parner11.png'},{id:'mercedes',name:'Mercedes-Benz',image:'/assets/images/partner/parner8.png'}];`).replace(/export const demoPartnerIntro =\s*'[^']*';/,"export const demoPartnerIntro = 'Марки в подбраните обяви. Наличността се потвърждава с Астракар.';"));
for(const file of ['Header.svelte','Footer.svelte'])await edit(root+'/auto-best/src/lib/components/layout/'+file,s=>s.replace(/<a[^\n]*brand\.instagramUrl[^\n]*<\/a>/g,'').replace(/<a[^\n]*brand\.facebookUrl[^\n]*<\/a>/g,'').replace('<span>YouTube</span>','<span>Mobile.bg</span>'));
await edit(root+'/auto-best/src/lib/components/home/VideoSection.svelte',s=>s.replace('<span class="dn-videos__brand-mark"><SocialBrandIcon name="youtube" size={32} /></span>','').replace('<span class="dn-videos__all-icon"><SocialBrandIcon name="youtube" size={40} /></span>','').replace('  import SocialBrandIcon from \'$components/company/SocialBrandIcon.svelte\';\n',''));
await walk(root+'/carwow/src',s=>s.replaceAll('Понеделник - Събота: 9:00 - 18:00',f.hours[0]).replaceAll('Понеделник - събота: 9:00 - 18:00',f.hours[0]).replaceAll('Понеделник–петък 9:00 – 18:00',f.hours[0]).replaceAll('Делнични дни: 9:00 - 18:00',f.hours[0]).replaceAll('Огледи през уикенда с уговорка','Потвърдете посещението по телефона.').replaceAll('DayNight inspected','Публикувана обява').replaceAll('/brand/daynight-logo-generated.png',f.logo).replaceAll('https://www.facebook.com/61566304063141/','https://astracar.mobile.bg/').replaceAll('https://www.instagram.com/daynight.auto.plovdiv/','https://astracar.mobile.bg/').replaceAll('с гарантиран произход','с данни в публикуваните обяви').replace(/\/assets\/daynight-auto-v3\/[^'"\s]*(?:showroom|team|entrance)[^'"\s]*/g,stock[9].images[0]));
await edit(root+'/carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte',s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,'const reviews: Review[] = [];').replace('Отзиви от клиенти','Отзиви — няма публикувани в демото'));
await edit(root+'/carwow/src/lib/components/detail/desktop/desktop-detail-reviews-data.ts',s=>s.replace(/export const desktopDetailReviews: DesktopDetailReview\[\] = \[[\s\S]*?\n\];/,'export const desktopDetailReviews: DesktopDetailReview[] = [];').replace(/percent: '[^']*'/g,"percent: '0%'").replace('[1, 2, 3, 4, 5] as const','[] as number[]'));
await edit(root+'/carwow/src/lib/components/detail/desktop/DesktopDetailReviews.svelte',s=>s.replace('>4.8<','>—<'));
await edit(root+'/carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte',s=>s.replaceAll('Астракар в YouTube','Астракар в Mobile.bg').replaceAll('Всички видеа','Всички обяви').replace('<img src="/assets/brands/youtube-logo.png" alt="YouTube" width="186" height="62" />','Mobile.bg'));
await edit(root+'/carwow/src/lib/components/layout/DesktopDealerFooter.svelte',s=>s.replace(/<a href="https:\/\/astracar.mobile.bg\/" aria-label="(?:Facebook|Instagram)"[^\n]*<\/a>/g,'').replace(/<a \{\.\.\.youtubeLink\}[^\n]*<\/a>/,'<a {...youtubeLink}>Mobile.bg</a>'));
await edit(root+'/carwow/src/lib/components/home/mobile/MobileHeader.svelte',s=>s.replace('object-position: left center;','object-position: left center;\n\t\tfilter: invert(1);'));
await edit(root+'/carwow/src/lib/components/layout/SiteChromeLogo.svelte',s=>s.replace('class={logoImageClasses}','class={logoImageClasses}\n            style:filter={tone === \'dark\' ? \'invert(1)\' : undefined}'));
await edit(root+'/carwow/src/lib/styles/tokens.css',s=>s.replaceAll('#d71920','#30343b').replaceAll('#a50f15','#171a20'));
await edit(root+'/carwow/src/lib/styles/daynight-home-desktop.css',s=>s.replaceAll('#c8102e','#30343b').replaceAll('#a50d20','#171a20'));
await edit(root+'/modern/apps/web/app/[locale]/styles.css',s=>s+'\n/* Faithful display inversion of the original monochrome dealer logo. */\nheader img[src*="astracar-logo"], header img[src*="lead-logo"] { filter: invert(1); }\n');
console.log('Identity and claims follow-up complete');
