import fs from 'node:fs/promises';import path from 'node:path';
const root=import.meta.dirname,f=JSON.parse(await fs.readFile(`${root}/business-facts.json`)),stock=JSON.parse(await fs.readFile(`${root}/stock.json`));
const read=p=>fs.readFile(p,'utf8'),write=(p,s)=>fs.writeFile(p,s);async function walk(d,fn){for(const e of await fs.readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())await walk(p,fn);else await fn(p);}}
const a=`${root}/auto-best`,c=`${root}/carwow`,m=`${root}/modern`;
await write(`${c}/src/lib/data/daynight-videos.ts`,`export const youtubeChannelUrl = ${JSON.stringify(f.stockUrl)};\nexport const homeVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'Обява',thumbnail:v.images[0],url:v.sourceUrl})),null,2)} as const;\n`);
let v=await read(`${c}/src/lib/components/home/desktop/DesktopHomeVideos.svelte`);v=v.replaceAll('Champion Auto Pro в YouTube','Автомобили отблизо').replaceAll('Всички видеа','Всички обяви').replace(/<span class="home-videos__title">[\s\S]*?<\/span>/,'<span class="home-videos__title">Автомобили отблизо</span>').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noopener noreferrer"><img src={video.thumbnail} alt={video.title} width="480" height="270" loading="lazy" /></a>').replace('.home-video__image iframe','.home-video__image img');await write(`${c}/src/lib/components/home/desktop/DesktopHomeVideos.svelte`,v);
let r=await read(`${c}/src/lib/components/home/desktop/DesktopHomeReviews.svelte`);r=r.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${JSON.stringify([{id:'stock',description:'Подбрани автомобили от публикуваните обяви. Потвърдете актуалната наличност по телефона.',avatar:f.logo,name:f.name,meta:'Автомобили'},{id:'trade',description:'Автокъщата публикува възможности за бартер и изкупуване. Условията се договарят индивидуално.',avatar:f.logo,name:f.name,meta:'Бартер'},{id:'visit',description:f.address+'. '+f.hours.join('. '),avatar:f.logo,name:f.name,meta:'Посещение'}],null,2)};`);r=r.replace(/\{#each starIds as star \(star\)\}[\s\S]*?\{\/each\}/g,'<span>Информация</span>').replaceAll('Какво казват клиентите','Полезна информация').replaceAll('Мнения от клиенти','Полезна информация');await write(`${c}/src/lib/components/home/desktop/DesktopHomeReviews.svelte`,r);
await walk(`${c}/src`,async p=>{if(!/\.(svelte|ts|css)$/.test(p))return;let s=await read(p),t=s;t=t.replace(/\/assets\/images\/pages\/daynight-team-[^'"\s]+/g,f.showroom).replaceAll('Понеделник - Събота: 9:00 - 18:00',f.hours.join(' · ')).replaceAll('Кристиан Кирилов',f.name).replaceAll('Избрани автомобилни видеа','Публикувани обяви').replaceAll('Champion Auto Pro в YouTube','Champion Auto Pro в Mobile.bg');
 t=t.replace(/\/brand\/daynight-og\.svg/g,f.showroom).replaceAll('/assets/images/home2/daynight-hero-cutoff-imagegen-v1.webp',f.showroom);if(t!==s)await write(p,t);});
for(const variant of ['auto-best','carwow']){const p=`${root}/${variant}/src/app.html`;let s=await read(p);s=s.replace('/favicon.ico',f.logo).replaceAll('/brand/daynight-favicon.png',f.logo);await write(p,s);}
await write(`${c}/static/site.webmanifest`,JSON.stringify({name:f.name,short_name:f.shortName,start_url:'/',display:'standalone',icons:[{src:f.logo,sizes:'336x160',type:'image/png'}]},null,2));
await fs.appendFile(`${m}/apps/web/app/[locale]/styles.css`,`\n/* Original dealer logo on light surfaces. */\nimg[src*="champion%2Flogo.png"],img[src*="champion/logo.png"],img[src="/lead-logo.png"] { filter: invert(1) grayscale(1); mix-blend-mode: multiply; object-fit: contain; }\n`);
// Archive media superseded by the skin outside the deployable Auto Best directory.
const refs=new Set();await walk(`${a}/src`,async p=>{if(/\.(css|html|js|svelte|ts)$/.test(p)){for(const match of (await read(p)).matchAll(/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi))refs.add(match[0]);}});
const archived=[];await walk(`${a}/static`,async p=>{const rel='/'+path.relative(`${a}/static`,p).replaceAll('\\','/');if(!refs.has(rel)){const dest=path.resolve(root,'assets/superseded-auto-best',rel.slice(1));if(!dest.startsWith(path.resolve(root)+path.sep)||!path.resolve(p).startsWith(path.resolve(a,'static')+path.sep))throw Error('Boundary');await fs.mkdir(path.dirname(dest),{recursive:true});await fs.rename(p,dest);archived.push(rel);}});
const guard=`${a}/scripts/check-assets.mjs`;await write(guard,(await read(guard)).replace(/const guardedMediaCount = \d+;/,`const guardedMediaCount = ${refs.size};`));await write(`${root}/qa/auto-best-media-manifest.json`,JSON.stringify({referenced:[...refs],archived,count:refs.size},null,2));
console.log('Content truthfulness, media, favicons and exact asset manifest updated.');
