import fs from 'node:fs/promises';import path from 'node:path';
const root=import.meta.dirname,f=JSON.parse(await fs.readFile(`${root}/business-facts.json`)),stock=JSON.parse(await fs.readFile(`${root}/stock.json`));
f.accent='#282522';f.accentDark='#151311';f.showroom='/assets/champion/cover.jpg';await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(f,null,2));
const changes=[];const read=p=>fs.readFile(p,'utf8');const write=(p,s)=>fs.writeFile(p,s);
const swaps=[['Day & Night Auto Group',f.name],['Day &amp; Night Auto Group',f.name],['DAY NIGHT AUTO GROUP',f.name],['Day Night Auto Group',f.name],['Day Night Auto',f.name],['Day & Night',f.name],['Ден и Нощ Ауто Груп',f.name],['Спартак Ауто',f.name],['0877 733 110',f.phoneDisplay],['087 982 4625',f.phoneDisplay],['0877733110','0885072555'],['0879824625','0885072555'],['+359877733110','+359885072555'],['+359879824625','+359885072555'],['София','Варна'],['Пловдив','Варна'],['Студентски град','Цар Освободител 302'],['ул. „Атанас Манчев“ 18, Цар Освободител 302',f.address],['ул. Атанас Манчев 18','бул. Цар Освободител 302'],['daynight.mobile.bg','championautopro.mobile.bg'],['daynightautogroup.bg','championautopro.mobile.bg'],['https://www.instagram.com/dayandnight_autogroup/',f.stockUrl],['https://www.facebook.com/deninoshtautogroup/',f.stockUrl],['https://www.youtube.com/@kristiankirilov1355/videos',f.stockUrl]];
async function walk(dir,fn){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit','.vercel'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p,fn);else await fn(p);}}
for(const variant of ['auto-best','modern','carwow']){
 const vroot=`${root}/${variant}`;const dirs=variant==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo']:['src'];
 for(const dir of dirs)await walk(`${vroot}/${dir}`,async p=>{if(!/\.(svelte|tsx?|css|html|svg)$/.test(p))return;let s=await read(p),t=s;for(const [a,b]of swaps)t=t.replaceAll(a,b);if(t!==s){await write(p,t);changes.push(path.relative(root,p));}});
 const pub=variant==='modern'?`${vroot}/apps/web/public`:`${vroot}/static`;await fs.mkdir(`${pub}/assets/champion`,{recursive:true});
 for(const name of await fs.readdir(`${root}/assets`))if(/\.(png|jpg|webp)$/.test(name))await fs.copyFile(`${root}/assets/${name}`,`${pub}/assets/champion/${name}`);
}
// Auto Best: preserve source composition and route behavior, replace the actual wired data.
const a=`${root}/auto-best`;
await write(`${a}/src/lib/config/brand.ts`,`export const brand = ${JSON.stringify({name:f.name,shortName:f.shortName,city:f.city,youtubeUrl:f.stockUrl,instagramUrl:f.stockUrl,facebookUrl:f.stockUrl,phone:f.phoneDisplay,phoneHref:f.phoneHref,addressLine:f.address,address:f.address+', '+f.city,appointment:f.hours.join(' · '),logo:f.logo},null,2)} as const;\n`);
let inv=await read(`${a}/src/lib/data/inventory.ts`);inv=inv.replace('  image: string;','  image: string;\n  gallery: string[];\n  sourceUrl: string;');
const vehicles=stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,category:({SUV:'SUV',Hatchback:'Хечбек',Estate:'Комби',Coupe:'Купе',Sedan:'Седан'})[v.body],body:v.body==='Estate'?'Wagon':v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:[],condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`}));
inv=inv.replace(/export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`export const featuredVehicles: Vehicle[] = ${JSON.stringify(vehicles,null,2)};`);await write(`${a}/src/lib/data/inventory.ts`,inv);
let filters=await read(`${a}/src/lib/data/listing.ts`);for(const [key,values] of Object.entries({makes:['',...new Set(stock.map(v=>v.make))],bodies:['','SUV','Sedan','Hatchback','Wagon'],fuels:['','Дизел','Бензин','Електрически'],years:['',...new Set(stock.map(v=>String(v.year)))].sort(),prices:['','10000','20000','30000','40000','50000','90000'],mileages:['','50000','100000','200000','300000']}))filters=filters.replace(new RegExp(`${key}: \\[[^\\]]*\\]`),`${key}: ${JSON.stringify(values)}`);await write(`${a}/src/lib/data/listing.ts`,filters);
let map=await read(`${a}/src/lib/components/company/ShowroomMap.svelte`);map=map.replace("  import { showroomCoordinates } from '$data/company';\n",'').replace(/const mapEmbedUrl = .*;/,`const mapEmbedUrl = ${JSON.stringify(f.mapsEmbedUrl)};`);await write(`${a}/src/lib/components/company/ShowroomMap.svelte`,map);
let detail=await read(`${a}/src/routes/listing-detail-v1/[id]/+page.svelte`);detail=detail.replace('  let activeTabsByVehicle',"  let galleryIndex = $state(0);\n  let activeTabsByVehicle");detail=detail.replace('src={data.vehicle.image}','src={data.vehicle.gallery[galleryIndex % data.vehicle.gallery.length]}');detail=detail.replace('<div class="dn-detail-gallery__count" aria-hidden="true">','<button type="button" class="dn-detail-gallery__count" aria-label="Следваща снимка" onclick={() => galleryIndex = (galleryIndex + 1) % data.vehicle.gallery.length}>');detail=detail.replace(/(<button type="button" class="dn-detail-gallery__count"[\s\S]*?)<\/div>/,'$1</button>');detail=detail.replace('<span>1</span>','<span>{galleryIndex + 1}/{data.vehicle.gallery.length}</span>');await write(`${a}/src/routes/listing-detail-v1/[id]/+page.svelte`,detail);
// Retain the media section as an honest stock-photo preview: no inherited video/channel attribution.
let video=await read(`${a}/src/lib/components/home/VideoSection.svelte`);video=video.replace('<span class="dn-videos__intro">Гледайте ни в</span><span class="dn-videos__brand-mark"><SocialBrandIcon name="youtube" size={32} /></span>YouTube','Автомобили отблизо').replace('Избрани автомобилни видеа с Кристиан Кирилов.','Снимки от публикуваните обяви на Champion Auto Pro.').replaceAll('Всички видеа','Всички обяви').replaceAll(' в YouTube (нов раздел)',' в Mobile.bg (нов раздел)').replaceAll('Пуснете видеото:','Разгледайте:').replace(/<iframe[\s\S]*?<\/iframe>/,`<img src={video.thumbnail} alt={video.title} width="720" height="404" />`).replace('href={`https://www.youtube.com/watch?v=${video.id}`}','href={video.id}').replaceAll('гледайте в YouTube','вижте обявата').replaceAll('Гледайте в YouTube','Вижте обявата').replace("  import SocialBrandIcon from '$components/company/SocialBrandIcon.svelte';\n",'');await write(`${a}/src/lib/components/home/VideoSection.svelte`,video);
let vd=await read(`${a}/src/lib/data/videos.ts`);vd=vd.replace(/export const featuredVideos: readonly FeaturedVideo\[\] = \[[\s\S]*?\n\];/,`export const featuredVideos: readonly FeaturedVideo[] = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.sourceUrl,title:v.title,duration:'Обява',thumbnail:v.images[0]})),null,2)};`);await write(`${a}/src/lib/data/videos.ts`,vd);
// Replace source-person portraits and showroom images; generic studio cars remain decorative.
await walk(`${a}/src`,async p=>{if(!/\.(svelte|ts|css)$/.test(p))return;let s=await read(p);let t=s.replace(/\/assets\/images\/lead\/day-night-(?:about-kristian[^'"\s]*|contact-kristian[^'"\s]*|portrait[^'"\s]*|about-showroom[^'"\s]*|showroom-color[^'"\s]*)\.(?:webp|png)/g,f.showroom);if(s!==t)await write(p,t);});
let acss=await read(`${a}/src/app.css`);acss=acss.replaceAll('#c40101',f.accent);acss+=`\n/* Original dealer logo, CSS treatment for light surfaces; original bitmap retained. */\nimg[src="${f.logo}"] { filter: invert(1) grayscale(1); mix-blend-mode: multiply; object-fit: contain; }\n`;await write(`${a}/src/app.css`,acss);
// Carwow: retain all source route templates, populate listing adapters with the same snapshot.
const c=`${root}/carwow`;await write(`${c}/src/lib/data/champion-stock.json`,JSON.stringify(stock,null,2));
let site=await read(`${c}/src/lib/data/daynight-site.ts`);for(const [key,value]of Object.entries({name:f.name,shortName:f.shortName,phone:'0885072555',phoneLabel:f.phoneDisplay,email:'',location:f.address+', '+f.city,mapUrl:f.mapsUrl,mapLabel:f.name+' Варна',sourceInventory:f.stockUrl,inventoryCount:stock.length,logoLight:f.logo,logoDark:f.logo,heroTitle:f.name,heroSubtitle:'Автомобили, бартер и лизинг във Варна'}))site=site.replace(new RegExp(`\\b${key}:\\s*(?:'[^']*'|"[^"]*"|\\d+)`),`${key}: ${JSON.stringify(value)}`);await write(`${c}/src/lib/data/daynight-site.ts`,site);
let current=await read(`${c}/src/lib/data/daynight-current-inventory.ts`);current=current.slice(0,current.indexOf('export const currentDayNightListings'))+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:v.priceEur.toLocaleString('bg-BG')+' €',priceBgn:(v.priceEur*1.95583).toFixed(2)+' лв.',status:'Публикувана обява',date:v.date,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',color:v.color,fuel:v.fuel,power:v.powerHp?v.powerHp+' к.с.':'—',transmission:v.transmission,body:({SUV:'SUV',Hatchback:'Хечбек',Estate:'Комби',Coupe:'Купе',Sedan:'Седан'})[v.body],features:['Оборудването се потвърждава по оригиналната обява'],image:v.images[0]})),null,2)};\n`;await write(`${c}/src/lib/data/daynight-current-inventory.ts`,current);
let cv=await read(`${c}/src/lib/data/daynight-vehicles.ts`);cv=`import championStock from './champion-stock.json';\n`+cv;cv=cv.replace('const identity = getVehicleIdentity(listing);',"const original = championStock.find(v => v.id === listing.id)!;\n\tconst identity = {brand: original.make, model: original.model, shortTitle: original.title};").replace('gallery: [listing.image]','gallery: original.images').replace("doors: body === 'Купе' ? 3 : 5","doors: 0").replace(/monthly: `[^`]*`,/,"monthly: 'Условия по запитване',").replace("'Наличен';","'Публикувана обява';").replace('Наличен автомобил в Варна','Публикувана обява — оглед във Варна').replace('`DN-','`CAP-');await write(`${c}/src/lib/data/daynight-vehicles.ts`,cv);
let reviews=await read(`${c}/src/lib/data/daynight-reviews.ts`);reviews=reviews.replace(/export const daynightReviews = \[[\s\S]*?\] satisfies DayNightReview\[\];/,`export const daynightReviews = [] satisfies DayNightReview[];`).replace('`${daynightReviewCount} отзива`',"'Няма добавени отзиви'");await write(`${c}/src/lib/data/daynight-reviews.ts`,reviews);
await walk(`${c}/src`,async p=>{if(!/\.(svelte|ts|css)$/.test(p))return;let s=await read(p),t=s;t=t.replace(/https:\/\/www\.google\.com\/maps\/search\/\?api=1&query=[^'"\s`]+/g,f.mapsUrl).replaceAll('Делнични дни: 9:00 - 18:00 · Неделя: по уговорка',f.hours.join(' · '));t=t.replace(/(?:\/brand\/daynight-logo-generated\.png|\/assets\/images\/[^'"\s]*(?:daynight-logo|logo-daynight)[^'"\s]*\.(?:png|webp))/g,f.logo);if(s!==t)await write(p,t);});
// Logo treatment uses the original file without a padded dark badge.
const ccss=`${c}/src/lib/styles/tokens.css`;await write(ccss,(await read(ccss)).replace('--sa-yellow: #f5c542','--sa-yellow: #d3cec7')+`\nimg[src="${f.logo}"] { filter: invert(1) grayscale(1); mix-blend-mode: multiply; object-fit: contain; }\n`);
await write(`${root}/qa/personalization-files.json`,JSON.stringify(changes,null,2));
console.log('Auto Best and Carwow identity/data personalized.');
