import fs from 'node:fs/promises';import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const root=import.meta.dirname;const cards=JSON.parse(await fs.readFile(`${root}/qa/stock-cards.json`));const picks=[8,1,2,3,4,5,6,7,9,10,11,12,13,14,15,0];const stock=[],downloads=[];
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();
for(const [n,index] of picks.entries()){
 const c=cards[index],facts=c.parts.find(p=>p.cls==='params').text,top=c.parts.find(p=>p.cls==='zaglavie').text;
 await p.goto(c.url,{waitUntil:'domcontentloaded'});const detail=await p.evaluate(()=>({text:document.body.innerText,images:[...document.images].map(i=>i.src).filter(s=>s.includes('photosorg')),links:[...document.querySelectorAll('a')].map(a=>a.href)}));
 await fs.writeFile(`${root}/qa/detail-${n+1}.json`,JSON.stringify(detail,null,2));
 const urls=[...new Set(detail.images.map(s=>s.replace(/(\/photosorg\/\d+\/\d+\/)(?:big\d\/)?/,'$1big1/')))];
 const images=[];for(const [i,url] of urls.slice(0,4).entries()){const name=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;const r=await fetch(url);if(!r.ok)throw Error(url);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));images.push(`/assets/champion/${name}`);downloads.push({url,path:`assets/${name}`,sourcePage:c.url});}
 const id=c.url.match(/obiava-(\d+)/)[1],year=Number(facts.match(/(19|20)\d{2}/)[0]),mileage=Number(facts.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),price=Number(top.split('\n').find(line=>line.includes('€')).match(/([\d ]+)\s*€/)[1].replace(/\s/g,''));
 const title=c.title.split('/')[0].replace(/-Гаранционен.*|-108000км\.|55000 km/g,'').trim(),make=title.startsWith('Mercedes-Benz')?'Mercedes-Benz':title.split(' ')[0];const fuel=facts.includes('Хибриден')?'Хибрид':facts.includes('Дизелов')?'Дизел':facts.includes('Бензинов')?'Бензин':'Електрически';
 const body=facts.includes('Джип')?'SUV':facts.includes('Хечбек')?'Hatchback':facts.includes('Комби')?'Estate':facts.includes('Купе')?'Coupe':'Sedan';
 stock.push({id,title,fullTitle:c.title,make,model:title.slice(make.length).trim(),year,mileageKm:mileage,priceEur:price,fuel,transmission:facts.includes('Автоматична')?'Автоматик':'Ръчна',body,powerHp:Number(facts.match(/(\d+)\s*к\.с\./)?.[1]||0),color:facts.match(/км\s+(.+?)\s+(?:Хибриден|Дизелов|Бензинов|Електрически)/)?.[1]||'',date:facts.match(/^(.+?г\.)/)[1],vat:'Не се начислява ДДС',sourceUrl:c.url,images,description:`${title}, ${year} г., ${fuel.toLowerCase()}, ${mileage.toLocaleString('bg-BG')} км. Публикувана обява към 07.09.2026. Наличност, оборудване и условия се потвърждават с Champion Auto Pro.`,rawFacts:facts});console.log(n+1,title,images.length);
}
await b.close();
for(const [name,url] of [['logo.png','https://cdn2.focus.bg/mobile/images/houseslogos/h17466001698666567.pic'],['cover.jpg','https://cdn2.focus.bg/mobile/images/housespicts/h17466001698666567.pic']]){const r=await fetch(url);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));downloads.push({url,path:`assets/${name}`,sourcePage:'https://championautopro.mobile.bg/'});}
const query=encodeURIComponent('Champion Auto Pro, бул. Цар Освободител 302, Варна');
const facts={name:'Champion Auto Pro',shortName:'Champion Auto Pro',accent:'#c71f27',accentDark:'#9e1720',phoneDisplay:'0885 072 555',phoneHref:'tel:+359885072555',email:'',address:'бул. „Цар Освободител“ 302 / Автомивка Izgi Europe Motor',city:'Варна',country:'България',hours:['Понеделник – петък: 09:30–18:00','Събота: 10:00–15:00','Неделя: почивен ден'],mapsUrl:'https://www.google.com/maps/search/?api=1&query='+query,mapsEmbedUrl:'https://maps.google.com/maps?q='+query+'&output=embed',website:'https://championautopro.mobile.bg/',stockUrl:'https://championautopro.mobile.bg/',services:['Продажба на автомобили','Бартер и изкупуване','Лизинг','Доставка от чужбина'],logo:'/assets/champion/logo.png',showroom:stock[0].images[0],stockSnapshotDate:'2026-09-07',stockCount:stock.length,stockNote:'Подбрани публикувани обяви. Наличностите и условията се потвърждават по телефона.',sources:['https://championautopro.mobile.bg/','https://championautopro.mobile.bg/contacts','https://championautopro.mobile.bg/about'],limitations:['No verified email or social profile linked from marketplace.','No reputation or finance approval claims reproduced.','Representative inventory snapshot, not live feed.']};
await fs.writeFile(`${root}/stock.json`,JSON.stringify(stock,null,2));await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));await fs.writeFile(`${root}/assets/provenance.json`,JSON.stringify({capturedAt:new Date().toISOString(),downloads,notes:'Original dealer media; watermarks retained. Logo format/legibility to inspect. No new rights determination.'},null,2));
