import fs from 'node:fs/promises';import path from 'node:path';const root=import.meta.dirname;
async function walk(d,fn){for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())await walk(p,fn);else await fn(p);}}
for(const dir of ['modern/apps/web/app','modern/packages/marketplace-ui'])await walk(`${root}/${dir}`,async p=>{if(!p.endsWith('.tsx')||p.includes('.test.'))return;let s=await fs.readFile(p,'utf8'),t=s.replaceAll('Studentski grad','Tsar Osvoboditel 302').replaceAll('Sofia','Varna');if(s!==t)await fs.writeFile(p,t);});
const chrome=`${root}/carwow/src/lib/server/daynight-template-chrome.ts`;let ch=await fs.readFile(chrome,'utf8');ch=ch.replaceAll('https://www.facebook.com/61566304063141/','https://championautopro.mobile.bg/').replaceAll('https://www.instagram.com/daynight.auto.plovdiv/','https://championautopro.mobile.bg/');await fs.writeFile(chrome,ch);
const p=`${root}/auto-best/src/lib/components/home/VideoSection.svelte`;let s=await fs.readFile(p,'utf8');s=s.replace(/\s*\.dn-videos__brand-mark \{[^}]*\}/,'').replace(/\s*\.dn-videos__intro \{[^}]*\}/,'').replace('.dn-video-card iframe {','.dn-video-card__media > img {').replace(', iframe:focus-visible','');await fs.writeFile(p,s);
// Prevent reintroducing the title-adjacent price parsing defect if research is rerun.
const prep=`${root}/prepare.mjs`;s=await fs.readFile(prep,'utf8');s=s.replace("top.match(/([\\d\\s]+)\\s*€/)[1]","top.split('\\n').find(line=>line.includes('€')).match(/([\\d ]+)\\s*€/)[1]");await fs.writeFile(prep,s);
// Dealer logo uses its real aspect and is not split into source-specific wordmark regions.
const mb=`${root}/modern/packages/marketplace-ui/components/dealer-mobile-brand-bar.tsx`;s=await fs.readFile(mb,'utf8');s=s.replace('light && "h-10 bg-black px-2.5"','light && "h-10"').replace('aspect-[1780/512]','aspect-[336/160]').replace('height={512}','height={160}').replace('width={1780}','width={336}');s=s.replace(/style=\{\s*wordmarkTone === "original"[\s\S]*?\n            \}/,'style={{ filter: wordmarkTone === "light" ? "grayscale(1)" : "invert(1) grayscale(1)", mixBlendMode: wordmarkTone === "light" ? "screen" : "multiply" }}');s=s.replace(/\{wordmarkTone === "original" \? null : \([\s\S]*?\n          \)\}/,'');await fs.writeFile(mb,s);
console.log('Remaining language and logo boundaries corrected.');
