import fs from 'node:fs/promises';
const root='clients/asko-96/modern';
const stock=JSON.parse(await fs.readFile('clients/asko-96/stock.json','utf8'));
const entry={brandCoverage:[...new Set(stock.map(v=>v.make))].map(brand=>({authorizationVerified:false,brand,relationship:'independent_importer'})),claimStatus:'unclaimed',contact:{email:'askogroup@abv.bg',phone:'+359899769696',websiteUrl:'https://asko96.bg/'},dealerOrgId:'dealer-asko-96',description:'Автомобили, внос по поръчка и собствен лизинг в София.',displayName:'АСКО 96',headquarters:{city:'София',countryCode:'BG'},headline:'Автомобили на Ботевградско шосе 300',id:'directory-asko-96',inventory:{activeListingCount:stock.length,inTransitCount:0,localCount:stock.length,orderableCount:0,sourceStockCount:0},orgType:'dealer',profileImage:{alt:'АСКО 96 София',url:'/assets/asko96/asko96-showroom.jpg'},representativeVehicles:stock.slice(0,3).map(v=>({availability:'local',href:`/listing/asko-${v.id}`,id:`asko-${v.id}`,image:{alt:v.title,url:v.images[0]},price:{amount:v.priceEur,currency:'EUR'},title:v.title})),slug:'asko-96',tradeLanes:[],verification:{businessVerified:false,inventoryCurrent:false,trustedSupplier:false}};
await fs.writeFile(`${root}/packages/marketplace/mock-directory.ts`,`import { organizationDirectoryEntriesSchema } from "./directory";\n// ASKO96 representative stock snapshot; this is not a live inventory feed.\nexport const mockOrganizationDirectoryCoreEntries = organizationDirectoryEntriesSchema.parse(${JSON.stringify([entry],null,2)});\nexport const createMockOrganizationDirectoryScaleEntries = (_totalOrganizations = 1) => mockOrganizationDirectoryCoreEntries;\nexport const mockOrganizationDirectoryEntries = mockOrganizationDirectoryCoreEntries;\n`);
const contact=`${root}/apps/web/app/[locale]/contact/page.tsx`;
let text=await fs.readFile(contact,'utf8');text=text.replaceAll('/day-night-contact-hero-v1.png','/assets/asko96/asko96-showroom.jpg');await fs.writeFile(contact,text);
for(const icon of ['apple-icon.png','icon.png'])await fs.copyFile('clients/asko-96/assets/asko96-logo.png',`${root}/apps/web/app/-/${icon}`);
console.log('Modern directory, actual contact photo and icons personalized. Generic decorative hero artwork retained.');
