import fs from 'node:fs/promises';import path from 'node:path';
const root=path.resolve('clients/asko-96/modern');const facts=JSON.parse(await fs.readFile('clients/asko-96/business-facts.json'));const stock=JSON.parse(await fs.readFile('clients/asko-96/stock.json'));const changes=[];
const replacements=[['Day & Night Auto Group','АСКО 96'],['Day &amp; Night Auto Group','АСКО 96'],['Day Night Auto Group','АСКО 96'],['Day & Night','АСКО 96'],['Day Night Auto','АСКО 96'],['Ден и Нощ Ауто Груп','АСКО 96'],['dayandnight_autogroup','asko96'],['Студентски град','Ботевградско шосе'],['Studentski grad','Botevgradsko shose'],['0877 733 110','0899 76 96 96'],['0877733110','0899769696'],['+359877733110','+359899769696'],['daynightautogroup.bg','asko96.bg']];
async function walk(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p);else if(/\.(tsx?|css|json|svg)$/.test(e.name)&&!e.name.includes('.test.')&&!e.name.includes('.spec.')){let s=await fs.readFile(p,'utf8'),next=s;for(const [a,b] of replacements)next=next.replaceAll(a,b);if(next!==s){await fs.writeFile(p,next);changes.push(path.relative(root,p))}}}}
await walk(path.join(root,'apps/web'));for(const pkg of ['marketplace','marketplace-ui','marketplace-domain','seo'])await walk(path.join(root,'packages',pkg));
const lf=path.join(root,'packages/marketplace/lead-site.ts');let l=await fs.readFile(lf,'utf8');const config={accent:facts.accent,address:facts.address,city:facts.city,contactUrl:facts.phoneHref,country:facts.country,countryCode:'BG',currency:'EUR',email:facts.email,heroPath:'/assets/asko96/asko96-showroom.jpg',locale:'bg-BG',logoPath:'/assets/asko96/asko96-wordmark.png',mapsEmbedUrl:facts.mapsEmbedUrl,mapsUrl:facts.mapsUrl,name:facts.name,phoneDisplay:facts.phoneDisplay,phoneHref:facts.phoneHref,shortName:facts.shortName,slug:'asko-96',socialLinks:{facebook:facts.facebook,youtube:facts.youtube},staticDemoMode:true,tagline:'Автомобили, внос по поръчка и собствен лизинг в София.'};l=l.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify(config,null,2)};`);await fs.writeFile(lf,l);
const listings=stock.map((v,i)=>({id:`asko-${v.id}`,slug:`asko-${v.id}`,category:'car',dealerOrgId:'dealer-asko-96',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:'София',region:'Ботевградско шосе',country:'България'},features:[],spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Estate:'wagon',Coupe:'coupe',Sedan:'sedan'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-asko-96',type:'dealer',displayName:'АСКО 96',verificationStatus:'unverified',city:'София'},publishedAt:new Date(Date.UTC(2026,8,6,10,0,-i)).toISOString(),promoted:false}));
const mf=path.join(root,'packages/marketplace-domain/testing/mock-data.ts');let m=await fs.readFile(mf,'utf8');m=m.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`// Representative stock captured from https://asko96.mobile.bg/ on 2026-09-06.\nexport const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`);await fs.writeFile(mf,m);
const assets=path.join(root,'apps/web/public/assets/asko96');await fs.mkdir(assets,{recursive:true});for(const e of await fs.readdir('clients/asko-96/assets'))if(/\.(png|webp|jpg)$/.test(e))await fs.copyFile(path.join('clients/asko-96/assets',e),path.join(assets,e));
await fs.copyFile('clients/asko-96/assets/asko96-wordmark.png',path.join(root,'apps/web/public/lead-logo.png'));await fs.copyFile('clients/asko-96/assets/asko96-showroom.jpg',path.join(root,'apps/web/public/lead-hero.jpg'));
await fs.writeFile('audits/2026-09-06/asko96-build/modern-personalization.json',JSON.stringify({changes,stockCount:listings.length,config,detailRoute:`/bg/listing/${listings[0].slug}`},null,2));console.log(JSON.stringify({rebrandedFiles:changes.length,vehicles:listings.length,detailRoute:`/bg/listing/${listings[0].slug}`}));

