import fs from 'node:fs/promises';
const root='clients/asko-96';const cards=JSON.parse(await fs.readFile('audits/2026-09-06/asko96-build/stock-cards.json'));const picks=[0,1,3,4,6,11,15,16,18,21,23,24,29,32,33,39];const vehicles=[];const downloads=[];
for(let n=0;n<picks.length;n++){const c=cards[picks[n]],facts=c.parts.find(p=>p.cls==='params').text,top=c.parts.find(p=>p.cls==='zaglavie').text;const id=c.url.match(/obiava-(\d+)/)[1];const year=Number(facts.match(/(19|20)\d{2}/)?.[0]);const mileage=Number(facts.match(/г\.\s*([\d\s]+)\s*км/)?.[1].replace(/\s/g,'')||0);const price=Number(top.match(/([\d\s]+)\s*€/)?.[1].replace(/\s/g,'')||0);if(!year||!price)throw Error('Missing facts '+c.title);
 const title=c.title.split('/')[0].replaceAll('!','').trim();const make=c.title.startsWith('Mercedes-Benz')?'Mercedes-Benz':c.title.split(' ')[0];const fuel=facts.includes('Хибриден')?'Хибрид':facts.includes('Дизелов')?'Дизел':facts.includes('Бензинов')?'Бензин':'Електрически';const body=facts.includes('Джип')?'SUV':facts.includes('Хечбек')?'Hatchback':facts.includes('Комби')?'Estate':facts.includes('Купе')?'Coupe':'Sedan';const images=[];
 for(let i=0;i<Math.min(4,c.images.length);i++){let url=c.images[i].startsWith('//')?'https:'+c.images[i]:c.images[i];url=url.replace(/(\/photosorg\/\d+\/\d+\/)/,'$1big1/');const name=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;images.push(`/assets/asko96/${name}`);downloads.push({url,path:`${root}/assets/${name}`,sourcePage:c.url})}
 vehicles.push({id,title,fullTitle:c.title,make,model:title.slice(make.length).trim(),year,mileageKm:mileage,priceEur:price,fuel,transmission:facts.includes('Автоматична')?'Автоматик':'Ръчна',body,powerHp:Number(facts.match(/(\d+)\s*к\.с\./)?.[1]||0),color:facts.match(/км\s+(.+?)\s+(?:Хибриден|Дизелов|Бензинов|Електрически)/)?.[1]||'',date:facts.match(/^(.+?г\.)/)?.[1]||String(year),vat:top.includes('без ДДС')?'Цената е без ДДС':top.includes('Не се начислява')?'Не се начислява ДДС':'Виж оригиналната обява',sourceUrl:c.url,images,description:`${title}, ${year} г., ${fuel.toLowerCase()}, ${mileage.toLocaleString('bg-BG')} км. За актуална наличност, оборудване и условия се свържете с АСКО 96.`,rawFacts:facts});}
for(let i=0;i<downloads.length;i+=6)await Promise.all(downloads.slice(i,i+6).map(async d=>{const r=await fetch(d.url);if(!r.ok)throw Error(r.status+' '+d.url);await fs.writeFile(d.path,Buffer.from(await r.arrayBuffer()))}));
const facts={name:'АСКО 96',latinName:'ASKO96',shortName:'АСКО 96',accent:'#d7ae35',accentDark:'#8b6811',phoneDisplay:'0899 76 96 96',phoneHref:'tel:+359899769696',email:'askogroup@abv.bg',address:'бул. „Ботевградско шосе“ 300',city:'София',country:'България',hours:['Понеделник – петък: 09:00–18:30','Събота: 10:00–16:00','Неделя: почивен ден'],mapsUrl:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('АСКО 96, Ботевградско шосе 300, София'),mapsEmbedUrl:'https://maps.google.com/maps?q='+encodeURIComponent('АСКО 96, Ботевградско шосе 300, София')+'&output=embed',website:'https://asko96.bg/',stockUrl:'https://asko96.mobile.bg/',facebook:'https://www.facebook.com/p/Asko96-100050328800477/',youtube:'https://www.youtube.com/@asko96bulgaria',services:['Продажба на автомобили','Замяна и изкупуване','Внос по поръчка','Собствен лизинг','Сервизно обслужване'],logo:'/assets/asko96/asko96-logo.png',showroom:'/assets/asko96/asko96-showroom.jpg',stockSnapshotDate:'2026-09-06',stockCount:vehicles.length,stockNote:'Подбрани автомобили от публикуваните обяви. Наличностите и условията се потвърждават с АСКО 96.',sources:['https://asko96.bg/en/home-2/','https://asko96.mobile.bg/','https://asko96.mobile.bg/contacts']};
await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));await fs.writeFile(`${root}/stock.json`,JSON.stringify(vehicles,null,2));await fs.writeFile(`${root}/assets/provenance.json`,JSON.stringify({capturedAt:new Date().toISOString(),logo:{source:'https://asko96.bg/wp-content/uploads/2024/03/withMedalAsko96.png'},showroom:{source:'https://asko96.bg/wp-content/uploads/elementor/thumbs/AskoSofia-scaled-1-qmio02f260rrsb49jnscua9c182kw8mayfqdlb9hac.jpg'},stock:downloads},null,2));console.log(JSON.stringify({vehicles:vehicles.length,images:downloads.length}));
