<script>
  import {brand,assets,vehicles,services} from './data.js';
  const params=new URLSearchParams(location.search);
  const selectedVehicle=vehicles.find(v=>v.id===params.get('vehicle'));
  const topics=[{id:'general',title:'Общ въпрос',description:'Автомобил, който ви интересува, или въпрос към екипа.'},...services];
  let topic=$state(topics.some(t=>t.id===params.get('topic'))?params.get('topic'):'general');
  let chosen=$derived(topics.find(t=>t.id===topic));
  const preparations={general:['Вашият въпрос и предпочитания','Удобно време за разговор'],inspection:['Моделът, който искате да видите','Удобен ден и час за посещение'],import:['Марка, модел и бюджет','Предпочитано оборудване','Линк към обява, ако имате избрана'],leasing:['Избраният автомобил','Предпочитана първоначална вноска','Срок, който искате да обсъдите']};
  function changeTopic(value){topic=value;const p=new URLSearchParams({topic});if(selectedVehicle)p.set('vehicle',selectedVehicle.id);history.replaceState(null,'','/contact.html?'+p);}
</script>
<section class="dn-contact-hero"><div class="container"><div><div class="dn-breadcrumb"><a href="/">Начало</a><span>Контакти</span></div><span class="dn-eyebrow">{brand.shortName} · София</span><h1>Следващата стъпка <br />започва с <span>разговор.</span></h1><p>За автомобил, оглед или внос — свържете се директно с екипа.</p><a class="theme-btn" href={brand.phoneHref}><i class="fal fa-phone" aria-hidden="true"></i> {brand.phone}</a></div><img src={assets.cutoutSilver} alt="" width="1000" height="667" /></div></section>
<section class="container dn-contact-content">
  <div class="dn-contact-points"><a href={brand.phoneHref}><i class="fal fa-phone" aria-hidden="true"></i><div><h2>Обадете ни се</h2><strong>{brand.phone}</strong><span>Директен разговор с екипа</span></div><i class="far fa-arrow-up-right" aria-hidden="true"></i></a><a href={brand.mapsUrl} target="_blank" rel="noreferrer"><i class="fal fa-map-marker-alt" aria-hidden="true"></i><div><h2>Елате на място</h2><strong>София, Студентски град</strong><span>ул. „Атанас Манчев“ 18 · По уговорка</span></div><i class="far fa-arrow-up-right" aria-hidden="true"></i></a><a href={brand.contactUrl} target="_blank" rel="noreferrer"><i class="fal fa-comment-alt" aria-hidden="true"></i><div><h2>Пишете на продавача</h2><strong>Контакт през Mobile.bg</strong><span>Запитване в официалния ни профил</span></div><i class="far fa-arrow-up-right" aria-hidden="true"></i></a></div>
  <div class="dn-preparation"><div><span class="dn-eyebrow">Да уточним детайлите</span><h2>С какво можем да помогнем?</h2><p>Изберете тема и подгответе най-важното за разговора.</p><fieldset><legend class="dn-sr-only">Тема на разговора</legend>{#each topics as t (t.id)}<label class:active={topic===t.id}><input type="radio" name="topic" value={t.id} checked={topic===t.id} onchange={()=>changeTopic(t.id)} />{t.title}</label>{/each}</fieldset></div><div class="dn-preparation-card" aria-live="polite"><h3>{chosen.title}</h3>{#if selectedVehicle}<p class="dn-selected-vehicle"><i class="fal fa-car" aria-hidden="true"></i> {selectedVehicle.title}</p>{/if}<p>{chosen.description}</p><ul>{#each preparations[topic]||preparations.general as item (item)}<li><i class="far fa-check" aria-hidden="true"></i>{item}</li>{/each}</ul><a class="theme-btn" href={brand.phoneHref}>Обсъдете с екипа <i class="far fa-arrow-up-right" aria-hidden="true"></i></a></div></div>
</section>
