import fs from 'node:fs/promises';import path from 'node:path';const root='J:/cars/clients/ivo-auto',f=JSON.parse(await fs.readFile(root+'/business-facts.json')),v=JSON.parse(await fs.readFile(root+'/stock.json'));
async function walk(d){let a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())a.push(...await walk(p));else a.push(p)}return a}async function edit(p,fn){let s=await fs.readFile(p,'utf8');await fs.writeFile(p,fn(s))}
for(const key of ['auto-best','carwow','modern']){
 const dirs=key==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui']:['src'];
 for(const d of dirs)for(const p of await walk(root+'/'+key+'/'+d))if(/\.(svelte|tsx?|css|html)$/.test(p)&&!/(test|spec)\./.test(p))await edit(p,s=>s.replaceAll('в Варна','във Варна').replaceAll('Спартак Ауто',f.name).replaceAll('Пловдив','Варна').replaceAll('Внос по заявка','Запитване за автомобил').replaceAll('Внос по поръчка','Запитване за автомобил').replaceAll('Заявете внос','Попитайте екипа').replaceAll('Собствени наличности','Публикувани обяви').replaceAll('Проверени автомобили','Публикувани автомобили').replaceAll('Понеделник - Събота: 9:00 - 18:00',f.hoursNote).replaceAll('Делнични дни: 9:00 - 18:00 · Неделя: по уговорка',f.hoursNote).replaceAll('Понеделник–петък 9:00 – 18:00',f.hoursNote).replace(/https:\/\/www\.(facebook\.com\/61566304063141\/|instagram\.com\/daynight\.auto\.plovdiv\/)/g,f.stockUrl).replace(/\/assets\/daynight-auto-v3\/[A-Za-z0-9_./-]+\.(?:webp|png|jpg)/g,v[0].images[0]));
}
await edit(root+'/auto-best/src/lib/components/company/ShowroomMap.svelte',s=>s.replace(/const mapEmbedUrl = `[^`]+`;/,'const mapEmbedUrl = brand.mapsEmbedUrl;').replace("  import { showroomCoordinates } from '$data/company';\n",''));
await edit(root+'/auto-best/src/lib/components/home/VideoSection.svelte',s=>s.replaceAll('в YouTube','в Mobile.bg').replaceAll('гледайте в YouTube','вижте в Mobile.bg'));
await edit(root+'/auto-best/src/lib/data/home.ts',s=>s.replace('Можем да съдействаме с проверка на история, документи и техническо състояние преди финално решение.','Поискайте сервизна история, документи и възможност за независим оглед преди решение.').replace('Да — можем да обсъдим внос по поръчка според критерии за модел, бюджет и оборудване.','Попитайте продавача за конкретния автомобил и възможностите според вашите критерии.'));
const c=root+'/carwow/src/lib/';
await edit(c+'components/detail/desktop/DesktopDetailLocationMap.svelte',s=>s.replace(/const mapUrl =\s*'[^']*';/,'const mapUrl = daynightSite.mapUrl;'));
await edit(c+'components/home/desktop/DesktopHomeVideos.svelte',s=>s.replaceAll('Иво Ауто в YouTube','Обяви на Иво Ауто').replaceAll('Всички видеа','Всички обяви').replace(/<span class="home-videos__title">[\s\S]*?<\/span>/,'<span class="home-videos__title">Снимки и подробности</span>').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noopener noreferrer"><img src={video.thumbnail} alt={video.title} width="480" height="270" loading="lazy" /></a>').replace('.home-video__image iframe {','.home-video__image img {'));
await edit(c+'components/home/desktop/DesktopHomeReviews.svelte',s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${JSON.stringify([{id:'stock',description:f.stockNote,avatar:f.logo,name:'Публикувани автомобили',meta:'Mobile.bg'},{id:'contact',description:f.address+', Варна',avatar:f.logo,name:'Посещение',meta:f.hoursNote},{id:'terms',description:'Бартер и лизинг са посочени в обявите. Конкретните условия се уточняват по телефона.',avatar:f.logo,name:'Условия',meta:f.phoneDisplay}],null,2)};`).replace("const starIds = ['star-1', 'star-2', 'star-3', 'star-4', 'star-5'] as const;","const starIds: string[] = [];").replaceAll('Отзиви от клиенти','Полезна информация').replaceAll('Какво казват клиентите','Преди посещение'));
await edit(c+'components/detail/desktop/desktop-detail-reviews-data.ts',s=>s.slice(0,s.indexOf('export const desktopDetailStarIndexes'))+`export const desktopDetailStarIndexes: number[] = [];\nexport const desktopDetailRatingRows: {id:string;label:string;percent:string}[] = [];\nexport const desktopDetailReviews: DesktopDetailReview[] = ${JSON.stringify([{id:'stock',name:'Наличност',date:'Потвърждение по телефона',text:f.stockNote,avatar:f.logo},{id:'visit',name:'Посещение',date:'Варна',text:f.address+'. '+f.hoursNote,avatar:f.logo}],null,2)};`);
for(const p of [c+'components/detail/desktop/DesktopDetailReviews.svelte',c+'components/reviews/DesktopPublicReviewsPage.svelte',c+'components/reviews/ReviewsContent.svelte'])await edit(p,s=>s.replaceAll('Отзиви от клиенти','Преди посещение').replaceAll('Добавете отзив','Свържете се с нас').replaceAll('4.8','—').replace('const starIndexes = [1, 2, 3, 4, 5] as const;','const starIndexes: number[] = [];').replaceAll('Имейлът няма да бъде публикуван','Уточнете наличността и условията с продавача.'));
await edit(c+'components/about/DesktopAboutPage.svelte',s=>s.replace("const demoNames = ['Александър Петров', 'Николай Димитров', 'Мария Иванова', 'Елена Георгиева'];","const demoNames = ['Контакт за автомобили', 'Въпроси за бартер', 'Въпроси за условия', 'Уговорете оглед'];").replaceAll('Съдействаме с регистрацията, документите и вариантите за финансиране на избрания автомобил.','Попитайте за документите и условията за избрания автомобил.'));
await edit(c+'data/daynight-team.ts',s=>s.replace(/name: [^\n]+/g,"name: 'Контакт с Иво Ауто',").replace(/bio: '[^']*'/g,"bio: 'Попитайте за публикуваните автомобили и условията за оглед.'").replace(/detail:\s*(?:"[^"]*"|'[^']*')/g,"detail: 'Свържете се с Иво Ауто по телефона, за да уточните наличността, оборудването и условията.'"));
await edit(c+'components/home/desktop/DesktopHomeWhyDayNight.svelte',s=>s.replace("value: '4',\n\t\t\tlabel: 'директни канала за контакт'","value: '2',\n\t\t\tlabel: 'публични телефона'").replaceAll('Налични автомобила','Подбрани обяви'));
// Remove source favicons from wired application routes by replacing them with the transparent wordmark.
for(const key of ['auto-best','carwow'])await edit(root+'/'+key+'/src/app.html',s=>s.replace(/href="[^"]*(?:favicon[^" ]*|logo[^" ]*)"/g,`href="${f.logo}"`));
console.log('Secondary content pass complete');
