import fs from 'node:fs/promises';import path from 'node:path';const root='J:/cars/clients/ivo-auto/auto-best';
let s=await fs.readFile(root+'/src/lib/components/layout/Header.svelte','utf8');s=s.replace('<img src={brand.logo} alt={brand.name} width="220" height="58" fetchpriority="high" />','<picture><source media="(max-width: 767px)" srcset={brand.logoLight} /><img src={brand.logo} alt={brand.name} width="220" height="58" fetchpriority="high" /></picture>');await fs.writeFile(root+'/src/lib/components/layout/Header.svelte',s);
for(const name of ['SearchBox','MobileBudget']){const p=root+'/src/lib/components/home/'+name+'.svelte';s=await fs.readFile(p,'utf8');s=s.replaceAll('60000','10000').replaceAll('70000','20000').replaceAll('60 000','10 000').replaceAll('60–70 000','10–20 000').replaceAll('70 000','20 000');await fs.writeFile(p,s)}
// Retain the master's generic transparent decorative artwork in its unchanged geometry.
await fs.copyFile('J:/cars/templates/auto-best/src/lib/data/vehicle-artwork.ts',root+'/src/lib/data/vehicle-artwork.ts');let orig=await fs.readFile('J:/cars/templates/auto-best/src/lib/components/ui/HeroVehicles.svelte','utf8');await fs.writeFile(root+'/src/lib/components/ui/HeroVehicles.svelte',orig);
s=await fs.readFile(root+'/src/app.css','utf8');s=s.replace('--dn-red: #c40101','--dn-red: #242424').replace('--dn-red-hover: #a90000','--dn-red-hover: #080808');await fs.writeFile(root+'/src/app.css',s);
async function walk(d){let a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())a.push(...await walk(p));else a.push(p)}return a}
const refs=new Set();for(const p of await walk(root+'/src'))if(/\.(css|html|js|svelte|ts)$/.test(p)){const text=await fs.readFile(p,'utf8');for(const m of text.matchAll(/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi))refs.add(m[0]);}
const removed=[];for(const p of await walk(root+'/static')){const rel='/'+path.relative(root+'/static',p).replaceAll('\\','/');if(!refs.has(rel)){const absolute=path.resolve(p);if(!absolute.startsWith(path.resolve(root+'/static')+path.sep))throw Error('Out of scope asset');await fs.unlink(p);removed.push(rel)}}
await fs.writeFile('J:/cars/clients/ivo-auto/evidence/auto-asset-inventory.json',JSON.stringify({refs:[...refs],removed,decorative:'Master transparent car cutouts retained solely as decorative artwork, not dealer stock.'},null,2));s=await fs.readFile(root+'/scripts/check-assets.mjs','utf8');s=s.replace(/const guardedMediaCount = \d+;/,`const guardedMediaCount = ${refs.size};`);await fs.writeFile(root+'/scripts/check-assets.mjs',s);console.log(refs.size,'referenced assets; unreferenced cloned assets removed:',removed.length);
