import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/ivo-auto',f=JSON.parse(await fs.readFile(root+'/business-facts.json')),stock=JSON.parse(await fs.readFile(root+'/stock.json'));const changed=[];
async function edit(p,fn){const s=await fs.readFile(p,'utf8'),n=fn(s);if(s!==n){await fs.writeFile(p,n);changed.push(p)}}
async function walk(d){let a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())a.push(...await walk(p));else a.push(p)}return a}
const repl=[['Day & Night Auto Group',f.name],['Day &amp; Night Auto Group',f.name],['DAY & NIGHT AUTO GROUP',f.name],['DAY NIGHT AUTO GROUP',f.name],['Day Night Auto Group',f.name],['Day & Night',f.name],['Day Night Auto',f.name],['Ден и Нощ Ауто Груп',f.name],['087 982 4625',f.phoneDisplay],['0877 733 110',f.phoneDisplay],['0877733110','0878720035'],['0879824625','0878720035'],['+359877733110','+359878720035'],['+359879824625','+359878720035'],['София','Варна'],['Sofia','Varna'],['ул. „Атанас Манчев“ 18, Студентски град',f.address],['ул. Атанас Манчев 18',f.address],['Атанас Манчев 18','Цар Освободител 256'],['Студентски град','Владислав Варненчик'],['daynight.mobile.bg','ivoauto-varna.mobile.bg'],['Собствен лизинг','Лизинг по запитване'],['собствен лизинг','лизинг по запитване']];
for(const key of ['auto-best','carwow','modern']){
 const dirs=key==='modern'?['apps/web','packages/marketplace','packages/marketplace-domain','packages/marketplace-ui','packages/seo']:['src'];
 for(const d of dirs)for(const p of await walk(root+'/'+key+'/'+d))if(/\.(svelte|tsx?|css|html|json|svg)$/.test(p)&&!/(test|spec)\./.test(p))await edit(p,s=>{for(const [a,b]of repl)s=s.replaceAll(a,b);s=s.replace(/https:\/\/(?:www\.)?(?:instagram\.com\/dayandnight_autogroup\/|facebook\.com\/deninoshtautogroup\/|youtube\.com\/@kristiankirilov1355(?:\/videos)?)/g,f.stockUrl);return s});
 const publicDir=root+'/'+key+(key==='modern'?'/apps/web/public':'/static');await fs.mkdir(publicDir+'/assets/ivo-auto',{recursive:true});for(const e of await fs.readdir(root+'/assets'))if(/\.(svg|webp)$/.test(e))await fs.copyFile(root+'/assets/'+e,publicDir+'/assets/ivo-auto/'+e);
}
const ar=root+'/auto-best';
await fs.writeFile(ar+'/src/lib/config/brand.ts',`export const brand = ${JSON.stringify({...f,addressLine:f.address,address:f.address+', '+f.city,phone:f.phoneDisplay,appointment:f.hoursNote,youtubeUrl:f.stockUrl,instagramUrl:f.stockUrl,facebookUrl:f.stockUrl},null,2)} as const;\n`);
await edit(ar+'/src/lib/data/inventory.ts',s=>s.replace('  id: number;','  gallery: string[];\n  sourceUrl: string;\n  description: string;\n  id: number;').replace(/export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`export const featuredVehicles: Vehicle[] = ${JSON.stringify(stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,description:v.description,category:({SUV:'Джип',Wagon:'Комби',Coupe:'Купе',Minivan:'Ван',Sedan:'Седан'})[v.body]||v.body,body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:v.features,condition:'used',priceEur:v.priceEur,href:'/listing-detail-v1/'+(i+1)})),null,2)};`));
await edit(ar+'/src/lib/data/listing.ts',s=>s.replace(/makes: \[[^\n]+/,`makes: ['', ...new Set(featuredVehicles.map(v=>v.make))],`).replace(/bodies: \[[^\n]+/,`bodies: ['', ...new Set(featuredVehicles.map(v=>v.body))],`).replace(/years: \[[^\n]+/,`years: ['', ...new Set(featuredVehicles.map(v=>v.year))].sort(),`).replace(/prices: \[[^\n]+/,`prices: ['', '3000', '5000', '10000', '20000', '50000', '100000', '120000'],`).replace(/mileages: \[[^\n]+/,`mileages: ['', '75000', '100000', '150000', '200000', '250000', '300000'],`));
const detail=ar+'/src/routes/listing-detail-v1/[id]/+page.svelte';await edit(detail,s=>s.replace("let { data }: { data: PageData } = $props();","let { data }: { data: PageData } = $props();\n  let selectedPhotos = $state<Record<number, number>>({});\n  let photoIndex = $derived(selectedPhotos[data.vehicle.id] ?? 0);").replace('src={data.vehicle.image}','src={data.vehicle.gallery[photoIndex]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>',`<div class="dn-detail-gallery__count">{#each data.vehicle.gallery as photo, index (photo)}<button type="button" aria-label={\`Снимка \${index + 1}\`} aria-pressed={photoIndex === index} onclick={() => selectedPhotos[data.vehicle.id] = index}>{index + 1}</button>{/each}</div>`));
// All identity-bearing source imagery is substituted at its existing wired reference.
for(const p of await walk(ar+'/src'))if(/\.(svelte|ts|css|html)$/.test(p))await edit(p,s=>s.replace(/\/assets\/images\/lead\/[A-Za-z0-9._-]+\.(?:webp|jpg|png)/g,m=>m.includes('logo')?f.logo:stock[0].images[0]));
// No verified dealer video channel: keep the section/card geometry, show listing links and photographs.
await edit(ar+'/src/lib/data/videos.ts',s=>s.replace(/export const featuredVideos:[\s\S]*/,`export const featuredVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'Обява',thumbnail:v.images[0],url:v.sourceUrl})),null,2)};\n`));
await edit(ar+'/src/lib/components/home/VideoSection.svelte',s=>s.replace(/<h2 id="videos-title"[\s\S]*?<\/h2>/,`<h2 id="videos-title" class="dn-home-section-title">Още за автомобилите</h2>`).replace(/<p>[^<]*<\/p>/,'<p>Снимки и подробности от публикуваните обяви на Иво Ауто.</p>').replaceAll('Всички видеа','Всички обяви').replaceAll('Гледайте в YouTube','Вижте обявата').replaceAll('Към канала','Към обявите').replace('onclick={(event) => play(video.id, event)}','onclick={() => window.open(video.url, "_blank", "noopener,noreferrer")}').replace('href={`https://www.youtube.com/watch?v=${video.id}`}','href={video.url}').replace('Пуснете видеото:','Отворете обявата:'));
const cr=root+'/carwow';
await edit(cr+'/src/lib/data/daynight-site.ts',s=>s.replace(/name: '[^']*'/,`name: '${f.name}'`).replace(/shortName: '[^']*'/,`shortName: '${f.name}'`).replace(/location: '[^']*'/,`location: '${f.address}, Варна'`).replace(/mapUrl:\s*'[^']*'/,`mapUrl: '${f.mapsUrl}'`).replace(/inventoryCount: \d+/,`inventoryCount: ${stock.length}`).replace(/logoLight: '[^']*'/,`logoLight: '${f.logoLight}'`).replace(/logoDark: '[^']*'/,`logoDark: '${f.logo}'`).replace(/heroSubtitle: '[^']*'/,`heroSubtitle: 'Автомобили във Варна · бул. Цар Освободител 256'`));
const current=stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:v.priceEur.toLocaleString('bg-BG')+' €',priceBgn:(v.priceEur*1.95583).toLocaleString('bg-BG',{maximumFractionDigits:2})+' лв.',status:'Публикувана обява',date:v.date,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',color:v.color,fuel:v.fuel,power:v.powerHp?v.powerHp+' к.с.':'—',transmission:v.transmission,body:({SUV:'Джип',Sedan:'Седан',Coupe:'Купе',Wagon:'Комби',Minivan:'Ван'})[v.body]||v.body,features:v.features,image:v.images[0],gallery:v.images}));
await edit(cr+'/src/lib/data/daynight-current-inventory.ts',s=>s.slice(0,s.indexOf('export const currentDayNightListings')).replace('image: string;','image: string;\n gallery: string[];')+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(current,null,2)};\n`);
await edit(cr+'/src/lib/data/daynight-vehicles.ts',s=>s.replace('gallery: [listing.image]','gallery: listing.gallery').replace(/monthly: `[^`]+`/,"monthly: 'Условия по запитване'").replace("doors: body === 'Купе' ? 3 : 5","doors: 0").replaceAll('Наличен автомобил в Варна','Публикуван автомобил във Варна').replaceAll('DN-','IVO-'));
for(const p of await walk(cr+'/src'))if(/\.(svelte|ts|css|html)$/.test(p))await edit(p,s=>s.replace(/\/(?:brand|assets\/daynight|assets\/images\/pages)\/[A-Za-z0-9_./-]+\.(?:webp|jpg|png)/g,m=>m.includes('logo')?f.logo:stock[0].images[0]));
await edit(cr+'/src/lib/data/daynight-videos.ts',s=>`export const youtubeChannelUrl = '${f.stockUrl}';\nexport const homeVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'Обява',thumbnail:v.images[0],url:v.sourceUrl})),null,2)} as const;`);
// Replace unverified reviews with truthful practical information at the existing data boundary.
await edit(cr+'/src/lib/data/daynight-reviews.ts',s=>s.slice(0,s.indexOf('export const daynightReviews'))+`export const daynightReviews = ${JSON.stringify([{name:'Автомобили',label:'Публикувани обяви',text:f.stockNote},{name:'Посещение',label:'Варна',text:f.address},{name:'Телефон',label:'Контакт',text:f.phoneDisplay},{name:'Бартер',label:'Според обявата',text:'Попитайте за условията за конкретния автомобил.'},{name:'Лизинг',label:'Според обявата',text:'Условията се потвърждават индивидуално с продавача.'},{name:'Работно време',label:'Преди посещение',text:f.hoursNote}].map((v,i)=>({...v,id:'info-'+i,avatar:f.logo})),null,2)} satisfies DayNightReview[];\nexport const daynightReviewCount=daynightReviews.length;\nexport const daynightReviewCountLabel='Полезна информация';\nexport const daynightReviewLinkLabel='Контакт и условия';\n`);
const mr=root+'/modern';await edit(mr+'/packages/marketplace/lead-site.ts',s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify({accent:f.accent,address:f.address,city:f.city,contactUrl:f.phoneHref,country:f.country,countryCode:'BG',currency:'EUR',email:'',heroPath:stock[0].images[0],locale:'bg-BG',logoPath:f.logo,mapsEmbedUrl:f.mapsEmbedUrl,mapsUrl:f.mapsUrl,name:f.name,phoneDisplay:f.phoneDisplay,phoneHref:f.phoneHref,shortName:f.name,slug:'ivo-auto',socialLinks:{},staticDemoMode:true,tagline:'Автомобили във Варна. Наличност и условия по телефона.'},null,2)};`));
const listings=stock.map((v,i)=>({id:'ivo-'+v.id,slug:'ivo-'+v.id,category:'car',dealerOrgId:'dealer-ivo-auto',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:'Варна',region:'Владислав Варненчик',country:'България'},features:v.features.map(bg=>({bg,en:bg})),spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Coupe:'coupe',Sedan:'sedan',Minivan:'minivan'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',...(v.powerHp?{enginePowerHp:v.powerHp}:{}),colorExterior:v.color},seller:{id:'dealer-ivo-auto',type:'dealer',displayName:f.name,verificationStatus:'unverified',city:'Варна'},publishedAt:new Date(Date.UTC(2026,8,7,10,0,-i)).toISOString(),promoted:false}));
await edit(mr+'/packages/marketplace-domain/testing/mock-data.ts',s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`));
await fs.writeFile(root+'/evidence/personalization.json',JSON.stringify({changed,stockCount:stock.length,modernDetail:'/bg/listing/'+listings[0].slug},null,2));console.log('Personalized',changed.length,'files; 16 vehicles/64 photos per variant');
