import fs from 'node:fs/promises';
import {chromium} from './auto-best/node_modules/playwright/index.mjs';
const root='J:/cars/clients/ivo-auto',data=JSON.parse(await fs.readFile(root+'/evidence/stock.json'));const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();const stock=[],downloads=[];
for(let n=0;n<data.cards.length;n++){
 const c=data.cards[n],raw=c.parts.find(p=>p.cls==='params').text,top=c.parts.find(p=>p.cls==='zaglavie').text,id=c.url.match(/obiava-(\d+)/)[1];
 await p.goto(c.url,{waitUntil:'domcontentloaded'});
 const detail=await p.evaluate(()=>({text:document.body.innerText,images:[...document.images].map(i=>i.currentSrc||i.src).filter(s=>s.includes('photosorg'))}));await fs.writeFile(`${root}/evidence/detail-${id}.json`,JSON.stringify(detail,null,2));
 const urls=[...new Set(detail.images.map(u=>u.replace(/\/big\d+\//,'/big1/')))];const images=[];
 for(const [i,url] of urls.slice(0,4).entries()) {const name=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;const r=await fetch(url);if(!r.ok)throw Error(r.status+' '+url);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));images.push('/assets/ivo-auto/'+name);downloads.push({url,path:'assets/'+name,sourcePage:c.url});}
 const make=c.title.split(' ')[0],year=Number(raw.match(/(?:19|20)\d{2}/)[0]),mileageKm=Number(raw.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),priceEur=Number(top.match(/([\d\s]+)\s*€/)[1].replace(/\s/g,''));
 const fuel=raw.includes('Дизелов')?'Дизел':raw.includes('Бензинов')?'Бензин':raw.includes('Хибриден')?'Хибрид':'Електрически';const body=raw.includes('Джип')?'SUV':raw.includes('Комби')?'Wagon':raw.includes('Купе')?'Coupe':raw.includes('Ван')?'Minivan':raw.includes('Хечбек')?'Hatchback':'Sedan';
 stock.push({id,title:c.title,make,model:c.title.slice(make.length).trim(),year,mileageKm,priceEur,fuel,transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',body,powerHp:Number(raw.match(/(\d+)\s*к\.с\./)?.[1]||0),color:raw.match(/км\s+(.+?)\s+(?:Дизелов|Бензинов|Електрически|Хибриден)/)?.[1]||'',date:raw.match(/^(.+?г\.)/)[1],features:['4x4','Навигация','Парктроник'].filter(x=>detail.text.includes(x)),vat:'Не се начислява ДДС',sourceUrl:c.url,images,description:`${c.title}, ${year} г., ${mileageKm.toLocaleString('bg-BG')} км. Публикувана обява на Иво Ауто. Потвърдете наличността, оборудването и условията по телефона.`,rawFacts:raw});console.log(n+1,c.title,images.length);
}
await b.close();await fs.writeFile(root+'/stock.json',JSON.stringify(stock,null,2));await fs.writeFile(root+'/assets/provenance.json',JSON.stringify({capturedAt:new Date().toISOString(),logo:{status:'temporary text wordmark; no verified official logo found',source:'https://ivoauto-varna.mobile.bg/'},stock:downloads,watermarks:'Preserved source photos without cropping or watermark removal'},null,2));
const mapsQuery=encodeURIComponent('Иво Ауто, бул. Цар Освободител 256, Варна');const facts={name:'Иво Ауто',latinName:'IVO AUTO',shortName:'Иво Ауто',phoneDisplay:'0878 720 035',phoneHref:'tel:+359878720035',secondaryPhone:'0898 300 036',address:'бул. „Цар Освободител“ 256',city:'Варна',country:'България',email:'',hours:[],hoursNote:'Свържете се за работно време и оглед.',mapsUrl:'https://www.google.com/maps/search/?api=1&query='+mapsQuery,mapsEmbedUrl:'https://maps.google.com/maps?q='+mapsQuery+'&output=embed',stockUrl:'https://ivoauto-varna.mobile.bg/',website:null,socialLinks:{},logo:'/assets/ivo-auto/wordmark.svg',logoLight:'/assets/ivo-auto/wordmark-light.svg',logoStatus:'Temporary text wordmark, not an official logo',accent:'#222222',accentNote:'Neutral temporary identity; official brand colours not verified',services:['Продажба на автомобили','Бартер според обявата','Лизинг според обявата'],stockCount:stock.length,stockSnapshotDate:'2026-09-07',stockNote:'Подбрани публикувани обяви; наличностите и условията се потвърждават с Иво Ауто.',sources:['https://ivoauto-varna.mobile.bg/','https://ivoauto-varna.mobile.bg/contacts','https://ivoauto-varna.mobile.bg/about']};await fs.writeFile(root+'/business-facts.json',JSON.stringify(facts,null,2));
for(const [suffix,color]of [['','#171717'],['-light','#ffffff']])await fs.writeFile(`${root}/assets/wordmark${suffix}.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="70" viewBox="0 0 300 70"><text x="2" y="49" font-family="Arial,sans-serif" font-weight="700" font-size="48" fill="${color}">ИВО АУТО</text></svg>`);
