export type CapturedDealer = {
  address: string;
  languages: string;
  openingHours: string;
  years: string;
  listings: string;
  referrals: string;
  descriptionAccuracy: string;
  highlights: string[];
  logo: string;
  logoWidth?: number;
};
/** Static reference facts from Android captures 204 and 205, not live dealer data. */
export const capturedDealers: Record<string, CapturedDealer> = {
  "21784728210405323": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11782122632841845": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11781786688563618": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21781366888650416": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21784223776383846": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21781186627237038": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21775198700636300": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21758203454344162": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11782540302515038": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11784224743668074": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11777018671764829": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11783434857807146": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11782479430635636": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11779001443562014": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21781097577012835": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21783785043166128": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21784134153263153": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21765900685685588": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21777637702876978": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21780050061781136": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11781282994167628": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11775899765171119": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11781969350224394": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21782920140707096": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21782329010196509": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21784136402983332": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11775198338574112": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21781787768273938": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11778599312336917": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11782541049698048": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21762334502775312": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21782329865022942": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11784380846697521": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11784130537689775": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11778179700610297": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11782329384140338": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11778085846169037": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11774291387702102": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "21782661898906066": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  },
  "11781790478711568": {
    "address": "ул. „Атанас Манчев“ 18, Студентски град, София",
    "languages": "",
    "openingHours": "Посещения с предварителна уговорка.",
    "years": "",
    "listings": "40",
    "referrals": "",
    "descriptionAccuracy": "",
    "highlights": [],
    "logo": "/dealer-brand/logo-on-light.webp",
    "logoWidth": 128
  }
};
