// Generated by Cars native configuration adapter; change dealer.json, not this file.
export const carsLocale = {
  "schemaVersion": 1,
  "dealerId": "ae-sharjah-al-hamoor-al-thahabi",
  "defaultLocale": "en",
  "enabledLocales": [
    "en",
    "bg"
  ],
  "dealerCountry": "AE",
  "inventoryCurrency": "AED"
} as const;
