import * as stylex from '@stylexjs/stylex';
const s = stylex.create({
  calculator: { maskImage: 'url(/variant-5/icons/native-vector/calculator.svg)' },
  brandMark: { maskImage: 'url(/variant-5/icons/native-vector/brandMark.svg)' },
  userRemove: { maskImage: 'url(/variant-5/icons/native-vector/userRemove.svg)' },
  userAdd: { maskImage: 'url(/variant-5/icons/native-vector/userAdd.svg)' },
  bellOn: { maskImage: 'url(/variant-5/icons/native-vector/bellOn.svg)' },
  refresh: { maskImage: 'url(/variant-5/icons/native-vector/refresh.svg)' },
  base: {
    display: 'inline-block',
    flexShrink: 0,
    backgroundColor: 'currentColor',
    maskSize: 'contain',
    maskPosition: 'center',
    maskRepeat: 'no-repeat',
    verticalAlign: 'middle',
  },
  size: (size: number) => ({ width: size, height: size }),
  layoutCard: { maskImage: 'url(/variant-5/icons/native-vector/layoutCard.svg)' },
  sortAscending: { maskImage: 'url(/variant-5/icons/native-vector/sortAscending.svg)' },
  sortDescending: { maskImage: 'url(/variant-5/icons/native-vector/sortDescending.svg)' },
  ratingStar: { maskImage: 'url(/variant-5/icons/native-vector/ratingStar.svg)' },
  electricCar: { maskImage: 'url(/variant-5/icons/native-vector/electricCar.svg)' },
  mobeeLogo: {
    maskImage: 'url(/variant-5/icons/native-vector/mobeeLogo.svg)',
    backgroundImage: 'linear-gradient(115deg,#9353cf,#b69ef3)',
  },
  helmet: { maskImage: 'url(/variant-5/icons/native-vector/helmet.svg)' },
  bicycle: { maskImage: 'url(/variant-5/icons/native-vector/bicycle.svg)' },
  umbrella: { maskImage: 'url(/variant-5/icons/native-vector/umbrella.svg)' },
  category: { maskImage: 'url(/variant-5/icons/native-vector/category.svg)' },
  photo: { maskImage: 'url(/variant-5/icons/native-vector/photo.svg)' },
  registration: { maskImage: 'url(/variant-5/icons/native-vector/registration.svg)' },
  checkCircle: { maskImage: 'url(/variant-5/icons/native-vector/checkCircle.svg)' },
  date: { maskImage: 'url(/variant-5/icons/native-vector/date.svg)' },
  back: { maskImage: 'url(/variant-5/icons/native-vector/back.svg)' },
  arrow: { maskImage: 'url(/variant-5/icons/native-vector/arrow.svg)' },
  bell: { maskImage: 'url(/variant-5/icons/native-vector/bell.svg)' },
  bike: { maskImage: 'url(/variant-5/icons/native-vector/bike.svg)' },
  camera: { maskImage: 'url(/variant-5/icons/native-vector/camera.svg)' },
  car: { maskImage: 'url(/variant-5/icons/native-vector/car.svg)' },
  check: { maskImage: 'url(/variant-5/icons/native-vector/check.svg)' },
  down: { maskImage: 'url(/variant-5/icons/native-vector/down.svg)' },
  left: { maskImage: 'url(/variant-5/icons/native-vector/left.svg)' },
  right: { maskImage: 'url(/variant-5/icons/native-vector/right.svg)' },
  up: { maskImage: 'url(/variant-5/icons/native-vector/up.svg)' },
  help: { maskImage: 'url(/variant-5/icons/native-vector/help.svg)' },
  user: { maskImage: 'url(/variant-5/icons/native-vector/user.svg)' },
  checklist: { maskImage: 'url(/variant-5/icons/native-vector/checklist.svg)' },
  fuel: { maskImage: 'url(/variant-5/icons/native-vector/fuel.svg)' },
  gauge: { maskImage: 'url(/variant-5/icons/native-vector/gauge.svg)' },
  heart: { maskImage: 'url(/variant-5/icons/native-vector/heart.svg)' },
  heartFilled: { maskImage: 'url(/variant-5/icons/native-vector/heartFilled.svg)' },
  home: { maskImage: 'url(/variant-5/icons/native-vector/home.svg)' },
  info: { maskImage: 'url(/variant-5/icons/native-vector/info.svg)' },
  grid: { maskImage: 'url(/variant-5/icons/native-vector/grid.svg)' },
  list: { maskImage: 'url(/variant-5/icons/native-vector/list.svg)' },
  mail: { maskImage: 'url(/variant-5/icons/native-vector/mail.svg)' },
  pin: { maskImage: 'url(/variant-5/icons/native-vector/pin.svg)' },
  message: { maskImage: 'url(/variant-5/icons/native-vector/message.svg)' },
  mic: { maskImage: 'url(/variant-5/icons/native-vector/mic.svg)' },
  phone: { maskImage: 'url(/variant-5/icons/native-vector/phone.svg)' },
  plus: { maskImage: 'url(/variant-5/icons/native-vector/plus.svg)' },
  reset: { maskImage: 'url(/variant-5/icons/native-vector/reset.svg)' },
  search: { maskImage: 'url(/variant-5/icons/native-vector/search.svg)' },
  settings: { maskImage: 'url(/variant-5/icons/native-vector/settings.svg)' },
  share: { maskImage: 'url(/variant-5/icons/native-vector/share.svg)' },
  shield: { maskImage: 'url(/variant-5/icons/native-vector/shield.svg)' },
  filter: { maskImage: 'url(/variant-5/icons/native-vector/filter.svg)' },
  sparkles: { maskImage: 'url(/variant-5/icons/native-vector/sparkles.svg)' },
  star: { maskImage: 'url(/variant-5/icons/native-vector/star.svg)' },
  tag: { maskImage: 'url(/variant-5/icons/native-vector/tag.svg)' },
  trash: { maskImage: 'url(/variant-5/icons/native-vector/trash.svg)' },
  truck: { maskImage: 'url(/variant-5/icons/native-vector/truck.svg)' },
  users: { maskImage: 'url(/variant-5/icons/native-vector/users.svg)' },
  wrench: { maskImage: 'url(/variant-5/icons/native-vector/wrench.svg)' },
  close: { maskImage: 'url(/variant-5/icons/native-vector/close.svg)' },
  electric: { maskImage: 'url(/variant-5/icons/native-vector/electric.svg)' },
  zoom: { maskImage: 'url(/variant-5/icons/native-vector/zoom.svg)' },
  sort: { maskImage: 'url(/variant-5/icons/native-vector/sort.svg)' },
  mileage: { maskImage: 'url(/variant-5/icons/native-vector/mileage.svg)' },
  motorhome: { maskImage: 'url(/variant-5/icons/native-vector/motorhome.svg)' },
  transmission: { maskImage: 'url(/variant-5/icons/native-vector/transmission.svg)' },
  smartSearch: { maskImage: 'url(/variant-5/icons/native-vector/smartSearch.svg)' },
  searches: { maskImage: 'url(/variant-5/icons/native-vector/searches.svg)' },
  timer: { maskImage: 'url(/variant-5/icons/native-vector/timer.svg)' },
  globe: { maskImage: 'url(/variant-5/icons/native-vector/globe.svg)' },
  edit: { maskImage: 'url(/variant-5/icons/native-vector/edit.svg)' },
  map: { maskImage: 'url(/variant-5/icons/native-vector/map.svg)' },
  send: { maskImage: 'url(/variant-5/icons/native-vector/send.svg)' },
});
const names = [
  'calculator',
  'brandMark',
  'userRemove',
  'userAdd',
  'bellOn',
  'refresh',
  'layoutCard',
  'sortAscending',
  'sortDescending',
  'ratingStar',
  'electricCar',
  'mobeeLogo',
  'registration',
  'checkCircle',
  'helmet',
  'bicycle',
  'umbrella',
  'category',
  'photo',
  'date',
  'back',
  'arrow',
  'bell',
  'bike',
  'camera',
  'car',
  'check',
  'down',
  'left',
  'right',
  'up',
  'help',
  'user',
  'checklist',
  'fuel',
  'gauge',
  'heart',
  'heartFilled',
  'home',
  'info',
  'grid',
  'list',
  'mail',
  'pin',
  'message',
  'mic',
  'phone',
  'plus',
  'reset',
  'search',
  'settings',
  'share',
  'shield',
  'filter',
  'sparkles',
  'star',
  'tag',
  'trash',
  'truck',
  'users',
  'wrench',
  'close',
  'electric',
  'zoom',
  'sort',
  'mileage',
  'motorhome',
  'transmission',
  'smartSearch',
  'searches',
  'timer',
  'globe',
  'edit',
  'map',
  'send',
] as const;
export type NativeIconName = (typeof names)[number];
export function isNativeIcon(name: string): name is NativeIconName {
  return (names as readonly string[]).includes(name);
}
export function NativeIcon({ name, size = 24 }: { name: NativeIconName; size?: number }) {
  return <span aria-hidden="true" {...stylex.props(s.base, s[name], s.size(size))} />;
}
