import * as stylex from '@stylexjs/stylex';
import { colors } from '@/styles/tokens.stylex';
import { controlShape } from '@/styles/control-tokens.stylex';
import { showroomDesktop } from '@/styles/showroom-desktop-tokens.stylex';

export const s = stylex.create({
  page: { backgroundColor: colors.background, minWidth: 0 },
  desktopHeader: { display: { default: 'none', '@media (min-width: 1024px)': 'block' } },
  hero: {
    position: 'relative',
    aspectRatio: { default: '4 / 3', '@media (min-width: 700px)': 'auto' },
    height: {
      default: 'auto',
      '@media (min-width: 700px)': 320,
      '@media (min-width: 1024px)': 360,
    },
    backgroundColor: colors.stripe,
    overflow: 'hidden',
  },
  photo: { objectFit: 'cover', objectPosition: 'center', width: '100%', height: '100%' },
  heroShade: {
    position: 'absolute',
    inset: 0,
    backgroundImage:
      'linear-gradient(180deg, rgba(0,0,0,.6) 0%, rgba(0,0,0,.24) 40%, transparent 75%)',
  },
  back: {
    position: 'absolute',
    zIndex: 2,
    top: 12,
    left: { default: 8, '@media (min-width: 1024px)': showroomDesktop.gutter },
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
    color: '#fff',
    textDecoration: 'none',
    outlineColor: '#fff',
    outlineOffset: -4,
  },
  drawer: {
    position: 'relative',
    marginTop: -20,
    paddingInline: {
      default: 0,
      '@media (min-width: 700px)': 24,
      '@media (min-width: 1024px)': showroomDesktop.gutter,
    },
    paddingTop: { default: 0, '@media (min-width: 700px)': 24 },
    paddingBottom: 24,
    borderTopLeftRadius: {
      default: 24,
      '@media (min-width: 1024px)': showroomDesktop.drawerRadius,
    },
    borderTopRightRadius: {
      default: 24,
      '@media (min-width: 1024px)': showroomDesktop.drawerRadius,
    },
    backgroundColor: colors.background,
    boxShadow: '0 -2px 12px #0000000a',
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 1024px)': 'minmax(0,1fr) 380px',
    },
    alignItems: 'start',
    gap: { default: 24, '@media (min-width: 1024px)': 24 },
  },
  main: { minWidth: 0 },
  drawerHeader: {
    display: 'grid',
    gap: 4,
    padding: { default: 16, '@media (min-width: 700px)': 0 },
    paddingBottom: { default: 8, '@media (min-width: 700px)': 16 },
  },
  title: {
    color: colors.text,
    fontSize: { default: 20, '@media (min-width: 1024px)': 34 },
    lineHeight: { default: '28px', '@media (min-width: 1024px)': '42px' },
    fontWeight: { default: 500, '@media (min-width: 1024px)': 700 },
    overflowWrap: 'anywhere',
  },
  lead: {
    color: colors.text,
    fontSize: { default: 16, '@media (min-width: 1024px)': 15 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '26px' },
    maxWidth: 700,
    marginBottom: 20,
  },
  serviceLabel: { color: colors.muted, fontSize: 13, lineHeight: '20px' },
  summary: { color: colors.muted, fontSize: 16, lineHeight: '24px', maxWidth: 600 },
  summaryAction: {
    display: { default: 'grid', '@media (min-width: 1024px)': 'none' },
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    gap: 8,
    marginTop: 8,
  },
  action: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    width: '100%',
    maxWidth: '100%',
    paddingBlock: 4,
    paddingInline: 0,
    borderWidth: 0,
    color: colors.text,
    backgroundColor: 'transparent',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
    textDecoration: 'none',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    outlineColor: colors.text,
    outlineOffset: 3,
  },
  actionFace: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    width: '100%',
    minHeight: { default: 36, '@media (min-width: 1024px)': 48 },
    paddingBlock: { default: 6, '@media (min-width: 1024px)': 12 },
    paddingInline: 16,
    borderRadius: controlShape.pill,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.text,
    color: colors.background,
    backgroundColor: { default: colors.text, ':hover': colors.muted },
  },
  contactFace: {
    color: colors.text,
    borderColor: colors.line,
    backgroundColor: { default: colors.background, ':hover': colors.controlSurface },
  },
  sections: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    paddingInline: 0,
    backgroundColor: colors.background,
  },
  section: {
    padding: { default: 16, '@media (min-width: 700px)': 24 },
    scrollMarginTop: 64,
    borderWidth: { default: 0, '@media (min-width: 1024px)': 1 },
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: { default: 0, '@media (min-width: 1024px)': 16 },
    marginTop: { default: 0, '@media (min-width: 1024px)': 20 },
  },
  heading: {
    fontSize: { default: 18, '@media (min-width: 1024px)': 20 },
    fontWeight: 500,
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '28px' },
    marginBottom: 12,
  },
  expectations: { display: 'grid', gap: 16, listStyle: 'none' },
  expectation: {
    display: 'grid',
    gridTemplateColumns: '20px minmax(0,1fr)',
    gap: 12,
    alignItems: 'start',
  },
  check: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 20,
    height: 24,
    color: colors.muted,
  },
  itemTitle: { fontSize: 16, fontWeight: 500, lineHeight: '24px', marginBottom: 4 },
  copy: {
    fontSize: { default: 16, '@media (min-width: 1024px)': 15 },
    lineHeight: { default: '24px', '@media (min-width: 1024px)': '26px' },
    color: colors.text,
    overflowWrap: 'anywhere',
  },
  steps: { display: 'grid', gap: 16, listStyle: 'none' },
  step: { display: 'grid', gridTemplateColumns: '28px minmax(0,1fr)', gap: 12 },
  number: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.stripe,
    color: colors.muted,
    fontSize: 14,
    fontWeight: 500,
  },
  faqs: { borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: colors.cardLine },
  faq: { borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.cardLine },
  question: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    minHeight: 52,
    paddingBlock: 14,
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '24px',
    listStyle: 'none',
  },
  chevron: { flexShrink: 0, color: colors.muted },
  answer: { paddingBottom: 16, paddingRight: 24 },
  aside: {
    display: 'grid',
    gap: 24,
    marginInline: { default: 16, '@media (min-width: 700px)': 0 },
    position: { default: 'static', '@media (min-width: 1024px)': 'sticky' },
    top: 24,
    minWidth: 0,
  },
  enquiry: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    padding: 24,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.cardLine,
    borderRadius: showroomDesktop.panelRadius,
    backgroundColor: colors.stripe,
  },
  note: { color: colors.muted, fontSize: 12, lineHeight: '18px' },
  related: { minWidth: 0 },
  relatedLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 52,
    paddingBlock: 12,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.cardLine,
    fontSize: 14,
    fontWeight: 500,
    textDecoration: 'none',
    color: { default: colors.text, ':hover': colors.muted },
  },
  demo: { fontSize: 12, lineHeight: '18px', color: colors.muted, marginTop: 28 },
});
