// Generated by Cars native configuration adapter; change dealer.json, not this file.
export const carsLocale = {
  "schemaVersion": 1,
  "dealerId": "navara-car",
  "defaultLocale": "bg",
  "enabledLocales": [
    "en",
    "bg"
  ],
  "dealerCountry": "BG",
  "inventoryCurrency": "EUR"
} as const;
