import fs from 'node:fs';
function edit(file, from, to) {
  const before = fs.readFileSync(file, 'utf8');
  if (before.split(from).length !== 2) throw new Error('Expected one match: ' + file + ' :: ' + from);
  fs.writeFileSync(file, before.replace(from, to));
  console.log('Updated', file);
}
edit('src/components/Header.tsx', "header:{height:68,display:'flex',alignItems:'center',paddingInline:8", "header:{height:60,display:'flex',alignItems:'center',paddingInline:0");
edit('src/components/Header.tsx', "paddingInline:8,overflow:'hidden'", "paddingInline:16,overflow:'hidden'");
edit('src/components/Header.tsx', "logo:{width:124", "backTitle:{paddingInline:8},logo:{width:124");
edit('src/components/Header.tsx', 'stylex.props(s.title)', 'stylex.props(s.title,back&&s.backTitle)');
edit('src/components/ui.tsx', 'gap:8,minHeight:48,paddingInline:16', 'gap:8,minHeight:44,paddingInline:16');
edit('src/components/ProfileScreens.tsx', "minHeight:'calc(100dvh - 68px)',padding:16", "minHeight:'calc(100dvh - 60px)',padding:16,paddingTop:24");
edit('src/components/ProfileScreens.tsx', 'minHeight:48,paddingBlock:12', 'minHeight:48,paddingBlock:8,fontWeight:500');
edit('src/components/ProfileScreens.tsx', "version:{paddingInline:16,fontSize:10", "version:{paddingInline:16,fontSize:12");
edit('src/components/ProfileScreens.tsx', 'icon="settings" onClick={()=>setLanguage(true)}', 'icon="globe" onClick={()=>setLanguage(true)}');
edit('src/components/SellScreen.tsx', "minHeight:'calc(100dvh - 132px)'", "minHeight:'calc(100dvh - 124px)'");
edit('src/components/SellScreen.tsx', "flexDirection:'column',gap:8},footer", "flexDirection:'column',gap:12},footer");
edit('src/components/SellScreen.tsx', 'variant="purple" icon="euro"', 'variant="purple" icon="calculator"');
edit('src/components/SellScreen.tsx', 'variant="outline" icon="gauge"', 'variant="outline" icon="timer"');
edit('src/components/HomeScreen.tsx', "fontWeight:700,fontFamily:'var(--font-hero)',whiteSpace", "fontWeight:400,fontFamily:'var(--font-hero)',whiteSpace");
edit('src/components/SavedScreens.tsx', "minHeight:'calc(100dvh - 132px)'", "minHeight:'calc(100dvh - 124px)'");
edit('src/components/SavedScreens.tsx', 'paddingInline:4,fontSize:12', 'paddingInline:4,fontSize:14');
edit('src/components/SavedScreens.tsx', 'emptyTitle:{fontSize:12', 'emptyTitle:{fontSize:14');
edit('src/components/SavedScreens.tsx', "alignItems:'flex-start',gap:8,fontSize:12", "alignItems:'flex-start',gap:8,fontSize:14");
edit('src/components/SavedScreens.tsx', 'marginTop:24,borderRadius:16', 'marginTop:16,borderRadius:16');
edit('src/components/DetailScreen.tsx', "import { money, number }", "import { money, number, serializeFilters }");
edit('src/components/DetailScreen.tsx', 'const {parked,checklist}=useAppState()', 'const {parked,checklist,filters}=useAppState()');
edit('src/components/DetailScreen.tsx', 'back="/results"', "back={'/results?'+serializeFilters(filters)}");
edit('src/components/DetailScreen.tsx', "price:{fontFamily:'var(--font-hero)',fontSize:22", "price:{fontFamily:'var(--font-hero)',fontSize:20");
edit('src/components/DetailScreen.tsx', "counter:{position:'absolute',right:8,bottom:8,paddingBlock:6,paddingInline:12,backgroundColor:'#ffffffdd',borderRadius:16,fontSize:12,color:'#1b1b23'}", "counter:{position:'absolute',right:8,bottom:8,width:84,height:32,display:'flex',alignItems:'center',justifyContent:'center',gap:8,backgroundColor:'#38393c',borderRadius:8,fontSize:14,fontWeight:700,color:'#fff'}");
edit('src/components/DetailScreen.tsx', 'stylex.props(s.counter)}>1 /', 'stylex.props(s.counter)}><Icon name="camera" size={20}/>1 /');
edit('src/components/DetailScreen.tsx', "borderWidth:0,borderRadius:10,backgroundColor:colors.surface,color:colors.purple,width:'100%'", "borderWidth:1,borderStyle:'solid',borderColor:colors.line,borderRadius:12,backgroundColor:colors.background,color:colors.accent,width:'100%'");
edit('src/components/DetailScreen.tsx', '<span>from {money(v.monthly||Math.round(v.price*.01061))} mth.</span>', '<span {...stylex.props(s.financeAmount)}>from <strong>{money(v.monthly||Math.round(v.price*.01061))}</strong> mth. <Icon name="info" size={14}/></span>');
edit('src/components/DetailScreen.tsx', '<strong>Calculate Financing</strong><Icon name="right" size={18}/>', '<strong {...stylex.props(s.financeAction)}>Calculate Financing</strong>');
edit('src/components/DetailScreen.tsx', "ad:{height:270,backgroundColor:colors.background}", "ad:{height:264,backgroundColor:colors.surface,display:'flex',alignItems:'center',justifyContent:'center'},watermark:{fontFamily:'var(--font-hero)',fontWeight:700,fontStyle:'italic',fontSize:96,color:colors.iconBg,opacity:.9},financeAmount:{display:'inline-flex',alignItems:'center',gap:4,color:colors.text,fontWeight:700,whiteSpace:'nowrap'},financeAction:{flex:1,textAlign:'center'},ratingButton:{display:'inline-flex',alignItems:'center',gap:16,borderWidth:0,backgroundColor:'transparent',color:colors.muted,padding:0}");
edit('src/components/DetailScreen.tsx', 'onClick={()=>setPriceInfo(true)} {...stylex.props(ui.resetLink)}><PriceRating veryGood={v.deal}/>', 'onClick={()=>setPriceInfo(true)} {...stylex.props(s.ratingButton)}><PriceRating veryGood={v.deal} detail/><Icon name="info" size={14}/>');
edit('src/components/DetailScreen.tsx', '<div {...stylex.props(s.ad)} aria-label="Reserved reference advertising area"/>', '<div {...stylex.props(s.ad)} aria-label="Reserved reference advertising area"><span aria-hidden="true" {...stylex.props(s.watermark)}>M</span></div>');
edit('src/components/DetailScreen.tsx', "gap:24,padding:24,backgroundColor:colors.surface", "gap:24,padding:24,backgroundColor:colors.background,borderWidth:1,borderStyle:'solid',borderColor:colors.line,borderRadius:16,marginInline:8,marginTop:-8,position:'relative'");
edit('src/components/VehicleCard.tsx', 'bar:{width:13,height:2', 'bar:{width:13,height:2');
edit('src/components/VehicleCard.tsx', "rating:{color:colors.muted,fontSize:10,lineHeight:'13px',fontWeight:700}", "rating:{color:colors.muted,fontSize:12,lineHeight:'16px',fontWeight:500},detailBar:{width:16,height:8},inactiveBar:{backgroundColor:colors.line}");
edit('src/components/VehicleCard.tsx', 'export function PriceRating({veryGood=false}:{veryGood?:boolean})', 'export function PriceRating({veryGood=false,detail=false}:{veryGood?:boolean;detail?:boolean})');
edit('src/components/VehicleCard.tsx', 'stylex.props(s.bar)', 'stylex.props(s.bar,detail&&s.detailBar,!veryGood&&i===4&&s.inactiveBar)');
edit('src/components/HomeScreen.tsx', '<span {...stylex.props(s.deals)}>•DEALS</span>', '<span {...stylex.props(s.deals)}>DEALS</span>');
edit('src/components/HomeScreen.tsx', "borderRadius:7,paddingInline:5,fontSize:20,marginInline:4", "borderRadius:5,paddingLeft:12,paddingRight:5,fontSize:20,fontWeight:500,marginInline:4,position:'relative',clipPath:'polygon(10px 0,100% 0,100% 100%,10px 100%,0 50%)','::before':{content:'\"\"',position:'absolute',left:5,top:'45%',width:4,height:4,borderRadius:'50%',backgroundColor:'#fff'}");
edit('src/components/AssistantEntry.tsx', "borderColor:'#9154ae'", "borderColor:'transparent',backgroundImage:'linear-gradient(#300047,#300047),linear-gradient(110deg,#903fa5,#80a6e6)',backgroundOrigin:'border-box',backgroundClip:'padding-box, border-box'");
edit('src/components/Icon.tsx', "import { ArrowLeft,", "import { Car, Caravan, Calculator, Globe, Timer, MessageSquareText, ArrowLeft,");
edit('src/components/Icon.tsx', 'Camera, CarFront, Check', 'Camera, Check');
edit('src/components/Icon.tsx', 'MapPin, MessageSquare, Mic', 'MapPin, Mic');
edit('src/components/Icon.tsx', 'car: CarFront', 'car: Car');
edit('src/components/Icon.tsx', 'message: MessageSquare', 'message: MessageSquareText');
edit('src/components/Icon.tsx', 'const icons = {', 'const icons = { calculator: Calculator, globe: Globe, timer: Timer,');
edit('src/components/Icon.tsx', "name === 'motorhome' ? Truck", "name === 'motorhome' ? Caravan");
edit('src/components/Icon.tsx', "  if (name === 'searches')", "  if (name === 'sparkles') return <svg width={size} height={size} viewBox=\"0 0 28 28\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M12 7c-1.5 7-3.5 9-10 11 6.5 1.5 8.5 4 10 9 1.5-5 3.5-7.5 10-9-6.5-2-8.5-4-10-11ZM22 0c-.8 3.6-2.4 5.2-6 6 3.6.8 5.2 2.4 6 6 .8-3.6 2.4-5.2 6-6-3.6-.8-5.2-2.4-6-6Z\"/></svg>;\n  if (name === 'searches')");
edit('scripts/capture-web.mjs', "import path from 'node:path';", "import path from 'node:path';\nimport sharp from 'sharp';");
edit('scripts/capture-web.mjs', 'height: 880 }, deviceScaleFactor: 1', 'height: 872 }, deviceScaleFactor: 3');
edit('scripts/capture-web.mjs', "await page.screenshot({ path: path.join(out, name + '.png') });", "await sharp(await page.screenshot()).resize(427,872).png().toFile(path.join(out, name + '.png'));");
edit('scripts/inspect-reference.mjs', 'height:2640}).resize(427,880)', 'height:2616}).resize(427,872)');
edit('scripts/inspect-reference.mjs', 'width:854,height:880', 'width:854,height:872');
