import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/priselci';
async function walk(d){let out=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.vercel','.git'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
async function edit(p,fn){const s=await fs.readFile(p,'utf8'),n=fn(s);if(s!==n)await fs.writeFile(p,n);}
await edit(`${root}/carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte`,s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,'const reviews: Review[] = []; // No verified testimonials.').replace('{#if showReviews}','{#if showReviews && reviews.length > 0}'));
for(const p of await walk(`${root}/carwow/src`))if(p.endsWith('.svelte'))await edit(p,s=>s.replace(/<a\b[^>]*(?:aria-label="(?:Facebook|Instagram|YouTube)"|\{\.\.\.(?:facebookLinkProps|instagramLinkProps|youtubeLink)\})[^>]*>[\s\S]*?<\/a>/g,'').replaceAll('Отзиви от клиенти','Отзиви — няма потвърдени публикации').replaceAll('Организираме вноса','Уточнете възможностите').replaceAll('Координираме покупката, доставката и предаването в България.','Попитайте дали автокъщата предлага внос за конкретния автомобил.').replaceAll('Оценка, замяна или директно изкупуване на автомобил.','Попитайте дали е възможна замяна за конкретния автомобил.').replaceAll('Използвайте формата за запитване','Демо форма; за контакт се обадете').replaceAll('Проверяваме автомобила, продавача и условията в обявата.','Изпратете обявата при разговор, за да уточните възможностите.'));
await edit(`${root}/carwow/src/lib/data/daynight-site.ts`,s=>s.replace("logoLight: '/assets/priselci/wordmark.svg'","logoLight: '/assets/priselci/wordmark-light.svg'").replace("logoDark: '/assets/priselci/wordmark-light.svg'","logoDark: '/assets/priselci/wordmark.svg'"));
for(const p of await walk(`${root}/modern/apps/web/app`))if(/\.(tsx?|json)$/.test(p))await edit(p,s=>s.replaceAll('Не. Можете да предложите автомобила за директно изкупуване, без да купувате друг.','Попитайте автокъщата дали предлага изкупуване или замяна. Услугата не е потвърдена за този демо сайт.').replaceAll('След огледа получавате конкретни условия за изкупуване или бартер.','Възможността и условията за изкупуване или замяна се потвърждават по телефона.').replaceAll('Автокъща Приселци представя собствени наличности и услуги за внос, лизинг и изкупуване на автомобили.','Този демонстрационен сайт показва подбрани публични обяви на Автокъща Приселци. Наличностите и услугите се потвърждават с автокъщата.'));
console.log('Removed remaining inline source testimonials and unmatched social links; qualified unverified services.');
