import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/priselci', facts=JSON.parse(await fs.readFile(`${root}/business-facts.json`)),stock=JSON.parse(await fs.readFile(`${root}/stock.json`));
const json=x=>JSON.stringify(x,null,2),changes=[];
async function walk(d){const out=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit','.vercel','.turbo'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
async function edit(p,fn){const before=await fs.readFile(p,'utf8'),after=fn(before);if(before!==after){await fs.writeFile(p,after);changes.push(path.relative(root,p));}}
const replacements=[['Day &amp; Night Auto Group',facts.name],['Day & Night Auto Group',facts.name],['DAY & NIGHT AUTO GROUP',facts.name],['DAY NIGHT AUTO GROUP',facts.name],['Day Night Auto Group',facts.name],['Day & Night',facts.shortName],['Day Night Auto',facts.shortName],['Ден и Нощ Ауто Груп',facts.name],['087 982 4625',facts.phoneDisplay],['0877 733 110',facts.phoneDisplay],['0877733110',facts.phone],['0879824625',facts.phone],['+359877733110','+359886251705'],['+359879824625','+359886251705'],['София',facts.city],['Пловдив',facts.city],['Sofia','Varna'],['ул. „Атанас Манчев“ 18, Студентски град',facts.address],['ул. Атанас Манчев 18',facts.address],['Студентски град',facts.address],['Studentski grad','Tsar Osvoboditel 285'],['Собствен лизинг','Запитване за лизинг'],['собствен лизинг','лизинг след потвърждение'],['Премиум автомобили','Употребявани автомобили'],['премиум автомобили','употребявани автомобили'],['Понеделник - Събота: 9:00 - 18:00','Работно време: по телефона'],['Делнични дни: 9:00 - 18:00 · Неделя: по уговорка','Уточнете работното време по телефона'],['Понеделник–петък: 9:00–18:00','Работно време: по телефона']];
for(const variant of ['auto-best','carwow','modern']) {
 const dirs=variant==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo','packages/internationalization']:['src'];
 for(const dir of dirs)for(const p of await walk(`${root}/${variant}/${dir}`))if(/\.(svelte|tsx?|css|html|json|svg)$/.test(p)&&!p.includes('.test.')&&!p.includes('.spec.'))await edit(p,s=>{
  for(const [a,b] of replacements)s=s.replaceAll(a,b);
  s=s.replace(/https?:\/\/(?:www\.)?(?:daynight\.mobile\.bg|daynightautogroup\.bg|dayandnightautogroup\.bg)([^\s'"<>)]*)/g,facts.stockUrl);
  s=s.replace(/https?:\/\/(?:www\.)?(?:youtube\.com\/@kristiankirilov1355|instagram\.com\/dayandnight_autogroup|facebook\.com\/deninoshtautogroup)[^\s'"<>)]*/g,facts.stockUrl);
  // Identity-bearing source photos are replaced with this dealer's photographed stock; generic cutouts stay decorative.
  s=s.replace(/\/(?:assets|brand)\/[A-Za-z0-9_./%-]*(?:day-night-logo|daynight-logo|daynight-og)[A-Za-z0-9_./%-]*\.(?:png|webp|svg)/g,facts.logo);
  s=s.replace(/\/assets\/images\/lead\/day-night-(?:stock|guide|showroom|video)[A-Za-z0-9_.-]*\.(?:png|webp|jpe?g)/g,facts.hero);
  s=s.replace(/\/assets\/images\/(?:pages|services)\/[A-Za-z0-9_.-]*daynight[A-Za-z0-9_.-]*\.(?:png|webp|jpe?g)/g,facts.hero);
  return s;
 });
 const dest=variant==='modern'?`${root}/${variant}/apps/web/public/assets/priselci`:`${root}/${variant}/static/assets/priselci`;
 await fs.mkdir(dest,{recursive:true});for(const file of await fs.readdir(`${root}/assets`))if(/\.(svg|webp)$/.test(file))await fs.copyFile(`${root}/assets/${file}`,`${dest}/${file}`);
}
// Auto Best's wired brand, inventory and filter options.
await fs.writeFile(`${root}/auto-best/src/lib/config/brand.ts`,`export const brand = ${json({name:facts.name,shortName:facts.shortName,city:facts.city,phone:facts.phoneDisplay,phoneHref:facts.phoneHref,addressLine:facts.address,address:`${facts.address}, ${facts.city}`,appointment:'Уточнете работното време и огледа по телефона',logo:facts.logo,youtubeUrl:facts.stockUrl,instagramUrl:facts.stockUrl,facebookUrl:facts.stockUrl})} as const;\n`);
await edit(`${root}/auto-best/src/lib/data/inventory.ts`,s=>{
 s=s.replace('  image: string;','  image: string;\n  gallery: string[];\n  sourceUrl: string;\n  description: string;');
 const vehicles=stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,description:v.description,category:({Wagon:'Комби',Hatchback:'Хечбек',Sedan:'Седан',Convertible:'Кабрио',Minivan:'Ван',SUV:'SUV'})[v.body],body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:[],condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`}));
 return s.replace(/\/\/ Equipment facets[\s\S]*?export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`// Representative Mobile.bg sale listings captured 2026-09-07; confirm availability.\nexport const featuredVehicles: Vehicle[] = ${json(vehicles)};`);
});
await edit(`${root}/auto-best/src/lib/data/listing.ts`,s=>s.replace(/makes: \[[^\n]+/,`makes: ${JSON.stringify(['',...new Set(stock.map(v=>v.make))])},`).replace(/bodies: \[[^\n]+/,`bodies: ${JSON.stringify(['',...new Set(stock.map(v=>v.body))])},`).replace(/transmissions: \[[^\n]+/,`transmissions: ['', 'Ръчна', 'Автоматик'],`).replace(/versions: \[[^\n]+/,`versions: [''],`).replace(/years: \[[^\n]+/,`years: ${JSON.stringify(['',...new Set(stock.map(v=>String(v.year)))].sort())},`).replace(/prices: \[[^\n]+/,`prices: ['', '2000', '3000', '4000', '5000', '6000', '8000', '10000'],`).replace(/mileages: \[[^\n]+/,`mileages: ['', '150000', '200000', '250000', '300000'],`));
await edit(`${root}/auto-best/src/app.css`,s=>s.replaceAll('#c40101',facts.accent).replaceAll('#a60000','#105432'));
await edit(`${root}/auto-best/src/lib/components/company/ShowroomMap.svelte`,s=>s.replace("  import { showroomCoordinates } from '$data/company';",'').replace(/const mapEmbedUrl = `[^`]+`;/,`const mapEmbedUrl = ${JSON.stringify(facts.mapsEmbedUrl)};`));
await edit(`${root}/auto-best/src/lib/data/company.ts`,s=>s.replace(/export const showroomCoordinates = \{[\s\S]*?\} as const;/,'// Map uses verified address search; no unverified coordinates.').replaceAll('Внос по заявка','Въпрос за автомобил').replaceAll('Да — можем','Попитайте дали можем').replaceAll('Оценка за бартер','Въпрос за замяна').replaceAll('Предложете своя автомобил за индивидуална оценка.','Попитайте дали е възможна замяна за избрания автомобил.'));
await edit(`${root}/auto-best/src/lib/data/videos.ts`,s=>s.replace(/export const featuredVideos: readonly FeaturedVideo\[\] = \[[\s\S]*?\n\];/,'export const featuredVideos: readonly FeaturedVideo[] = []; // No verified dealer video channel.'));
await edit(`${root}/auto-best/src/lib/components/home/VideoSection.svelte`,s=>s.replace('<section','{#if featuredVideos.length > 0}\n<section').replace('</section>','</section>\n{/if}'));
const detail=`${root}/auto-best/src/routes/listing-detail-v1/[id]/+page.svelte`;
await edit(detail,s=>s.replace("  let activeTabsByVehicle",'  let galleryIndex = $state(0);\n  let activeTabsByVehicle').replace('src={data.vehicle.image}','src={data.vehicle.gallery[galleryIndex % data.vehicle.gallery.length]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<div class="dn-detail-gallery__count">\n                  {#each data.vehicle.gallery as photo, index (photo)}<button type="button" aria-label={`Снимка ${index + 1}`} aria-pressed={galleryIndex === index} onclick={() => galleryIndex = index}><span></span></button>{/each}\n                </div>').replace('{data.vehicle.title} е част от актуалната селекция на {brand.name}. Свържете се с\n                    екипа за потвърдени данни за състоянието, наличността и следващите стъпки.','{data.vehicle.description}').replace('<ul class="dn-detail-equipment">','{#if !data.vehicle.equipment.length}<p>Оборудването се потвърждава по оригиналната обява и при оглед.</p>{/if}\n                  <ul class="dn-detail-equipment">'));
// Carwow's existing listing adapter retains its routes, cards and gallery behavior.
await fs.writeFile(`${root}/carwow/src/lib/data/priselci-stock.json`,json(stock));
await edit(`${root}/carwow/src/lib/data/daynight-current-inventory.ts`,s=>s.slice(0,s.indexOf('export const currentDayNightListings'))+`export const currentDayNightListings: CurrentDayNightListing[] = ${json(stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:`${v.priceEur.toLocaleString('bg-BG')} €`,priceBgn:`${(v.priceEur*1.95583).toFixed(2)} лв.`,status:'Публикувана обява',date:v.date,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,color:v.color,fuel:v.fuel,power:`${v.powerHp} к.с.`,transmission:v.transmission,body:({Wagon:'Комби',Hatchback:'Хечбек',Sedan:'Седан',Convertible:'Кабрио',Minivan:'Ван',SUV:'SUV'})[v.body],features:v.features,image:v.images[0]})))};\n`);
await edit(`${root}/carwow/src/lib/data/daynight-vehicles.ts`,s=>"import stock from './priselci-stock.json';\n"+s.replace('const identity = getVehicleIdentity(listing);','const original = stock.find(v => v.id === listing.id)!;\n\tconst identity = {brand: original.make, model: original.model, shortTitle: original.title};').replace("const availability = isIncoming ? 'Очакван внос' : 'Наличен';","const availability = isIncoming ? 'Очакван внос' : 'Публикувана обява';").replace('gallery: [listing.image]','gallery: original.images').replace("doors: body === 'Купе' ? 3 : 5","doors: 0").replace("engine: '—'","engine: `${original.engineCc} см³`").replace(/monthly: `[^`]+`/,'monthly: \'Условия по запитване\'').replace('`DN-${listing.id.slice(-6)}`','`PR-${listing.id.slice(-6)}`').replace('Наличен автомобил в Варна — свържете се за оглед.','Обява от 07.09.2026 — потвърдете наличността и огледа.'));
await edit(`${root}/carwow/src/lib/data/daynight-site.ts`,s=>s.replace(/location: '[^']*'/,`location: '${facts.address}, ${facts.city}'`).replace(/mapUrl:\s*'[^']*'/,`mapUrl: '${facts.mapsUrl}'`).replace(/inventoryCount: \d+/,`inventoryCount: ${stock.length}`).replace(/logoDark: '[^']*'/,`logoDark: '${facts.logoLight}'`).replace(/heroSubtitle: '[^']*'/,"heroSubtitle: 'Автомобили във Варна. Изберете обява и се обадете за оглед.'"));
await edit(`${root}/carwow/src/lib/data/daynight-reviews.ts`,s=>s.replace(/export const daynightReviews = \[[\s\S]*?\] satisfies DayNightReview\[\];/,'export const daynightReviews: DayNightReview[] = [];').replace('`${daynightReviewCount} отзива`',"'Няма потвърдени отзиви'"));
await edit(`${root}/carwow/src/lib/data/daynight-videos.ts`,s=>s.slice(0,s.indexOf('export const homeVideos'))+'export const homeVideos: {id:string;title:string;duration:string;thumbnail:string;url:string}[] = [];\n');
await edit(`${root}/carwow/src/lib/components/detail/desktop/desktop-detail-reviews-data.ts`,s=>s.replace(/export const desktopDetailReviews: DesktopDetailReview\[\] = \[[\s\S]*?\n\];/,'export const desktopDetailReviews: DesktopDetailReview[] = [];').replace(/percent: '\d+%'/g,"percent: '0%'"));
for(const p of await walk(`${root}/carwow/src`))if(/\.(svelte|ts)$/.test(p))await edit(p,s=>s.replace(/>4\.[89]<\/span>/g,'>—</span>').replace(/https:\/\/www\.google\.com\/maps\/embed\?pb=[^'"\s<]+/g,facts.mapsEmbedUrl));
// Modern: full monorepo retained. Only the existing demo fixtures and wired identity are personalized.
const modern=`${root}/modern`;
const config={accent:facts.accent,address:facts.address,city:facts.city,contactUrl:facts.phoneHref,country:facts.country,countryCode:'BG',currency:'EUR',email:'',heroPath:facts.hero,locale:'bg-BG',logoPath:facts.logo,mapsEmbedUrl:facts.mapsEmbedUrl,mapsUrl:facts.mapsUrl,name:facts.name,phoneDisplay:facts.phoneDisplay,phoneHref:facts.phoneHref,shortName:facts.shortName,slug:'priselci',socialLinks:{},staticDemoMode:true,tagline:'Употребявани автомобили във Варна. Обадете се за наличност и оглед.'};
await edit(`${modern}/packages/marketplace/lead-site.ts`,s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${json(config)};`));
const listings=stock.map((v,i)=>({id:`priselci-${v.id}`,slug:`priselci-${v.id}`,category:'car',dealerOrgId:'dealer-priselci',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:facts.city,region:'Варна',country:facts.country},features:[],spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Convertible:'convertible',Minivan:'minivan',Sedan:'sedan'})[v.body],fuelType:v.fuel==='Дизел'?'diesel':'gasoline',transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-priselci',type:'dealer',displayName:facts.name,verificationStatus:'unverified',city:facts.city},publishedAt:new Date(Date.UTC(2026,8,7,10,0,-i)).toISOString(),promoted:false}));
await edit(`${modern}/packages/marketplace-domain/testing/mock-data.ts`,s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${json(listings)};`));
const entry={brandCoverage:[...new Set(stock.map(v=>v.make))].map(brand=>({authorizationVerified:false,brand,relationship:'independent_importer'})),claimStatus:'unclaimed',contact:{phone:'+359886251705',websiteUrl:facts.stockUrl},dealerOrgId:'dealer-priselci',description:config.tagline,displayName:facts.name,headquarters:{city:facts.city,countryCode:'BG'},headline:'Автомобили на бул. Цар Освободител 285',id:'directory-priselci',inventory:{activeListingCount:stock.length,inTransitCount:0,localCount:stock.length,orderableCount:0,sourceStockCount:0},orgType:'dealer',profileImage:{alt:stock[4].title,url:facts.hero},representativeVehicles:stock.slice(0,3).map(v=>({availability:'local',href:`/listing/priselci-${v.id}`,id:`priselci-${v.id}`,image:{alt:v.title,url:v.images[0]},price:{amount:v.priceEur,currency:'EUR'},title:v.title})),slug:'priselci',tradeLanes:[],verification:{businessVerified:false,inventoryCurrent:false,trustedSupplier:false}};
await fs.writeFile(`${modern}/packages/marketplace/mock-directory.ts`,`import { organizationDirectoryEntriesSchema } from './directory';\nexport const mockOrganizationDirectoryCoreEntries = organizationDirectoryEntriesSchema.parse(${json([entry])});\nexport const createMockOrganizationDirectoryScaleEntries = (_totalOrganizations = 1) => mockOrganizationDirectoryCoreEntries;\nexport const mockOrganizationDirectoryEntries = mockOrganizationDirectoryCoreEntries;\n`);
for(const p of await walk(`${modern}/apps/web`))if(/\.(tsx?|json|css)$/.test(p)&&!p.includes('node_modules'))await edit(p,s=>s.replaceAll('/day-night-contact-hero-v1.png',facts.hero).replaceAll('/lead-logo.png',facts.logo).replaceAll('/lead-hero.jpg',facts.hero));
await fs.writeFile(`${root}/evidence/personalized-files.json`,json(changes));
console.log({changedFiles:changes.length,stock:stock.length});
