import fs from 'node:fs/promises';
const root='J:/cars/clients/priselci';
const cards=JSON.parse(await fs.readFile(`${root}/evidence/cards.json`));
const picks=[0,2,3,5,6,7,8,9,10,12,13,18,27,32,33,38];
const stock=[],downloads=[];
for(const [n,index] of picks.entries()) {
 const c=cards[index],raw=c.parts.find(p=>p.cls==='params').text,top=c.parts.find(p=>p.cls==='zaglavie').text,info=c.parts.find(p=>p.cls==='info').text;
 if(/за части|разкомплект|продаден/i.test(c.title+' '+info))throw Error('Unsuitable stock '+c.title);
 const title=c.title.replaceAll('!','').trim(),make=title.startsWith('Mercedes-Benz')?'Mercedes-Benz':title.split(' ')[0];
 const year=Number(raw.match(/(?:19|20)\d{2}/)[0]),mileageKm=Number(raw.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),priceEur=Number(top.match(/([\d\s]+)\s*€/)[1].replace(/\s/g,''));
 const fuel=raw.includes('Дизелов')?'Дизел':'Бензин';const body=raw.includes('Джип')?'SUV':raw.includes('Комби')?'Wagon':raw.includes('Кабрио')?'Convertible':raw.includes('Хечбек')?'Hatchback':raw.includes('Ван')?'Minivan':'Sedan';
 const images=[];
 for(const [i,source] of c.images.entries()) {const url=source.replace(/(\/photosorg\/\d+\/\d+\/)/,'$1big1/'),name=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;const res=await fetch(url);if(!res.ok)throw Error(`${res.status} ${url}`);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await res.arrayBuffer()));images.push(`/assets/priselci/${name}`);downloads.push({url,path:`assets/${name}`,sourcePage:c.url});}
 const powerHp=Number(raw.match(/(\d+)\s*к\.с\./)?.[1]||0),engineCc=Number(raw.match(/(\d+)\s*куб\.см/)?.[1]||0);
 stock.push({id:c.url.match(/obiava-(\d+)/)[1],title,make,model:title.slice(make.length).trim(),year,mileageKm,priceEur,fuel,body,transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',powerHp,engineCc,color:raw.match(/км\s+(.+?)\s+(?:Дизелов|Бензинов)/)?.[1]||'',date:raw.match(/^(.+?г\.)/)[1],vat:'Не се начислява ДДС',sourceUrl:c.url,images,features:(info.split('Особености - ')[1]||'').split(', ').filter(Boolean),description:`${title}, ${year} г., ${mileageKm.toLocaleString('bg-BG')} км. Подбрана обява от 07.09.2026. Потвърдете наличността, оборудването и условията с Автокъща Приселци.`,rawFacts:raw});
}
const mapsQuery='бул. Цар Освободител 285, Варна, България';
const facts={name:'Автокъща Приселци',shortName:'Приселци',latinName:'Priselci',phoneDisplay:'0886 251 705',phoneHref:'tel:+359886251705',phone:'0886251705',address:'бул. „Цар Освободител“ 285',city:'Варна',country:'България',hours:['Работното време се уточнява по телефона.'],email:'',stockUrl:'https://priselci.mobile.bg/',website:null,socialLinks:{},mapsUrl:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(mapsQuery),mapsEmbedUrl:'https://maps.google.com/maps?q='+encodeURIComponent(mapsQuery)+'&output=embed',accent:'#176b43',accentStatus:'Temporary restrained green drawn from Mobile.bg profile presentation; no independent dealer brand palette verified.',logo:'/assets/priselci/wordmark.svg',logoLight:'/assets/priselci/wordmark-light.svg',logoStatus:'Temporary text wordmark, not an official dealer logo. Profile and matched search found no official logo or social account.',hero:stock[4].images[0],stockSnapshotDate:'2026-09-07',stockCount:stock.length,advertisedCategoryCount:63,services:['Продажба на употребявани автомобили','Съдействие при регистрация','Запитване за лизинг'],serviceNotes:'Listing text advertises registration, financing and consumables/service assistance; terms require direct confirmation. No own-finance claim or numeric discounts reproduced.',sources:['https://priselci.mobile.bg/','https://priselci.mobile.bg/contacts','https://priselci.mobile.bg/about','https://www.auto.bg/dealer/priselci'],addressNote:'Source misspells Цар as Цал; normalized street spelling. No precise coordinates independently verified.'};
await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));await fs.writeFile(`${root}/stock.json`,JSON.stringify(stock,null,2));
for(const [name,color] of [['wordmark.svg','#163c2b'],['wordmark-light.svg','#ffffff']])await fs.writeFile(`${root}/assets/${name}`,`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="80" viewBox="0 0 320 80"><text x="1" y="19" font-family="Arial,sans-serif" font-size="15" letter-spacing="3" fill="${color}">АВТОКЪЩА</text><text x="0" y="64" font-family="Arial,sans-serif" font-weight="700" font-size="45" fill="${color}">ПРИСЕЛЦИ</text></svg>`);
await fs.writeFile(`${root}/assets/favicon.svg`,'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#176b43"/><text x="12" y="49" font-family="Arial" font-size="45" fill="white">П</text></svg>');
await fs.writeFile(`${root}/assets/provenance.json`,JSON.stringify({capturedAt:new Date().toISOString(),photos:downloads,wordmark:{source:'Local text rendering of verified dealer name',official:false},notes:['Original listing photos with watermarks retained.','16 representative sale listings selected; not a live inventory feed.','No dealer showroom photo independently verified. Hero uses an identified stock vehicle photograph.']},null,2));console.log({vehicles:stock.length,photos:downloads.length});
