import { chromium } from 'playwright';
import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.connectOverCDP(process.argv[2]);
const page=await browser.contexts()[0].newPage();
await page.setViewportSize({width:1440,height:1000});
const results=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const open=async(route)=>{await page.goto('http://127.0.0.1:6440'+route,{waitUntil:'domcontentloaded'});await page.waitForTimeout(1200);};
await open('/inventory/');
await page.locator('.select2-selection').filter({hasText:'Make'}).first().click();
await page.getByRole('option',{name:'BMW',exact:true}).click();
await page.waitForTimeout(700);
const titles=await page.locator('.stm-isotope-sorting-main .listing-list-loop').allTextContents();
assert.equal(titles.length,5);assert(titles.every(t=>t.includes('BMW')));
assert(page.url().includes('make=bmw'));
results.push({test:'Inventory Make filter',count:titles.length,result:'pass'});
await open('/inventory/?make=nonexistent');
assert(await page.getByText('No vehicles match your search.').isVisible());
results.push({test:'Inventory empty state',result:'pass'});
await open('/inventory/');
await page.locator('.stm_ajax_pagination a').filter({hasText:/^2$/}).click();
await page.waitForTimeout(700);
assert(page.url().includes('/page/2/'));
results.push({test:'Inventory pagination',result:'pass'});
for(const route of ['loan-calculators','leasing-calculators','import-car-calculator','insurance-calculator']){
 await open('/'+route+'/');
 const field=page.locator('.ccb-field-quantity input').first();
 const before=await page.locator('body').innerText();
 await field.fill('20000');await field.press('Tab');await page.waitForTimeout(450);
 const after=await page.locator('body').innerText();
 assert.notEqual(before,after,route+' recalculates');
 results.push({test:route+' recalculates',result:'pass'});
}
await open('/pricing/');
assert.equal(await page.locator('[data-pricing-style]:visible').count(),1);
assert(await page.locator('[data-pricing-style="7"]').isVisible());
results.push({test:'Pricing defaults to style 7',result:'pass'});
await open('/');
await page.getByRole('tab',{name:'Popular items',exact:true}).click();
await page.locator('#popular-tab-content').waitFor({state:'visible'});
assert(await page.locator('#popular-tab-content').isVisible());
assert((await page.locator('#popular-tab-content img').count())>0);
results.push({test:'Homepage popular vehicles tab',result:'pass'});
await open('/listings/bmw-m5/');
await page.locator('.motors-elementor-thumbs-gallery .swiper-slide').nth(1).click();
await page.waitForTimeout(400);
assert.equal(await page.locator('.motors-elementor-big-gallery').evaluate(e=>e.swiper.activeIndex),1);
results.push({test:'BMW gallery thumbnail changes main image',result:'pass'});
await page.setViewportSize({width:390,height:844});
await open('/inventory/');
await page.locator('.mobile-menu-trigger').click();
await page.waitForTimeout(300);
assert(await page.getByRole('dialog',{name:'Navigation'}).isVisible());
await page.keyboard.press('Escape');
assert(await page.locator('.mobile-menu-trigger').evaluate(e=>document.activeElement===e));
results.push({test:'Inventory mobile navigation opens',result:'pass'});
await page.setViewportSize({width:1440,height:1000});
await open('/contact-us/');
await page.locator('input[name="first-name"]').fill('Local');
await page.locator('input[name="last-name"]').fill('Preview');
await page.locator('input[type="email"]:visible').first().fill('preview@example.test');
await page.getByRole('button',{name:'Submit',exact:true}).click();
assert(await page.locator('[data-local-feedback]').isVisible());
results.push({test:'Contact form gives honest local feedback',result:'pass'});
await writeFile('references/interactions.json',JSON.stringify({results,errors},null,2));
console.log(JSON.stringify({results,errors},null,2));
await page.close();await browser.close();
