import type { VehicleCardContent } from "#lib/content.ts";
import { normalizeCatalogBudget } from "#lib/data/mobile-catalog.ts";

export interface DiscoveryCar extends VehicleCardContent {
  priceAmount: number;
  currency: string;
  id: string;
  make: string;
  year: number;
  arrival: number;
  offer: boolean;
  exclusive: boolean;
  body: string;
}


export const discoveryCars: readonly DiscoveryCar[] = [
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21784728210405323.webp",
    "imageAlt": "Mercedes-Benz GLA 45 AMG Очакван внос AMG EDITION 1CARBONPANOHKCAMRED",
    "href": "/vehicle?id=21784728210405323",
    "title": "Mercedes-Benz GLA 45 AMG Очакван внос AMG EDITION 1CARBONPANOHKCAMRED",
    "location": "София",
    "mileage": "170000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "coupe",
    "price": "26699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 26699,
    "currency": "EUR",
    "mileageValue": 170000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21784728210405323",
    "make": "Mercedes-Benz",
    "year": 2016,
    "body": "coupe",
    "arrival": 40,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11782122632841845.webp",
    "imageAlt": "Mercedes-Benz S 63 AMG Mercedes S63 AMGE-PERFORMANCENARDO GREYRED CARBON",
    "href": "/vehicle?id=11782122632841845",
    "title": "Mercedes-Benz S 63 AMG Mercedes S63 AMGE-PERFORMANCENARDO GREYRED CARBON",
    "location": "София",
    "mileage": "30000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "143699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 143699,
    "currency": "EUR",
    "mileageValue": 30000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11782122632841845",
    "make": "Mercedes-Benz",
    "year": 2024,
    "body": "other",
    "arrival": 39,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11781786688563618.webp",
    "imageAlt": "Mercedes-Benz S 400 ОЧАКВАН ВНОС Mercedes S400d Long* AMG* Chauffeur",
    "href": "/vehicle?id=11781786688563618",
    "title": "Mercedes-Benz S 400 ОЧАКВАН ВНОС Mercedes S400d Long* AMG* Chauffeur",
    "location": "София",
    "mileage": "179000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "48699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 48699,
    "currency": "EUR",
    "mileageValue": 179000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11781786688563618",
    "make": "Mercedes-Benz",
    "year": 2019,
    "body": "other",
    "arrival": 38,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21781366888650416.webp",
    "imageAlt": "Mercedes-Benz GLS 400 ОЧАКВАН ВНОС GLS400d 63 AMG OPTIC* 3xTV* CARBON* B",
    "href": "/vehicle?id=21781366888650416",
    "title": "Mercedes-Benz GLS 400 ОЧАКВАН ВНОС GLS400d 63 AMG OPTIC* 3xTV* CARBON* B",
    "location": "София",
    "mileage": "149000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "72699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 72699,
    "currency": "EUR",
    "mileageValue": 149000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21781366888650416",
    "make": "Mercedes-Benz",
    "year": 2021,
    "body": "suv",
    "arrival": 37,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21784223776383846.webp",
    "imageAlt": "Mercedes-Benz GLE 53 4MATIC Очакван ВносGLE53 AMG Coupe* NIGHT Pack* ОБДУХВАНЕ",
    "href": "/vehicle?id=21784223776383846",
    "title": "Mercedes-Benz GLE 53 4MATIC Очакван ВносGLE53 AMG Coupe* NIGHT Pack* ОБДУХВАНЕ",
    "location": "София",
    "mileage": "105000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "71699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 71699,
    "currency": "EUR",
    "mileageValue": 105000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21784223776383846",
    "make": "Mercedes-Benz",
    "year": 2022,
    "body": "suv",
    "arrival": 36,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21781186627237038.webp",
    "imageAlt": "Mercedes-Benz GLE 400 Coupe AMG360Night PackageBURMHUDP",
    "href": "/vehicle?id=21781186627237038",
    "title": "Mercedes-Benz GLE 400 Coupe AMG360Night PackageBURMHUDP",
    "location": "София",
    "mileage": "166000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "63699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 63699,
    "currency": "EUR",
    "mileageValue": 166000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21781186627237038",
    "make": "Mercedes-Benz",
    "year": 2021,
    "body": "suv",
    "arrival": 35,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21775198700636300.webp",
    "imageAlt": "Mercedes-Benz GL 63 AMG Mercedes GL63 AMG* 3xTV* 360* VENT+ HEAT* PANORAMA",
    "href": "/vehicle?id=21775198700636300",
    "title": "Mercedes-Benz GL 63 AMG Mercedes GL63 AMG* 3xTV* 360* VENT+ HEAT* PANORAMA",
    "location": "София",
    "mileage": "139000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "32699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 32699,
    "currency": "EUR",
    "mileageValue": 139000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21775198700636300",
    "make": "Mercedes-Benz",
    "year": 2016,
    "body": "suv",
    "arrival": 34,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21758203454344162.webp",
    "imageAlt": "Mercedes-Benz G 350 Mercedes G350d AMG FACE* CAM* Heat+ Vent seats* FU",
    "href": "/vehicle?id=21758203454344162",
    "title": "Mercedes-Benz G 350 Mercedes G350d AMG FACE* CAM* Heat+ Vent seats* FU",
    "location": "София",
    "mileage": "130000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "54699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 54699,
    "currency": "EUR",
    "mileageValue": 130000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21758203454344162",
    "make": "Mercedes-Benz",
    "year": 2017,
    "body": "suv",
    "arrival": 33,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11782540302515038.webp",
    "imageAlt": "Mercedes-Benz E 63 AMG Mercedes-Benz E63S AMG* FACELIFT* 360* HUD* BURM*",
    "href": "/vehicle?id=11782540302515038",
    "title": "Mercedes-Benz E 63 AMG Mercedes-Benz E63S AMG* FACELIFT* 360* HUD* BURM*",
    "location": "София",
    "mileage": "96000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "84699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 84699,
    "currency": "EUR",
    "mileageValue": 96000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11782540302515038",
    "make": "Mercedes-Benz",
    "year": 2021,
    "body": "other",
    "arrival": 32,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11784224743668074.webp",
    "imageAlt": "Mercedes-Benz E 400 Очакван внос E400d * Facelift* AMG * 360* 3D BURM*",
    "href": "/vehicle?id=11784224743668074",
    "title": "Mercedes-Benz E 400 Очакван внос E400d * Facelift* AMG * 360* 3D BURM*",
    "location": "София",
    "mileage": "162000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "42699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 42699,
    "currency": "EUR",
    "mileageValue": 162000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11784224743668074",
    "make": "Mercedes-Benz",
    "year": 2021,
    "body": "other",
    "arrival": 31,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11777018671764829.webp",
    "imageAlt": "Mercedes-Benz E 350 ОЧАКВАН ВНОС Mercedes E350d * AMG Line*",
    "href": "/vehicle?id=11777018671764829",
    "title": "Mercedes-Benz E 350 ОЧАКВАН ВНОС Mercedes E350d * AMG Line*",
    "location": "София",
    "mileage": "140000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "28699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 28699,
    "currency": "EUR",
    "mileageValue": 140000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11777018671764829",
    "make": "Mercedes-Benz",
    "year": 2018,
    "body": "other",
    "arrival": 30,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11783434857807146.webp",
    "imageAlt": "Mercedes-Benz CLS 53 AMG ОЧАКВАН CLS53 AMG * CARBON* 360* HUD* BURM* Assis",
    "href": "/vehicle?id=11783434857807146",
    "title": "Mercedes-Benz CLS 53 AMG ОЧАКВАН CLS53 AMG * CARBON* 360* HUD* BURM* Assis",
    "location": "София",
    "mileage": "166000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "54699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 54699,
    "currency": "EUR",
    "mileageValue": 166000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11783434857807146",
    "make": "Mercedes-Benz",
    "year": 2020,
    "body": "other",
    "arrival": 29,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11782479430635636.webp",
    "imageAlt": "Mercedes-Benz CLS 400 Очакван Внос AMG * Designo* 360* Digital FullMax",
    "href": "/vehicle?id=11782479430635636",
    "title": "Mercedes-Benz CLS 400 Очакван Внос AMG * Designo* 360* Digital FullMax",
    "location": "София",
    "mileage": "171000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "37699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 37699,
    "currency": "EUR",
    "mileageValue": 171000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11782479430635636",
    "make": "Mercedes-Benz",
    "year": 2020,
    "body": "other",
    "arrival": 28,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11779001443562014.webp",
    "imageAlt": "Mercedes-Benz AMG GT Mercedes AMG GT43 BURMESTER* * CAM360* DIGITAL* AS",
    "href": "/vehicle?id=11779001443562014",
    "title": "Mercedes-Benz AMG GT Mercedes AMG GT43 BURMESTER* * CAM360* DIGITAL* AS",
    "location": "София",
    "mileage": "165000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "65699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 65699,
    "currency": "EUR",
    "mileageValue": 165000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11779001443562014",
    "make": "Mercedes-Benz",
    "year": 2019,
    "body": "other",
    "arrival": 27,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21781097577012835.webp",
    "imageAlt": "Land Rover Range Rover Sport Range Rover SPORT SVR* 600HP* PANO* 360CAM* MERIDI",
    "href": "/vehicle?id=21781097577012835",
    "title": "Land Rover Range Rover Sport Range Rover SPORT SVR* 600HP* PANO* 360CAM* MERIDI",
    "location": "София",
    "mileage": "155000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "54699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 54699,
    "currency": "EUR",
    "mileageValue": 155000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21781097577012835",
    "make": "Land",
    "year": 2021,
    "body": "suv",
    "arrival": 26,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21783785043166128.webp",
    "imageAlt": "BMW X7 Очакван Внос M50d xDrive INDIVIDUAL Swarovski Sky",
    "href": "/vehicle?id=21783785043166128",
    "title": "BMW X7 Очакван Внос M50d xDrive INDIVIDUAL Swarovski Sky",
    "location": "София",
    "mileage": "150000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "53699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 53699,
    "currency": "EUR",
    "mileageValue": 150000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21783785043166128",
    "make": "BMW",
    "year": 2021,
    "body": "suv",
    "arrival": 25,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21784134153263153.webp",
    "imageAlt": "BMW X6 Очакван Вно X6M Compе TVCARBONINDIVIDUALTWO-TonePA",
    "href": "/vehicle?id=21784134153263153",
    "title": "BMW X6 Очакван Вно X6M Compе TVCARBONINDIVIDUALTWO-TonePA",
    "location": "София",
    "mileage": "160000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "71669 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 71669,
    "currency": "EUR",
    "mileageValue": 160000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21784134153263153",
    "make": "BMW",
    "year": 2023,
    "body": "suv",
    "arrival": 24,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21765900685685588.webp",
    "imageAlt": "BMW X6 BMW X6 3. 0d M Sport* Digital* CAMERA* ASSISTANCE*",
    "href": "/vehicle?id=21765900685685588",
    "title": "BMW X6 BMW X6 3. 0d M Sport* Digital* CAMERA* ASSISTANCE*",
    "location": "София",
    "mileage": "185000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "28478.45 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 28478.45,
    "currency": "EUR",
    "mileageValue": 185000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21765900685685588",
    "make": "BMW",
    "year": 2015,
    "body": "suv",
    "arrival": 23,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21777637702876978.webp",
    "imageAlt": "BMW X6 BMW X6 4.0d M Sport* Digital* CAMERA* ASSISTANCE",
    "href": "/vehicle?id=21777637702876978",
    "title": "BMW X6 BMW X6 4.0d M Sport* Digital* CAMERA* ASSISTANCE",
    "location": "София",
    "mileage": "183000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "28699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 28699,
    "currency": "EUR",
    "mileageValue": 183000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21777637702876978",
    "make": "BMW",
    "year": 2017,
    "body": "suv",
    "arrival": 22,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21780050061781136.webp",
    "imageAlt": "BMW X6 BMW X6 M50i LASER 360HARMAN FULLMAX",
    "href": "/vehicle?id=21780050061781136",
    "title": "BMW X6 BMW X6 M50i LASER 360HARMAN FULLMAX",
    "location": "София",
    "mileage": "160000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "55699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 55699,
    "currency": "EUR",
    "mileageValue": 160000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21780050061781136",
    "make": "BMW",
    "year": 2020,
    "body": "suv",
    "arrival": 21,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11781282994167628.webp",
    "imageAlt": "BMW M5 Очакван Внос Competition* 625HP* FACE* B&W* LASER*",
    "href": "/vehicle?id=11781282994167628",
    "title": "BMW M5 Очакван Внос Competition* 625HP* FACE* B&W* LASER*",
    "location": "София",
    "mileage": "133000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "68699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 68699,
    "currency": "EUR",
    "mileageValue": 133000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11781282994167628",
    "make": "BMW",
    "year": 2021,
    "body": "other",
    "arrival": 20,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11775899765171119.webp",
    "imageAlt": "BMW 430 BMW 430xi Gran Coupe* M Sport* Digital* CAM* HARMA",
    "href": "/vehicle?id=11775899765171119",
    "title": "BMW 430 BMW 430xi Gran Coupe* M Sport* Digital* CAM* HARMA",
    "location": "София",
    "mileage": "35000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "41699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 41699,
    "currency": "EUR",
    "mileageValue": 35000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11775899765171119",
    "make": "BMW",
    "year": 2023,
    "body": "other",
    "arrival": 19,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11781969350224394.webp",
    "imageAlt": "Audi Rs6 Audi RS6 Avant PERFORMANCE CERAMIC B&O 360",
    "href": "/vehicle?id=11781969350224394",
    "title": "Audi Rs6 Audi RS6 Avant PERFORMANCE CERAMIC B&O 360",
    "location": "София",
    "mileage": "169000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "wagon",
    "price": "69699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 69699,
    "currency": "EUR",
    "mileageValue": 169000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11781969350224394",
    "make": "Audi",
    "year": 2020,
    "body": "wagon",
    "arrival": 18,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21782920140707096.webp",
    "imageAlt": "Audi Q8 ОЧАКВАН ВНОС Q8 50 TDI quattro S line Plus Exclus",
    "href": "/vehicle?id=21782920140707096",
    "title": "Audi Q8 ОЧАКВАН ВНОС Q8 50 TDI quattro S line Plus Exclus",
    "location": "София",
    "mileage": "163000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "50699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 50699,
    "currency": "EUR",
    "mileageValue": 163000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21782920140707096",
    "make": "Audi",
    "year": 2021,
    "body": "suv",
    "arrival": 17,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21782329010196509.webp",
    "imageAlt": "Audi Q7 AUDI Q7 FACE* HD MATRIX* ОБДУХВАНЕ 6+ 1",
    "href": "/vehicle?id=21782329010196509",
    "title": "Audi Q7 AUDI Q7 FACE* HD MATRIX* ОБДУХВАНЕ 6+ 1",
    "location": "София",
    "mileage": "160000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "41699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 41699,
    "currency": "EUR",
    "mileageValue": 160000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21782329010196509",
    "make": "Audi",
    "year": 2021,
    "body": "suv",
    "arrival": 16,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21784136402983332.webp",
    "imageAlt": "Audi Q7 Очакван Внос Q7 3.0TDI MATRIXHUDPANOCAM6+ 1",
    "href": "/vehicle?id=21784136402983332",
    "title": "Audi Q7 Очакван Внос Q7 3.0TDI MATRIXHUDPANOCAM6+ 1",
    "location": "София",
    "mileage": "188000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "29699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 29699,
    "currency": "EUR",
    "mileageValue": 188000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21784136402983332",
    "make": "Audi",
    "year": 2017,
    "body": "suv",
    "arrival": 15,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11775198338574112.webp",
    "imageAlt": "Audi A8 Audi A8 Long 4.2 TDI W12 Pack MEGA FULL | NIGHT",
    "href": "/vehicle?id=11775198338574112",
    "title": "Audi A8 Audi A8 Long 4.2 TDI W12 Pack MEGA FULL | NIGHT",
    "location": "София",
    "mileage": "204000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "27500 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 27500,
    "currency": "EUR",
    "mileageValue": 204000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11775198338574112",
    "make": "Audi",
    "year": 2016,
    "body": "other",
    "arrival": 14,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21781787768273938.webp",
    "imageAlt": "Mercedes-Benz GLS 400 ОЧАКВАН ВНОС Mercedes GLS400d AMGLine360BURMPANORA",
    "href": "/vehicle?id=21781787768273938",
    "title": "Mercedes-Benz GLS 400 ОЧАКВАН ВНОС Mercedes GLS400d AMGLine360BURMPANORA",
    "location": "София",
    "mileage": "172000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "59699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 59699,
    "currency": "EUR",
    "mileageValue": 172000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21781787768273938",
    "make": "Mercedes-Benz",
    "year": 2021,
    "body": "suv",
    "arrival": 13,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11778599312336917.webp",
    "imageAlt": "Mercedes-Benz E 350 Mercedes 350d * AMG OPTIC* ОБДУХВАНЕ* 360* MULTIBE",
    "href": "/vehicle?id=11778599312336917",
    "title": "Mercedes-Benz E 350 Mercedes 350d * AMG OPTIC* ОБДУХВАНЕ* 360* MULTIBE",
    "location": "София",
    "mileage": "177000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "33699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 33699,
    "currency": "EUR",
    "mileageValue": 177000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11778599312336917",
    "make": "Mercedes-Benz",
    "year": 2018,
    "body": "other",
    "arrival": 12,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11782541049698048.webp",
    "imageAlt": "Mercedes-Benz AMG GT S Mercedes-AMG GT S PRIOR DESIGN Designo Exclusive C",
    "href": "/vehicle?id=11782541049698048",
    "title": "Mercedes-Benz AMG GT S Mercedes-AMG GT S PRIOR DESIGN Designo Exclusive C",
    "location": "София",
    "mileage": "70000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "coupe",
    "price": "88699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 88699,
    "currency": "EUR",
    "mileageValue": 70000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11782541049698048",
    "make": "Mercedes-Benz",
    "year": 2017,
    "body": "coupe",
    "arrival": 11,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21762334502775312.webp",
    "imageAlt": "Lamborghini Urus LAMBORGHINI Urus FULLMAXX",
    "href": "/vehicle?id=21762334502775312",
    "title": "Lamborghini Urus LAMBORGHINI Urus FULLMAXX",
    "location": "София",
    "mileage": "86000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "172669 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 172669,
    "currency": "EUR",
    "mileageValue": 86000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21762334502775312",
    "make": "Lamborghini",
    "year": 2021,
    "body": "suv",
    "arrival": 10,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21782329865022942.webp",
    "imageAlt": "BMW X5 ОЧАКВАН ВНОС M50d 360SwarovskiSkyPanoHUDОБДУХВАНЕ",
    "href": "/vehicle?id=21782329865022942",
    "title": "BMW X5 ОЧАКВАН ВНОС M50d 360SwarovskiSkyPanoHUDОБДУХВАНЕ",
    "location": "София",
    "mileage": "167000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "suv",
    "price": "45699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 45699,
    "currency": "EUR",
    "mileageValue": 167000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "21782329865022942",
    "make": "BMW",
    "year": 2020,
    "body": "suv",
    "arrival": 9,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11784380846697521.webp",
    "imageAlt": "Audi A8 Audi A8 5.0TDI* HD MATRIX* 360CAM* Distronic Plus*",
    "href": "/vehicle?id=11784380846697521",
    "title": "Audi A8 Audi A8 5.0TDI* HD MATRIX* 360CAM* Distronic Plus*",
    "location": "София",
    "mileage": "186000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "28699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 28699,
    "currency": "EUR",
    "mileageValue": 186000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11784380846697521",
    "make": "Audi",
    "year": 2020,
    "body": "other",
    "arrival": 8,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11784130537689775.webp",
    "imageAlt": "Mercedes-Benz S 580 Очакван внос S580 Long BRABUS 4Matic BURMES Plug i",
    "href": "/vehicle?id=11784130537689775",
    "title": "Mercedes-Benz S 580 Очакван внос S580 Long BRABUS 4Matic BURMES Plug i",
    "location": "София",
    "mileage": "72000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "86699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 86699,
    "currency": "EUR",
    "mileageValue": 72000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11784130537689775",
    "make": "Mercedes-Benz",
    "year": 2022,
    "body": "other",
    "arrival": 7,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11778179700610297.webp",
    "imageAlt": "Mercedes-Benz V 300 Mercedes V250d* VIP* BUSINESS* TV* ОБДУХВАНЕ+ ПОДГ",
    "href": "/vehicle?id=11778179700610297",
    "title": "Mercedes-Benz V 300 Mercedes V250d* VIP* BUSINESS* TV* ОБДУХВАНЕ+ ПОДГ",
    "location": "София",
    "mileage": "44500 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "54699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 54699,
    "currency": "EUR",
    "mileageValue": 44500,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11778179700610297",
    "make": "Mercedes-Benz",
    "year": 2018,
    "body": "other",
    "arrival": 6,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11782329384140338.webp",
    "imageAlt": "Mercedes-Benz V 300 Очакван Внос V250d LongAMG LineDesignoEdition",
    "href": "/vehicle?id=11782329384140338",
    "title": "Mercedes-Benz V 300 Очакван Внос V250d LongAMG LineDesignoEdition",
    "location": "София",
    "mileage": "187000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "33699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 33699,
    "currency": "EUR",
    "mileageValue": 187000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11782329384140338",
    "make": "Mercedes-Benz",
    "year": 2016,
    "body": "other",
    "arrival": 5,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11778085846169037.webp",
    "imageAlt": "Mercedes-Benz E 400 Mercedes E400d AMG LineASSISTANCEMULTIBEAMFULL*",
    "href": "/vehicle?id=11778085846169037",
    "title": "Mercedes-Benz E 400 Mercedes E400d AMG LineASSISTANCEMULTIBEAMFULL*",
    "location": "София",
    "mileage": "172000 km",
    "transmission": "Automatic",
    "fuel": "Diesel",
    "seats": "",
    "bodyType": "other",
    "price": "29699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 29699,
    "currency": "EUR",
    "mileageValue": 172000,
    "mileageUnit": "km",
    "fuelType": "diesel",
    "transmissionType": "automatic",
    "id": "11778085846169037",
    "make": "Mercedes-Benz",
    "year": 2019,
    "body": "other",
    "arrival": 4,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11774291387702102.webp",
    "imageAlt": "Audi Rs7 AUDI RS7 Ceramic Масажи Обдухване Full",
    "href": "/vehicle?id=11774291387702102",
    "title": "Audi Rs7 AUDI RS7 Ceramic Масажи Обдухване Full",
    "location": "София",
    "mileage": "144000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "72699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 72699,
    "currency": "EUR",
    "mileageValue": 144000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11774291387702102",
    "make": "Audi",
    "year": 2021,
    "body": "other",
    "arrival": 3,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/21782661898906066.webp",
    "imageAlt": "Mercedes-Benz G 63 AMG Очакван внос G63 AMG FACE* 3xTV* CAM* Heat+ Vent",
    "href": "/vehicle?id=21782661898906066",
    "title": "Mercedes-Benz G 63 AMG Очакван внос G63 AMG FACE* 3xTV* CAM* Heat+ Vent",
    "location": "София",
    "mileage": "164000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "suv",
    "price": "61699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 61699,
    "currency": "EUR",
    "mileageValue": 164000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "21782661898906066",
    "make": "Mercedes-Benz",
    "year": 2017,
    "body": "suv",
    "arrival": 2,
    "offer": false,
    "exclusive": false
  },
  {
    "sample": false,
    "image": "/assets/daynight/inventory-current/11781790478711568.webp",
    "imageAlt": "Mercedes-Benz S 500 Очакван Внос S500 LongDESIGNOAMG Line3xTV",
    "href": "/vehicle?id=11781790478711568",
    "title": "Mercedes-Benz S 500 Очакван Внос S500 LongDESIGNOAMG Line3xTV",
    "location": "София",
    "mileage": "175000 km",
    "transmission": "Automatic",
    "fuel": "Petrol",
    "seats": "",
    "bodyType": "other",
    "price": "27699 EUR",
    "pricePeriod": "",
    "action": "Enquire",
    "rating": "",
    "reviews": "",
    "priceAmount": 27699,
    "currency": "EUR",
    "mileageValue": 175000,
    "mileageUnit": "km",
    "fuelType": "gasoline",
    "transmissionType": "automatic",
    "id": "11781790478711568",
    "make": "Mercedes-Benz",
    "year": 2016,
    "body": "other",
    "arrival": 1,
    "offer": false,
    "exclusive": false
  }
];

export const collections: readonly { id: CollectionId; title: DiscoveryTextKey }[] = [
  {
    "id": "newest",
    "title": "all"
  },
  {
    "id": "cheapest",
    "title": "cheapest"
  },
  {
    "id": "bmw",
    "title": "bmw"
  },
  {
    "id": "german",
    "title": "german"
  },
  {
    "id": "suvs",
    "title": "suvs"
  }
];
export type Collection = (typeof collections)[number];
export type CollectionId = "newest" | "offers" | "under-10000" | "cheapest" | "premium" | "exclusive" | "under-20000" | "bmw" | "german" | "suvs";

export function findCollection(id: string | null): Collection | undefined {
  return collections.find((collection) => collection.id === id);
}

export function findCar(id: string | null): DiscoveryCar | undefined {
  return discoveryCars.find((car) => car.id === id);
}

export interface DiscoveryFilters {
  make: string;
  model: string;
  priceMax: string;
  yearFrom: string;
  yearTo: string;
}

export const emptyDiscoveryFilters: Readonly<DiscoveryFilters> = {
  make: "",
  model: "",
  priceMax: "",
  yearFrom: "",
  yearTo: "",
};
export const discoveryBrands = [
  ...new Set(discoveryCars.map((car) => car.make)),
].toSorted((a, b) => a.localeCompare(b));
export const discoveryYears = [
  ...new Set(discoveryCars.map((car) => car.year)),
].toSorted((a, b) => b - a);

export type DiscoveryPanel = "make" | "model" | "price" | "year";
export const discoveryPanels = [
  { id: "make", title: "make" },
  { id: "model", title: "model" },
  { id: "price", title: "price" },
  { id: "year", title: "year" },
] as const;

/** The demo offers its supplied vehicle names; it does not invent model metadata. */
export function discoveryModels(make: string) {
  return discoveryCars
    .filter((car) => car.make === make)
    .map((car) => ({
      value: car.title,
      label: discoveryModelLabel(make, car.title),
    }))
    .toSorted((a, b) => a.label.localeCompare(b.label));
}

export function discoveryModelLabel(make: string, value: string): string {
  const name = value.startsWith(make + " ")
    ? value.slice(make.length + 1)
    : value;
  return name ? name[0].toLocaleUpperCase() + name.slice(1) : "";
}

export function readDiscoveryFilters(
  params: Pick<URLSearchParams, "get">,
): DiscoveryFilters {
  const make = params.get("make") ?? "";
  const model = params.get("model") ?? "";
  const year = (key: string) => {
    const value = params.get(key) ?? "";
    return discoveryYears.includes(Number(value)) ? String(Number(value)) : "";
  };
  return {
    make: discoveryBrands.includes(make) ? make : "",
    model: discoveryModels(make).some((option) => option.value === model)
      ? model
      : "",
    priceMax: normalizeCatalogBudget(params.get("priceMax") ?? "") ?? "",
    yearFrom: year("yearFrom"),
    yearTo: year("yearTo"),
  };
}

export function searchCars(
  query: string,
  filters: DiscoveryFilters = emptyDiscoveryFilters,
): DiscoveryCar[] {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  const budget = normalizeCatalogBudget(filters.priceMax);
  if (budget === undefined) return [];
  return discoveryCars
    .filter((car) => {
      if (filters.make && car.make !== filters.make) return false;
      if (filters.make && filters.model && car.title !== filters.model)
        return false;
      if (budget && car.priceAmount > Number(budget)) return false;
      if (filters.yearFrom && car.year < Number(filters.yearFrom)) return false;
      if (filters.yearTo && car.year > Number(filters.yearTo)) return false;
      const text =
        `${car.title} ${car.make} ${car.year} ${car.body}`.toLocaleLowerCase();
      return terms.every((term) => text.includes(term));
    })
    .toSorted((a, b) => b.arrival - a.arrival);
}

export function discoveryDestination(
  query: string,
  filters: DiscoveryFilters,
  parameters: Pick<URLSearchParams, "toString"> = new URLSearchParams(),
  hash = "",
): string {
  const next = new URLSearchParams(parameters.toString());
  for (const key of ["car", "collection", "returnTo"]) next.delete(key);
  next.set("q", query.trim());
  for (const key of [
    "make",
    "model",
    "priceMax",
    "yearFrom",
    "yearTo",
  ] as const) {
    const value =
      key === "priceMax"
        ? normalizeCatalogBudget(filters[key])
        : key === "model"
          ? discoveryModels(filters.make).some(
              (option) => option.value === filters.model,
            )
            ? filters.model
            : ""
          : filters[key];
    if (value) next.set(key, value);
    else next.delete(key);
  }
  return "/2?" + next.toString() + hash;
}

/** Detail return links stay inside the mobile experiment, including direct loads. */
export function discoveryReturn(value: string | null): string {
  if (!value || !/^\/2(?:[?#]|$)/.test(value)) return "/2";
  const destination = new URL(value, "https://preview.invalid");
  if (destination.pathname !== "/2" || destination.searchParams.has("car"))
    return "/2";
  destination.searchParams.delete("returnTo");
  return destination.pathname + destination.search + destination.hash;
}

export function discoveryYearLabel(
  filters: DiscoveryFilters,
  locale: "en" | "bg",
): string {
  return filters.yearFrom === filters.yearTo
    ? filters.yearFrom
    : filters.yearFrom && filters.yearTo
      ? filters.yearFrom + "–" + filters.yearTo
      : filters.yearFrom
        ? discoveryText(locale, "yearFrom") + " " + filters.yearFrom
        : filters.yearTo
          ? discoveryText(locale, "yearTo") + " " + filters.yearTo
          : "";
}

export function collectionCars(id: CollectionId): DiscoveryCar[] {
  const byPrice = (a: DiscoveryCar, b: DiscoveryCar) =>
    a.priceAmount - b.priceAmount;
  switch (id) {
    case "newest":
      return discoveryCars.toSorted((a, b) => b.arrival - a.arrival);
    case "offers":
      return discoveryCars.filter((car) => car.offer);
    case "under-10000":
      return discoveryCars
        .filter((car) => car.priceAmount <= 10000)
        .toSorted(byPrice);
    case "cheapest":
      return discoveryCars.toSorted(byPrice);
    case "premium":
      return discoveryCars
        .filter((car) => car.priceAmount >= 40000)
        .toSorted((a, b) => byPrice(b, a));
    case "exclusive":
      return discoveryCars.filter((car) => car.exclusive);
    case "under-20000":
      return discoveryCars
        .filter((car) => car.priceAmount <= 20000)
        .toSorted(byPrice);
    case "bmw":
      return discoveryCars.filter((car) => car.make === "BMW");
    case "german":
      return discoveryCars.filter((car) =>
        ["Audi", "BMW", "Mercedes-Benz", "Volkswagen"].includes(car.make),
      );
    case "suvs":
      return discoveryCars.filter((car) => car.body === "suv");
  }
}

const en = {
  home: "Home",
  newest: "Newest cars",
  offers: "Top offers",
  under10: "Up to €10,000",
  cheapest: "Cheapest cars",
  premium: "Premium cars",
  exclusive: "Exclusive cars",
  under20: "Up to €20,000",
  bmw: "Explore BMW",
  german: "German favourites",
  suvs: "SUVs for every day",
  all: "All cars",
  pricePill: "Up to €10k",
  brandPill: "By brand",
  suvPill: "SUVs",
  explore: "Explore cars",
  search: "Search cars",
  searchPlaceholder: "Search cars or keywords",
  searchResults: "Search results",
  searchIntro: "Choose a brand and your budget.",
  make: "Make",
  model: "Model",
  price: "Price",
  filters: "Search options",
  anyModel: "Any model",
  findMake: "Find a make",
  findModel: "Find a model",
  makeFirst: "Choose a make to see its available cars.",
  chooseMake: "Choose a make",
  modelContext: "Cars from",
  noOptions: "No matching options. Try another search.",
  budget: "Budget",
  anyBudget: "Any price",
  maximumPrice: "Maximum price (EUR)",
  budgetError: "Enter a positive amount, such as 25000.",
  keywordHint: "Add a car or keyword",
  upTo: "Up to",
  removeFilter: "Remove",
  backResults: "Back to results",
  backSearch: "Back to search",
  keyword: "Car or keyword",
  keywordPlaceholder: "Try SUV, Toyota or 2020",
  brand: "Brand",
  anyBrand: "Any brand",
  anyYear: "Any year",
  yearFrom: "From",
  yearTo: "To",
  newer: "2020 or newer",
  yearRange: "Year range",
  clearAll: "Clear all",
  showCars: "Show cars",
  noResults: "No cars found. Try a wider budget, another brand or year.",
  viewAll: "View all",
  back: "Back",
  backHome: "Back to collections",
  sample: "Датирана извадка от обяви; потвърдете цената и наличността директно с автокъщата.",
  sampleDetail:
    "Датирана извадка от обяви; потвърдете цената и наличността директно с автокъщата.",
  year: "Year",
  mileage: "Mileage",
  fuel: "Fuel",
  transmission: "Transmission",
  more: "Explore more cars",
} as const;
export type DiscoveryTextKey = keyof typeof en;
const bg: Record<DiscoveryTextKey, string> = {
  home: "Начало",
  newest: "Най-нови коли",
  offers: "Топ оферти",
  under10: "До 10 000 €",
  cheapest: "Най-евтини коли",
  premium: "Премиум коли",
  exclusive: "Ексклузивни коли",
  under20: "До 20 000 €",
  bmw: "Разгледай BMW",
  german: "Немски автомобили",
  suvs: "SUV за всеки ден",
  all: "Всички коли",
  pricePill: "До 10 000 €",
  brandPill: "По марка",
  suvPill: "SUV",
  explore: "Разгледай коли",
  search: "Търси коли",
  searchPlaceholder: "Търси кола или ключова дума",
  searchResults: "Резултати от търсенето",
  searchIntro: "Избери марка и бюджет.",
  make: "Марка",
  model: "Модел",
  price: "Цена",
  filters: "Опции за търсене",
  anyModel: "Всички модели",
  findMake: "Намери марка",
  findModel: "Намери модел",
  makeFirst: "Избери марка, за да видиш нейните налични коли.",
  chooseMake: "Избери марка",
  modelContext: "Коли от",
  noOptions: "Няма съвпадащи опции. Опитай друго търсене.",
  budget: "Бюджет",
  anyBudget: "Без ограничение",
  maximumPrice: "Максимална цена (EUR)",
  budgetError: "Въведи положителна сума, например 25000.",
  keywordHint: "Добави кола или ключова дума",
  upTo: "До",
  removeFilter: "Премахни",
  backResults: "Назад към резултатите",
  backSearch: "Назад към търсенето",
  keyword: "Кола или ключова дума",
  keywordPlaceholder: "Например SUV, Toyota или 2020",
  brand: "Марка",
  anyBrand: "Всички марки",
  anyYear: "Всички години",
  yearFrom: "От",
  yearTo: "До",
  newer: "2020 или по-нови",
  yearRange: "Години на производство",
  clearAll: "Изчисти",
  showCars: "Виж коли",
  noResults: "Няма намерени коли. Опитай друга марка, кола или година.",
  viewAll: "Виж всички",
  back: "Назад",
  backHome: "Назад към колекциите",
  sample: "Датирана извадка от обяви; потвърдете цената и наличността директно с автокъщата.",
  sampleDetail:
    "Датирана извадка от обяви; потвърдете цената и наличността директно с автокъщата.",
  year: "Година",
  mileage: "Пробег",
  fuel: "Гориво",
  transmission: "Скорости",
  more: "Разгледай още коли",
};
export function discoveryText(
  locale: "en" | "bg",
  key: DiscoveryTextKey,
): string {
  return (locale === "bg" ? bg : en)[key];
}
