import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/excellent-cars',stock=JSON.parse(await fs.readFile(`${root}/stock.json`)),facts=JSON.parse(await fs.readFile(`${root}/business-facts.json`));const hero=stock[0].images[0];
async function edit(p,fn){const s=await fs.readFile(p,'utf8');const n=fn(s);if(n!==s)await fs.writeFile(p,n);}
async function walk(d,fn){for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.vercel'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())await walk(p,fn);else if(/\.(svelte|tsx?|css|html|json)$/.test(e.name)&&!e.name.includes('.test.'))await edit(p,s=>fn(s,p));}}
const cr=`${root}/carwow`;
await edit(`${cr}/src/lib/components/home/desktop/DesktopHomeReviews.svelte`,s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${JSON.stringify(facts.services.slice(0,3).map((service,i)=>({id:`info-${i}`,description:['Потвърдете наличността и условията за избрания автомобил.','Уговорете оглед и тест драйв по телефона.','Проверка в избран от клиента сервиз преди покупка.'][i],avatar:stock[i].images[0],name:service,meta:'Excellent Cars'})),null,2)};`).replace("const starIds = ['star-1', 'star-2', 'star-3', 'star-4', 'star-5'] as const;","const starIds: string[] = [];"));
await walk(`${cr}/src`,s=>s.replaceAll('Услуги и информация от клиенти','Услуги и информация').replaceAll('Понеделник - Събота: 9:00 - 18:00','Пон–Пет: 08:30–19:00 · Съб: 09:00–18:00 · Нед: почивен ден').replaceAll('Делнични дни: 9:00 - 18:00 · Неделя: по уговорка','Пон–Пет: 08:30–19:00 · Съб: 09:00–18:00 · Нед: почивен ден').replace(/const starIndexes = \[[^\]]*\] as const;/g,'const starIndexes: number[] = [];').replace(/const stars = \[[^\]]*\] as const;/g,'const stars: number[] = [];').replace(/<a[^>]*href="https:\/\/www\.(?:facebook|instagram)\.com\/[^"\s]+"[^>]*>[\s\S]*?<\/a>/g,'').replace(/<a[^>]*\{\.\.\.youtubeLink\}[^>]*>[\s\S]*?<\/a>/g,'').replace(/<a[^>]*href=\{youtubeChannelUrl\}[^>]*aria-label="YouTube"[^>]*>[\s\S]*?<\/a>/g,''));
const ar=`${root}/auto-best`;
await edit(`${ar}/src/lib/components/layout/Footer.svelte`,s=>s.replace('src={brand.logo}','src="/assets/excellent/logo-cars.jpg"'));
await edit(`${ar}/src/lib/components/home/VideoSection.svelte`,s=>{const [before,css]=s.split('<style>');const rules=css.split(/(?<=\})/).filter(x=>!(/dn-video-card__play-icon|dn-video-card__duration|dn-video-card__actions button|dn-video-card__media iframe|dn-videos__brand-mark|dn-videos__all/.test(x))).join('');return before+'<style>'+rules});
const mr=`${root}/modern`;
await walk(`${mr}/apps/web`,s=>s.replaceAll('Day &amp; Night','Excellent Cars').replaceAll('/day-night-contact-hero-v1.png',hero));
// Keep all originals outside the served tree, and freeze the exact new Auto Best asset budget.
const refs=new Set();await walk(`${ar}/src`,s=>{for(const m of s.matchAll(/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi))refs.add(m[0]);return s;});
const moves=[];async function collect(d){for(const e of await fs.readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())await collect(p);else{const rel='/'+path.relative(`${ar}/static`,p).replaceAll('\\','/');if(!refs.has(rel))moves.push({from:p,to:`${root}/source-assets/auto-best${rel}`});}}}await collect(`${ar}/static`);
await fs.writeFile(`${root}/asset-archive-plan.json`,JSON.stringify({referencedCount:refs.size,moves},null,2));
for(const m of moves){for(const candidate of [m.from,m.to])if(!path.resolve(candidate).toLowerCase().startsWith(path.resolve(root).toLowerCase()+path.sep))throw Error('Escaped own directory');await fs.mkdir(path.dirname(m.to),{recursive:true});await fs.rename(m.from,m.to);}
await edit(`${ar}/scripts/check-assets.mjs`,s=>s.replace(/const guardedMediaCount = \d+;/,`// Exact personalized media inventory; original unused assets archived outside static.\nconst guardedMediaCount = ${refs.size};`));
await fs.writeFile(`${root}/BUILD-STATUS.md`,`# Excellent Cars — Fast Skin build\n\n2026-09-07. Fresh current masters 2026.09.06-refresh-1; personalizations wired in all variants.\n\n- Research complete: 16 published sale adverts, 64 original photos, published logo and showroom. Services/hours/phone/address verified. No reviews invented.\n- Auto Best: implementation ready for validation; asset budget precisely recounted, unused original assets archived inside this client.\n- Modern: frozen install passed; implementation complete, Prisma/typecheck/build queued next.\n- Carwow: implementation complete; npm install retry queued after PowerShell treated an npm deprecation warning as an error.\n- Previews: none started; allocated 6621/6622/6623.\n- CRM unregistered, no public URL, no outreach.\n`);
console.log({assetReferences:refs.size,archivedOriginals:moves.length});
