import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/excellent-cars';const facts=JSON.parse(await fs.readFile(`${root}/business-facts.json`));const stock=JSON.parse(await fs.readFile(`${root}/stock.json`));
const logo='/assets/excellent/logo-header.png',light='/assets/excellent/logo-cars.jpg',hero=stock[0].images[0];
facts.accent='#527b21';facts.accentLight='#98c93c';facts.logo=logo;facts.logoLight=light;facts.services.push('Изкупуване и бартер','Транспорт и доставка от чужбина','Автокозметични услуги','Пътна помощ');facts.sources.push('https://excellent.mobile.bg/about');await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));
await fs.copyFile('C:/Users/radev/.codex/generated_images/01a078b0-cf91-7303-ac07-2eaede852274/exec-51d40bb7-54df-4572-a015-52cbe8d1bc03.png',`${root}/assets/logo-header.png`);
const changes=[];async function edit(file,fn){const s=await fs.readFile(file,'utf8'),n=fn(s);if(s!==n){await fs.writeFile(file,n);changes.push(file.slice(root.length+1));}}
async function walk(dir,fn){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit','.vercel'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p,fn);else if(/\.(svelte|tsx?|css|json|html|svg)$/.test(e.name)&&!/(test|spec)\./.test(e.name))await edit(p,s=>fn(s,p));}}
const replacements=[['Day &amp; Night Auto Group',facts.name],['DAY NIGHT AUTO GROUP',facts.name],['Day & Night Auto Group',facts.name],['Day Night Auto Group',facts.name],['Day & Night',facts.name],['Day Night Auto',facts.name],['Ден и Нощ Ауто Груп',facts.name],['087 982 4625',facts.phoneDisplay],['0877 733 110',facts.phoneDisplay],['0877733110','0895996559'],['0879824625','0895996559'],['+359879824625','+359895996559'],['+359877733110','+359895996559'],['daynightautogroup.bg','excellent.cars.bg'],['daynight.mobile.bg','excellent.mobile.bg'],['Собствен лизинг','Лизинг по договаряне'],['собствен лизинг','лизинг по договаряне'],['София','Варна'],['Sofia','Varna'],['Студентски град','Възраждане 1'],['Studentski grad','Vazrazhdane 1'],['ул. „Атанас Манчев“ 18','бул. „Ян Хунияди“ / „Цар Освободител“'],['ул. Атанас Манчев 18','бул. Ян Хунияди / Цар Освободител']];
const base=s=>{for(const [a,b]of replacements)s=s.replaceAll(a,b);return s};
for(const variant of ['auto-best','modern','carwow']){
const vr=`${root}/${variant}`,publicDir=variant==='modern'?`${vr}/apps/web/public`:`${vr}/static`;await fs.mkdir(`${publicDir}/assets/excellent`,{recursive:true});
for(const e of await fs.readdir(`${root}/assets`))if(/\.(png|jpg|webp)$/.test(e))await fs.copyFile(`${root}/assets/${e}`,`${publicDir}/assets/excellent/${e}`);
const dirs=variant==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo']:['src'];for(const d of dirs)await walk(`${vr}/${d}`,base);
}
const ar=`${root}/auto-best`;
await fs.writeFile(`${ar}/src/lib/config/brand.ts`,`export const brand = ${JSON.stringify({name:facts.name,shortName:facts.shortName,city:facts.city,addressLine:facts.address,address:`${facts.address}, ${facts.city}`,phone:facts.phoneDisplay,phoneHref:facts.phoneHref,appointment:facts.hours.join(' · '),logo,darkLogo:logo,email:'',mapsUrl:facts.mapsUrl,mapsEmbedUrl:facts.mapsEmbedUrl,instagramUrl:'',facebookUrl:'',youtubeUrl:''},null,2)} as const;\n`);
const av=stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,description:v.description,category:({SUV:'SUV',Wagon:'Комби',Hatchback:'Хечбек',Coupe:'Купе',Sedan:'Седан'})[v.body],body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:v.equipment,condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`}));
await edit(`${ar}/src/lib/data/inventory.ts`,s=>s.replace('  image: string;','  image: string;\n  gallery: string[];\n  sourceUrl: string;\n  description: string;').replace(/\/\/ Equipment facets[\s\S]*?export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`// Excellent Cars public advert snapshot, 2026-09-07; confirm availability.\nexport const featuredVehicles: Vehicle[] = ${JSON.stringify(av,null,2)};`));
await edit(`${ar}/src/lib/data/company.ts`,s=>s.replace('42.648551','43.23375').replace('23.341905','27.87058'));
await edit(`${ar}/src/app.css`,s=>s.replace('#c40101',facts.accent).replace('#a90000','#3c5c17'));
await walk(`${ar}/src`,(s,p)=>{s=s.replace(/\/assets\/images\/lead\/day-night-stock-\d+\.webp/g,hero).replace(/\/assets\/images\/lead\/day-night-(?:about-(?:kristian|showroom)[^'"\s]*|contact-kristian[^'"\s]*|portrait[^'"\s]*|showroom-color[^'"\s]*)\.(?:webp|png)/g,hero).replace(/\/assets\/images\/lead\/day-night-guide-(?:inspection|import|leasing)\.webp/g,stock[2].images[0]);if(p.endsWith('Hero.svelte')&&p.includes('/home/'))s=s.replaceAll('/assets/images/lead/day-night-home-black-v1.webp',hero).replaceAll('/assets/images/lead/day-night-home-hero-v3.webp',hero);return s;});
for(const file of ['company/AboutHero.svelte','company/ContactIntent.svelte'])await edit(`${ar}/src/lib/components/${file}`,s=>s.replace('] as const;','].filter((item) => item.href) as { name: \'instagram\' | \'facebook\' | \'youtube\'; label: string; href: string }[];'));
await edit(`${ar}/src/lib/components/layout/Header.svelte`,s=>s.replace(/(<a [^\n]*href: brand\.(instagramUrl|youtubeUrl|facebookUrl)[^\n]*<\/a>)/g,'{#if brand.$2}$1{/if}'));
// Preserve the existing detail image area; make its source gallery count a real next-photo control.
await edit(`${ar}/src/routes/listing-detail-v1/[id]/+page.svelte`,s=>s.replace('  const phoneLinkAttributes',"  let galleryIndex = $state(0);\n  const phoneLinkAttributes").replace('src={data.vehicle.image}','src={data.vehicle.gallery[galleryIndex % data.vehicle.gallery.length]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<button type="button" class="dn-detail-gallery__count" aria-label="Следваща снимка" onclick={() => galleryIndex += 1}>{galleryIndex % data.vehicle.gallery.length + 1} / {data.vehicle.gallery.length}</button>').replace('{data.vehicle.title} е част от актуалната селекция на {brand.name}. Свържете се с\n                    екипа за потвърдени данни за състоянието, наличността и следващите стъпки.','{data.vehicle.description}').replace('Наличен автомобил от','Публикувана обява от'));
// The original video section remains the same card composition, populated by source advert links.
await edit(`${ar}/src/lib/components/home/VideoSection.svelte`,s=>{const style=s.slice(s.indexOf('<style>'));return `<script lang="ts">\nimport { featuredVehicles } from '$data/inventory';\nimport Icon from '$components/ui/Icon.svelte';\n</script>\n<section class="dn-videos" aria-labelledby="videos-title"><div class="container"><div class="dn-videos__panel"><div class="dn-videos__heading"><h2 id="videos-title">От нашите обяви</h2><p>${facts.stockNote}</p><a class="dn-videos__channel dn-home-section-action" href="/listing-grid">Всички автомобили <Icon name="arrow-right" size={18}/></a></div><div class="dn-videos__grid">{#each featuredVehicles.slice(0,3) as vehicle (vehicle.id)}<article class="dn-video-card"><div class="dn-video-card__media"><a class="dn-video-card__play" href={vehicle.href}><img src={vehicle.image} alt={vehicle.title} width="720" height="404" loading="lazy" /></a></div><div class="dn-video-card__content"><h3>{vehicle.title}</h3><div class="dn-video-card__actions"><a href={vehicle.href}>Разгледайте автомобила <Icon name="arrow-right" size={16}/></a></div></div></article>{/each}</div></div></div></section>\n${style}`;});
await fs.writeFile(`${ar}/src/lib/data/videos.ts`,'// No verified dealer YouTube feed. Homepage uses source-backed vehicle cards.\nexport const featuredVideos = [];\n');
const mr=`${root}/modern`;const config={accent:facts.accent,address:facts.address,city:facts.city,contactUrl:facts.phoneHref,country:facts.country,countryCode:'BG',currency:'EUR',email:'',heroPath:hero,locale:'bg-BG',logoPath:logo,mapsEmbedUrl:facts.mapsEmbedUrl,mapsUrl:facts.mapsUrl,name:facts.name,phoneDisplay:facts.phoneDisplay,phoneHref:facts.phoneHref,shortName:facts.shortName,slug:'excellent-cars',socialLinks:{},staticDemoMode:true,tagline:'Автомобили, бартер и лизинг по договаряне във Варна.'};
await edit(`${mr}/packages/marketplace/lead-site.ts`,s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify(config,null,2)};`));
const listings=stock.map((v,i)=>({id:`excellent-${v.id}`,slug:`excellent-${v.id}`,category:'car',dealerOrgId:'dealer-excellent-cars',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:facts.city,region:'Варна',country:facts.country},features:[],spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Coupe:'coupe',Sedan:'sedan'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-excellent-cars',type:'dealer',displayName:facts.name,verificationStatus:'unverified',city:facts.city},publishedAt:new Date(Date.UTC(2026,8,7,8,0,-i)).toISOString(),promoted:false}));
await edit(`${mr}/packages/marketplace-domain/testing/mock-data.ts`,s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`// Representative Excellent Cars public adverts captured 2026-09-07.\nexport const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`));
await fs.copyFile(`${root}/assets/logo-header.png`,`${mr}/apps/web/public/lead-logo.png`);await fs.copyFile(`${root}/assets/vehicle-01-1.webp`,`${mr}/apps/web/public/lead-hero.jpg`);
const cr=`${root}/carwow`;
await edit(`${cr}/src/lib/data/daynight-site.ts`,s=>s.replace(/mapUrl:\s*'[^']*'/,`mapUrl: ${JSON.stringify(facts.mapsUrl)}`).replace(/location: '[^']*'/,`location: ${JSON.stringify(facts.city+', '+facts.address)}`).replace('inventoryCount: 40','inventoryCount: 16').replace(/logoLight: '[^']*'/,`logoLight: '${light}'`).replace(/logoDark: '[^']*'/,`logoDark: '${logo}'`));
await fs.writeFile(`${cr}/src/lib/data/excellent-stock.json`,JSON.stringify(stock,null,2));
const current=stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:`${v.priceEur.toLocaleString('bg-BG')} €`,priceBgn:`${(v.priceEur*1.95583).toFixed(2)} лв.`,status:'Публикувана обява',date:v.date,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,color:v.color,fuel:v.fuel,power:`${v.powerHp} к.с.`,transmission:v.transmission,body:({SUV:'SUV',Wagon:'Комби',Hatchback:'Хечбек',Coupe:'Купе',Sedan:'Седан'})[v.body],features:v.equipment,image:v.images[0]}));
await edit(`${cr}/src/lib/data/daynight-current-inventory.ts`,s=>s.slice(0,s.indexOf('export const currentDayNightListings')).replace(/\/\/ Public listing[^\n]*/, '// Excellent Cars public advert snapshot, 2026-09-07.')+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(current,null,2)};\n`);
await edit(`${cr}/src/lib/data/daynight-vehicles.ts`,s=>`import excellentStock from './excellent-stock.json';\n`+s.replace('const identity = getVehicleIdentity(listing);','const original = excellentStock.find((vehicle) => vehicle.id === listing.id)!;\n\tconst identity = {brand: original.make, model: original.model, shortTitle: original.title};').replace("const availability = isIncoming ? 'Очакван внос' : 'Наличен';","const availability = isIncoming ? 'Очакван внос' : 'Публикувана обява';").replace("'Наличен автомобил в Варна — свържете се за оглед.'","'Публикувана обява — потвърдете наличността с Excellent Cars.'").replace(/monthly: `[^`]*`,/,"monthly: 'Условия по договаряне',").replace('gallery: [listing.image]','gallery: original.images').replace('doors: body === \'Купе\' ? 3 : 5','doors: 0').replace('lot: `DN-','lot: `EX-'));
const reviews=facts.services.slice(0,6).map((service,i)=>({id:`service-${i}`,text:['Потвърдете наличността и уговорете посещение по телефона.','Оглед и тест драйв на избрания автомобил след уговорка.','Възможност за проверка в избран от клиента сервиз.','Съдействие при регистрация и транзитни номера.','Обсъдете индивидуалните условия за избрания автомобил.','Предложете своя автомобил за оценка.'][i],avatar:stock[i].images[0],name:'Excellent Cars',label:service}));
await edit(`${cr}/src/lib/data/daynight-reviews.ts`,s=>s.slice(0,s.indexOf('export const daynightReviews'))+`// Published service information, not customer testimonials.\nexport const daynightReviews = ${JSON.stringify(reviews,null,2)} satisfies DayNightReview[];\nexport const daynightReviewCount = daynightReviews.length;\nexport const daynightReviewCountLabel = 'Услуги и информация';\nexport const daynightReviewLinkLabel = 'Виж услугите';\n`);
await fs.writeFile(`${cr}/src/lib/data/daynight-videos.ts`,`// Source-backed advert cards; no verified dealer video channel.\nexport const youtubeChannelUrl = 'https://excellent.mobile.bg/';\nexport const homeVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'Обява',thumbnail:v.images[0],url:v.sourceUrl})),null,2)} as const;\n`);
await edit(`${cr}/src/lib/components/home/desktop/DesktopHomeVideos.svelte`,s=>s.replace(/Excellent Cars в YouTube/g,'Excellent Cars — обяви').replace('label="Всички видеа"','label="Всички обяви"').replace(/Excellent Cars в <img[^>]+\/>/,'От нашите обяви').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noreferrer"><img src={video.thumbnail} alt={video.title} width="480" height="270" loading="lazy" style="width:100%;height:100%;object-fit:cover" /></a>'));
await walk(`${cr}/src`,(s,p)=>{s=s.replace(/https:\/\/www\.instagram\.com\/dayandnight_autogroup\/?/g,facts.stockUrl).replace(/https:\/\/www\.facebook\.com\/deninoshtautogroup\/?/g,facts.stockUrl).replace(/https:\/\/www\.youtube\.com\/@kristiankirilov1355(?:\/videos)?/g,facts.stockUrl);s=s.replace(/\/assets\/images\/(?:pages|services)\/[^'"\s]*(?:daynight|day-night)[^'"\s]*\.(?:webp|png|jpg)/g,hero).replaceAll('/assets/daynight-auto-v3/class-b-banners/webp/contact-showroom-entrance-banner-1x-2400x1100.webp',hero).replaceAll('/assets/daynight-contact/contact-support-cutouts.webp',hero);if(!p.includes('/admin/'))s=s.replaceAll('Отзиви','Услуги и информация').replaceAll('отзиви','услуги').replaceAll('Клиентски мнения','Услуги и информация').replaceAll('Какво казват клиентите','Как можем да съдействаме').replaceAll('Реални истории','Полезна информация');return s;});
await edit(`${cr}/src/lib/styles/tokens.css`,s=>s.replace('--sa-red: #d71920','--sa-red: #527b21').replace('--sa-red-strong: #a50f15','--sa-red-strong: #3c5c17').replace('--sa-yellow: #f5c542','--sa-yellow: #98c93c'));
// Replace inherited browser identity with dealer logo in each runtime.
for(const [vr,pub]of [[ar,'static'],[cr,'static'],[mr,'apps/web/public']]){const appFile=vr===mr?null:`${vr}/src/app.html`;if(appFile)await edit(appFile,s=>s.replace(/href="[^"]*favicon[^"]*"/g,`href="${logo}"`).replace(/href="%sveltekit.assets%\/[^" ]+\.png"/g,`href="%sveltekit.assets%${logo}"`));}
await fs.writeFile(`${root}/personalization.json`,JSON.stringify({changedFiles:changes,stockCount:stock.length,detailRoutes:{'auto-best':'/listing-detail-v1/1',modern:`/bg/listing/${listings[0].slug}`,carwow:`/inventory/${stock[0].title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${stock[0].id.slice(-6)}`},logoAdaptation:{tool:'built-in imagegen',source:'assets/logo-cars.jpg',output:'assets/logo-header.png',description:'Transparent background and dark lettering for light headers; generated adaptation of published logo, original preserved.'}},null,2));console.log({files:changes.length,stock:stock.length});
