import fs from 'node:fs/promises';
import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const root='J:/cars/clients/excellent-cars';
const cards=JSON.parse(await fs.readFile(`${root}/research/cards.json`));
// Omit Tucson/Honda cards whose headline and prose disagree on model/power/price.
const picks=[4,0,1,6,7,8,9,10,11,13,14,15,17,18,20,35];
const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage();
const downloads=[],stock=[];
for(const [n,index] of picks.entries()){
const c=cards[index],raw=c.parts.find(x=>x.cls==='params').text,top=c.parts.find(x=>x.cls==='zaglavie').text,info=c.parts.find(x=>x.cls==='info').text;
await p.goto(c.url,{waitUntil:'domcontentloaded',timeout:35000});
const detail=await p.evaluate(()=>({text:document.body.innerText,images:[...document.images].map(i=>i.currentSrc||i.src).filter(s=>s.includes('photosorg')),links:[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(s=>s.includes('photosorg'))}));await fs.writeFile(`${root}/research/detail-${n+1}.json`,JSON.stringify(detail,null,2));
const urls=[...new Set([...detail.images,...detail.links].filter(s=>!s.includes('small')).map(s=>s.replace(/\/(?:big\d|orig)\//,'/').replace(/(\/photosorg\/\d+\/\d+\/)/,'$1big1/')))];
if(!urls.length)throw Error('No gallery '+c.title);
const id=c.url.match(/obiava-(\d+)/)[1],make=c.title.startsWith('Mercedes-Benz')?'Mercedes-Benz':c.title.startsWith('Land Rover')?'Land Rover':c.title.split(' ')[0],title=c.title.split('*').slice(0,2).join(' ').trim(),year=Number(raw.match(/(?:19|20)\d{2}/)[0]),mileageKm=Number(raw.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),priceEur=Number(top.match(/([\d\s]+)\s*€/)[1].replace(/\s/g,''));
const images=[];for(const [i,url] of urls.slice(0,4).entries()){const name=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;const r=await fetch(url);if(!r.ok)throw Error('Image '+r.status);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));images.push(`/assets/excellent/${name}`);downloads.push({url,path:`assets/${name}`,sourcePage:c.url});}
const fuel=raw.includes('Хибриден')?'Хибрид':raw.includes('Дизелов')?'Дизел':raw.includes('Бензинов')?'Бензин':'Електрически';
const equipment=[['4x4',/4x4/],['Панорамен покрив',/Панорамен покрив/],['Подгряване на седалки',/Подгряване на седалките/],['Навигация',/Навигация/],['Парктроник',/Парктроник/],['Безключов достъп',/Безключово палене/]].filter(([,re])=>re.test(info)).map(([label])=>label);
stock.push({id,title,fullTitle:c.title,make,model:title.slice(make.length).trim(),year,mileageKm,priceEur,fuel,transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',body:raw.includes('Джип')?'SUV':raw.includes('Хечбек')?'Hatchback':raw.includes('Комби')?'Wagon':raw.includes('Купе')?'Coupe':'Sedan',powerHp:Number(raw.match(/(\d+)\s*к\.с\./)?.[1]||0),color:raw.match(/км\s+(.+?)\s+(?:Хибриден|Дизелов|Бензинов|Електрически)/)?.[1]||'',date:raw.match(/^(.+?г\.)/)[1],engineCc:Number(raw.match(/(\d+)\s*куб\.см/)?.[1]||0),equipment,vat:top.includes('Не се начислява')?'Не се начислява ДДС':'ДДС: виж оригиналната обява',sourceUrl:c.url,images,rawFacts:raw,description:`${title}, ${year} г., ${fuel.toLowerCase()}, ${mileageKm.toLocaleString('bg-BG')} км. Данни от публикуваната обява. Потвърдете наличността, оборудването и условията с Excellent Cars.`});console.log(n+1,title,priceEur,images.length);
}
await p.goto('https://excellent.mobile.bg/about',{waitUntil:'domcontentloaded'});await fs.writeFile(`${root}/research/about-correct.json`,JSON.stringify(await p.evaluate(()=>({text:document.body.innerText,links:[...document.querySelectorAll('a[href]')].map(a=>({text:a.innerText,href:a.href}))})),null,2));
for(const [name,url] of [['logo-original.png','https://cdn2.focus.bg/mobile/images/houseslogos/h14617507379518336.pic'],['showroom.jpg','https://cdn2.focus.bg/mobile/images/housespicts/h14617507379518336.pic'],['logo-cars.jpg','https://g1-bg.cars.bg/users_logos/d3ca58cbae82fa10f3551b41c01acb64.jpg']]){const r=await fetch(url);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));downloads.push({url,path:`assets/${name}`,sourcePage:'https://excellent.mobile.bg/'});}
await browser.close();
const query=encodeURIComponent('Excellent Cars, бул. Ян Хунияди и Цар Освободител, Варна');
const facts={name:'Excellent Cars',shortName:'Excellent Cars',city:'Варна',country:'България',address:'бул. „Ян Хунияди“, ъгъла с бул. „Цар Освободител“',phoneDisplay:'0895 996 559',phoneHref:'tel:+359895996559',additionalPhones:['0894 883 833','0878 377 562'],email:'',hours:['Понеделник – петък: 08:30–19:00','Събота: 09:00–18:00','Неделя: почивен ден'],mapsUrl:`https://www.google.com/maps/search/?api=1&query=${query}`,mapsEmbedUrl:`https://maps.google.com/maps?q=${query}&output=embed`,website:'https://excellent.cars.bg/',stockUrl:'https://excellent.mobile.bg/',services:['Продажба на автомобили','Оглед и тест драйв','Проверка в сервиз по избор на клиента','Съдействие при регистрация и транзитни номера','Лизинг с индивидуални условия'],stockCount:stock.length,stockSnapshotDate:'2026-09-07',stockNote:'Подбрани публикувани обяви към 07.09.2026. Наличностите и условията се потвърждават по телефона.',sources:['https://excellent.mobile.bg/','https://excellent.mobile.bg/contacts','https://excellent.cars.bg/'],limitations:['Не е потвърден служебен имейл или официален социален профил.','Местоположението е по описанието на дилъра; Google 178 е запазено само като изследователска бележка.','Пропуснати карти с противоречие между заглавие и описание: Hyundai Tucson/Santa Fe, Honda CR-V.']};
await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));await fs.writeFile(`${root}/stock.json`,JSON.stringify(stock,null,2));await fs.writeFile(`${root}/assets/provenance.json`,JSON.stringify({capturedAt:new Date().toISOString(),note:'Official marketplace dealer logo and vehicle photos; original watermarks retained. Existing template licenses carried forward; no new rights determination.',assets:downloads},null,2));
