/** Shared inventory contract. No React, browser APIs or fixture imports. */
export type Vehicle = {
  images?: string[]; sourceUrl?: string; observedAt?: string; specifications?: string; priceOnRequest?: boolean; mileageOnRequest?: boolean;
  imagePlaceholder?: boolean; proposalBenefits?: string[];
  referenceId?: string;
  tier?: 'Luxe' | 'Prime' | 'Lite';
  optionsType?: string;
  originalMileage?: number;
  cylinders?: number;
  zeroDownPayment?: boolean;
  slug: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  previousPrice?: number;
  monthly: number;
  mileage: number;
  fuel: 'Petrol' | 'Diesel' | 'Hybrid' | 'Electric' | 'Not published';
  transmission: 'Automatic' | 'Manual' | 'Not published';
  body: 'SUV' | 'Sedan' | 'Hatchback' | 'Coupe' | 'MPV' | 'Convertible' | 'Pickup' | 'Other';
  location: string;
  image: string;
  color: string;
  badges: string[];
  highlights: string[];
  power: string;
  engine: string;
  warranty: string;
  condition: string;
};
