import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const dir=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const project=path.resolve(dir,'../../../templates/carwow');
const before=JSON.parse(await fs.readFile(path.join(dir,'before.json'),'utf8'));
const after=JSON.parse(await fs.readFile(path.join(dir,'after.json'),'utf8'));
const comments={
 '/':'Available budgets first, readable 44px favorite/compare controls, coherent location, chat moved out of mobile browsing content.',
 '/inventory':'Filters and sorting persist in the URL. Apply/Cancel and shared modal focus contract. Availability stays separate from promotion.',
 '/sell-your-car/request':'Direct entry starts intake. Success appears only after a successful validated submission response.',
 '/calculator':'One validated EUR calculation model; fields update the breakdown and detail handoff preserves price and term. Inputs are explicitly illustrative.',
 '/financing':'Readable mobile telephone action, 44px target, consistent desktop action roles.',
 '/blog':'Search and categories precede mobile articles; compact rows; editorial guides clearly named; footer clipping repaired.',
 '/team':'Compact mobile identity/contact cards and consistent demonstration disclosure.',
 '/reviews':'Shared demonstration records and derived sample aggregates; clear disclosure; semantic page heading.',
 '/compare':'Visible selection removal/replacement, narrower sticky mobile labels, scrolling instructions and a page heading.',
 '/faq':'Flat accordion family and deliberate group spacing; existing answers retained.',
 '/terms':'Duplicate paragraphs removed and footer links describe the content that actually exists.',
 '/contact':'Shared appointment/location data; vehicle and photo/video intent prefill; same-route query changes reset form correctly.'
};
const routes=[...new Set(after.map(r=>r.route))].map(route=>({route,note:comments[route]||'Focused shared pattern/content repairs; existing composition retained.'}));
const data={before,after,routes};
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carwow — before / after</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f5f5;color:#181818;font:15px/1.5 system-ui,sans-serif}header{padding:24px 32px;background:#fff;border-bottom:1px solid #ddd}h1{margin:0;font-size:26px}header p{margin:6px 0 16px;color:#555}.controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}select,button,a.button{font:inherit;padding:10px 14px;border:1px solid #bbb;background:white;color:#181818;border-radius:6px}button{cursor:pointer}button[aria-pressed=true]{background:#181818;color:white}button:focus-visible,select:focus-visible,a:focus-visible{outline:2px solid #181818;outline-offset:3px}main{padding:20px 32px}#note{margin:0 0 16px;max-width:90ch}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.pair section{min-width:0}h2{font-size:16px;margin:0 0 8px;display:flex;justify-content:space-between}h2 a{font-size:13px;font-weight:400;color:#555}.frame{height:72vh;overflow:auto;border:1px solid #ddd;background:white;text-align:center}.frame img{display:block;width:100%;height:auto;margin:auto}.mobile .frame img{max-width:390px}#metrics{margin:14px 0;color:#555}footer{padding:12px 32px 32px;color:#555}footer a{color:inherit} @media(max-width:700px){header,main{padding:16px}.pair{gap:8px}.frame{height:66vh}h1{font-size:22px}}</style>
<header><h1>Carwow template — before / after</h1><p>Local master repair · 8 September 2026 · Same routes and viewport sizes · Existing desktop/mobile designs retained</p><div class="controls"><label>Route <select id="route"></select></label><button id="mobile" aria-pressed="true">Mobile · 390px</button><button id="desktop" aria-pressed="false">Desktop · 1440px</button><label><input id="sync" type="checkbox"> Sync scroll</label><a class="button" href="http://127.0.0.1:6463/" target="_blank">Open live preview</a></div></header>
<main><p id="note"></p><div class="pair mobile" id="pair"><section><h2>Before <a id="before-link" target="_blank">Full-size image</a></h2><div class="frame" id="left"><img id="before" alt="Before repair"></div></section><section><h2>After <a id="after-link" target="_blank">Full-size image</a></h2><div class="frame" id="right"><img id="after" alt="After repair"></div></section></div><p id="metrics"></p></main><footer>Review <a href="REPORT.md">findings and validation</a> · <a href="../../../templates/carwow/docs/ARCHITECTURE.md">architecture</a> · <a href="../../../templates/carwow/docs/COMPONENT-PATTERNS.md">component patterns</a>. Local QA does not establish real staff delivery or verified business claims.</footer>
<script>const data=${JSON.stringify(data).replaceAll('<','\\u003c')};let width=390;const route=document.querySelector('#route');for(const r of data.routes)route.add(new Option(r.route,r.route));function render(){let r=route.value,b=data.before.find(x=>x.width===width&&x.route===r),a=data.after.find(x=>x.width===width&&x.route===r);for(const [kind,item] of [['before',b],['after',a]]){document.querySelector('#'+kind).src=kind+'/'+item.filename;document.querySelector('#'+kind+'-link').href=kind+'/'+item.filename;}document.querySelector('#note').textContent=data.routes.find(x=>x.route===r).note;document.querySelector('#metrics').textContent='Page height: '+b.height.toLocaleString()+'px → '+a.height.toLocaleString()+'px. Fixed navigation appears at its viewport position within full-page captures.';document.querySelector('#pair').classList.toggle('mobile',width===390);document.querySelector('#mobile').setAttribute('aria-pressed',String(width===390));document.querySelector('#desktop').setAttribute('aria-pressed',String(width===1440));left.scrollTop=right.scrollTop=0;}route.onchange=render;mobile.onclick=()=>{width=390;render()};desktop.onclick=()=>{width=1440;render()};let lock=false;for(const [a,b] of [[left,right],[right,left]])a.onscroll=()=>{if(lock||!sync.checked)return;lock=true;b.scrollTop=a.scrollTop/Math.max(1,a.scrollHeight-a.clientHeight)*(b.scrollHeight-b.clientHeight);requestAnimationFrame(()=>lock=false)};render();</script></html>`;
await fs.writeFile(path.join(dir,'before-after.html'),html);
async function walk(base,rel=''){let out=[];for(const e of await fs.readdir(path.join(base,rel),{withFileTypes:true})){let r=path.join(rel,e.name);if(e.isDirectory())out.push(...await walk(base,r));else out.push(r)}return out}
const changes=[];for(const rel of await walk(path.join(project,'src'))){const current=await fs.readFile(path.join(project,'src',rel));let previous;try{previous=await fs.readFile(path.join(dir,'before-source/src',rel))}catch{}if(!previous||!previous.equals(current))changes.push({path:'src/'+rel.replaceAll('\\','/'),kind:previous?'modified':'added',sha256:crypto.createHash('sha256').update(current).digest('hex')});}
await fs.writeFile(path.join(dir,'changes.json'),JSON.stringify(changes,null,2));console.log('Review generated, source files changed:',changes.length);
