import type { Vehicle } from './types';
import capturedListingDetails from './native-data/listing-details.json';
const common = {
  category: 'car' as const,
  transmission: 'Automatic',
  body: 'SUV',
  color: 'Black',
  seats: 5,
  doors: 5,
  rating: 4.9,
  reviews: 1269,
  features: [
    'Navigation system',
    'Heated seats',
    'Parking sensors',
    'LED headlights',
    'Cruise control',
    'Bluetooth',
    'Air conditioning',
  ],
};
const baseVehicles: Vehicle[] = [
  {
    ...common,
    id: 'bmw-x6',
    reviews: 1270,
    make: 'BMW',
    model: 'X6',
    variant: 'xDrive30d M Sport Pro AHK+ACC+Pano+Innovation',
    price: 73937,
    financeMonthly: 784,
    year: 2025,
    registration: '06/2025',
    mileage: 18500,
    power: 286,
    fuel: 'Diesel',
    dealer: 'Autohaus Hofmann GmbH',
    location: '85053 Ingolstadt',
    images: [
      '/images/x6-gallery-01.webp',
      '/images/x6-gallery-02.webp',
      '/images/x6-gallery-03.webp',
      '/images/x6-gallery-04.webp',
      '/images/x6-gallery-05.webp',
      '/images/x6-gallery-06.webp',
      '/images/x6-gallery-07.webp',
      '/images/x6-gallery-08.webp',
      '/images/x6-gallery-09.webp',
      '/images/x6-gallery-10.webp',
      '/images/x6-gallery-11.webp',
      '/images/x6-gallery-12.webp',
      '/images/x6-gallery-13.webp',
      '/images/x6-gallery-14.webp',
      '/images/x6-gallery-15.webp',
      '/images/x6-gallery-16.webp',
      '/images/x6-gallery-17.webp',
      '/images/x6-gallery-18.webp',
      '/images/x6-gallery-19.webp',
      '/images/x6-gallery-20.webp',
    ],
    sponsored: true,
    technicalData: [
      ['Vehicle condition', 'Used vehicle'],
      ['Category', "SUV/Off-road Vehicle/Pickup Truck, Employee's Car"],
      ['Model range', 'G06'],
      ['Trim line', 'M Sport Pro'],
      ['Vehicle Number', '5027124'],
      ['Origin', 'German edition'],
      ['Mileage', '18,500 km'],
      ['Cubic Capacity', '2,993 ccm'],
      ['Power', '210 kW (286 hp)'],
      ['Drive type', 'Internal combustion engine'],
      ['Fuel', 'Diesel'],
      ['Number of Seats', '5'],
      ['Door Count', '4/5'],
      ['Transmission', 'Automatic'],
      ['Emission Class', 'Euro 6e'],
      ['Emissions Sticker', '4 (Green)'],
      ['First Registration', '06/2025'],
      ['Number of Vehicle Owners', '1'],
      ['HU', 'New'],
      ['Climatisation', 'Automatic climatisation, 4 zones'],
      ['Parking sensors', 'Self-steering systems, Rear, Camera, Front'],
      ['Airbags', 'Front and Side and More Airbags'],
      ['Colour (Manufacturer)', 'Saphirschwarz Metallic'],
      ['Colour', 'Black Metallic'],
      ['Interior Design', 'Imitation leather, Black'],
      ['Cylinders', '6'],
    ],
    features: [
      'ABS',
      'Adaptive cornering lights',
      'Adaptive Cruise Control',
      'Alarm system',
      'Alloy wheels',
      'Ambient lighting',
      'Android Auto',
      'Apple CarPlay',
      'Arm rest',
      'Blind spot assist',
      'Bluetooth',
      'Central locking',
      'DAB radio',
      'Digital cockpit',
      'Distance warning system',
      'Dynamic chassis control',
      'Electric seat adjustment',
      'Electric side mirror',
      'Electric tailgate',
      'Electric windows',
      'Eletric seat adjustment with memory function',
      'Emergency brake assist',
      'Emergency call system',
      'ESP',
      'Fatigue warning system',
      'Folding exterior mirrors',
      'Four-wheel drive',
      'Full Service History',
      'Glare-free high beam headlights',
      'Hands-free kit',
      'Head-up display',
      'Heated rear seats',
      'Heated seats',
      'Heated steering wheel',
      'High beam assist',
      'Hill-start assist',
      'Immobilizer',
      'Isofix',
      'Keyless central locking',
      'Lane change assist',
      'Leather steering wheel',
      'LED headlights',
      'LED running lights',
      'Light sensor',
      'Lumbar support',
      'Multifunction steering wheel',
      'Navigation system',
      'Non-smoker vehicle',
      'On-board computer',
      'Paddle shifters',
      'Panoramic roof',
      'Power Assisted Steering',
      'Rain sensor',
      'Seat ventilation',
      'Sound system',
      'Sport seats',
      'Sports package',
      'Sports suspension',
      'Start-stop system',
      'Sunroof',
      'Tinted windows',
      'Touchscreen',
      'Traction control',
      'Traffic sign recognition',
      'Trailer coupling, swiveling',
      'Tyre pressure monitoring',
      'USB port',
      'Voice control',
      'Warranty',
      'WLAN / Wi-Fi hotspot',
    ],
    specialFeatures: ['Comfort Paket Plus', 'Travel Paket', 'BMW Niere Iconic Glow'],
    attributes: {
      modelRange: 'G06',
      trimLine: 'M Sport Pro',
      origin: 'German edition',
      capacity: '2993',
      owners: '1',
      emission: 'Euro 6e',
      sticker: '4 (Green)',
      metallic: 'Metallic',
      air: 'Automatic air conditioning, 4 zones',
      cylinders: '6',
    },
  },
  {
    ...common,
    id: 'bmw-540',
    make: 'BMW',
    model: '540',
    variant: 'd xDrive Touring M Sport Steptronic',
    price: 52440,
    previousPrice: 53990,
    year: 2024,
    registration: '03/2024',
    mileage: 33987,
    power: 303,
    fuel: 'Diesel',
    body: 'Estate',
    dealer: 'WELLER Performance GmbH & Co. KG',
    location: '48163 Münster',
    images: ['/images/bmw-540.webp'],
    deal: true,
  },
  {
    ...common,
    id: 'bmw-x3',
    make: 'BMW',
    model: 'X3',
    variant: '20d xDrive M Sport AHK Pano 19-inch',
    price: 57670,
    previousPrice: 61550,
    year: 2026,
    registration: 'New vehicle',
    mileage: 0,
    power: 197,
    fuel: 'Diesel',
    dealer: 'BMW Premium Selection',
    location: '53757 Sankt Augustin',
    images: [
      '/images/bmw-x3.webp',
      ...Array.from({ length: 8 }, (_, i) => '/images/bmw-x3-' + i + '.webp'),
    ],
    deal: true,
  },
  {
    ...common,
    id: 'bmw-120',
    make: 'BMW',
    model: '120',
    variant: 'M Sport Automatic · New car',
    price: 32990,
    monthly: 199,
    year: 2026,
    registration: 'New vehicle',
    mileage: 0,
    power: 170,
    fuel: 'Petrol',
    body: 'Saloon',
    dealer: 'BMW Partner',
    location: '22848 Norderstedt',
    images: ['/images/bmw-120.webp'],
    deal: true,
  },
];
/** Native fixture additions are captured locally, never live offers. */
export const capturedVehicles: Vehicle[] = baseVehicles.map((vehicle) => {
  const captured = (capturedListingDetails as unknown as Record<string, Partial<Vehicle>>)[
    vehicle.id
  ];
  const listing = captured
    ? { ...vehicle, ...captured, attributes: { ...vehicle.attributes, ...captured.attributes } }
    : vehicle;
  return {
    ...listing,
    sample: true,
    priceRating: vehicle.deal ? 'very-good' : 'good',
  };
});

/** Fictional stock for judging the showroom grid; these are not live offers. */
const demoStock = [
  {
    id: 'demo-mercedes-gle-2019',
    make: 'Mercedes-Benz',
    model: 'GLE',
    variant: '350 d Coupé · AMG Line',
    price: 34900,
    year: 2019,
    mileage: 119000,
    power: 258,
    fuel: 'Diesel',
    body: 'SUV',
    color: 'Black',
    images: ['/images/demo/mercedes-gle-coupe.webp'],
  },
  {
    id: 'demo-audi-rs6-2021',
    make: 'Audi',
    model: 'RS6',
    variant: 'Avant · quattro',
    price: 87900,
    year: 2021,
    mileage: 52000,
    power: 600,
    fuel: 'Petrol',
    body: 'Estate',
    color: 'Grey',
    images: ['/images/demo/audi-rs6-avant.webp'],
  },
  {
    id: 'demo-mercedes-amg-gt-2020',
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    variant: '63 S · 4MATIC+',
    price: 74900,
    year: 2020,
    mileage: 46000,
    power: 639,
    fuel: 'Petrol',
    body: 'Coupe',
    color: 'Grey',
    doors: 4,
    images: ['/images/demo/mercedes-amg-gt.webp'],
  },
  {
    id: 'demo-bmw-x6-2018',
    make: 'BMW',
    model: 'X6',
    variant: 'M50d · xDrive',
    price: 42900,
    year: 2018,
    mileage: 128000,
    power: 381,
    fuel: 'Diesel',
    body: 'SUV',
    color: 'Black',
    images: ['/images/demo/bmw-x6.webp'],
  },
  {
    id: 'demo-audi-rs-q8-2020',
    make: 'Audi',
    model: 'RSQ8',
    variant: 'quattro · Tiptronic',
    price: 69900,
    year: 2020,
    mileage: 84500,
    power: 600,
    fuel: 'Petrol',
    body: 'SUV',
    color: 'Grey',
    images: ['/images/demo/audi-rs-q8.webp'],
  },
  {
    id: 'demo-bmw-540-2022',
    make: 'BMW',
    model: '540',
    variant: 'd xDrive Touring · M Sport',
    price: 42950,
    year: 2022,
    mileage: 65000,
    power: 286,
    fuel: 'Diesel',
    body: 'Estate',
    color: 'White',
    images: ['/images/bmw-540-gallery-02.webp', '/images/bmw-540-gallery-03.webp'],
  },
  {
    id: 'demo-bmw-x3-2023',
    make: 'BMW',
    model: 'X3',
    variant: '20d xDrive · M Sport',
    price: 38900,
    year: 2023,
    mileage: 48800,
    power: 190,
    fuel: 'Diesel',
    body: 'SUV',
    color: 'White',
    images: ['/images/bmw-x3-gallery-03.webp', '/images/bmw-x3-gallery-04.webp'],
  },
  {
    id: 'demo-bmw-120-2025',
    make: 'BMW',
    model: '120',
    variant: 'M Sport · Automatic',
    price: 24900,
    year: 2025,
    mileage: 12000,
    power: 170,
    fuel: 'Petrol',
    body: 'Saloon',
    color: 'Black',
    images: ['/images/bmw-120-gallery-02.webp', '/images/bmw-120-gallery-01.webp'],
  },
  {
    id: 'demo-mercedes-gle-2018',
    make: 'Mercedes-Benz',
    model: 'GLE',
    variant: '350 d Coupé · AMG Line',
    price: 31900,
    year: 2018,
    mileage: 157000,
    power: 258,
    fuel: 'Diesel',
    body: 'SUV',
    color: 'Black',
    images: ['/images/demo/mercedes-gle-coupe.webp'],
  },
  {
    id: 'demo-audi-rs6-2022',
    make: 'Audi',
    model: 'RS6',
    variant: 'Avant · Performance',
    price: 99900,
    year: 2022,
    mileage: 28600,
    power: 600,
    fuel: 'Petrol',
    body: 'Estate',
    color: 'Grey',
    images: ['/images/demo/audi-rs6-avant.webp'],
  },
  {
    id: 'demo-bmw-x6-2017',
    make: 'BMW',
    model: 'X6',
    variant: '40d · xDrive',
    price: 34950,
    year: 2017,
    mileage: 162000,
    power: 313,
    fuel: 'Diesel',
    body: 'SUV',
    color: 'Black',
    images: ['/images/demo/bmw-x6.webp'],
  },
  {
    id: 'demo-mercedes-amg-gt-2021',
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    variant: '63 S · 4MATIC+',
    price: 82900,
    year: 2021,
    mileage: 33700,
    power: 639,
    fuel: 'Petrol',
    body: 'Coupe',
    color: 'Grey',
    doors: 4,
    images: ['/images/demo/mercedes-amg-gt.webp'],
  },
];
export const demoVehicles: Vehicle[] = demoStock.map((vehicle) => ({
  ...common,
  ...vehicle,
  sample: true,
  registration: '01/' + vehicle.year,
  dealer: 'Demo showroom',
  location: '',
  rating: 0,
  reviews: 0,
  attributes: { description: 'Sample vehicle · Showroom template preview' },
}));
export const vehicles: Vehicle[] = [...capturedVehicles, ...demoVehicles];
export const makes = [
  'Audi',
  'BMW',
  'Ford',
  'Mercedes-Benz',
  'Opel',
  'Porsche',
  'Skoda',
  'Toyota',
  'Volkswagen',
  'Hyundai',
  'Honda',
  'Kia',
  'Peugeot',
  'Renault',
  'Tesla',
  'Volvo',
];
export const topMakes = [
  'Volkswagen',
  'Mercedes-Benz',
  'BMW',
  'Audi',
  'Skoda',
  'Ford',
  'Opel',
  'Hyundai',
];
export const models: Record<string, string[]> = {
  BMW: [
    '1 Series',
    '120',
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '540',
    '6 Series',
    '7 Series',
    '840',
    '850',
    'i3',
    'i4',
    'i5',
    'i7',
    'iX',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
  ],
  Volkswagen: ['Golf', 'Polo', 'Passat', 'Tiguan', 'T-Roc', 'Touareg', 'ID.3', 'ID.4', 'ID.7'],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
  'Mercedes-Benz': [
    'A-Class',
    'B-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'CLA',
    'GLA',
    'GLC',
    'GLE',
    'EQA',
    'EQE',
  ],
  Ford: ['Fiesta', 'Focus', 'Kuga', 'Mustang', 'Puma'],
  Skoda: ['Fabia', 'Octavia', 'Superb', 'Kodiaq', 'Enyaq'],
  Hyundai: ['i10', 'i20', 'i30', 'Kona', 'Tucson', 'IONIQ 5'],
  Toyota: ['Yaris', 'Corolla', 'C-HR', 'RAV4', 'Land Cruiser'],
  Honda: ['CB', 'CBR', 'Civic', 'CR-V'],
  Opel: ['Astra', 'Corsa', 'Grandland', 'Mokka'],
};
export const equipment = [
  'Air conditioning',
  'Bluetooth',
  'Cruise control',
  'Heated seats',
  'LED headlights',
  'Navigation system',
  'Parking sensors',
  'Panoramic roof',
  'Tow bar',
  'Apple CarPlay',
  'Rear view camera',
  'Alloy wheels',
];
export function getVehicle(id: string) {
  return vehicles.find((vehicle) => vehicle.id === id);
}
