import type { VehicleCategory } from './types';
// Native make lists captured from the installed Android category pickers.
export const categoryMakes: Partial<Record<VehicleCategory, string[]>> = {
  bike: [
    'Access Motor',
    'Adly',
    'Aeon',
    'AGM MOTORS',
    'Aixam',
    'American Ironhorse',
    'Aprilia',
    'Arctic Cat',
    'Baotian',
    'Barossa',
    'Bashan',
    'Beeline',
    'Benda',
    'Benelli',
    'Beta',
    'Big Dog Motorcycles',
    'Bimota',
    'Black Tea',
    'Blata',
    'BMW',
    'Bombardier',
    'Boom',
    'Brixton',
    'Brough Superior',
    'BRP',
    'BSA',
    'Buell',
    'Burelli',
    'Cagiva',
    'Can-Am',
    'Cectek',
    'CFMOTO',
    'Cobra Moto',
    'CPI',
    'Daelim',
    'Derbi',
    'Dinli',
    'DKW',
    'DREEMS',
    'Ducati',
    'e-max',
    'e-Schwalbe',
    'E-Ton',
    'emco',
    'Energica',
    'evmoto',
    'Explorer',
    'Fantic',
    'FB Mondial',
    'Felo Moto',
    'Futura',
    'Gasgas',
    'Generic',
    'GG Motorradtechnik',
    'Gilera',
    'GOES',
    'Gorilla',
    'Govecs',
    'GTS Benelux',
    'Harley-Davidson',
    'Heinkel',
    'Hercules',
    'Herkules',
    'Honda',
    'Horex',
    'Horwin',
    'Husaberg',
    'Husqvarna',
    'Hyosung',
    'Indian',
    'Italjet',
    'Jawa',
    'Jinling',
    'Kawasaki',
    'KAYO',
    'Keeway',
    'Kimi',
    'KL Mobility / Piper',
    'Knievel',
    'KOVE',
    'Kreidler',
    'KSR',
    'KTM',
    'Kumpan',
    'Kymco',
    'Lambretta',
    'Laverda',
    'Leonart',
    'Lifan',
    'Linhai',
    'LiveWire',
    'LML',
    'Loncin',
    'Luxxon',
    'Maico',
    'Malaguti',
    'Mash',
    'MBK',
    'Megelli',
    'Metorbike',
    'Moto Guzzi',
    'Moto Morini',
    'Motobi',
    'Motowell',
    'Motron',
    'MV Agusta',
    'Mz',
    'NAON',
    'Nerva',
    'NITO',
    'NIU',
    'Norton',
    'NSU',
    'Odes',
    'Online',
    'Pegasus',
    'Peugeot',
    'PGO',
    'Piaggio',
    'Piper',
    'PohlBock',
    'Polaris',
    'Puch',
    'QJ Motor',
    'Quadix',
    'Quadro',
    'Ray',
    'Rewaco',
    'RGNT',
    'Rieju',
    'Rivero',
    'Royal Alloy',
    'Royal Enfield',
    'Sachs',
    'Scrooser',
    'Seat',
    'Segway',
    'Seikel',
    'Sherco',
    'Shineray',
    'Si.o',
    'Silence',
    'Simson',
    'Skyteam',
    'SMC',
    'Sportiva',
    'Stark',
    'Steereon',
    'Stels',
    'Super Soco',
    'Sur-Ron',
    'Suzuki',
    'SWM',
    'SYM',
    'Talaria',
    'Tauris',
    'TGB',
    'Thunderbike',
    'TiSTO',
    'TM',
    'Triton',
    'Triumph',
    'TRS',
    'UM',
    'Ural',
    'Vespa',
    'VICTORY',
    'Vincent',
    'VOGE',
    'Voltago',
    'Voxan',
    'WMI',
    'Yamaha',
    'Zero',
    'Zhongyu',
    'Zontes',
    'Zündapp',
  ],
  'electric-bike': [
    '19twentyfiver',
    'Abarth',
    'Academy',
    'ADORE',
    'Advanced',
    'Ahooga',
    'Antric',
    'ATLANTA',
    'Audi',
    'Babboe',
    'Bad Bike',
    'Bakfiets',
    'Batavus',
    'Bennobikes',
    'Bergamont',
    'Berlin Bike',
    'BESV',
    'BH Bikes',
    'Bianchi',
    'Bionicon',
    'Biria',
    'Blaupunkt',
    'Bmc',
    'BMW',
    'Böttcher',
    'Brennabor',
    'Brinckers',
    'Brompton',
    'Bullit',
    'BULLS',
    'Butchers & Bicycles',
    'Ca Go',
    'Cannondale',
    'Canyon',
    'car.los',
    'Carla Cargo',
    'Carqon',
    'Carver',
    'Centurion',
    'Chike',
    'Christiania Bikes',
    'CityQ',
    'Claas',
    'cluuv',
    'Coboc',
    'CONE Bikes',
    'Contoura',
    'Conway',
    'Corratec',
    'Crussis',
    'Cube',
    'Deruiz',
    'Desiknio',
    'Diablo Bikes',
    'Diamant',
    'Dolly Bikes',
    'Dutch ID',
    'Dynabike',
    'e-bike manufaktur',
    'Econic One',
    'Electra',
    'Excelsior',
    'Falter',
    'Fantic',
    'FEDDZ',
    'Fiido',
    'Fischer',
    'FlexiModal',
    'Flyer',
    'Focus',
    'Fuji',
    'Gasgas',
    'Gazelle',
    'Gepida',
    'Ghost',
    'Giant',
    'GoCab',
    'Gocycle',
    'Grace',
    'Grecos',
    "Green's",
    'Gudereit',
    'Haibike',
    'Hartje',
    'Hase Bikes',
    'HAWK Bikes',
    'HEAD bike',
    'HEPHA',
    'Hercules',
    'Himiway',
    'Hinterher',
    'HNF',
    'Hoheacht',
    'Hollandia',
    'Husqvarna',
    'i:SY',
    'Invelo',
    'isicargo',
    'IXGO',
    'Jeep E-Bikes',
    'Johansson',
    'Johnny Loco',
    'Kalkhoff',
    'Kayza',
    'Kemoway',
    'Keskin eBike',
    'Kettler',
    'Klever',
    'Kneissl Design',
    'Koga',
    'Kreidler',
    'Kross',
    'KTM',
    'Lapierre',
    'Larry vs Harry',
    'LeaderFox',
    'Lekker',
    'LEMMO',
    'Lettler',
    'LIQ Bike',
    'Liv',
    'Look',
    'Lovens',
    'M1-Sporttechnik',
    'Malaguti',
    'MATE',
    'MC E-Bike',
    'Mercedes-Benz',
    'Merida',
    'Metz',
    'Misterride',
    'Mobilemaster',
    'Momentum',
    'Mondraker',
    'Monty',
    'Morrison',
    'Moustache',
    'muli',
    'MV Agusta',
    'My Boo',
    'My Esel',
    'myco',
    'NCM',
    'Nicolai',
    'Nihola',
    'NOX cycles',
    'Noxon',
    'NS BIKES',
    'O2Feel',
    'Omnium',
    'ONOMOTION',
    'Orbea',
    'OZ Racing',
    'Patria',
    'Pegasus',
    'pfautec',
    'Piaggio',
    'Pinarello',
    'Porsche',
    'Propain',
    'Prophete',
    'Pyrobikes',
    'QiO',
    'QWIC',
    'Rabeneick',
    'Radkutsche',
    'Radon',
    'Raleigh',
    'Raymon',
    'Reebok',
    'Riese & Müller',
    'Rock Machine',
    'Rocky-mountain',
    'Rondo',
    'Rose',
    'Rotwild',
    'Rover E-Bikes',
    'Royal Cargo Bike',
    'Ruff Cycles',
    'Ryke',
    'Santa-cruz',
    'Schindelhauer',
    'Schoof & Jensen',
    'Scott',
    'Serial 1',
    'Sherco',
    'Simplon',
    'Solex E-Bikes',
    'Sparta',
    'Specialized',
    'Stevens',
    'Storck',
    'Stromer',
    'SUPER73',
    'SUSHI BIKES',
    'Swype',
    'Telefunken',
    'TENWAYS',
    'Tern',
    'TOTEM',
    'Tour de Suisse',
    'Tout Terrain',
    'Trek',
    'Trenoli',
    'Tricargo',
    'Triobike',
    'Triumph',
    'Union',
    'Univega',
    'Urban Arrow',
    'UrbanBiker',
    'Urtopia',
    'Urwahn',
    'Van Raam',
    'VanMoof',
    'Vaun',
    'Velo de Ville',
    'Veloe',
    'Veloretti',
    'Victoria',
    'Vii',
    'Vogue Bike',
    'Vowag',
    'VSF Fahrradmanufaktur',
    'Waldbike',
    'WANDERER',
    'Whyte Bikes',
    'Wilier',
    'Winora',
    'Winther Bikes',
    'Wittich',
    'Woom',
    'XCYC',
    'Yamaha',
    'Yoonit',
    'ZEMMI',
    'Zemo',
  ],
  motorhome: [
    'ABI',
    'Across',
    'Adria',
    'Affinity',
    'Ahorn',
    'Airstream',
    'Algovia',
    'Alpha',
    'Alpincamper',
    'Antilope VAN',
    'Arca',
    'Atlantis',
    'Autostar',
    'Avento',
    'Azar4',
    'Balcamp',
    'Bavaria-Camp',
    'Bawemo',
    'Bela',
    'Benimar',
    'Beyerland',
    'Bimobil',
    'Bravia',
    'Bresler Mobile',
    'Burow',
    'Bürstner',
    'Camppass',
    'Carado',
    'Caravelair',
    'Caro',
    'Carthago',
    'Challenger',
    'Chateau',
    'Chausson',
    'Chrysler',
    'CI International',
    'Citroën',
    'Clever',
    'Coachmen',
    'Concorde',
    'Corigon',
    'Crawler',
    'Cristall',
    'Crosscamp',
    'CS Reisemobile',
    'Decamp',
    'Deddle',
    'Dehler',
    'Delta',
    'Dethleffs',
    'DOMO',
    'Dopfer',
    'Dörr Explore',
    'Dovra',
    'Dreamer',
    'Due Erre',
    'Dux Camper',
    'Easy Camper',
    'Eifelland',
    'Elnagh',
    'Esterel',
    'Etrusco',
    'Eura Mobil',
    'Euro Liner',
    'EVM',
    'Extreme',
    'Fendt',
    'FFB - Tabbert',
    'Fiat',
    'Fischer',
    'Fleetwood',
    'Fleurette',
    'Ford',
    'Ford / Reimo',
    'Forster',
    'Four Wheel Campers',
    'FR-Mobil',
    'Frankia',
    'Freedo RV',
    'FUSO',
    'General Motors',
    'GiottiLine',
    'Globe-Traveller',
    'Globecar',
    'Glücksmobil',
    'Granduca',
    'Hannes Camper',
    'Hehn',
    'Heku',
    'Hobby',
    'Holiday Rambler',
    'Home-Car',
    'Hotomobil',
    'HRZ',
    'Hunter Nature',
    'HYMER / ERIBA / HYMERCAR',
    'Ilusion',
    'Innova',
    'Itineo',
    'Iveco',
    'Joa Camp',
    'Joint',
    'Kabe',
    'Kaiser',
    'Karmann',
    'Kip',
    'Knaus',
    'La Marca',
    'La Strada',
    'Laika',
    'Le Voyageur',
    'LMC',
    'Loef',
    'LQ4',
    'M+M Mobile',
    'Malibu',
    'MAN',
    'Masuria',
    'Mazda',
    'McLouis',
    'MegaMobil',
    'Mercedes-Benz',
    'Miller',
    'Mirage',
    'Mitsubishi',
    'Mobilvetta',
    'Monaco',
    'Moncayo',
    'Mooveo',
    'Morelo',
    'Next',
    'Niesmann + Bischoff',
    'Niewiadów',
    'Noah Camper',
    'NobelART',
    'Nomade Nation',
    'Nordstar',
    'Northern Lights Campers',
    'Notin',
    'Opel',
    'Orangecamp',
    'Ormocar',
    'P.L.A.',
    'Panama',
    'Paul & Paula',
    'Peugeot',
    'Phoenix',
    'Pilote',
    'Polar',
    'Pössl',
    'Protec',
    'Raclet',
    'Randger',
    'Rapido',
    'Reimo',
    'Reisemobile Beier',
    'Renault',
    'Rhön Camp',
    'Rimor',
    'Riva',
    'Riviera',
    'RMB',
    'Roadcar',
    'ROADfans',
    'Roadtrek',
    'Robel-Mobil',
    'Robeta',
    'Roller Team',
    'Romahome',
    'RS Camp',
    'Salty Blue',
    'SEA',
    'Seitz',
    'Selbstbau',
    'Six-Pac',
    'Sloop',
    'SOD',
    'Solifer',
    'Soma Camp',
    'Sprite',
    'Sterckeman',
    'Sun Living',
    'Sunlight',
    'Sunvan',
    'Sylt-Camper',
    'T@b',
    'Tabbert',
    'TEC',
    'Tischer',
    'Tourne',
    'Toyota',
    'Trigano',
    'Triple E',
    'TSL Landsberg/ Rockwood',
    'Vanderer',
    'Vanestro',
    'vanexxt',
    'VANING',
    'Vannado',
    'VANTourer',
    'VARIO mobil',
    'VIICA Vans',
    'Volkswagen',
    'Wanderlust',
    'Wanner',
    'Weinsberg',
    'Weippert',
    'Westfalia',
    'Wildboar',
    'Wilde',
    'Wilk',
    'Wingamm',
    'Winnebago',
    'Woelcke',
    'XGO',
    'Yucon',
  ],
  truck: [
    'BYD',
    'DAF',
    'Demag',
    'Faun',
    'Ford',
    'Freightliner',
    'FUSO',
    'Ginaf',
    'Grove',
    'Hako',
    'HN Schörling',
    'Iveco',
    'Kamaz',
    'Liebherr',
    'Mack',
    'Magirus Deutz',
    'MAN',
    'Meiller',
    'Mercedes-Benz',
    'Mitsubishi',
    'Nissan',
    'Opel',
    'Palfinger',
    'Peugeot',
    'RB Expedition',
    'Renault',
    'Ruthmann',
    'Scania',
    'Schmidt',
    'Skoda',
    'Steyr',
    'Tatra',
    'Toyota',
    'Unimog',
    'Volkswagen',
    'Volvo',
    'Wiese',
    'Yanmar',
  ],
};
