import type { VehicleCategory } from './types';
// Visible native category choices from emulator reference captures 220–223.
export const categoryTopMakes: Partial<Record<VehicleCategory, string[]>> = {
  bike: ['BMW', 'Honda', 'Yamaha', 'Kawasaki', 'Suzuki', 'KTM', 'Ducati', 'Harley-Davidson'],
  'electric-bike': ['R&M', 'Cube', 'Haibike', 'Kalkhoff', 'BULLS', 'Focus', 'Winora', 'KTM'],
  motorhome: ['Hymer', 'Fendt', 'Knaus', 'Dethleffs', 'Bürstner', 'LMC', 'Weinsberg', 'Tabbert'],
};
export const categoryBrandImages: Partial<Record<VehicleCategory, Record<string, string>>> = {
  bike: {
    BMW: '/images/categories/bike-0.webp',
    Honda: '/images/categories/bike-1.webp',
    Yamaha: '/images/categories/bike-2.webp',
    Kawasaki: '/images/categories/bike-3.webp',
    Suzuki: '/images/categories/bike-4.webp',
    KTM: '/images/categories/bike-5.webp',
    Ducati: '/images/categories/bike-6.webp',
    'Harley-Davidson': '/images/categories/bike-7.webp',
  },
  'electric-bike': {
    'R&M': '/images/categories/electric-bike-0.webp',
    Cube: '/images/categories/electric-bike-1.webp',
    Haibike: '/images/categories/electric-bike-2.webp',
    Kalkhoff: '/images/categories/electric-bike-3.webp',
    BULLS: '/images/categories/electric-bike-4.webp',
    Focus: '/images/categories/electric-bike-5.webp',
    Winora: '/images/categories/electric-bike-6.webp',
    KTM: '/images/categories/electric-bike-7.webp',
  },
  motorhome: {
    Hymer: '/images/categories/motorhome-0.webp',
    Fendt: '/images/categories/motorhome-1.webp',
    Knaus: '/images/categories/motorhome-2.webp',
    Dethleffs: '/images/categories/motorhome-3.webp',
    Bürstner: '/images/categories/motorhome-4.webp',
    LMC: '/images/categories/motorhome-5.webp',
    Weinsberg: '/images/categories/motorhome-6.webp',
    Tabbert: '/images/categories/motorhome-7.webp',
  },
};
export const truckCategories = [
  'Over 7.5 t',
  'Trailer',
  'Up to 7.5 t',
  'Semi-Trailer Truck',
  'Semi-trailer',
  'Buses',
  'Agriculture',
  'Construction',
  'Forklift',
];

export const categoryVehicleTypes: Partial<Record<VehicleCategory, string[]>> = {
  bike: [
    'Chopper/Cruiser',
    'Combination/Sidecar',
    'Dirt Bike',
    'Enduro/Touring Enduro',
    'Lightweight Motorcycle/Motorbike',
    'Motor-assisted Bicycle/Small Moped',
    'Motorcycle',
    'Naked Bike',
    'Other vehicle type',
    'Pocketbike',
    'Quad',
    'Racing',
    'Roadster',
    'Rally/Cross',
    'Scooter',
    'Sport Touring Motorcycles',
    'Sports/Super Sports Bike',
    'Streetfighter',
    'Super Moto',
    'Tourer',
    'Trike',
  ],
  'electric-bike': [
    'Cargo bike',
    'City bike',
    'Cross bike',
    'Fatbike',
    'Folding bike',
    'Mountain bike',
    'Racing bike',
    'Trekking bike',
    'Other vehicle type',
  ],
  motorhome: [
    'Alcoves',
    'Integrated',
    'Van',
    'Mobile Home',
    'Partly Integrated',
    'Cabin',
    'Motor Homes, Other',
    'Motor Homes/Pickup',
    'Caravan',
    'Other vehicle type',
  ],
};
