// Names and artwork from the installed Android picker; not a live marketplace feed.
export const allMakes = [
  'Abarth',
  'AC',
  'Acura',
  'Aiways',
  'Aixam',
  'Alfa Romeo',
  'ALPINA',
  'Alpine',
  'Alvis',
  'Ariel',
  'Artega',
  'Asia Motors',
  'Aston Martin',
  'Audi',
  'Austin',
  'Austin Healey',
  'Auto Union',
  'Barkas',
  'BAW',
  'Bentley',
  'Bizzarrini',
  'BMW',
  'Borgward',
  'Bovensiepen',
  'Brilliance',
  'Bugatti',
  'Buick',
  'BYD',
  'Cadillac',
  'Casalini',
  'Caterham',
  'Cenntro',
  'Changan',
  'Chatenet',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Cobra',
  'Corvette',
  'Cupra',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'Dallara',
  'Datsun',
  'Delahaye',
  'DeLorean',
  'DeTomaso',
  'DFM',
  'DFSK',
  'Dodge',
  'Donkervoort',
  'DS Automobiles',
  'e.GO',
  'Elaris',
  'Estrima',
  'Facel Vega',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'Foton',
  'GAC Gonow',
  'Geely',
  'Gemballa',
  'Genesis',
  'GMC',
  'Grecav',
  'GWM',
  'Hamann',
  'Heinkel',
  'Holden',
  'Honda',
  'Hongqi',
  'Horch',
  'Hummer',
  'Hyundai',
  'INEOS',
  'Infiniti',
  'Invicta',
  'Isuzu',
  'Iveco',
  'JAC',
  'Jaguar',
  'Jeep',
  'Jetour',
  'Jiayuan',
  'KGM',
  'Kia',
  'Koenigsegg',
  'KTM',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Landwind',
  'Leapmotor',
  'LEVC',
  'Lexus',
  'Ligier',
  'Lincoln',
  'Lotus',
  'Lucid',
  'Lynk&Co',
  'Mahindra',
  'MAN',
  'Maserati',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Messerschmitt',
  'MG',
  'Microcar',
  'Microlino',
  'MINI',
  'Mitsubishi',
  'Morgan',
  'NIO',
  'Nissan',
  'NSU',
  'Oldsmobile',
  'OMODA',
  'Opel',
  'ORA',
  'Packard',
  'Pagani',
  'Peugeot',
  'Piaggio',
  'Plymouth',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Proton',
  'Renault',
  'Riley',
  'Rimac',
  'Rolls-Royce',
  'Rover',
  'Ruf',
  'Saab',
  'Santana',
  'Seat',
  'Seres',
  'Silence',
  'Simca',
  'Skoda',
  'Smart',
  'speedART',
  'Spyker',
  'Ssangyong',
  'Studebaker',
  'Subaru',
  'Suzuki',
  'SWM',
  'Talbot',
  'Tata',
  'TECHART',
  'Tesla',
  'Togg',
  'Toyota',
  'Trabant',
  'Triumph',
  'TVR',
  'TYN-e',
  'Vincent',
  'VinFast',
  'Volkswagen',
  'Volvo',
  'Voyah',
  'Wartburg',
  'Westfield',
  'WEY',
  'Wiesmann',
  'XEV',
  'XPENG',
  'Zeekr',
  'Zhidou',
];
export const makeImages: Record<string, string> = {
  Audi: '/images/makes/audi.webp',
  BMW: '/images/makes/bmw.webp',
  Ford: '/images/makes/ford.webp',
  'Mercedes-Benz': '/images/makes/mercedes-benz.webp',
  Opel: '/images/makes/opel.webp',
  Porsche: '/images/makes/porsche.webp',
  Skoda: '/images/makes/skoda.webp',
  Toyota: '/images/makes/toyota.webp',
  Abarth: '/images/makes/abarth.webp',
  AC: '/images/makes/ac.webp',
  Acura: '/images/makes/acura.webp',
  Aiways: '/images/makes/aiways.webp',
  Aixam: '/images/makes/aixam.webp',
  'Alfa Romeo': '/images/makes/alfa-romeo.webp',
  ALPINA: '/images/makes/alpina.webp',
  Alpine: '/images/makes/alpine.webp',
  Ariel: '/images/makes/ariel.webp',
  Artega: '/images/makes/artega.webp',
  'Asia Motors': '/images/makes/asia-motors.webp',
  'Aston Martin': '/images/makes/aston-martin.webp',
  Austin: '/images/makes/austin.webp',
  'Austin Healey': '/images/makes/austin-healey.webp',
  'Auto Union': '/images/makes/auto-union.webp',
  Barkas: '/images/makes/barkas.webp',
  BAW: '/images/makes/baw.webp',
  Bentley: '/images/makes/bentley.webp',
  Bizzarrini: '/images/makes/bizzarrini.webp',
  Borgward: '/images/makes/borgward.webp',
  Brilliance: '/images/makes/brilliance.webp',
  Bugatti: '/images/makes/bugatti.webp',
  BYD: '/images/makes/byd.webp',
  Cadillac: '/images/makes/cadillac.webp',
  Casalini: '/images/makes/casalini.webp',
  Caterham: '/images/makes/caterham.webp',
  Cenntro: '/images/makes/cenntro.webp',
  Changan: '/images/makes/changan.webp',
  Chatenet: '/images/makes/chatenet.webp',
  Chevrolet: '/images/makes/chevrolet.webp',
  Cobra: '/images/makes/cobra.webp',
  Corvette: '/images/makes/corvette.webp',
  Cupra: '/images/makes/cupra.webp',
  Dacia: '/images/makes/dacia.webp',
  Daewoo: '/images/makes/daewoo.webp',
  Daihatsu: '/images/makes/daihatsu.webp',
  Dallara: '/images/makes/dallara.webp',
  Datsun: '/images/makes/datsun.webp',
  Delahaye: '/images/makes/delahaye.webp',
  DeLorean: '/images/makes/delorean.webp',
  DeTomaso: '/images/makes/detomaso.webp',
  DFSK: '/images/makes/dfsk.webp',
  Dodge: '/images/makes/dodge.webp',
  Donkervoort: '/images/makes/donkervoort.webp',
  'DS Automobiles': '/images/makes/ds-automobiles.webp',
  'e.GO': '/images/makes/e-go.webp',
  Elaris: '/images/makes/elaris.webp',
  Estrima: '/images/makes/estrima.webp',
  'Facel Vega': '/images/makes/facel-vega.webp',
  Ferrari: '/images/makes/ferrari.webp',
  Fiat: '/images/makes/fiat.webp',
  Fisker: '/images/makes/fisker.webp',
  Foton: '/images/makes/foton.webp',
  'GAC Gonow': '/images/makes/gac-gonow.webp',
  Gemballa: '/images/makes/gemballa.webp',
  Genesis: '/images/makes/genesis.webp',
  GMC: '/images/makes/gmc.webp',
  Grecav: '/images/makes/grecav.webp',
  GWM: '/images/makes/gwm.webp',
  Hamann: '/images/makes/hamann.webp',
  Heinkel: '/images/makes/heinkel.webp',
  Holden: '/images/makes/holden.webp',
  Honda: '/images/makes/honda.webp',
  Hongqi: '/images/makes/hongqi.webp',
  Horch: '/images/makes/horch.webp',
  Hummer: '/images/makes/hummer.webp',
  Hyundai: '/images/makes/hyundai.webp',
  INEOS: '/images/makes/ineos.webp',
  Infiniti: '/images/makes/infiniti.webp',
  Invicta: '/images/makes/invicta.webp',
  Isuzu: '/images/makes/isuzu.webp',
  Iveco: '/images/makes/iveco.webp',
  JAC: '/images/makes/jac.webp',
  Jaguar: '/images/makes/jaguar.webp',
  Jeep: '/images/makes/jeep.webp',
  Jiayuan: '/images/makes/jiayuan.webp',
  KGM: '/images/makes/kgm.webp',
  Kia: '/images/makes/kia.webp',
  Koenigsegg: '/images/makes/koenigsegg.webp',
  KTM: '/images/makes/ktm.webp',
  Lada: '/images/makes/lada.webp',
  Lamborghini: '/images/makes/lamborghini.webp',
  Lancia: '/images/makes/lancia.webp',
  'Land Rover': '/images/makes/land-rover.webp',
  Landwind: '/images/makes/landwind.webp',
  Leapmotor: '/images/makes/leapmotor.webp',
  LEVC: '/images/makes/levc.webp',
  Ligier: '/images/makes/ligier.webp',
  Lincoln: '/images/makes/lincoln.webp',
  Lotus: '/images/makes/lotus.webp',
  Lucid: '/images/makes/lucid.webp',
  'Lynk&Co': '/images/makes/lynk-co.webp',
  Mahindra: '/images/makes/mahindra.webp',
  MAN: '/images/makes/man.webp',
  Maserati: '/images/makes/maserati.webp',
  Maybach: '/images/makes/maybach.webp',
  Mazda: '/images/makes/mazda.webp',
  McLaren: '/images/makes/mclaren.webp',
  Messerschmitt: '/images/makes/messerschmitt.webp',
  MG: '/images/makes/mg.webp',
  Microcar: '/images/makes/microcar.webp',
  Microlino: '/images/makes/microlino.webp',
  MINI: '/images/makes/mini.webp',
  Mitsubishi: '/images/makes/mitsubishi.webp',
  Morgan: '/images/makes/morgan.webp',
  NIO: '/images/makes/nio.webp',
  Nissan: '/images/makes/nissan.webp',
  NSU: '/images/makes/nsu.webp',
  Oldsmobile: '/images/makes/oldsmobile.webp',
  ORA: '/images/makes/ora.webp',
  Packard: '/images/makes/packard.webp',
  Pagani: '/images/makes/pagani.webp',
  Peugeot: '/images/makes/peugeot.webp',
  Piaggio: '/images/makes/piaggio.webp',
  Plymouth: '/images/makes/plymouth.webp',
  Polestar: '/images/makes/polestar.webp',
  Pontiac: '/images/makes/pontiac.webp',
  Proton: '/images/makes/proton.webp',
  Renault: '/images/makes/renault.webp',
  'Rolls-Royce': '/images/makes/rolls-royce.webp',
  Rover: '/images/makes/rover.webp',
  Ruf: '/images/makes/ruf.webp',
  Saab: '/images/makes/saab.webp',
  Santana: '/images/makes/santana.webp',
  Seat: '/images/makes/seat.webp',
  Seres: '/images/makes/seres.webp',
  Silence: '/images/makes/silence.webp',
  Simca: '/images/makes/simca.webp',
  Smart: '/images/makes/smart.webp',
  speedART: '/images/makes/speedart.webp',
  Spyker: '/images/makes/spyker.webp',
  Studebaker: '/images/makes/studebaker.webp',
  Subaru: '/images/makes/subaru.webp',
  Suzuki: '/images/makes/suzuki.webp',
  SWM: '/images/makes/swm.webp',
  Talbot: '/images/makes/talbot.webp',
  Tata: '/images/makes/tata.webp',
  TECHART: '/images/makes/techart.webp',
  Tesla: '/images/makes/tesla.webp',
  Trabant: '/images/makes/trabant.webp',
  Triumph: '/images/makes/triumph.webp',
  TVR: '/images/makes/tvr.webp',
  'TYN-e': '/images/makes/tyn-e.webp',
  Vincent: '/images/makes/vincent.webp',
  Volkswagen: '/images/makes/volkswagen.webp',
  Volvo: '/images/makes/volvo.webp',
  Wartburg: '/images/makes/wartburg.webp',
  Westfield: '/images/makes/westfield.webp',
  WEY: '/images/makes/wey.webp',
  Wiesmann: '/images/makes/wiesmann.webp',
  XEV: '/images/makes/xev.webp',
  XPENG: '/images/makes/xpeng.webp',
  Zhidou: '/images/makes/zhidou.webp',
};
export const popularMakes = [
  'Audi',
  'BMW',
  'Ford',
  'Mercedes-Benz',
  'Opel',
  'Porsche',
  'Skoda',
  'Toyota',
  'Volkswagen',
];
