// Generated from verified native Android dialog captures. Re-run scripts/integrate-native-filter-options.mjs to refresh.
export type NativeFilterCapture = {
  mode: 'range' | 'single' | 'multiple';
  includeAny: boolean;
  options: string[];
  source: string;
};
export const nativeFilterOptions: Record<string, NativeFilterCapture> = {
  condition: {
    mode: 'single',
    includeAny: true,
    options: ['New', 'Used'],
    source: 'reference/android/filter-options/condition-0.xml',
  },
  payment: {
    mode: 'single',
    includeAny: false,
    options: ['Buy', 'Leasing'],
    source: 'reference/android/filter-options/payment-0.xml',
  },
  price: {
    mode: 'range',
    includeAny: true,
    options: ['Price (€)', 'From', 'To', '73937', '500', '90000'],
    source: 'reference/android/filter-options/price-0.xml',
  },
  year: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '1900', '2026'],
    source: 'reference/android/filter-options/year-0.xml',
  },
  mileage: {
    mode: 'range',
    includeAny: true,
    options: ['Mileage (km)', 'From', 'To', '5000', '200000'],
    source: 'reference/android/filter-options/mileage-0.xml',
  },
  power: {
    mode: 'range',
    includeAny: true,
    options: ['Power (hp)', 'HP', 'kW', 'From', 'To', '34', '454'],
    source: 'reference/android/filter-options/power-0.xml',
  },
  fuel: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Petrol',
      'Diesel',
      'Electric',
      'Hybrid (petrol/electric)',
      'Hybrid (diesel/electric)',
      'Ethanol (FFV, E85, etc.)',
      'Hydrogen',
      'LPG',
      'Natural Gas',
      'Other fuel type',
    ],
    source: 'reference/android/filter-options/fuel-0.xml',
  },
  location: {
    mode: 'single',
    includeAny: true,
    options: ['Location and vicinity', 'Enter location or postal code', 'Country'],
    source: 'reference/android/filter-options/location-0.xml',
  },
  body: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Convertible/Roadster',
      'Estate car',
      'Off-road Vehicle/Pickup Truck/SUV',
      'Other vehicle type',
      'Saloon',
      'Small Car',
      'Sports Car/Coupe',
      'Van/Minibus',
    ],
    source: 'reference/android/filter-options/body-0.xml',
  },
  seats: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '2', '10', '3', '4', '5', '6', '7', '8', '9'],
    source: 'reference/android/filter-options/seats-0.xml',
  },
  doors: {
    mode: 'single',
    includeAny: true,
    options: ['2/3', '4/5', '6/7'],
    source: 'reference/android/filter-options/doors-0.xml',
  },
  slidingDoor: {
    mode: 'single',
    includeAny: true,
    options: ['Sliding door right', 'Sliding door left', 'Sliding door both-sided'],
    source: 'reference/android/filter-options/slidingDoor-0.xml',
  },
  transmission: {
    mode: 'multiple',
    includeAny: false,
    options: ['Automatic', 'Manual gearbox', 'Semi-automatic'],
    source: 'reference/android/filter-options/transmission-0.xml',
  },
  capacity: {
    mode: 'range',
    includeAny: true,
    options: ['Cubic capacity (cm³)', 'From', 'To', '1000', '9000'],
    source: 'reference/android/filter-options/capacity-0.xml',
  },
  color: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'beige',
      'blue',
      'brown',
      'yellow',
      'gold',
      'green',
      'grey',
      'orange',
      'red',
      'black',
      'silver',
      'purple',
      'white',
    ],
    source: 'reference/android/filter-options/color-0.xml',
  },
  description: {
    mode: 'single',
    includeAny: false,
    options: [
      'Feature Search',
      'e.g. LED-Scheinwerfer…',
      "Didn't find your favorite feature? Search for it by entering one or more features.",
    ],
    source: 'reference/android/filter-options/description-0.xml',
  },
  air: {
    mode: 'single',
    includeAny: true,
    options: [
      'Automatic air conditioning',
      'Manual or automatic climate control',
      'Automatic climatisation, 2 zones',
      'Automatic climatisation, 3 zones',
      'Automatic climatisation, 4 zones',
      'No climatisation',
    ],
    source: 'reference/android/filter-options/air-0.xml',
  },
  interior: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Android Auto',
      'Apple CarPlay',
      'Bluetooth',
      'CD player',
      'Hands-free kit',
      'Head-up display',
      'Integrated music streaming',
      'Leather steering wheel',
      'Multifunction steering wheel',
      'Navigation system',
      'Sound system',
      'TV',
      'Touchscreen',
      'USB port',
      'Voice control',
      'WLAN / Wi-Fi hotspot',
    ],
    source: 'reference/android/filter-options/interior-0.xml',
  },
  security: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'ABS',
      'Alarm system',
      'Blind spot assist',
      'Distance warning system',
      'Dynamic chassis control',
      'ESP',
      'Emergency brake assist',
      'Emergency call system',
      'Fatigue warning system',
      'High beam assist',
      'Hill start assist',
      'Lane change assist',
      'Night vision assist',
      'Speed limit control system',
      'Traction control',
      'Traffic sign recognition',
    ],
    source: 'reference/android/filter-options/security-0.xml',
  },
  other: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Air suspension',
      'Immobilizer',
      'Isofix',
      'Passenger seat Isofix point',
      'Power Assisted Steering',
    ],
    source: 'reference/android/filter-options/other-0.xml',
  },
  controls: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Autom. dimming interior mirror',
      'Central locking',
      'Digital cockpit',
      'Electric side mirror',
      'Electric windows',
      'Folding exterior mirrors',
      'Keyless central locking',
      'On-board computer',
      'Virtual side mirror',
    ],
    source: 'reference/android/filter-options/controls-0.xml',
  },
  extras: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Ambient lighting',
      'Cargo barrier',
      'Disabled accessible',
      'Electric tailgate',
      'Heated steering wheel',
      'Heated windshield',
      'Induction charging for smartphones',
      'Paddle shifters',
      'Rain sensor',
      'Right-hand drive',
      'Roof rack',
      'Ski bag',
      "Smoker's package",
      'Sports package',
      'Sports suspension',
      'Start-stop system',
      'Tinted windows',
      'Winter package',
    ],
    source: 'reference/android/filter-options/extras-0.xml',
  },
  headlights: {
    mode: 'multiple',
    includeAny: false,
    options: ['Xenon headlights', 'Bi-xenon headlights', 'LED headlights', 'Laser headlights'],
    source: 'reference/android/filter-options/headlights-0.xml',
  },
  headlightExtras: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Fog lamps',
      'Glare-free high beam headlights',
      'Headlight washer system',
      'Light sensor',
    ],
    source: 'reference/android/filter-options/headlightExtras-0.xml',
  },
  airbags: {
    mode: 'single',
    includeAny: true,
    options: [
      'Driver Airbag',
      'Front Airbags',
      'Front and Side Airbags',
      'Front and Side and More Airbags',
    ],
    source: 'reference/android/filter-options/airbags-0.xml',
  },
  wheels: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'All season tyres',
      'Alloy wheels',
      'Steel wheels',
      'Summer tyres',
      'Tyre pressure monitoring',
      'Winter tyres',
    ],
    source: 'reference/android/filter-options/wheels-0.xml',
  },
  breakdown: {
    mode: 'multiple',
    includeAny: false,
    options: ['Spare tyre', 'Emergency tyre', 'Emergency tyre repair kit'],
    source: 'reference/android/filter-options/breakdown-0.xml',
  },
  parking: {
    mode: 'multiple',
    includeAny: false,
    options: ['360° camera', 'Camera', 'Rear', 'Front', 'Self-steering systems'],
    source: 'reference/android/filter-options-remaining/parking-0.xml',
  },
  seatFeatures: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Arm rest',
      'Electric backseat adjustment',
      'Electric seat adjustment',
      'Eletric seat adjustment with memory function',
      'Fold flat passenger seat',
      'Heated rear seats',
      'Heated seats',
      'Lumbar support',
      'Massage seats',
      'Seat ventilation',
      'Sport seats',
    ],
    source: 'reference/android/filter-options-remaining/seatFeatures-0.xml',
  },
  roof: {
    mode: 'multiple',
    includeAny: false,
    options: ['Folding roof', 'Panoramic roof', 'Sunroof'],
    source: 'reference/android/filter-options-remaining/roof-0.xml',
  },
  daylight: {
    mode: 'multiple',
    includeAny: false,
    options: ['LED running lights'],
    source: 'reference/android/filter-options-remaining/daylight-0.xml',
  },
  coupling: {
    mode: 'single',
    includeAny: true,
    options: [
      'Fixed, detachable or swiveling',
      'Detachable or swiveling',
      'Trailer coupling, swiveling',
    ],
    source: 'reference/android/filter-options-remaining/coupling-0.xml',
  },
  unbraked: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '300', '800'],
    source: 'reference/android/filter-options-remaining/unbraked-0.xml',
  },
  braked: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '500', '3500'],
    source: 'reference/android/filter-options-remaining/braked-0.xml',
  },
  support: {
    mode: 'range',
    includeAny: true,
    options: ['Support load from (kg)', 'From', 'To', '50', '200'],
    source: 'reference/android/filter-options-remaining/support-0.xml',
  },
  drive: {
    mode: 'single',
    includeAny: true,
    options: ['All wheel drive', 'Front wheel drive', 'Rear wheel drive'],
    source: 'reference/android/filter-options-remaining/drive-0.xml',
  },
  bending: {
    mode: 'multiple',
    includeAny: false,
    options: ['Adaptive lighting', 'Adaptive cornering lights'],
    source: 'reference/android/filter-options-remaining/bending-0.xml',
  },
  cruise: {
    mode: 'single',
    includeAny: true,
    options: ['Adaptive Cruise Control'],
    source: 'reference/android/filter-options-remaining/cruise-0.xml',
  },
  radio: {
    mode: 'multiple',
    includeAny: false,
    options: ['Tuner/radio', 'DAB radio'],
    source: 'reference/android/filter-options-remaining/radio-0.xml',
  },
  material: {
    mode: 'multiple',
    includeAny: false,
    options: [
      'Alcantara',
      'Cloth',
      'Imitation leather',
      'Part leather',
      'Full leather',
      'Velour',
      'Other',
    ],
    source: 'reference/android/filter-options-remaining/material-0.xml',
  },
  interiorColor: {
    mode: 'multiple',
    includeAny: false,
    options: ['beige', 'black', 'blue', 'brown', 'grey', 'red', 'Other'],
    source: 'reference/android/filter-options-remaining/interiorColor-0.xml',
  },
  weight: {
    mode: 'range',
    includeAny: true,
    options: ['Weight (kg)', 'From', 'To', '400', '3000'],
    source: 'reference/android/filter-options-remaining/weight-0.xml',
  },
  cylinders: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '3', '12', '4', '6', '8', '10'],
    source: 'reference/android/filter-options-remaining/cylinders-0.xml',
  },
  tank: {
    mode: 'range',
    includeAny: true,
    options: ['Tank capacity (l)', 'From', 'To', '30', '150'],
    source: 'reference/android/filter-options-remaining/tank-0.xml',
  },
  online: {
    mode: 'single',
    includeAny: true,
    options: ['1 Day', '3 Days', '7 Days', '14 Days'],
    source: 'reference/android/filter-options-remaining/online-0.xml',
  },
  listing: {
    mode: 'multiple',
    includeAny: false,
    options: ['Ads with pictures', 'Ads with video', 'Discount offers'],
    source: 'reference/android/filter-options-remaining/listing-0.xml',
  },
  seller: {
    mode: 'single',
    includeAny: true,
    options: ['Dealer', 'Private seller', 'Company vehicles'],
    source: 'reference/android/filter-options-remaining/seller-0.xml',
  },
  commercial: {
    mode: 'single',
    includeAny: true,
    options: ['Only show', 'Do not show'],
    source: 'reference/android/filter-options-remaining/commercial-0.xml',
  },
  vat: {
    mode: 'single',
    includeAny: true,
    options: ['VAT reclaimable', 'VAT not reclaimable'],
    source: 'reference/android/filter-options-remaining/vat-0.xml',
  },
  rating: {
    mode: 'range',
    includeAny: true,
    options: ['From', 'To', '3', '5', '4'],
    source: 'reference/android/filter-options-remaining/rating-0.xml',
  },
  consumption: {
    mode: 'single',
    includeAny: true,
    options: [
      '3 l/100 km',
      '5 l/100 km',
      '6 l/100 km',
      '7 l/100 km',
      '8 l/100 km',
      '9 l/100 km',
      '10 l/100 km',
      '12 l/100 km',
      '15 l/100 km',
    ],
    source: 'reference/android/filter-options-remaining/consumption-0.xml',
  },
  emission: {
    mode: 'single',
    includeAny: true,
    options: [
      'Euro 1',
      'Euro 2',
      'Euro 3',
      'Euro 4',
      'Euro 5',
      'Euro 6',
      'Euro 6c',
      'Euro 6d-TEMP',
      'Euro 6d',
      'Euro 6e',
      'Euro 7',
    ],
    source: 'reference/android/filter-options-remaining/emission-0.xml',
  },
  sticker: {
    mode: 'single',
    includeAny: true,
    options: ['1 (None)', '2 (Red)', '3 (Yellow)', '4 (Green)'],
    source: 'reference/android/filter-options-remaining/sticker-0.xml',
  },
  maintenance: {
    mode: 'multiple',
    includeAny: false,
    options: ['Full Service History', 'New service', 'Non-smoker vehicle', 'Warranty'],
    source: 'reference/android/filter-options-remaining/maintenance-0.xml',
  },
  damaged: {
    mode: 'single',
    includeAny: true,
    options: ['Do not show', 'Show only'],
    source: 'reference/android/filter-options-remaining/damaged-0.xml',
  },
  owners: {
    mode: 'single',
    includeAny: true,
    options: ['Up to 1', 'Up to 2', 'Up to 3', 'Up to 4'],
    source: 'reference/android/filter-options-remaining/owners-0.xml',
  },
  inspection: {
    mode: 'single',
    includeAny: true,
    options: ['New', '3 months', '6 months', '9 months', '12 months', '18 months'],
    source: 'reference/android/filter-options-remaining/inspection-0.xml',
  },
  programme: {
    mode: 'single',
    includeAny: true,
    options: [
      'Alfa Romeo Certified',
      'Aston Martin Timeless',
      'BMW Premium Selection',
      'Certified by Bentley',
      'CUPRA Approved',
      'DS Certified',
      'Ferrari Approved',
      'Hyundai Promise',
      'Jaguar APPROVED',
      'Kia Zertifizierte Gebrauchtwagen',
      'Land Rover APPROVED',
      'MINI NEXT',
      'Nissan Intelligent Choice',
      'Porsche Approved',
      'Rolls-Royce Provenance',
      'SEAT Zertifizierte Gebrauchtwagen',
      'Selezione Lamborghini Certified Pre-Owned',
      'Škoda plus',
      'SPOTICAR',
      'Toyota Approved Used Cars',
      'VOLVO SELEKT',
      'VW NFZ Zertifizierte Gebrauchtwagen',
      'VW PKW Zertifizierte Gebrauchtwagen',
    ],
    source: 'reference/android/filter-options-remaining/programme-0.xml',
  },
  registration: {
    mode: 'multiple',
    includeAny: false,
    options: ['Classic', 'Demonstration Vehicle', "Employee's Car", 'Pre-Registration'],
    source: 'reference/android/filter-options-remaining/registration-0.xml',
  },
};
