export const dealerProfile = {
  name: 'Любо кар',
  shortName: 'LUBO CAR',
  slug: 'lyubo-car',
  sourcePrefix: 'LC',
  observedAt: '2026-09-09',
  city: 'София',
  region: 'Суходол',
  address: 'ул. Околовръстен път, около 300 м след светофара на Суходол, посока Люлин',
  phoneDisplay: '0897 500 500',
  phoneHref: 'tel:+359897500500' as const,
  phoneE164: '+359897500500',
  secondaryPhoneDisplay: '0895 454 575 / 0899 620 620',
  secondaryPhoneE164: '+359895454575',
  hoursLabel: 'Всеки ден 09:00–18:00 според актуалната контактна страница и текущите обяви. По-стари/отделни текстове с 08:00 не се използват.',
  coordinates: { latitude: 42.6996, longitude: 23.2305 },
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=LUBO%20CAR%20%D0%A1%D1%83%D1%85%D0%BE%D0%B4%D0%BE%D0%BB%20%D0%A1%D0%BE%D1%84%D0%B8%D1%8F',
  mapsEmbedUrl: 'https://maps.google.com/maps?q=42.6996,23.2305&z=16&output=embed',
  sourceInventory: 'https://lubocar.mobile.bg/',
  sourceContacts: 'https://lubocar.mobile.bg/contacts',
  sampleCount: 8,
  accent: '#d72632',
  logo: '/brand/lubo-car-ink.svg' as const,
  logoInk: '/brand/lubo-car-ink.svg',
  logoWhite: '/brand/lubo-car-white.svg',
  tagline: 'Употребявани автомобили в Суходол, София. Датираните обяви са ориентир; наличността и огледът се потвърждават по телефона.',
  inspectionSummary: 'Текущите обяви посочват възможност за тест драйв. Уточнете конкретния автомобил, адреса и часа по телефона; демото не гарантира тази услуга.',
  provenanceSummary: 'Твърденията за произход, сервизна история, техническо състояние и обслужване в обявите са seller claims и не са независима проверка.',
  financingSummary: 'Текущите обяви споменават лизинг/изплащане, но този демо проект не възпроизвежда срокове за одобрение, отстъпки, проценти или кредитни условия. Потвърдете всяка финансова оферта директно.',
  financingShort: 'Условията се потвърждават индивидуално',
  socialLinks: {} as const,
} as const;
