import fs from 'node:fs/promises';
const root='J:/cars/clients/excellent-cars';
const results=JSON.parse(await fs.readFile(`${root}/qa-final/results.json`));
const builds=JSON.parse(await fs.readFile(`${root}/qa-final/build-results.json`));
const focused=JSON.parse(await fs.readFile(`${root}/qa-final/focused-results.json`));
if(results.length!==3||results.some(r=>!r.pass)||builds.length!==5||builds.some(r=>r.exitCode!==0)||!focused.length||focused.some(r=>!r.pass))throw Error('Final acceptance requires all expected checks passing');
if(results.some(r=>r.routes.some(route=>route.consoleErrors?.length||route.pageErrors?.length)))throw Error('Review console/page errors before final acceptance');
for(const r of results){
 const file=`${root}/${r.template}/.client/project.json`,m=JSON.parse(await fs.readFile(file));
 m.state='local-demo-verified';m.offeredHomes=m.availableHomes.filter(h=>h.id==='main');
 m.localPreviewUrl=`http://127.0.0.1:${r.port}${r.template==='modern'?'/cars':'/'}`;
 m.qa={...m.qa,desktop:true,mobile:true,identity:true,contactPath:true,verifiedAt:new Date().toISOString(),widths:[390,1440],routeChecks:r.routes.length,interactionPasses:r.interactions.length,evidence:`${root}/qa-final/${r.client}/${r.template}/result.json`,build:r.template==='auto-best'?'qa-final/auto-validate.log: current architecture, assets, Svelte check and build passed':'qa-final/build-results.json: current framework check and production build passed',visualReview:'Viewport screenshots manually inspected; current logo contrast and contact destinations corrected.'};
 m.knownLimits=['Local prospect demo only; no public preview or CRM registration.','Stock and prices are the dated 2026-09-07 source snapshot, not a live feed.','No enquiry delivery, private account, chat backend or live import-feed integration verified.','Retained sample admin/team/partner routes are template demo surfaces, not evidence of real staff or partnerships.'];
 if(r.template==='modern')m.knownLimits.push('Gallery opens, changes photos and closes; inherited keyboard focus restoration is imperfect (mobile returns to body, desktop to a different gallery trigger).');
 await fs.writeFile(file,JSON.stringify(m,null,2)+'\n');
}
const report=`# Excellent Cars — final local verification\n\nVerified 2026-09-08. All three requested variants pass the local review flow at 390 and 1440px: 28 route/viewport checks and 6 interaction passes.\n\n| Variant | Local entry | Framework evidence |\n| --- | --- | --- |\n| Auto Best | http://127.0.0.1:6621/ | Current qa-final/auto-validate.log: architecture/assets/Svelte check/build pass |\n| Modern | http://127.0.0.1:6622/cars | Current qa-final/modern-typecheck.log and modern-build.log, exit 0 |\n| Carwow | http://127.0.0.1:6623/ | Current qa-final/carwow-check-final.log and carwow-build-final.log, exit 0 |\n\nChecks cover entry, inventory, one real detail, contact, about/imports, mobile menu Escape/focus return, filter dismissal, search, detail navigation, gallery where offered, and enquiry/phone destinations. The current checked pages have no broken images, horizontal overflow, uncaught page errors or console errors. See results.json and variant screenshots here. focused-results.json additionally verifies the financing phone, vehicle-detail map, static redirects, manifest, Modern lightbox and corrected budget filters. numeric-stock.json matches all 16 parsed prices and mileages against the captured stock.\n\nFinal repairs: readable existing logos on dark/colored headers, client logo in the retained chat button, unconfigured social placeholders hidden, financing phone and detail map bound to Excellent data, the inherited sample-profile map corrected, stale proposal/manifest/SVG identity removed, and non-breaking spaces parsed correctly for numeric prices and mileages. Svelte autofixer found no issues in edited components. React changes preserve existing rendering and state boundaries. No template layout, route structure, dependencies or backend was replaced.\n\nKnown accessibility gap: the Modern lightbox opens, changes photos and closes, but focus returns to the page body on mobile or a different gallery trigger on desktop. Menu Escape/focus return passes. This retained source interaction is recorded for a separate template accessibility fix.\n\nAll three local review servers remain available; publicUrl is null. Stock/photos retain captured source provenance. Forms, chat, account functions and live import feeds are not delivery-certified. Sample admin/team/partner routes remain declared template demonstrations. No external enquiry, deployment, commit, push or CRM change was made.\n`;
await fs.writeFile(`${root}/qa-final/FINAL.md`,report);
await fs.appendFile(`${root}/CLIENT.md`,'\n## Final verification — 2026-09-08\n\nAll three local variants verified at 390/1440px; 28 route states and 6 interaction passes. Current fixes, build logs, screenshots, contact checks and remaining demo limits are recorded in [qa-final/FINAL.md](qa-final/FINAL.md). Review servers 6621/6622/6623 remain running, superseding the earlier stopped/queued runtime notes. No public deployment or message delivery is implied.\n');
await fs.writeFile(`${root}/BUILD-STATUS.md`,report);
console.log('Excellent metadata finalized');
