import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/autolife';const stock=JSON.parse(await fs.readFile(root+'/stock.json'));const updates=[];
const fixes=[['Day &amp; Night','Аутолайф'],['https://www.facebook.com/61566304063141/','https://autolife.mobile.bg/'],['https://www.instagram.com/daynight.auto.plovdiv/','https://autolife.mobile.bg/'],['Понеделник - Събота: 9:00 - 18:00','Работно време: уточнете по телефона'],['Понеделник – Събота: 9:00 – 18:00','Работно време: уточнете по телефона'],['Понеделник - Събота: 09:00 - 18:00','Работно време: уточнете по телефона'],['09:00 – 18:00','По телефона'],['09:00 - 18:00','По телефона'],['In-house leasing','Leasing enquiries'],['Import on request','Vehicle enquiry'],['Внос · Условия за лизинг','Публикувани обяви · Огледи'],['автомобили, внос по заявка, условия за лизинг, бартер и огледи с предварителна уговорка','публикувани автомобили и контакт за оглед'],['Автомобили, внос и условия за лизинг','Автомобили и запитвания'],['Подбрани автомобили, внос и условия за лизинг','Подбрани автомобили и запитвания'],['Подбираме автомобили според вашите критерии, организираме оглед в {brand.city} и обсъждаме внос, бартер или условия за лизинг директно с екипа.','Разгледайте публикуваните автомобили и се обадете за наличност и посещение в {brand.city}.'],['Да — можем да обсъдим търсене на автомобил според критерии за модел, бюджет и оборудване.','Обадете се, за да обсъдите търсения модел. Внос по поръчка не е потвърдена услуга.'],['Можем да съдействаме с проверка на история, документи и техническо състояние преди финално решение.','Преди покупка поискайте документи, история и независима техническа проверка.'],['Проверяваме автомобила, продавача и условията в обявата.','Обсъдете конкретния автомобил и условията в обявата.'],['Координираме покупката, доставката и предаването в България.','Вносът и доставката не са потвърдени услуги. Попитайте по телефона.'],['Организираме вноса','Уточнете възможностите'],['Изпратете обява или опишете желания автомобил и получете конкретни варианти за внос от Аутолайф.','Разгледайте обявите или попитайте по телефона за търсения автомобил.'],['Един телефон за автомобил, внос или финансиране. Шоурум в Тополи.','Телефон за наличност и оглед. ГП4, разклон за Тополи.'],['От наличен автомобил до внос по заявка — екипът ни е на една връзка разстояние.','Обадете се за актуална наличност, цена и работно време.'],['Аутолайф представя собствени наличности и услуги за внос, лизинг и изкупуване на автомобили.','Аутолайф публикува обяви за автомобили. Услуги извън продажбите се уточняват по телефона.'],['Аутолайф ще уточни заявката за внос и доставка до България.','Вносът и доставката не са потвърдени услуги на Аутолайф.'],['Разгледайте услугата ни за внос от Китай и поискайте конкретна оферта за автомобил.','Вносът от Китай не е потвърдена услуга. Разгледайте публикуваните автомобили.'],['Варна — автомобили в наличност, внос по заявка и условия за лизинг.','Варна — публикувани автомобили и контакт за оглед.']];
async function walk(dir,variant){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.turbo'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p,variant);else if(/\.(tsx?|svelte|css|html)$/.test(e.name)&&!e.name.includes('.test.')&&!e.name.includes('.spec.')){let s=await fs.readFile(p,'utf8'),t=s;for(const [a,b]of fixes)t=t.replaceAll(a,b);t=t.replaceAll('/brand/daynight-logo-generated.png','/assets/autolife/wordmark.svg');
// Replace identifiable stock, portraits and showroom source media; retain generic studio cutouts as decorative only.
t=t.replace(/\/assets\/images\/lead\/day-night-stock-\d+\.webp/g,(_)=>stock[(p.length)%stock.length].images[0]);
t=t.replace(/\/assets\/[^'"`\s<>)]+(?:showroom|team-sales|team-evaluation|team-documents|team-customer)[^'"`\s<>)]+\.(?:webp|jpg|png)/g,'/assets/autolife/cover.jpg');
if(/Hero\.svelte$/.test(p)&&variant==='auto-best')t=t.replaceAll('/assets/images/lead/day-night-home-black-v1.webp','/assets/autolife/cover.jpg').replaceAll('/assets/images/lead/day-night-home-hero-v3.webp','/assets/autolife/cover.jpg');
if(p.endsWith('app.css')&&variant==='auto-best')t=t.replace('#c40101','#a46d24').replace('#a90000','#81521b');if(p.endsWith('tokens.css')&&variant==='carwow')t=t.replace('#d71920','#a46d24').replace('#a50f15','#81521b').replace('#f5c542','#d5af51');
if(t!==s){await fs.writeFile(p,t);updates.push(p);}}}}
for(const v of ['auto-best','carwow'])await walk(root+'/'+v+'/src',v);await walk(root+'/modern/apps/web','modern');await walk(root+'/modern/packages/marketplace-ui','modern');
for(const v of ['auto-best','carwow']){const file=root+'/'+v+'/src/app.html';let s=await fs.readFile(file,'utf8');s=s.replace(/href="%sveltekit.assets%\/favicon.ico"/g,'href="%sveltekit.assets%/assets/autolife/wordmark.svg"');await fs.writeFile(file,s);}
// Preserve Auto Best's strict exact-count asset guard using this copy's actual source inventory.
const base=root+'/auto-best',source=[];async function files(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await files(p));else out.push(p)}return out;}
const refs=new Set(['/favicon.ico']);const refRe=/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi;
for(const p of await files(base+'/src'))if(/\.(css|html|js|svelte|ts)$/.test(p)){const s=await fs.readFile(p,'utf8');for(const m of s.matchAll(refRe))refs.add(m[0]);}
const retired=[];for(const p of await files(base+'/static')){const rel='/'+path.relative(base+'/static',p).replaceAll('\\','/');if(!refs.has(rel)){retired.push(rel);await fs.unlink(p)}}
let guard=await fs.readFile(base+'/scripts/check-assets.mjs','utf8');guard=guard.replace(/const guardedMediaCount = \d+;/,`const guardedMediaCount = ${refs.size};`);await fs.writeFile(base+'/scripts/check-assets.mjs',guard);
await fs.writeFile(root+'/evidence/content-media-pass.json',JSON.stringify({updates,retiredFromAutoStatic:retired,guardedMediaCount:refs.size,decorative:'Source studio cutouts, generic automotive editorial imagery, OEM logos and illustrations retained as decorative. Not dealer stock.'},null,2));console.log('Content/media pass',updates.length,'files; Auto static',refs.size);
