import fs from 'node:fs/promises';
const root='J:/cars/clients/autolife', cards=JSON.parse(await fs.readFile(root+'/evidence/stock.json')).cards;
const picks=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]; const stock=[],downloads=[];
for(const [n,k] of picks.entries()){const c=cards[k],raw=c.parts.find(x=>x.cls==='params').text,top=c.parts.find(x=>x.cls==='zaglavie').text; const id=c.url.match(/obiava-(\d+)/)[1];const year=Number(raw.match(/(?:19|20)\d{2}/)[0]),mileageKm=Number(raw.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),priceEur=Number(top.match(/([\d\s]+)\s*€/)[1].replace(/\s/g,''));
const make=c.title.startsWith('Mercedes-Benz')?'Mercedes-Benz':c.title.split(' ')[0],model=c.title.slice(make.length).trim().split(' ').slice(0,2).join(' '),title=make+' '+model;
const images=c.images.slice(0,4).map((url,i)=>{const file=`vehicle-${String(n+1).padStart(2,'0')}-${i+1}.webp`;downloads.push({url:url.replace(/(\/photosorg\/\d+\/\d+\/)/,'$1big1/'),file,sourcePage:c.url});return '/assets/autolife/'+file});
stock.push({id,title,fullTitle:c.title,make,model,year,mileageKm,priceEur,fuel:raw.includes('Дизелов')?'Дизел':raw.includes('Хибриден')?'Хибрид':raw.includes('Бензинов')?'Бензин':'Електрически',transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',body:raw.includes('Джип')?'SUV':raw.includes('Хечбек')?'Hatchback':raw.includes('Комби')?'Wagon':raw.includes('Купе')?'Coupe':raw.includes('Ван')?'Van':'Sedan',bodyLabel:raw.match(/(Джип|Хечбек|Комби|Купе|Ван|Седан)$/)?.[0]||'Автомобил',powerHp:Number(raw.match(/(\d+)\s*к\.с\./)?.[1]||0),engineCc:Number(raw.match(/(\d+)\s*куб\.см/)?.[1]||0),color:raw.match(/км\s+(.+?)\s+(?:Дизелов|Бензинов|Хибриден)/)?.[1]||'',date:raw.match(/^(.+?г\.)/)[1],vat:top.includes('Не се начислява')?'Не се начислява ДДС':'Виж оригиналната обява',sourceUrl:c.url,images,features:c.parts.find(x=>x.cls==='info').text.replace(/^Особености - /,'').split(', ').slice(0,35),description:`${c.title}, ${year} г., ${mileageKm.toLocaleString('bg-BG')} км. Публикувана обява на Аутолайф. Потвърдете наличността, оборудването и цената по телефона.`,rawFacts:raw});}
const contact=JSON.parse(await fs.readFile(root+'/evidence/contact.json'));for(const [kind,pattern] of [['logo','houseslogos'],['cover','housespicts']]) {const url=contact.images.find(i=>i.src.includes(pattern)).src;downloads.push({url,file:kind+'.jpg',sourcePage:contact.url});}
for(let i=0;i<downloads.length;i+=4) await Promise.all(downloads.slice(i,i+4).map(async d=>{const r=await fetch(d.url);if(!r.ok)throw Error(r.status+' '+d.url);await fs.writeFile(root+'/assets/'+d.file,Buffer.from(await r.arrayBuffer()));}));
await fs.writeFile(root+'/stock.json',JSON.stringify(stock,null,2));await fs.writeFile(root+'/assets/provenance.json',JSON.stringify({capturedAt:new Date().toISOString(),note:'Public dealer media preserved with original watermarks; local prospect review, no new rights determination.',downloads},null,2)); console.log(stock.map(v=>[v.title,v.year,v.priceEur,v.images.length]));
