// Generated by Cars native configuration adapter; change dealer.json, not this file.
export const carsLocale = {
  "schemaVersion": 1,
  "dealerId": "pm-select-automotive",
  "defaultLocale": "bg",
  "enabledLocales": [
    "bg",
    "en"
  ],
  "dealerCountry": "BG",
  "inventoryCurrency": "EUR"
} as const;
