import fs from 'node:fs/promises';import path from 'node:path';
const root=import.meta.dirname,facts=JSON.parse(await fs.readFile(root+'/business-facts.json')),stock=JSON.parse(await fs.readFile(root+'/stock.json'));
async function walk(dir){let out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit','build'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
async function edit(rel,fn){const p=root+'/'+rel,s=await fs.readFile(p,'utf8');await fs.writeFile(p,fn(s.replaceAll('\r\n','\n')))}
for(const v of ['auto-best','carwow'])for(const p of await walk(root+'/'+v+'/src')){if(!/\.(svelte|ts|css|html)$/.test(p))continue;await edit(path.relative(root,p),s=>s.replaceAll('Понеделник - Събота: 9:00 - 18:00','За работно време се обадете предварително.').replaceAll('Делнични дни: 9:00 - 18:00 · Неделя: по уговорка','За работно време се обадете предварително.').replaceAll('Отзиви от клиенти','Услуги и информация').replaceAll('Мнения от клиенти','Услуги и информация').replace(/<a\b[^>]*(?:href="https:\/\/www\.(?:facebook\.com\/61566304063141\/|instagram\.com\/daynight\.auto\.plovdiv\/)"|\{\.\.\.youtubeLink\}|href=\{youtubeChannelUrl\})[^>]*>[\s\S]*?<\/a>/g,'').replace(/\/assets\/images\/lead\/day-night-stock-\d+\.webp/g,stock[0].images[0]).replace(/\/assets\/images\/lead\/day-night-(?:about-kristian-v1-light|contact-kristian-phone-v1-light|about-showroom-v1-light|showroom-color-v1|portrait-color-v1|contact-hero-v2)\.webp/g,stock[13].images[0]).replace(/\/assets\/daynight-auto-v3\/[^'"`\s]+(?:showroom|portrait|team|staff|kristian)[^'"`\s]*\.(?:webp|jpg|png)/g,stock[13].images[0]));}
for(const file of ['Header.svelte'])await edit('auto-best/src/lib/components/layout/'+file,s=>s.replace(/<a \{\.\.\.\{ href: brand\.(?:instagramUrl|youtubeUrl|facebookUrl) \}\}[^>]*>[\s\S]*?<\/a>/g,''));
for(const file of ['AboutHero.svelte','ContactIntent.svelte'])await edit('auto-best/src/lib/components/company/'+file,s=>s.replace(/\{#each (socialProfiles|socialPlatforms) as /g,'{#each $1.filter(item => item.href) as '));
await edit('auto-best/src/lib/data/videos.ts',s=>s.slice(0,s.indexOf('// Selected'))+'export const featuredVideos: readonly FeaturedVideo[] = [];\n');
await edit('auto-best/src/lib/data/demo-content.ts',s=>s.replace(/export const demoTeamMembers: DemoTeamMember\[\] = \[[\s\S]*?\n\];/,'export const demoTeamMembers: DemoTeamMember[] = [];').replace('Примерни профили за визуален преглед. Имената и снимките ще бъдат заменени с реалния екип.','За въпроси и оглед се свържете с Аутомаркет Варна на 0886 424 400.'));
await edit('carwow/src/lib/data/daynight-vehicles.ts',s=>s.replace("match[0].replaceAll(' ', '')","match[0].replace(/\\s/g, '')"));
await edit('carwow/src/lib/data/daynight-videos.ts',()=>`export const youtubeChannelUrl = 'https://automarket.mobile.bg/';\nexport const homeVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,thumbnail:v.images[0],url:v.sourceUrl,duration:''})),null,2)} as const;\n`);
await edit('carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte',s=>s.replaceAll('Аутомаркет Варна в YouTube','Разгледайте отблизо').replaceAll('Всички видеа','Всички обяви').replace(/<span class="home-videos__title">[\s\S]*?<\/span>/,'<span class="home-videos__title">Разгледайте отблизо</span>').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noopener noreferrer"><img src={video.thumbnail} alt={video.title} style="width:100%;height:100%;object-fit:cover" loading="lazy" /></a>'));
// Official black/red wordmark palette at existing token boundaries.
await edit('auto-best/src/app.css',s=>s.replace('--dn-red: #c40101','--dn-red: #a50f15').replace('--dn-red-hover: #a90000','--dn-red-hover: #7e0b10'));
await edit('carwow/src/lib/styles/tokens.css',s=>s.replace('--sa-yellow: #f5c542','--sa-yellow: #f3f3f3').replace('--sa-red: #d71920','--sa-red: #a50f15'));
await edit('auto-best/src/app.html',s=>s.replace('href="/favicon.ico"',`href="${facts.logo}"`));await edit('carwow/src/app.html',s=>s.replace(/href="[^"\n]*(?:favicon|icon)[^"\n]*"/g,`href="${facts.logo}"`));
// Keep the existing asset gate strict: inventory only files actually retained by source.
const src=await walk(root+'/auto-best/src'),refs=new Set();for(const p of src){if(!/\.(css|html|js|svelte|ts)$/.test(p))continue;const s=await fs.readFile(p,'utf8');for(const m of s.matchAll(/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi))refs.add(m[0]);}
const unused=[];for(const p of await walk(root+'/auto-best/static')){const pub='/'+path.relative(root+'/auto-best/static',p).split(path.sep).join('/');if(!refs.has(pub)){const dest=root+'/evidence/unused-auto-best-assets'+pub;await fs.mkdir(path.dirname(dest),{recursive:true});await fs.rename(p,dest);unused.push(pub)}}
await edit('auto-best/scripts/check-assets.mjs',s=>s.replace(/const guardedMediaCount = \d+;/,`const guardedMediaCount = ${refs.size};`));await fs.writeFile(root+'/evidence/asset-retention.json',JSON.stringify({referenced:refs.size,archived:unused},null,2));
console.log('content corrected, strict asset inventory',refs.size);
