import fs from 'node:fs/promises';import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const root=import.meta.dirname,variant=process.argv[2],modern=variant==='modern',base=`http://127.0.0.1:${modern?6657:6658}`,results=[],b=await chromium.launch({headless:true,channel:'chrome'});
try{for(const width of [390,1440]){const p=await b.newPage({viewport:{width,height:900}});p.setDefaultTimeout(10000);const r={width,errors:[]};p.on('pageerror',e=>r.errors.push(String(e)));try{await p.goto(base+(modern?'/cars':'/inventory'),{waitUntil:'networkidle',timeout:60000});
if(width===390){const menu=p.getByRole('button',{name:'Меню',exact:true});if(await menu.count()){await menu.click();await p.waitForTimeout(150);r.menuOpened=true;await p.screenshot({path:root+`/evidence/${variant}-menu-${width}.png`});await p.keyboard.press('Escape');r.menuDismissed=await p.locator('[role="dialog"]:visible,dialog[open]').count()===0;}
if(modern){await p.getByRole('button',{name:'Отвори филтрите',exact:true}).click();r.filterOpened=await p.getByRole('dialog').isVisible();await p.screenshot({path:root+`/evidence/${variant}-filters-${width}.png`});await p.keyboard.press('Escape');await p.waitForTimeout(200);r.filterDismissed=await p.getByRole('dialog').count()===0;await p.getByRole('button',{name:'Търси 16 автомобила',exact:true}).click();}else{await p.getByRole('button',{name:'Отвори търсене',exact:true}).click();}}
const input=p.locator('input:visible').filter({hasNot:p.locator('[type=hidden]')}).first();await input.fill('Ford');await input.press('Enter');await p.waitForTimeout(500);if(!modern&&width===390){const apply=p.getByRole('button',{name:/Покажи.*автомобил|Покажи резултат|Виж.*автомобил/}).filter({visible:true}).first();if(await apply.count())await apply.click();}await p.waitForTimeout(350);r.searchUrl=p.url();r.fordResult=(await p.locator('body').innerText()).includes('Ford');await p.screenshot({path:root+`/evidence/${variant}-search-${width}.png`});
await p.goto(base+(modern?'/bg/listing/automarket-11785576029711434':'/inventory/ford-focus-1-6d-711434'),{waitUntil:'networkidle'});r.detailUrl=p.url();r.phones=await p.locator('a[href^="tel:"]').evaluateAll(es=>[...new Set(es.map(e=>e.getAttribute('href')))]);if(!modern){const photo=p.getByRole('button',{name:width===390?'Снимка 2':'Покажи снимка 2',exact:true});await photo.click();r.galleryButtonSelected=true;}
const enquiry=p.locator('a:visible').filter({hasText:/Запитване|Заяви оглед|Заявете оглед|Попитай/}).first();if(await enquiry.count()){r.enquiryHref=await enquiry.getAttribute('href');await enquiry.click();await p.waitForTimeout(300);r.enquiryUrl=p.url();r.enquiryDialog=await p.locator('[role="dialog"]:visible,dialog[open]').count();await p.screenshot({path:root+`/evidence/${variant}-enquiry-${width}.png`});await p.keyboard.press('Escape');}else{r.enquiryPhoneVerified=r.phones.some(x=>x.includes('886424400'));}
}catch(e){r.failure=String(e)}results.push(r);console.log(JSON.stringify(r));await fs.writeFile(root+`/evidence/${variant}-interactions.json`,JSON.stringify(results,null,2));await p.close();}}finally{await b.close();}
