import fs from 'node:fs/promises';import path from 'node:path';
const root=import.meta.dirname, stock=JSON.parse(await fs.readFile(root+'/stock.json'));
const facts={name:'Аутомаркет Варна',shortName:'Аутомаркет',latinName:'AUTOMARKET',city:'Варна',country:'България',phoneDisplay:'0886 424 400',phoneHref:'tel:+359886424400',email:'',address:'бул. Цар Освободител — 300 м вдясно след Дом на Камиона, посока летището',hours:['За работно време и оглед се обадете предварително.'],stockUrl:'https://automarket.mobile.bg/',website:null,socialLinks:{},accent:'#a50f15',accentDark:'#7e0b10',logo:'/assets/automarket/cover.png',showroom:null,stockCount:stock.length,stockSnapshotDate:'2026-09-07',stockNote:'Представителни обяви към 07.09.2026 г. Потвърдете наличността и условията по телефона.',services:['Продажба на употребявани автомобили','Внос от ЕС и доставка по поръчка','Бартер с доплащане','Съдействие при регистрация и транзитни номера','Транспорт в страната','Запитване за лизинг чрез финансови партньори'],sources:['https://automarket.mobile.bg/','https://automarket.mobile.bg/contacts','https://automarket.mobile.bg/about'],limitations:['Няма публикувано работно време, имейл или потвърден социален профил.','Логото е оригинално, но с ниска резолюция; не е налична отделна снимка на автокъщата.','Картата търси по име и описание; точен географски пин не е потвърден.']};
facts.mapsUrl='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(facts.name+', '+facts.address);facts.mapsEmbedUrl='https://maps.google.com/maps?q='+encodeURIComponent(facts.name+' '+facts.city+' Цар Освободител Дом на Камиона')+'&output=embed';await fs.writeFile(root+'/business-facts.json',JSON.stringify(facts,null,2));
const changed=[];async function edit(rel,fn){const p=root+'/'+rel,s=await fs.readFile(p,'utf8'),v=fn(s.replaceAll('\r\n','\n'));if(v!==s){await fs.writeFile(p,v);changed.push(rel)}}
async function walk(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.git','.svelte-kit','build'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
const rep=[['DAY NIGHT AUTO GROUP',facts.name],['Day &amp; Night Auto Group',facts.name],['Day & Night Auto Group',facts.name],['Day Night Auto Group',facts.name],['Day Night Auto',facts.name],['Day & Night',facts.shortName],['Ден и Нощ Ауто Груп',facts.name],['087 982 4625',facts.phoneDisplay],['0877 733 110',facts.phoneDisplay],['0877733110','0886424400'],['+359877733110','+359886424400'],['+359879824625','+359886424400'],['daynight.mobile.bg','automarket.mobile.bg'],['daynightautogroup.bg','automarket.mobile.bg'],['Собствен лизинг','Запитване за лизинг'],['собствен лизинг','лизинг чрез партньори'],['Премиум автомобили','Употребявани автомобили'],['премиум автомобили','употребявани автомобили'],['ул. „Атанас Манчев“ 18, Студентски град',facts.address],['Студентски град, ул. Атанас Манчев 18',facts.address],['ул. Атанас Манчев 18',facts.address],['Студентски град','Владислав Варненчик'],['София','Варна'],['Пловдив','Варна']];
for(const variant of ['auto-best','carwow','modern']){const dirs=variant==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo']:['src'];for(const dir of dirs)for(const p of await walk(root+'/'+variant+'/'+dir)){if(!/\.(svelte|ts|tsx|css|html|json|svg)$/.test(p)||/\.(test|spec)\./.test(p))continue;await edit(path.relative(root,p),s=>{for(const [a,b]of rep)s=s.replaceAll(a,b);return s.replace(/https:\/\/(?:www\.)?(?:instagram\.com\/dayandnight_autogroup\/?|facebook\.com\/deninoshtautogroup\/?|youtube\.com\/@kristiankirilov1355(?:\/videos)?)/g,'https://automarket.mobile.bg/');});}
const pub=root+'/'+variant+(variant==='modern'?'/apps/web/public':'/static');await fs.mkdir(pub+'/assets/automarket',{recursive:true});for(const e of await fs.readdir(root+'/assets'))if(/\.(png|webp)$/.test(e))await fs.copyFile(root+'/assets/'+e,pub+'/assets/automarket/'+e);}
// Auto Best: actual wired identity and inventory boundaries.
await edit('auto-best/src/lib/config/brand.ts',()=>`export const brand = ${JSON.stringify({name:facts.name,shortName:facts.shortName,city:facts.city,youtubeUrl:'',instagramUrl:'',facebookUrl:'',phone:facts.phoneDisplay,phoneHref:facts.phoneHref,addressLine:facts.address,address:facts.address+', '+facts.city,appointment:facts.hours[0],logo:facts.logo,mapsUrl:facts.mapsUrl,mapsEmbedUrl:facts.mapsEmbedUrl},null,2)} as const;\n`);
const vehicles=stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,category:({Wagon:'Комби',Hatchback:'Хечбек',Sedan:'Седан',SUV:'SUV'})[v.body]||v.body,body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:['4x4','Навигация','Парктроник'].filter(x=>v.features.includes(x)),condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`}));
await edit('auto-best/src/lib/data/inventory.ts',s=>s.replace('  image: string;','  image: string;\n  gallery: string[];\n  sourceUrl: string;').replace(/\/\/ Equipment facets[\s\S]*?export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`// Representative dealer listings captured 2026-09-07.\nexport const featuredVehicles: Vehicle[] = ${JSON.stringify(vehicles,null,2)};`));
await edit('auto-best/src/lib/data/listing.ts',s=>s.replace(/makes: \[[^\]]*\]/,`makes: ['', ...new Set(featuredVehicles.map(v => v.make))]`).replace(/bodies: \[[^\]]*\]/,`bodies: ['', ...new Set(featuredVehicles.map(v => v.body))]`).replace(/transmissions: \[[^\]]*\]/,`transmissions: ['', 'Ръчна', 'Автоматик']`).replace(/years: \[[^\]]*\]/,`years: ['', ...new Set(featuredVehicles.map(v => v.year))]`).replace(/prices: \[[^\]]*\]/,`prices: ['', '3000', '5000', '10000', '15000', '25000']`).replace(/mileages: \[[^\]]*\]/,`mileages: ['', '100000', '150000', '200000', '250000']`));
await edit('auto-best/src/lib/components/company/ShowroomMap.svelte',s=>s.replace("  import { showroomCoordinates } from '$data/company';\n",'').replace(/const mapEmbedUrl = .*?;/,'const mapEmbedUrl = brand.mapsEmbedUrl;').replace(/const directionsUrl = .*?;/,'const directionsUrl = brand.mapsUrl;'));
await edit('auto-best/src/lib/data/company.ts',s=>s.replace(/export const showroomCoordinates = \{[\s\S]*?\} as const;/,''));
// No official video/social channel was found. Keep the existing media section geometry as stock links.
await edit('auto-best/src/lib/components/home/VideoSection.svelte',s=>{const styles=s.slice(s.indexOf('<style>'));return `<script lang="ts">\nimport { featuredVehicles } from '$data/inventory';\nimport Icon from '$components/ui/Icon.svelte';\n</script>\n<section class="dn-videos" aria-labelledby="videos-title"><div class="container"><div class="dn-videos__panel"><div class="dn-videos__heading dn-home-section-heading"><h2 id="videos-title" class="dn-home-section-title">Разгледайте отблизо</h2><p>Снимки от публикуваните обяви на Аутомаркет Варна.</p><a class="dn-videos__channel dn-home-section-action" href="/listing-grid">Всички автомобили <Icon name="arrow-right" size={16}/></a></div><div class="dn-videos__grid">{#each featuredVehicles.slice(0,3) as vehicle (vehicle.id)}<article class="dn-video-card"><a class="dn-video-card__media" href={vehicle.href}><img style="width:100%;height:100%;object-fit:cover" src={vehicle.image} alt={vehicle.title} loading="lazy"/></a><div class="dn-video-card__content"><h3>{vehicle.title}</h3><div class="dn-video-card__actions"><a href={vehicle.href}>Снимки и детайли <Icon name="arrow-right" size={16}/></a></div></div></article>{/each}</div></div></div></section>\n${styles}`;});
// Galleries keep the original media frame and count position, making its existing indicator functional.
await edit('auto-best/src/routes/listing-detail-v1/[id]/+page.svelte',s=>s.replace("  const phoneLinkAttributes", "  let photoByVehicle = $state<Record<number, number>>({});\n  const photo = $derived(photoByVehicle[data.vehicle.id] ?? 0);\n  const phoneLinkAttributes").replace('src={data.vehicle.image}','src={data.vehicle.gallery[photo]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<div class="dn-detail-gallery__count">{#each data.vehicle.gallery as src, index (src)}<button type="button" aria-label={`Снимка ${index + 1}`} aria-pressed={photo === index} onclick={() => photoByVehicle[data.vehicle.id] = index} style="min-width:32px;min-height:44px;border:0;background:transparent;color:white">{index + 1}</button>{/each}</div>'));
// Carwow consumes its existing listing mapper and gallery.
const cw=stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:v.priceEur.toLocaleString('bg-BG')+' €',priceBgn:(v.priceEur*1.95583).toFixed(2)+' лв.',status:'Публикувана обява',date:v.date,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',color:v.color,fuel:v.fuel,power:v.powerHp+' к.с.',transmission:v.transmission,body:({SUV:'Джип',Wagon:'Комби',Hatchback:'Хечбек',Sedan:'Седан'})[v.body]||v.body,features:v.features,image:v.images[0],gallery:v.images}));
await edit('carwow/src/lib/data/daynight-current-inventory.ts',s=>s.slice(0,s.indexOf('export const currentDayNightListings')).replace('image: string;','image: string;\n gallery: string[];')+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(cw,null,2)};\n`);
await edit('carwow/src/lib/data/daynight-vehicles.ts',s=>s.replace('gallery: [listing.image]','gallery: listing.gallery').replace("const availability = isIncoming ? 'Очакван внос' : 'Наличен';","const availability = isIncoming ? 'Очакван внос' : 'Публикувана обява';").replace('Наличен автомобил в Варна — свържете се за оглед.','Обява към 07.09.2026 г. — потвърдете наличността и огледа по телефона.').replace(/monthly: `от \$\{[^\n]+/,"monthly: 'Условия по запитване',").replace('`DN-${','`AM-${'));
await edit('carwow/src/lib/data/daynight-site.ts',s=>s.replace(/location: '[^']*'/,`location: ${JSON.stringify('гр. Варна, '+facts.address)}`).replace(/mapUrl:\s*'[^']*'/,`mapUrl: ${JSON.stringify(facts.mapsUrl)}`).replace('inventoryCount: 40','inventoryCount: 16').replace(/logoLight: '[^']*'/,`logoLight: '${facts.logo}'`).replace(/logoDark: '[^']*'/,`logoDark: '${facts.logo}'`).replace(/heroSubtitle: '[^']*'/,"heroSubtitle: 'Автомобили от ЕС, оглед и запитване във Варна'"));
// Reviews become source-backed service information, retaining the existing cards.
const info=facts.services.slice(0,3).map((x,i)=>({id:'service-'+i,text:['Внос на употребявани автомобили от ЕС и доставка по поръчка.','Обсъдете замяна на автомобила си срещу доплащане.','Съдействие при регистрация в КАТ и транзитни номера.'][i],avatar:facts.logo,name:x,label:'Информация от публикуваните обяви'}));
await edit('carwow/src/lib/data/daynight-reviews.ts',s=>s.slice(0,s.indexOf('export const daynightReviews'))+`export const daynightReviews: DayNightReview[] = ${JSON.stringify(info,null,2)};\nexport const daynightReviewCount = daynightReviews.length;\nexport const daynightReviewCountLabel = 'Услуги и информация';\nexport const daynightReviewLinkLabel = 'Виж информацията';\n`);
await edit('carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte',s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${JSON.stringify(info.map(v=>({id:v.id,description:v.text,avatar:v.avatar,name:v.name,meta:v.label})),null,2)};`).replace('Отзиви от клиенти','Услуги и информация').replace("const starIds = ['star-1', 'star-2', 'star-3', 'star-4', 'star-5'] as const;","const starIds: string[] = [];"));
// Modern's complete monorepo retained, wired demo listings and identity replaced.
const conf={...facts,contactUrl:facts.phoneHref,countryCode:'BG',currency:'EUR',heroPath:stock[13].images[0],locale:'bg-BG',logoPath:facts.logo,slug:'automarket-varna',staticDemoMode:true,tagline:'Автомобили от ЕС, внос по поръчка и бартер във Варна.'};
const keys=['accent','address','city','contactUrl','country','countryCode','currency','email','heroPath','locale','logoPath','mapsEmbedUrl','mapsUrl','name','phoneDisplay','phoneHref','shortName','slug','socialLinks','staticDemoMode','tagline'];
await edit('modern/packages/marketplace/lead-site.ts',s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify(Object.fromEntries(keys.map(k=>[k,conf[k]])),null,2)};`));
const listings=stock.map((v,i)=>({id:'automarket-'+v.id,slug:'automarket-'+v.id,category:'car',dealerOrgId:'dealer-automarket-varna',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:'Варна',region:'Владислав Варненчик',country:'България'},features:v.features,spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Coupe:'coupe',Sedan:'sedan',Van:'van'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-automarket-varna',type:'dealer',displayName:facts.name,verificationStatus:'unverified',city:'Варна'},publishedAt:new Date(Date.UTC(2026,8,7,10,0,-i)).toISOString(),promoted:false}));
await edit('modern/packages/marketplace-domain/testing/mock-data.ts',s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`));
await fs.copyFile(root+'/assets/cover.png',root+'/modern/apps/web/public/lead-logo.png');await fs.copyFile(root+'/assets/vehicle-14-1.webp',root+'/modern/apps/web/public/lead-hero.jpg');
await fs.writeFile(root+'/evidence/personalization.json',JSON.stringify({changed,stockCount:stock.length,modernDetail:'/bg/listing/'+listings[0].slug},null,2));console.log('Changed',changed.length,'files');
