import fs from 'node:fs/promises';
import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const root=import.meta.dirname, data=JSON.parse(await fs.readFile(root+'/evidence/research-stock.json'));
const picks=[0,2,4,6,8,10,12,14,15,18,19,20,21,23,30,35];const stock=[],downloads=[];
const b=await chromium.launch({headless:true,channel:'chrome'});const p=await b.newPage();
try {for(const [n,idx] of picks.entries()){const c=data.cards[idx],raw=c.parts.find(p=>p.cls==='params').text,top=c.parts.find(p=>p.cls==='zaglavie').text;const id=c.url.match(/obiava-(\d+)/)[1];
await p.goto(c.url,{waitUntil:'domcontentloaded'});const detail=await p.evaluate(()=>({url:location.href,text:document.body.innerText,images:[...document.images].map(i=>i.src).filter(s=>s.includes('photosorg'))}));await fs.writeFile(`${root}/evidence/listing-${id}.json`,JSON.stringify(detail,null,2));
const urls=[...new Set(detail.images)].filter(s=>s.includes(id)).slice(0,5);if(!urls.length)urls.push(...c.images);
const images=[];for(const [j,url] of urls.entries()){const name=`vehicle-${String(n+1).padStart(2,'0')}-${j+1}.webp`;const r=await fetch(url);if(!r.ok)throw Error(r.status+' '+url);await fs.writeFile(`${root}/assets/${name}`,Buffer.from(await r.arrayBuffer()));images.push('/assets/automarket/'+name);downloads.push({url,path:'assets/'+name,sourcePage:c.url});}
const make=c.title.startsWith('Mercedes-Benz')?'Mercedes-Benz':c.title.split(' ')[0],year=Number(raw.match(/(?:19|20)\d{2}/)[0]),mileageKm=Number(raw.match(/г\.\s*([\d\s]+)\s*км/)[1].replace(/\s/g,'')),priceEur=Number(top.match(/([\d\s]+(?:[.,]\d+)?)\s*€/)[1].replace(/\s/g,'').replace(',','.'));
const fuel=raw.includes('Хибриден')?'Хибрид':raw.includes('Дизелов')?'Дизел':raw.includes('Бензинов')?'Бензин':'Електрически',body=raw.includes('Джип')?'SUV':raw.includes('Хечбек')?'Hatchback':raw.includes('Комби')?'Wagon':raw.includes('Купе')?'Coupe':raw.includes('Ван')?'Van':'Sedan';
stock.push({id,title:c.title,make,model:c.title.slice(make.length).trim(),year,mileageKm,priceEur,fuel,transmission:raw.includes('Автоматична')?'Автоматик':'Ръчна',body,powerHp:Number(raw.match(/(\d+)\s*к\.с\./)?.[1]||0),color:raw.match(/км\s+(.+?)\s+(?:Хибриден|Дизелов|Бензинов|Електрически)/)?.[1]||'',date:raw.match(/^(.+?г\.)/)?.[1],vat:'Не се начислява ДДС',sourceUrl:c.url,images,rawFacts:raw,description:`${c.title}, ${year} г., ${mileageKm.toLocaleString('bg-BG')} км. Представителна обява към 07.09.2026 г. Потвърдете наличността и условията с Аутомаркет Варна.`,features:(c.parts.find(p=>p.cls==='info')?.text.split('Особености - ')[1]||'').split(', ').filter(Boolean)});console.log(n+1,c.title,priceEur,images.length);}
for(const [kind,segment] of [['logo','houseslogos'],['cover','housespicts']]){const url=`https://cdn2.focus.bg/mobile/images/${segment}/h12015396395487220.pic`;const r=await fetch(url);await fs.writeFile(`${root}/assets/${kind}.png`,Buffer.from(await r.arrayBuffer()));downloads.push({url,path:`assets/${kind}.png`,sourcePage:'https://automarket.mobile.bg/'});}
await fs.writeFile(root+'/stock.json',JSON.stringify(stock,null,2));await fs.writeFile(root+'/assets/provenance.json',JSON.stringify({capturedAt:new Date().toISOString(),source:'https://automarket.mobile.bg/',note:'Official dealer profile media and representative sale listings; original watermarks retained. Public preview not published.',downloads},null,2));
}finally{await b.close();}
