import fs from 'node:fs/promises';
const root=import.meta.dirname.replaceAll('\\','/');
for(const [variant,port]of [['auto-best',6656],['carwow',6658],['modern',6657]]){
const env=variant==='modern'?`$env:SKIP_ENV_VALIDATION='true'\n$env:AUTOMARKET_PUBLIC_DATA_MODE='demo'\n$env:NEXT_PUBLIC_WEB_URL='http://127.0.0.1:6657'\n$env:NEXT_PUBLIC_API_URL='http://127.0.0.1:6659'\n$env:NEXT_PUBLIC_APP_URL='http://127.0.0.1:6660'\n`:'';
const script=`$ErrorActionPreference='Continue'\n${env}$qaStarted=$null\ntry {\n $qaStarted = (& J:/cars/scripts/start-preview.ps1 -Client automarket-varna -Template ${variant} -Port ${port} | ConvertFrom-Json)\n if(-not $qaStarted.PID){throw 'Preview did not start'}\n $qaStarted | ConvertTo-Json | Set-Content '${root}/evidence/${variant}-runtime.json'\n Start-Sleep -Seconds 4\n Set-Location J:/cars\n & C:/nvm4w/nodejs/node.exe '${root}/browser-qa.mjs' '${variant}' *> '${root}/evidence/${variant}-browser.log'\n $qaCode=$LASTEXITCODE\n & C:/nvm4w/nodejs/node.exe '${root}/${variant==='auto-best'?'interact-auto':'interact-other'}.mjs' '${variant}' *> '${root}/evidence/${variant}-interaction.log'\n if($LASTEXITCODE -ne 0){$qaCode=$LASTEXITCODE}\n} finally {\n if($qaStarted.PID){\n $qaProcess=Get-CimInstance Win32_Process -Filter "ProcessId=$($qaStarted.PID)"\n if($qaProcess.CommandLine -match '--port ${port}') { & taskkill /PID $qaStarted.PID /T /F | Out-Null }\n }\n Set-Content '${root}/evidence/${variant}-preview-state.txt' 'Stopped after serialized QA; see runtime record and logs.'\n}\nexit $qaCode\n`;
await fs.writeFile(root+`/qa-${variant}.ps1`,script);
}
const p=root+'/carwow/src/lib/data/daynight-team.ts',s=(await fs.readFile(p,'utf8')).replaceAll('\r\n','\n');const entries=[['prodazhbi-showroom','Автомобили','Въпроси за публикуваните автомобили, оборудването и актуалната наличност.'],['barter-i-ocenka','Бартер','Обсъдете замяна на стар автомобил срещу доплащане.'],['dokumenti-finansirane','Регистрация и лизинг','Попитайте за съдействие при регистрация и за условията на финансовите партньори.'],['klientski-zapitvania','Оглед във Варна','Уточнете работно време, автомобил и удобен час по телефона.']].map(([slug,name,bio])=>({slug,name,role:'Контакт с Аутомаркет Варна',phone:'0886424400',email:'',image:'/assets/automarket/cover.png',bio,detail:bio+' Телефон: 0886 424 400.'}));await fs.writeFile(p,s.replace(/export const daynightTeam: DayNightTeamMember\[\] = \[[\s\S]*?\n\];/,`export const daynightTeam: DayNightTeamMember[] = ${JSON.stringify(entries,null,2)};`));
console.log('Serialized QA jobs ready');
