import type {Vehicle} from './vehicle';

// Captured public reference data; not a live inventory feed. Sources are recorded in reference/.
export const capturedVehicles: Vehicle[] = [
  {
    "slug": "2024-toyota-fortuner-exr",
    "referenceId": "9714841126",
    "year": 2024,
    "make": "Toyota",
    "model": "FORTUNER",
    "trim": "EXR • GCC Specs",
    "price": 94099,
    "previousPrice": 100999,
    "monthly": 1430,
    "mileage": 50000,
    "originalMileage": 50005,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841126.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2.7L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Luxe",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-toyota-land-cruiser-exr",
    "referenceId": "9718425910",
    "year": 2024,
    "make": "Toyota",
    "model": "LAND CRUISER",
    "trim": "EXR • GCC Specs",
    "price": 224599,
    "previousPrice": 227999,
    "monthly": 3413,
    "mileage": 44000,
    "originalMileage": 44692,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718425910.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "DC Fast Charging"
    ],
    "power": "Not captured",
    "engine": "4L",
    "warranty": "See vehicle report",
    "condition": "DC Fast Charging",
    "tier": "Luxe",
    "optionsType": "Basic",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2022-toyota-land-cruiser-exr-black-edition-1440",
    "referenceId": "9714841440",
    "year": 2022,
    "make": "Toyota",
    "model": "LAND CRUISER",
    "trim": "EXR BLACK EDITION • GCC Specs",
    "price": 201999,
    "previousPrice": 209999,
    "monthly": 3070,
    "mileage": 69000,
    "originalMileage": 69471,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841440.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Four wheel drive"
    ],
    "power": "Not captured",
    "engine": "3.5L",
    "warranty": "See vehicle report",
    "condition": "Four wheel drive",
    "tier": "Luxe",
    "optionsType": "Semi Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-lexus-rx350-prestige-9728",
    "referenceId": "9718349728",
    "year": 2025,
    "make": "Lexus",
    "model": "RX350",
    "trim": "PRESTIGE • GCC Specs",
    "price": 204490,
    "previousPrice": 216999,
    "monthly": 3107,
    "mileage": 36000,
    "originalMileage": 36513,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718349728.jpg",
    "color": "Grey",
    "badges": [
      "Free 1 yr warranty"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2.4L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Luxe",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-volvo-xc40-ultimate-dark-0848",
    "referenceId": "9714840848",
    "year": 2023,
    "make": "Volvo",
    "model": "XC40",
    "trim": "ULTIMATE DARK • GCC Specs",
    "price": 84599,
    "previousPrice": 90199,
    "monthly": 1286,
    "mileage": 41000,
    "originalMileage": 41973,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714840848.jpg",
    "color": "Silver",
    "badges": [
      "COMING SOON"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Luxe",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-toyota-fortuner-exr-1932",
    "referenceId": "9714841932",
    "year": 2024,
    "make": "Toyota",
    "model": "FORTUNER",
    "trim": "EXR • GCC Specs",
    "price": 98499,
    "monthly": 1497,
    "mileage": 52000,
    "originalMileage": 52968,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841932.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Four wheel drive"
    ],
    "power": "Not captured",
    "engine": "2.7L",
    "warranty": "See vehicle report",
    "condition": "Four wheel drive",
    "tier": "Luxe",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-nissan-patrol-le-t2-2271",
    "referenceId": "9714842271",
    "year": 2024,
    "make": "Nissan",
    "model": "PATROL",
    "trim": "LE T2 • GCC Specs",
    "price": 183099,
    "previousPrice": 184999,
    "monthly": 2782,
    "mileage": 49000,
    "originalMileage": 49762,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842271.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "5.6L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Luxe",
    "optionsType": "Semi Loaded",
    "cylinders": 8,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-land-rover-defender-p300-110-se-4221",
    "referenceId": "9718384221",
    "year": 2023,
    "make": "Land Rover",
    "model": "DEFENDER",
    "trim": "P300 110 SE • GCC Specs",
    "price": 256999,
    "previousPrice": 289999,
    "monthly": 3905,
    "mileage": 68000,
    "originalMileage": 68741,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718384221.jpg",
    "color": "White",
    "badges": [
      "Free 1 yr warranty"
    ],
    "highlights": [
      "Service History"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Service History",
    "tier": "Luxe",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2020-bmw-x2-sdrive-20i-5243",
    "referenceId": "9718385243",
    "year": 2020,
    "make": "BMW",
    "model": "X2",
    "trim": "SDRIVE 20I • GCC Specs",
    "price": 56599,
    "monthly": 860,
    "mileage": 66000,
    "originalMileage": 66545,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718385243.jpg",
    "color": "Black",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Service History"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Service History",
    "tier": "Luxe",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-bmw-430i-m-sport-5520",
    "referenceId": "9718405520",
    "year": 2023,
    "make": "BMW",
    "model": "430I",
    "trim": "M SPORT • GCC Specs",
    "price": 160899,
    "previousPrice": 164999,
    "monthly": 2445,
    "mileage": 77000,
    "originalMileage": 77474,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Coupe",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718405520.jpg",
    "color": "White",
    "badges": [
      "COMING SOON"
    ],
    "highlights": [
      "Manufacturer warranty"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Manufacturer warranty",
    "tier": "Luxe",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-mg-zs-std-2260",
    "referenceId": "9714842260",
    "year": 2024,
    "make": "MG",
    "model": "ZS",
    "trim": "STD • GCC Specs",
    "price": 35899,
    "previousPrice": 36999,
    "monthly": 546,
    "mileage": 38000,
    "originalMileage": 38752,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842260.jpg",
    "color": "Silver",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2017-mitsubishi-outlander-glx-mid-0593",
    "referenceId": "9718420593",
    "year": 2017,
    "make": "Mitsubishi",
    "model": "OUTLANDER",
    "trim": "GLX MID • GCC Specs",
    "price": 35099,
    "previousPrice": 35999,
    "monthly": 846,
    "mileage": 121000,
    "originalMileage": 121092,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718420593.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Four wheel drive"
    ],
    "power": "Not captured",
    "engine": "2.4L",
    "warranty": "See vehicle report",
    "condition": "Four wheel drive",
    "tier": "Lite",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-jac-j7-intelligent-2176",
    "referenceId": "9714842176",
    "year": 2023,
    "make": "JAC",
    "model": "J7",
    "trim": "INTELLIGENT • GCC Specs",
    "price": 27199,
    "previousPrice": 27999,
    "monthly": 414,
    "mileage": 57000,
    "originalMileage": 57538,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842176.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Boosted Engine"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Boosted Engine",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2022-toyota-yaris-se-2148",
    "referenceId": "9714842148",
    "year": 2022,
    "make": "Toyota",
    "model": "YARIS",
    "trim": "SE • GCC Specs",
    "price": 31599,
    "monthly": 481,
    "mileage": 124000,
    "originalMileage": 124181,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842148.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Fuel Efficient"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Fuel Efficient",
    "tier": "Lite",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-mg-5-std-2123",
    "referenceId": "9714842123",
    "year": 2024,
    "make": "MG",
    "model": "5",
    "trim": "STD • GCC Specs",
    "price": 26599,
    "monthly": 405,
    "mileage": 62000,
    "originalMileage": 62078,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842123.jpg",
    "color": "Silver",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-mitsubishi-attrage-glx-highline-2162",
    "referenceId": "9714842162",
    "year": 2023,
    "make": "Mitsubishi",
    "model": "ATTRAGE",
    "trim": "GLX HIGHLINE • GCC Specs",
    "price": 24799,
    "previousPrice": 25999,
    "monthly": 377,
    "mileage": 91000,
    "originalMileage": 91453,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842162.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.2L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 3,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-suzuki-dzire-glx-1812",
    "referenceId": "9714841812",
    "year": 2023,
    "make": "Suzuki",
    "model": "DZIRE",
    "trim": "GLX • GCC Specs",
    "price": 25599,
    "monthly": 389,
    "mileage": 92000,
    "originalMileage": 92236,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841812.jpg",
    "color": "Silver",
    "badges": [
      "COMING SOON"
    ],
    "highlights": [
      "Fuel Efficient"
    ],
    "power": "Not captured",
    "engine": "1.2L",
    "warranty": "See vehicle report",
    "condition": "Fuel Efficient",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-mitsubishi-attrage-glx-highline-2223",
    "referenceId": "9714842223",
    "year": 2025,
    "make": "Mitsubishi",
    "model": "ATTRAGE",
    "trim": "GLX HIGHLINE • GCC Specs",
    "price": 32499,
    "previousPrice": 33999,
    "monthly": 494,
    "mileage": 31000,
    "originalMileage": 31399,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842223.jpg",
    "color": "Black",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Fuel Efficient"
    ],
    "power": "Not captured",
    "engine": "1.2L",
    "warranty": "See vehicle report",
    "condition": "Fuel Efficient",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 3,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-jac-s3-intelligent-luxury-0600",
    "referenceId": "9714840600",
    "year": 2023,
    "make": "JAC",
    "model": "S3",
    "trim": "INTELLIGENT LUXURY • GCC Specs",
    "price": 30299,
    "monthly": 461,
    "mileage": 40000,
    "originalMileage": 40838,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714840600.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.6L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-suzuki-baleno-gl-2055",
    "referenceId": "9714842055",
    "year": 2025,
    "make": "Suzuki",
    "model": "BALENO",
    "trim": "GL • GCC Specs",
    "price": 37099,
    "previousPrice": 37999,
    "monthly": 564,
    "mileage": 21000,
    "originalMileage": 21849,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Hatchback",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842055.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Fuel Efficient"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Fuel Efficient",
    "tier": "Prime",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2022-kia-seltos-lx-3696",
    "referenceId": "9718423696",
    "year": 2022,
    "make": "Kia",
    "model": "SELTOS",
    "trim": "LX • GCC Specs",
    "price": 43499,
    "previousPrice": 45999,
    "monthly": 661,
    "mileage": 99000,
    "originalMileage": 99274,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718423696.jpg",
    "color": "Red",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Cruise control"
    ],
    "power": "Not captured",
    "engine": "1.6L",
    "warranty": "See vehicle report",
    "condition": "Cruise control",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2020-mitsubishi-pajero-gls-highline-3165",
    "referenceId": "9718383165",
    "year": 2020,
    "make": "Mitsubishi",
    "model": "PAJERO",
    "trim": "GLS HIGHLINE • GCC Specs",
    "price": 51799,
    "monthly": 788,
    "mileage": 92000,
    "originalMileage": 92480,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718383165.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Four wheel drive"
    ],
    "power": "Not captured",
    "engine": "3.8L",
    "warranty": "See vehicle report",
    "condition": "Four wheel drive",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2018-mitsubishi-pajero-gls-mid-1883",
    "referenceId": "9718421883",
    "year": 2018,
    "make": "Mitsubishi",
    "model": "PAJERO",
    "trim": "GLS MID • GCC Specs",
    "price": 42999,
    "previousPrice": 43999,
    "monthly": 797,
    "mileage": 119000,
    "originalMileage": 119756,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718421883.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Four wheel drive"
    ],
    "power": "Not captured",
    "engine": "3L",
    "warranty": "See vehicle report",
    "condition": "Four wheel drive",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-hyundai-creta-comfort-2089",
    "referenceId": "9714842089",
    "year": 2024,
    "make": "Hyundai",
    "model": "CRETA",
    "trim": "COMFORT • GCC Specs",
    "price": 57099,
    "previousPrice": 57999,
    "monthly": 868,
    "mileage": 47000,
    "originalMileage": 47109,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842089.jpg",
    "color": "Black white",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Cruise control"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Cruise control",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-toyota-corolla-xli-2142",
    "referenceId": "9714842142",
    "year": 2024,
    "make": "Toyota",
    "model": "COROLLA",
    "trim": "XLI • GCC Specs",
    "price": 53599,
    "monthly": 815,
    "mileage": 76000,
    "originalMileage": 76657,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842142.jpg",
    "color": "Silver",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.6L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Lite",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-mitsubishi-asx-glx-mid-2023",
    "referenceId": "9714842023",
    "year": 2024,
    "make": "Mitsubishi",
    "model": "ASX",
    "trim": "GLX MID • GCC Specs",
    "price": 47499,
    "previousPrice": 50999,
    "monthly": 722,
    "mileage": 72000,
    "originalMileage": 72132,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842023.jpg",
    "color": "Silver",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Cruise control"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Cruise control",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-mazda-6-s-1298",
    "referenceId": "9714841298",
    "year": 2023,
    "make": "Mazda",
    "model": "6",
    "trim": "S • GCC Specs",
    "price": 48399,
    "previousPrice": 50699,
    "monthly": 736,
    "mileage": 88000,
    "originalMileage": 88654,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841298.jpg",
    "color": "Blue",
    "badges": [
      "COMING SOON"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Lite",
    "optionsType": "Basic",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-suzuki-grand-vitara-glx-4077",
    "referenceId": "9718424077",
    "year": 2023,
    "make": "Suzuki",
    "model": "GRAND VITARA",
    "trim": "GLX • GCC Specs",
    "price": 52399,
    "monthly": 797,
    "mileage": 51000,
    "originalMileage": 51972,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718424077.jpg",
    "color": "Black white",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Service History"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Service History",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-nissan-kicks-sv-1632",
    "referenceId": "9714841632",
    "year": 2024,
    "make": "Nissan",
    "model": "KICKS",
    "trim": "SV • GCC Specs",
    "price": 51599,
    "previousPrice": 53399,
    "monthly": 784,
    "mileage": 38000,
    "originalMileage": 38064,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841632.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.6L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-toyota-veloz-gx",
    "referenceId": "9718403147",
    "year": 2025,
    "make": "Toyota",
    "model": "VELOZ",
    "trim": "GX • GCC Specs",
    "price": 64699,
    "monthly": 984,
    "mileage": 47000,
    "originalMileage": 47193,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718403147.jpg",
    "color": "Silver",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Good Tyre Condition"
    ],
    "power": "Not captured",
    "engine": "1.5L",
    "warranty": "See vehicle report",
    "condition": "Good Tyre Condition",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-mitsubishi-outlander-midline-6143",
    "referenceId": "9718426143",
    "year": 2025,
    "make": "Mitsubishi",
    "model": "OUTLANDER",
    "trim": "MIDLINE • GCC Specs",
    "price": 70599,
    "previousPrice": 71999,
    "monthly": 1073,
    "mileage": 53000,
    "originalMileage": 53356,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718426143.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-volkswagen-t-roc-r-line-4363",
    "referenceId": "9718334363",
    "year": 2023,
    "make": "Volkswagen",
    "model": "T ROC",
    "trim": "R LINE • GCC Specs",
    "price": 64199,
    "previousPrice": 74699,
    "monthly": 976,
    "mileage": 50000,
    "originalMileage": 50723,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718334363.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Panoramic Roof"
    ],
    "power": "Not captured",
    "engine": "1.4L",
    "warranty": "See vehicle report",
    "condition": "Panoramic Roof",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-ford-taurus-titanium-0988",
    "referenceId": "9718400988",
    "year": 2023,
    "make": "Ford",
    "model": "TAURUS",
    "trim": "TITANIUM • GCC Specs",
    "price": 79599,
    "previousPrice": 84999,
    "monthly": 1210,
    "mileage": 54000,
    "originalMileage": 54748,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718400988.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Manufacturer warranty"
    ],
    "power": "Not captured",
    "engine": "2L",
    "warranty": "See vehicle report",
    "condition": "Manufacturer warranty",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2025-mitsubishi-outlander-glx-mid-line-6154",
    "referenceId": "9718426154",
    "year": 2025,
    "make": "Mitsubishi",
    "model": "OUTLANDER",
    "trim": "GLX MID LINE • GCC Specs",
    "price": 70599,
    "previousPrice": 71999,
    "monthly": 1073,
    "mileage": 53000,
    "originalMileage": 53222,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718426154.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "2.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-ford-territory-titanium-5659",
    "referenceId": "9718405659",
    "year": 2024,
    "make": "Ford",
    "model": "TERRITORY",
    "trim": "TITANIUM • GCC Specs",
    "price": 84499,
    "previousPrice": 89799,
    "monthly": 1284,
    "mileage": 33000,
    "originalMileage": 33931,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718405659.jpg",
    "color": "Red",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "1.8L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Fully Loaded",
    "cylinders": 4,
    "zeroDownPayment": true
  },
  {
    "slug": "2023-kia-k8-lx-2143",
    "referenceId": "9714842143",
    "year": 2023,
    "make": "Kia",
    "model": "K8",
    "trim": "LX • GCC Specs",
    "price": 80399,
    "previousPrice": 81999,
    "monthly": 1222,
    "mileage": 89000,
    "originalMileage": 89198,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "Sedan",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714842143.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "3.5L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Prime",
    "optionsType": "Semi Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2021-nissan-patrol-se-platinum-city-9863",
    "referenceId": "9714839863",
    "year": 2021,
    "make": "Nissan",
    "model": "PATROL",
    "trim": "SE PLATINUM CITY • GCC Specs",
    "price": 123790,
    "previousPrice": 135299,
    "monthly": 1881,
    "mileage": 133000,
    "originalMileage": 133863,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714839863.jpg",
    "color": "Silver",
    "badges": [
      "COMING SOON"
    ],
    "highlights": [
      "Power packed"
    ],
    "power": "Not captured",
    "engine": "4L",
    "warranty": "See vehicle report",
    "condition": "Power packed",
    "tier": "Lite",
    "optionsType": "Fully Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-nissan-patrol-se-platinum-city-6451",
    "referenceId": "9718406451",
    "year": 2024,
    "make": "Nissan",
    "model": "PATROL",
    "trim": "SE PLATINUM CITY • GCC Specs",
    "price": 181699,
    "previousPrice": 185599,
    "monthly": 2761,
    "mileage": 74000,
    "originalMileage": 74224,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9718406451.jpg",
    "color": "Grey",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Manufacturer warranty"
    ],
    "power": "Not captured",
    "engine": "4L",
    "warranty": "See vehicle report",
    "condition": "Manufacturer warranty",
    "tier": "Luxe",
    "optionsType": "Fully Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2024-nissan-patrol-se-titanium-1439",
    "referenceId": "9714841439",
    "year": 2024,
    "make": "Nissan",
    "model": "PATROL",
    "trim": "SE TITANIUM • GCC Specs",
    "price": 169299,
    "previousPrice": 176299,
    "monthly": 2573,
    "mileage": 70000,
    "originalMileage": 70332,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841439.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Great condition"
    ],
    "power": "Not captured",
    "engine": "4L",
    "warranty": "See vehicle report",
    "condition": "Great condition",
    "tier": "Luxe",
    "optionsType": "Semi Loaded",
    "cylinders": 6,
    "zeroDownPayment": true
  },
  {
    "slug": "2022-toyota-land-cruiser-exr-1097",
    "referenceId": "9714841097",
    "year": 2022,
    "make": "Toyota",
    "model": "LAND CRUISER",
    "trim": "EXR • GCC Specs",
    "price": 175999,
    "monthly": 2675,
    "mileage": 92000,
    "originalMileage": 92992,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "body": "SUV",
    "location": "Millennium Place Hotel Barsha, Dubai",
    "image": "/reference-assets/catalog/9714841097.jpg",
    "color": "White",
    "badges": [
      "1.99% interest rate*"
    ],
    "highlights": [
      "Power packed"
    ],
    "power": "Not captured",
    "engine": "4L",
    "warranty": "See vehicle report",
    "condition": "Power packed",
    "tier": "Luxe",
    "optionsType": "Basic",
    "cylinders": 6,
    "zeroDownPayment": true
  }
];
