import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/avangard-auto',stock=JSON.parse(await fs.readFile(root+'/stock.json')),facts=JSON.parse(await fs.readFile(root+'/business-facts.json'));const read=p=>fs.readFile(root+'/'+p,'utf8'),write=(p,s)=>fs.writeFile(root+'/'+p,s);
async function walk(dir){let a=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.vercel'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())a.push(...await walk(p));else a.push(p);}return a;}
const services=[['Автомобили','Публикувани предложения','Разгледайте 16 избрани обяви. За актуална наличност се свържете с AVANGARD AUTO.'],['Регистрация','Съдействие в КАТ','В обявите се предлага съдействие при регистрация и издаване на транзитни номера.'],['Транспорт','В България','В обявите се предлага транспорт до всяка точка в България. Уточнете цена и условия.'],['Лизинг','Индивидуални условия','Автомобили с обявена възможност за лизинг. Условията се потвърждават за конкретната сделка.'],['Оглед','Варна','Бул. Цар Освободител 289, Варна. Обадете се за работно време и удобен час.'],['Контакт','0877 800 921','За въпроси: 0877 800 921 или 0896 391 615.']];
// Keep the source information-card layouts, replacing fictional testimony with sourced information.
let rev=await read('carwow/src/lib/data/daynight-reviews.ts');rev=rev.slice(0,rev.indexOf('export const daynightReviews'))+`export const daynightReviews = ${JSON.stringify(services.map(([name,label,text],i)=>({id:'info-'+i,name,label,text,avatar:'/assets/avangard/social-logo.jpg'})),null,2)} satisfies DayNightReview[];\nexport const daynightReviewCount = daynightReviews.length;\nexport const daynightReviewCountLabel = 'Полезна информация';\nexport const daynightReviewLinkLabel = 'Всички акценти';\n`;await write('carwow/src/lib/data/daynight-reviews.ts',rev);
let hr=await read('carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte');hr=hr.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${JSON.stringify(services.slice(0,3).map(([name,meta,description],i)=>({id:'info-'+i,name,meta,description,avatar:'/assets/avangard/social-logo.jpg'})))};`);await write('carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte',hr);
for(const p of await walk(root+'/carwow/src')){if(!/\.(svelte|ts|css|html)$/.test(p))continue;let s=await fs.readFile(p,'utf8');s=s.replace(/const (starIds|starIndexes|stars) = \[[^\]]*\] as const;/g,'const $1: number[] = [];').replaceAll('Отзиви от клиенти','Полезна информация').replaceAll('Отзиви на клиенти','Полезна информация').replaceAll('Клиентски отзиви','Полезна информация').replaceAll('Понеделник - Събота: 9:00 - 18:00','Обадете се за работно време').replaceAll('Делнични дни: 9:00 - 18:00 · Неделя: по уговорка','Обадете се за работно време').replaceAll('Доволни клиенти','Контакт с екипа').replaceAll('Споделени впечатления от огледи, покупки и работа с AVANGARD AUTO.','Информация за автомобилите, посещението и предлаганото съдействие.');await fs.writeFile(p,s);}
// No matched YouTube channel: retain the three media cards as real stock/social links.
const vp='auto-best/src/lib/components/home/VideoSection.svelte';let vs=await read(vp);vs=vs.replace(/<script lang="ts">[\s\S]*?<\/script>/,`<script lang="ts">\n import { brand } from '$config/brand';\n import { featuredVideos } from '$data/videos';\n import Icon from '$components/ui/Icon.svelte';\n import SocialBrandIcon from '$components/company/SocialBrandIcon.svelte';\n</script>`).replace('Гледайте ни в','Следвайте ни в').replaceAll('name="youtube"','name="facebook"').replaceAll('YouTube','Facebook').replaceAll('Избрани автомобилни видеа с Кристиан Кирилов.','Автомобили от обявите на AVANGARD AUTO.').replaceAll('Всички видеа','Всички публикации').replaceAll('Гледайте в Facebook','Отворете обявата').replace(/<button\s+class="dn-video-card__play"[\s\S]*?<\/button>/,`<a class="dn-video-card__play" href={video.url} target="_blank" rel="noopener noreferrer" aria-label={video.title}><img src={video.thumbnail} alt={video.title} width="720" height="404" loading="lazy" decoding="async" /><span class="dn-video-card__duration">{video.duration}</span></a>`).replace(/\{#if activeVideo === video.id\}[\s\S]*?\{\/if\}/g,'').replace('href={`https://www.youtube.com/watch?v=${video.id}`}','href={video.url}');await write(vp,vs);await write('auto-best/src/lib/data/videos.ts',`export const featuredVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:v.priceEur+' €',thumbnail:v.images[0],url:v.sourceUrl})),null,2)};\n`);
let hv=await read('carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte');hv=hv.replaceAll('в YouTube','— избрани автомобили').replaceAll('Всички видеа','Facebook').replace(/AVANGARD AUTO в <img[^>]*\/>/,'AVANGARD AUTO').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noopener noreferrer"><img src={video.thumbnail} alt={video.title} width="480" height="270" loading="lazy" style="width:100%;height:100%;object-fit:cover" /></a>');await write('carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte',hv);await write('carwow/src/lib/data/daynight-videos.ts',`export const youtubeChannelUrl = ${JSON.stringify(facts.facebook)};\nexport const homeVideos = ${JSON.stringify(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'',thumbnail:v.images[0],url:v.sourceUrl})),null,2)} as const;`);
// Replace source-dealer photography, branding and invented staff at their wired boundaries.
let dc=await read('auto-best/src/lib/data/demo-content.ts');dc=dc.replace(/export const demoTeamMembers: DemoTeamMember\[\] = \[[\s\S]*?\n\];/,`export const demoTeamMembers: DemoTeamMember[] = ${JSON.stringify(services.slice(0,4).map(([name,role],i)=>({id:'service-'+i,name,role,image:stock[i].images[0]})))};`).replace(/export const demoPartners: DemoPartner\[\] = \[[\s\S]*?\n\];/,`export const demoPartners: DemoPartner[] = ${JSON.stringify(stock.slice(0,6).map(v=>({id:v.id,name:v.make,image:v.images[0]})))};`).replace("'Демо съдържание'","'AVANGARD AUTO'").replace('Примерни профили за визуален преглед. Имената и снимките ще бъдат заменени с реалния екип.','Контакт за автомобилите и съдействие според публикуваните обяви.').replace('Примерни автомобилни марки за визуален преглед. Те не представят потвърдени партньорства.','Избрани автомобили от публикуваните обяви.');await write('auto-best/src/lib/data/demo-content.ts',dc);
let at=await read('auto-best/src/lib/components/company/AboutTeam.svelte');at=at.replace('>Екипът<','>Как можем да съдействаме<').replace('Демо профил: ','');await write('auto-best/src/lib/components/company/AboutTeam.svelte',at);
let tm=await read('carwow/src/lib/data/daynight-team.ts');tm=tm.replace(/export const daynightTeam: DayNightTeamMember\[\] = \[[\s\S]*?\n\];/,`export const daynightTeam: DayNightTeamMember[] = ${JSON.stringify(services.slice(0,4).map(([name,role,bio],i)=>({slug:['prodazhbi-showroom','barter-i-ocenka','dokumenti-finansirane','klientski-zapitvania'][i],name,role,phone:'0877800921',email:'',image:stock[i].images[0],bio,detail:bio})))};`);await write('carwow/src/lib/data/daynight-team.ts',tm);
const mediaMap=new Map();
for(const key of ['auto-best','carwow','modern']){const dirs=key==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui']:['src'];for(const dir of dirs)for(const p of await walk(root+'/'+key+'/'+dir)){if(!/\.(svelte|tsx?|css|html|svg)$/.test(p))continue;let s=await fs.readFile(p,'utf8');s=s.replace(/\/(?:assets|brand)\/[\w./-]+\.(?:png|webp|jpe?g)/g,url=>{if(url.includes('/avangard/'))return url;if(/(?:day.?night|lead\/|home-promos|pages\/.*(?:showroom|team))/.test(url)&&!/(cutout|car-slide)/.test(url)){if(!mediaMap.has(url))mediaMap.set(url,/logo/.test(url)?'/assets/avangard/wordmark.svg':/(hero|home-black|home-hero)/.test(url)?'/assets/avangard/social-cover.jpg':stock[mediaMap.size%stock.length].images[0]);return mediaMap.get(url);}return url;});s=s.replaceAll('Екипът на AVANGARD AUTO','Контакт с AVANGARD AUTO').replaceAll('Партньори','Автомобили').replaceAll('Бартер и оценка','Въпрос за автомобил').replaceAll('Оценка за бартер','Въпрос за автомобил').replaceAll('Оценка, покупка и бартер','Въпроси за автомобил').replaceAll('Предложете своя автомобил за индивидуална оценка.','Попитайте екипа за възможностите за вашия автомобил.').replaceAll('Да — можем да обсъдим внос по поръчка според критерии за модел, бюджет и оборудване.','Обявите включват съдействие при регистрация и транспорт в България.').replaceAll('Можем да съдействаме с проверка на история, документи и техническо състояние преди финално решение.','Уточнете историята, документите и техническото състояние преди покупка.').replaceAll("{ name: 'youtube', label: 'YouTube', href: brand.youtubeUrl }", "{ name: 'facebook', label: 'Facebook', href: brand.facebookUrl }");await fs.writeFile(p,s);}}
await write('evidence/media-replacements.json',JSON.stringify([...mediaMap],null,2));
// Existing semantic colour boundaries; monochrome matches the current official social identity.
for(const file of ['auto-best/src/app.css','carwow/src/lib/styles/tokens.css']){let s=await read(file);s=s.replace(/(--(?:dn-red|sa-red):\s*)#[a-fA-F0-9]+/g,'$1#252a30');await write(file,s);}
facts.accent='#252a30';facts.socialVerification='Matched public Facebook title and Instagram metadata captured 2026-09-07';facts.logoLimitation='Official Mobile.bg logo is 66x40; Instagram logo 100x100. Original assets preserved. Light/dark text wordmarks in headers are temporary typography, not an official logo reconstruction.';await write('business-facts.json',JSON.stringify(facts,null,2));
console.log('Content and media pass complete');

