import fs from 'node:fs/promises';import path from 'node:path';const root='J:/cars/clients/avangard-auto',stock=JSON.parse(await fs.readFile(root+'/stock.json'));const read=p=>fs.readFile(root+'/'+p,'utf8'),write=(p,s)=>fs.writeFile(root+'/'+p,s);
const entry={brandCoverage:[...new Set(stock.map(v=>v.make))].map(brand=>({authorizationVerified:false,brand,relationship:'independent_importer'})),claimStatus:'unclaimed',contact:{phone:'+359877800921',websiteUrl:'https://avangard-auto.mobile.bg/'},dealerOrgId:'dealer-avangard',description:'Автомобили във Варна. Регистрация, транспорт и лизинг според обявата.',displayName:'AVANGARD AUTO',headquarters:{city:'Варна',countryCode:'BG'},headline:'Автомобили на бул. Цар Освободител 289',id:'directory-avangard',inventory:{activeListingCount:16,inTransitCount:0,localCount:16,orderableCount:0,sourceStockCount:0},orgType:'dealer',profileImage:{alt:'AVANGARD AUTO Варна — официална Facebook корица',url:'/assets/avangard/social-cover.jpg'},representativeVehicles:stock.slice(0,3).map(v=>({availability:'local',href:`/listing/avangard-${v.id}`,id:`avangard-${v.id}`,image:{alt:v.title,url:v.images[0]},price:{amount:v.priceEur,currency:'EUR'},title:v.title})),slug:'avangard-auto',tradeLanes:[],verification:{businessVerified:false,inventoryCurrent:false,trustedSupplier:false}};
await write('modern/packages/marketplace/mock-directory.ts',`import { organizationDirectoryEntriesSchema } from './directory';\nexport const mockOrganizationDirectoryCoreEntries = organizationDirectoryEntriesSchema.parse(${JSON.stringify([entry],null,2)});\nexport const createMockOrganizationDirectoryScaleEntries = (_totalOrganizations = 1) => mockOrganizationDirectoryCoreEntries;\nexport const mockOrganizationDirectoryEntries = mockOrganizationDirectoryCoreEntries;\n`);
for(const icon of ['apple-icon.png','icon.png']){const p=`modern/apps/web/app/-/${icon}`;try{await fs.copyFile(root+'/assets/official-logo.png',root+'/'+p)}catch{}}
let c=await read('modern/apps/web/app/[locale]/contact/page.tsx');c=c.replaceAll('/day-night-contact-hero-v1.png','/assets/avangard/social-cover.jpg');await write('modern/apps/web/app/[locale]/contact/page.tsx',c);
let co=await read('auto-best/src/lib/data/company.ts');co=co.replace('Обсъдете автомобил, бюджет и внос с екипа.','В обявите се предлага транспорт в България. Попитайте за цена и условия.').replace('Разкажете ни за автомобила, който искате да предложите, и поискайте индивидуална оценка.','Попитайте екипа дали може да съдейства за вашия автомобил. Няма потвърдена услуга за изкупуване или бартер.').replace('Обсъдете критериите си за автомобил, бюджет и предпочитания за внос с екипа.','Попитайте за регистрация, транзитни номера и транспорт на избрания автомобил.');await write('auto-best/src/lib/data/company.ts',co);
let pr=await read('auto-best/src/lib/components/company/AboutProcess.svelte');pr=pr.replace('Подбираме автомобили според вашите критерии, организираме оглед в {brand.city} и обсъждаме внос, бартер или лизинг директно с екипа.','Разгледайте обявите и уговорете оглед в {brand.city}. Публикуваните предложения включват съдействие при регистрация, транспорт в България и възможност за лизинг.');await write('auto-best/src/lib/components/company/AboutProcess.svelte',pr);
let ap=await read('auto-best/src/lib/components/company/AboutPartners.svelte');ap=ap.replace('Демо партньорски лога','Избрани автомобили').replace('Демо лого: ','');await write('auto-best/src/lib/components/company/AboutPartners.svelte',ap);
async function walk(d){let a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit'].includes(e.name))continue;const p=path.join(d,e.name);a.push(...e.isDirectory()?await walk(p):[p]);}return a;}
for(const p of await walk(root+'/carwow/src')){if(!/\.(svelte|ts|html)$/.test(p))continue;let s=await fs.readFile(p,'utf8');s=s.replaceAll('Защо Day Night','За AVANGARD AUTO').replaceAll('/assets/images/sell/kristian-trust-disclosure-list-v1.webp',stock[0].images[0]).replaceAll('в Варна','във Варна').replaceAll('Изберете автомобил от наличността онлайн или на място във Варна, запишете оглед и тест драйв, след което уточняваме финансиране, бартер или лизинг с екипа на AVANGARD AUTO.','Изберете публикуван автомобил и се свържете с AVANGARD AUTO за наличност, оглед и условия. Възможностите извън публикуваните услуги се уточняват индивидуално.').replaceAll('оценка на замяна и съдействие по документите','съдействие по документите');await fs.writeFile(p,s);}
// Inform users before the inherited local form; do not promise delivery or unverified services.
for(const p of ['carwow/src/lib/components/contact/DesktopContactPage.svelte','carwow/src/lib/components/contact/MobileContactPage.svelte']){let s=await read(p);s=s.replace(/(<form\b)/,'<p>Демонстрационна форма — не изпраща съобщение до автокъщата. За реално запитване: 0877 800 921.</p>\n$1');await write(p,s);}
// Prevent sample form requests from touching any configured provider in this independent demo.
for(const p of ['carwow/src/lib/client/lead-submit.ts','carwow/src/lib/client/import-request-submit.ts']){let s=await read(p);s=s.replace(/(export async function \w+\([\s\S]*?\): Promise<[^>]+> \{)/,'$1\n return { ok: false, status: 503, error: "Демонстрационна форма. Обадете се на 0877 800 921." };');await write(p,s);}
console.log('Final identity and content boundaries applied');

