import fs from 'node:fs/promises';import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const key=process.argv[2],root='J:/cars/clients/avangard-auto/evidence',stock=JSON.parse(await fs.readFile('J:/cars/clients/avangard-auto/stock.json'));
const config={'auto-best':{port:6626,entry:'/',inventory:'/listing-grid',detail:'/listing-detail-v1/1',contact:'/contact'},carwow:{port:6628,entry:'/',inventory:'/inventory',detail:'/inventory/vw-passat-alltrack-119627',contact:'/contact'},modern:{port:6627,entry:'/cars',inventory:'/bg/cars',detail:'/bg/listing/avangard-'+stock[0].id,contact:'/bg/contact'}}[key];
const b=await chromium.launch({channel:'chrome',headless:true}),results=[];
try{for(const width of [390,1440]){const p=await b.newPage({viewport:{width,height:900}});p.setDefaultTimeout(9000);const r={width,steps:[]};const go=route=>p.goto(`http://127.0.0.1:${config.port}${route}`,{waitUntil:'networkidle',timeout:60000});const step=async(name,fn)=>{try{r.steps.push({name,ok:true,...await fn()});}catch(e){r.steps.push({name,ok:false,error:e.message});}};
 await go(config.entry);
 await step('navigation and Escape',async()=>{let button=p.getByRole('button',{name:/^(Меню|Отвори менюто|Отвори меню|Автомобили)$/}).filter({visible:true}).first();if(!await button.count())button=p.locator('button[aria-expanded]').filter({visible:true}).first();if(!await button.count())throw Error('No matching navigation trigger');await button.click();await p.waitForTimeout(300);await p.screenshot({path:`${root}/${key}-menu-${width}.png`});const expanded=await p.locator('[aria-expanded=true]').count();await p.keyboard.press('Escape');await p.waitForTimeout(300);return {expanded,afterEscape:await p.locator('[aria-expanded=true]').count(),url:p.url()};});
 await go(config.inventory);
 await step('filter opens and dismisses',async()=>{const button=key==='auto-best'?p.locator('.dn-listing-filter__toggle').filter({visible:true}):p.getByRole('button',{name:/Филтри|Отвори филтрите|Всички филтри/}).filter({visible:true}).first();if(!await button.count())return {presentation:'Inline desktop filters',selectCount:await p.locator('select:visible').count()};await button.click();await p.waitForTimeout(300);await p.screenshot({path:`${root}/${key}-filters-${width}.png`});const dialogs=await p.locator('[role=dialog]:visible').count();await p.keyboard.press('Escape');await p.waitForTimeout(300);return {dialogs,afterEscape:await p.locator('[role=dialog]:visible').count()};});
 await go(config.inventory);
 await step('search BMW',async()=>{let input=p.locator('input[name=q],input[type=search],input[placeholder*="Марка"],input[placeholder*="Търс"]').filter({visible:true}).first();if(!await input.count()){let trigger=key==='auto-best'?p.getByRole('button',{name:/Търсете марка|Отворете търсенето/}).filter({visible:true}).first():p.getByRole('button',{name:/Търси.*автомобила|Търсене|Търси/}).filter({visible:true}).first();await trigger.click();await p.waitForTimeout(250);input=p.locator('input[name=q],input[type=search],input[placeholder*="Марка"],input[placeholder*="Търс"]').filter({visible:true}).first();}await input.fill('BMW');await input.press('Enter');const submit=p.getByRole('button',{name:/Покажи \d|Виж \d|Покажи резултат/}).filter({visible:true}).first();if(await submit.count())await submit.click();await p.screenshot({path:`${root}/${key}-search-${width}.png`});return {url:p.url(),text:(await p.locator('body').innerText()).slice(0,5000)};});
 await go(config.inventory);
 await step('inventory to detail and enquiry',async()=>{const selector=key==='auto-best'?'a[href*="/listing-detail-v1/1"]':key==='modern'?'a[href*="/listing/avangard-"]':'a[href*="/inventory/vw-passat"]';await p.locator(selector).filter({visible:true}).first().click();await p.waitForURL(u=>u.pathname.includes(key==='auto-best'?'/listing-detail':key==='modern'?'/listing/':'/inventory/'));await p.waitForLoadState('networkidle');const detailUrl=p.url();const phoneLinks=await p.locator('a[href^="tel:"]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));const enquiry=p.getByRole('link',{name:/Запитване|Запитай|Контакт|Свърж|Попитай/}).filter({visible:true}).first();const enquiryButton=p.getByRole('button',{name:/Запитване|Запитай|Свърж|Попитай/}).filter({visible:true}).first();if(await enquiry.count())await enquiry.click();else if(await enquiryButton.count())await enquiryButton.click();await p.screenshot({path:`${root}/${key}-enquiry-${width}.png`});return {detailUrl,phoneLinks,enquiryUrl:p.url(),text:(await p.locator('body').innerText()).slice(-3000)};});
 await go(config.contact);
 await step('contact destinations and local validation',async()=>{const links=await p.locator('a[href^="tel:"],a[href*="maps"]').evaluateAll(es=>es.map(e=>({text:e.textContent,href:e.getAttribute('href')})));const forms=await p.locator('form').count();const required=await p.locator('form [required]').count();return {links,forms,required,note:'No external submission or phone navigation performed'};});
 results.push(r);await p.close();await fs.writeFile(`${root}/${key}-interactions.json`,JSON.stringify(results,null,2));}}
finally{await b.close();}console.log(JSON.stringify(results.map(r=>({width:r.width,steps:r.steps.map(s=>({name:s.name,ok:s.ok,error:s.error}))})),null,2));
