import fs from 'node:fs/promises';import path from 'node:path';
const root=path.dirname(new URL(import.meta.url).pathname).replace(/^\/([A-Z]:)/,'$1');
const facts=JSON.parse(await fs.readFile(path.join(root,'business-facts.json'))),stock=JSON.parse(await fs.readFile(path.join(root,'stock.json'))),changes=[];
const read=p=>fs.readFile(path.join(root,p),'utf8'),write=(p,s)=>fs.writeFile(path.join(root,p),s);
const logo='/assets/avangard/wordmark.svg';
for(const [name,color] of [['wordmark','#171a20'],['wordmark-light','#ffffff']])await write(`assets/${name}.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="64" viewBox="0 0 320 64"><text x="0" y="44" fill="${color}" font-family="Arial,sans-serif" font-size="35" font-weight="700">AVANGARD AUTO</text></svg>`);
const replacements=[['Day &amp; Night Auto Group',facts.name],['Day & Night Auto Group',facts.name],['DAY NIGHT AUTO GROUP',facts.name],['Day Night Auto Group',facts.name],['Day Night Auto',facts.name],['Day & Night',facts.name],['Ден и Нощ Ауто Груп',facts.name],['София','Варна'],['Sofia','Varna'],['Студентски град','Владислав Варненчик'],['Studentski grad','Vladislav Varnenchik'],['ул. „Атанас Манчев“ 18, Владислав Варненчик',facts.address],['ул. Атанас Манчев 18',facts.address],['0877 733 110',facts.phoneDisplay],['0877733110','0877800921'],['087 982 4625',facts.phoneDisplay],['0879824625','0877800921'],['+359879824625','+359877800921'],['+359877733110','+359877800921'],['daynight.mobile.bg','avangard-auto.mobile.bg'],['daynightautogroup.bg','avangard-auto.mobile.bg'],['https://www.instagram.com/dayandnight_autogroup/',facts.instagram],['https://www.facebook.com/deninoshtautogroup/',facts.facebook],['https://www.youtube.com/@kristiankirilov1355/videos',facts.facebook],['Собствен лизинг','Лизинг'],['собствен лизинг','лизинг'],['Внос по заявка','Транспорт в България'],['внос по заявка','транспорт в България'],['Внос по поръчка','Съдействие при регистрация'],['внос по поръчка','съдействие при регистрация']];
async function walk(dir){let a=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.git','.vercel'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())a.push(...await walk(p));else a.push(p);}return a;}
for(const key of ['auto-best','modern','carwow']) {
 const dirs=key==='modern'?['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo']:['src'];
 for(const dir of dirs)for(const p of await walk(path.join(root,key,dir))){if(!/\.(tsx?|svelte|css|html|svg|json)$/.test(p)||/\.(test|spec)\./.test(p))continue;const s=await fs.readFile(p,'utf8');let n=s;for(const[a,b]of replacements)n=n.replaceAll(a,b);if(n!==s){await fs.writeFile(p,n);changes.push(path.relative(root,p));}}
 const pub=key==='modern'?'apps/web/public':'static';await fs.mkdir(path.join(root,key,pub,'assets/avangard'),{recursive:true});for(const e of await fs.readdir(path.join(root,'assets')))if(/\.(png|jpg|webp|svg)$/.test(e))await fs.copyFile(path.join(root,'assets',e),path.join(root,key,pub,'assets/avangard',e));
}
await write('auto-best/src/lib/config/brand.ts',`export const brand = ${JSON.stringify({name:facts.name,shortName:facts.shortName,city:facts.city,addressLine:facts.address,address:facts.address+', '+facts.city,phone:facts.phoneDisplay,phoneHref:facts.phoneHref,appointment:facts.appointment,logo,youtubeUrl:facts.facebook,instagramUrl:facts.instagram,facebookUrl:facts.facebook},null,2)} as const;\n`);
let inv=await read('auto-best/src/lib/data/inventory.ts');inv=inv.slice(0,inv.indexOf('// Equipment')).replace('  image: string;','  image: string;\n  gallery: string[];\n  sourceUrl: string;\n  description: string;');
const vehicles=stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,sourceUrl:v.sourceUrl,description:v.description,category:v.bodyBg,body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:['4x4','Навигация','Парктроник'].filter(e=>v.features.includes(e)),condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`}));
await write('auto-best/src/lib/data/inventory.ts',inv+`export const featuredVehicles: Vehicle[] = ${JSON.stringify(vehicles,null,2)};\nexport const formatVehiclePrice = (priceEur: number) => new Intl.NumberFormat('bg-BG').format(priceEur) + ' €';\n`);
let mp=await read('auto-best/src/lib/components/company/ShowroomMap.svelte');mp=mp.replace("  import { showroomCoordinates } from '$data/company';",'').replace(/const mapEmbedUrl = .*;/,`const mapEmbedUrl = ${JSON.stringify(facts.mapsEmbedUrl)};`);await write('auto-best/src/lib/components/company/ShowroomMap.svelte',mp);
// Preserve the source gallery frame and use its existing dot control for actual photos.
let dp=await read('auto-best/src/routes/listing-detail-v1/[id]/+page.svelte');dp=dp.replace("  const phoneLinkAttributes", "  let selectedPhoto = $state(0);\n  const phoneLinkAttributes").replace('src={data.vehicle.image}','src={data.vehicle.gallery[selectedPhoto % data.vehicle.gallery.length]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<button class="dn-detail-gallery__count" type="button" aria-label="Следваща снимка" onclick={() => selectedPhoto += 1}>{(selectedPhoto % data.vehicle.gallery.length) + 1} / {data.vehicle.gallery.length}</button>');await write('auto-best/src/routes/listing-detail-v1/[id]/+page.svelte',dp);
const config={...facts,accent:'#22272b',contactUrl:facts.phoneHref,countryCode:'BG',currency:'EUR',email:'',heroPath:'/assets/avangard/social-cover.jpg',locale:'bg-BG',logoPath:logo,slug:'avangard-auto',socialLinks:{facebook:facts.facebook,instagram:facts.instagram},staticDemoMode:true,tagline:'Автомобили във Варна. Оглед, регистрация и транспорт.'};
const keys=['accent','address','city','contactUrl','country','countryCode','currency','email','heroPath','locale','logoPath','mapsEmbedUrl','mapsUrl','name','phoneDisplay','phoneHref','shortName','slug','socialLinks','staticDemoMode','tagline'];const lead=Object.fromEntries(keys.map(k=>[k,config[k]]));let lf=await read('modern/packages/marketplace/lead-site.ts');lf=lf.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify(lead,null,2)};`);await write('modern/packages/marketplace/lead-site.ts',lf);
const listings=stock.map((v,i)=>({id:`avangard-${v.id}`,slug:`avangard-${v.id}`,category:'car',dealerOrgId:'dealer-avangard',status:'active',title:v.title,description:v.description+' Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:'Варна',region:'Владислав Варненчик',country:'България'},features:v.features,spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Wagon:'wagon',Hatchback:'hatchback',Sedan:'sedan',Coupe:'coupe'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-avangard',type:'dealer',displayName:facts.name,verificationStatus:'unverified',city:'Варна'},publishedAt:new Date(Date.UTC(2026,8,7,7,0,-i)).toISOString(),promoted:false}));let md=await read('modern/packages/marketplace-domain/testing/mock-data.ts');md=md.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`);await write('modern/packages/marketplace-domain/testing/mock-data.ts',md);
let cs=await read('carwow/src/lib/data/daynight-site.ts');cs=cs.replace(/mapUrl:\s*'[^']*'/,`mapUrl: ${JSON.stringify(facts.mapsUrl)}`).replace(/inventoryCount: \d+/,'inventoryCount: 16').replace(/logoLight: '[^']*'/,`logoLight: '/assets/avangard/wordmark-light.svg'`).replace(/logoDark: '[^']*'/,`logoDark: '${logo}'`).replace(/heroSubtitle: '[^']*'/,"heroSubtitle: 'Автомобили във Варна. Свържете се за наличност и оглед.'");await write('carwow/src/lib/data/daynight-site.ts',cs);
let ci=await read('carwow/src/lib/data/daynight-current-inventory.ts');ci=ci.slice(ci.indexOf('export type'),ci.indexOf('export const')).replace('image: string;','image: string;\n gallery: string[];');const current=stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:v.priceEur.toLocaleString('bg-BG')+' €',priceBgn:(v.priceEur*1.95583).toFixed(2)+' лв.',status:'Публикувана обява',date:v.date,mileage:v.mileageKm.toLocaleString('bg-BG')+' км',color:v.color,fuel:v.fuel,power:v.powerHp+' к.с.',transmission:v.transmission,body:v.bodyBg,features:v.features,image:v.images[0],gallery:v.images}));await write('carwow/src/lib/data/daynight-current-inventory.ts',ci+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(current,null,2)};\n`);
let cv=await read('carwow/src/lib/data/daynight-vehicles.ts');cv=cv.replace('gallery: [listing.image]','gallery: listing.gallery').replace(/monthly: `от [^`]*`/,'monthly: \'Условия по запитване\'').replace("lot: `DN-","lot: `AV-");await write('carwow/src/lib/data/daynight-vehicles.ts',cv);
await write('evidence/personalization-files.json',JSON.stringify(changes,null,2));console.log({rebrandedFiles:changes.length,stock:stock.length});
