import fs from 'node:fs/promises';
const root=new URL('./',import.meta.url), read=async p=>JSON.parse(await fs.readFile(new URL(p,root),'utf8'));
const cards=(await read('evidence/stock-cards.json')).slice(0,16), stock=[], provenance=[];
for(const [i,c] of cards.entries()) {
 const d=await read(`evidence/detail-${i+1}.json`), raw=c.parts.find(p=>p.cls==='params').text, info=c.parts.find(p=>p.cls==='info').text;
 const field=k=>d.text.split(k+'\n')[1]?.split('\n')[0];
 const urls=[...new Set(d.images.filter(s=>s.includes('photosorg')&&!s.includes('big1')).map(s=>s.split('?')[0]))].slice(0,4), images=[];
 for(const [n,url] of urls.entries()) {const r=await fetch(url);if(!r.ok)throw Error(url);const file=`vehicle-${String(i+1).padStart(2,'0')}-${n+1}.webp`;await fs.writeFile(new URL('assets/'+file,root),Buffer.from(await r.arrayBuffer()));images.push('/assets/avangard/'+file);provenance.push({file:'assets/'+file,url,listing:c.url,capturedAt:new Date().toISOString(),watermark:'preserved'});}
 const make=c.title.split(' ')[0], model=c.title.slice(make.length).trim().split(',')[0].replace(/Лизинг.*$/,'').trim();
 const fuel=({Дизелов:'Дизел',Бензинов:'Бензин',Хибриден:'Хибрид',Електрически:'Електрически'})[field('Двигател')]||field('Двигател');
 const bodyBg=field('Категория');
 stock.push({id:c.url.match(/obiava-(\d+)/)[1],title:`${make} ${model}`,fullTitle:c.title,make,model,year:Number(field('Дата на производство').match(/\d{4}/)[0]),date:field('Дата на производство'),mileageKm:Number(field('Пробег [км]').replace(/\D/g,'')),priceEur:Number(c.parts[0].text.match(/([\d ]+) €/)[1].replaceAll(' ','')),fuel,transmission:field('Скоростна кутия')==='Автоматична'?'Автоматик':'Ръчна',body:({Джип:'SUV',Комби:'Wagon',Хечбек:'Hatchback',Седан:'Sedan',Купе:'Coupe'})[bodyBg]||'Sedan',bodyBg,powerHp:Number(field('Мощност').replace(/\D/g,'')),engineCc:Number(field('Кубатура [куб.см]')?.replace(/\D/g,''))||null,color:field('Цвят'),vat:'Не се начислява ДДС',sourceUrl:c.url,images,features:info.split('Особености - ')[1]?.split(',').map(s=>s.trim())||[],description:`${make} ${model}, ${raw}. Обявен от AVANGARD AUTO. Потвърдете наличността и условията по телефона преди посещение.`,rawFacts:raw});
}
const logoUrl='https://cdn2.focus.bg/mobile/images/houseslogos/h14628795864514771.pic';const logo=await fetch(logoUrl);await fs.writeFile(new URL('assets/official-logo.png',root),Buffer.from(await logo.arrayBuffer()));provenance.push({file:'assets/official-logo.png',url:logoUrl,capturedAt:new Date().toISOString(),usage:'Original dealer logo from matched Mobile.bg profile; unchanged'});
await fs.writeFile(new URL('stock.json',root),JSON.stringify(stock,null,2));await fs.writeFile(new URL('assets/provenance.json',root),JSON.stringify(provenance,null,2));
const address='бул. Цар Освободител 289',query=encodeURIComponent('AVANGARD AUTO '+address+', Варна, България');
await fs.writeFile(new URL('business-facts.json',root),JSON.stringify({name:'AVANGARD AUTO',shortName:'AVANGARD AUTO',city:'Варна',address,country:'България',phoneDisplay:'0877 800 921',phoneHref:'tel:+359877800921',secondaryPhone:'0896 391 615',email:'',hours:null,appointment:'Обадете се преди посещение',source:'https://avangard-auto.mobile.bg/',contactSource:'https://avangard-auto.mobile.bg/contacts',facebook:'https://www.facebook.com/avangardautovarna/',instagram:'https://www.instagram.com/avangard_auto_varna/',socialVerification:'Matched in owner research; direct access pending',mapsUrl:'https://www.google.com/maps/search/?api=1&query='+query,mapsEmbedUrl:'https://maps.google.com/maps?q='+query+'&output=embed',services:['Продажба на автомобили','Съдействие при регистрация и транзитни номера в КАТ','Транспорт в България','Лизинг — условия по конкретна обява'],unverified:['Работно време','Email','Собствен лизинг','Бартер','Внос по поръчка'],capturedAt:new Date().toISOString(),stockSampleCount:stock.length},null,2));console.log(stock.map(v=>({title:v.title,price:v.priceEur,year:v.year,photos:v.images.length})));
