import fs from 'node:fs/promises';import {chromium} from '../../templates/boxcar/node_modules/playwright/index.mjs';
const key=process.argv[2],root='J:/cars/clients/avangard-auto/evidence',stock=JSON.parse(await fs.readFile('J:/cars/clients/avangard-auto/stock.json'));
const configs={'auto-best':{port:6626,entry:'/',inventory:'/listing-grid',detail:'/listing-detail-v1/1',contact:'/contact',extra:['/about-us','/blog']},carwow:{port:6628,entry:'/',inventory:'/inventory',detail:'/inventory/vw-passat-alltrack-119627',contact:'/contact',extra:['/about','/services','/financing','/sell-your-car','/reviews']},modern:{port:6627,entry:'/cars',inventory:'/bg/cars',detail:'/bg/listing/avangard-'+stock[0].id,contact:'/bg/contact',extra:['/bg/imports','/bg/sell','/bg/lease']}};const c=configs[key];
const b=await chromium.launch({channel:'chrome',headless:true});const result=[];
try {
for(const width of [390,1440]) {const p=await b.newPage({viewport:{width,height:900}});const errors=[],consoleErrors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
 for(const [name,route] of [['entry',c.entry],['inventory',c.inventory],['detail',c.detail],['contact',c.contact],...c.extra.map((x,i)=>['extra-'+i,x])]){try{const r=await p.goto(`http://127.0.0.1:${c.port}${route}`,{waitUntil:'networkidle',timeout:90000});await p.evaluate(async()=>{await document.fonts.ready;for(let y=0;y<document.body.scrollHeight;y+=700){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,70));}window.scrollTo(0,0);});await p.waitForTimeout(300);const data=await p.evaluate(()=>({url:location.href,title:document.title,h1:[...document.querySelectorAll('h1')].map(e=>e.textContent),text:document.body.innerText,overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(i=>i.offsetWidth>0&&i.complete&&i.naturalWidth===0).map(i=>i.src),links:[...document.querySelectorAll('a')].filter(a=>a.getBoundingClientRect().width>0).map(a=>({text:a.textContent?.trim(),href:a.getAttribute('href')})),buttons:[...document.querySelectorAll('button')].filter(a=>a.getBoundingClientRect().width>0).map(a=>({text:a.textContent?.trim(),label:a.getAttribute('aria-label')})),inputs:[...document.querySelectorAll('input,select')].filter(a=>a.getBoundingClientRect().width>0).map(a=>({tag:a.tagName,name:a.name,type:a.type,placeholder:a.getAttribute('placeholder'),label:a.getAttribute('aria-label')}))}));await p.screenshot({path:`${root}/${key}-${name}-${width}.png`,fullPage:true});result.push({name,width,status:r.status(),...data,errors:[...errors],consoleErrors:[...consoleErrors]});console.log(key,width,name,r.status(),data.overflow,data.broken.length);await fs.writeFile(`${root}/${key}-routes.json`,JSON.stringify(result,null,2));}catch(e){result.push({name,width,route,error:e.message});console.log(key,width,name,e.message);}}
 await p.close();}
await fs.writeFile(`${root}/${key}-routes.json`,JSON.stringify(result,null,2));
} finally { await b.close(); }
