import fs from 'node:fs';
const clients=['avangard-auto','champion-auto-pro','astracar'];
const jobs=JSON.parse(fs.readFileSync('J:/cars/audits/2026-09-07/varna-leads/build-tasks.json')).tasks;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const exists=p=>fs.existsSync(p);
for(const c of clients){
 const root=`J:/cars/clients/${c}`, qa=`${root}/qa-final`;let rows=read(`${qa}/results.json`);
 for(const folder of ['modern-stable','modern-final','carwow-final'])if(exists(`${qa}/${folder}/results.json`)){for(const r of read(`${qa}/${folder}/results.json`))rows=rows.filter(x=>x.template!==r.template).concat(r);}
 const supplements={};for(const t of ['auto-best','modern','carwow'])if(exists(`${qa}/supplement/${t}.json`)){supplements[t]=read(`${qa}/supplement/${t}.json`);if(supplements[t].length!==2||supplements[t].some(x=>!x.pass))throw Error(`${c}/${t} supplement incomplete or failed`);}
 if(c==='champion-auto-pro'){const r=rows.find(x=>x.template==='carwow'),i=r.interactions.find(x=>x.width===390),s=supplements.carwow?.find(x=>x.width===390);if(i.galleryChanged===false&&s?.galleryChanged===true){i.originalAttempt={...i};i.galleryChanged=true;i.retestEvidence=`${qa}/supplement/carwow.json`;i.retestReason='Original harness read desktop Swiper images on mobile. Focused retest reads the visible mobile photo and proves thumbnail-selected image change.';i.pass=true;r.pass=r.routes.every(x=>x.pass)&&r.interactions.every(x=>x.pass);}}
 if(c==='avangard-auto'){const logos=read(`${qa}/logo-final/result.json`);if(logos.length!==2||logos.some(x=>!x.pass))throw Error('Avangard logo capture failed');}
 const numericBrowser=read(`${qa}/numeric-browser.json`);if(numericBrowser.length!==4||numericBrowser.some(x=>!x.pass))throw Error(`${c} numeric browser incomplete`);const required=c==='astracar'?['auto-best']:c==='champion-auto-pro'?['modern','carwow']:['auto-best','carwow'];for(const t of required)if(!supplements[t])throw Error(`${c}/${t} required supplement missing`);const facts=read(`${root}/business-facts.json`);const job=jobs.find(x=>x.slug===c);const summaries=[];
 for(const t of ['auto-best','modern','carwow']){
 const r=rows.find(x=>x.template===t);if(!r?.pass)throw Error(`${c}/${t} still lacks passing final browser QA`);
 const p=`${root}/${t}/.client/project.json`,m=read(p);m.state='personalized-local-qa-passed';m.selectedHome='main';m.offeredHomes=m.availableHomes.filter(h=>h.id==='main');m.publicUrl=null;
 const route=t==='modern'?'/cars':'/';const port=t==='auto-best'?job.ports.autoBest:t==='modern'?job.ports.modern:job.ports.carwow;
 m.preview={url:`http://127.0.0.1:${port}${route}`,state:c==='champion-auto-pro'&&t==='auto-best'?'running-owner-review':'stopped-after-verification'};
 m.qa={desktop:true,mobile:true,identity:true,contactPath:true,verifiedAt:new Date().toISOString(),widths:[390,1440],browserEvidence:`${qa}/FINAL.md`,routeChecks:r.routes.length,interactionChecks:r.interactions.length};
 m.businessFacts=`${root}/business-facts.json`;m.stock=`${root}/stock.json`;m.assetProvenance=`${root}/assets/provenance.json`;
 m.limitations=['Local unpublished prospect demo; no agreement or CRM registration implied.','Dated representative stock, not a live feed; confirm availability and prices.','Forms/calculators/provider flows remain demos; no message delivery verified or external enquiry sent.','Generic decorative source artwork and explicitly labelled sample administration remain.','Original asset/license provenance retained; no new rights determination.','Modern exact gallery-trigger focus restoration was not certified; inherited accessibility behavior remains.'];
 fs.writeFileSync(p,JSON.stringify(m,null,2)+'\n');summaries.push(`| ${t} | ${r.routes.length} routes; 2 interaction sequences passed | ${m.preview.url} |`);
 }
 const checks=read(`${qa}/checks.json`);
 if(checks.some(x=>!x.pass))throw Error(`${c} has failed framework checks`);
 for(const r of rows){r.checks=checks.filter(x=>x.template===r.template);r.supplement=supplements[r.template]||[];r.changes=read(`${qa}/changes.json`);r.numericStockEvidence=r.template==='carwow'?`${qa}/numeric-stock.json`:null;}
 fs.writeFileSync(`${qa}/final-results.json`,JSON.stringify(rows,null,2));
 fs.writeFileSync(`${qa}/results.json`,JSON.stringify(rows,null,2));
 const text=`# ${facts.name} — final local Fast Skin verification\n\n2026-09-08. Three independent copies of master version 2026.09.06-refresh-1. Physical J:/cars/clients/${c}; no Git repository. Layouts and runtime retained. No commit, push, deployment, CRM write or outreach.\n\n| Template | Browser QA at 390 / 1440 | Assigned local entry |\n| --- | --- | --- |\n${summaries.join('\n')}\n\nFinal result records: final-results.json. Failed cold/HMR attempts remain separately preserved; only the final passing run is counted. Source scan: source-identity-scan.json. Static old proposal/concept originals are outside the served root in provenance/; their public URLs redirect to contact.\n\nChecks cover home/entry, inventory, an actual listing detail, contact, about/imports, navigation, search/filter, menu Escape/focus where offered, gallery controls where present and enquiry/telephone destination. No call or external form submission was made. See supplemental records for changed home captures and numbered gallery controls.\n\nKnown limits: unpublished local prospect demos; dated representative inventory; provider/form delivery unconfigured; source decorative artwork retained; no new asset-license determination. Modern exact gallery-trigger focus restoration was not certified; inherited accessibility behavior remains. Hidden sample admin fixtures are not dealership operations. Preview processes started for verification were stopped; Champion Auto Best owner preview was restored and rendered on port 6631 (owner-preview.json).\n`;
 const checkText='\n## Framework evidence\n\n'+checks.map(x=>`- ${x.template}: [${x.path.split('/').pop()}](${x.path}) — passed; log updated ${x.modifiedAt}.`).join('\n')+'\n\nSvelte unused-style warnings and optional autofixer refactoring suggestions are retained; no framework errors. No layout refactor was made.\n';
 const changesText='\n## Changes and visual review\n\n'+read(`${qa}/changes.json`).map(x=>`- ${x}`).join('\n')+'\n\n'+read(`${qa}/visual-review.json`).map(x=>`- [${x.path.split('/').pop()}](${x.path}): ${x.finding}`).join('\n')+'\n\nNumeric stock parsing and budget counts: numeric-stock.json; rendered price/mileage filter count checks at both widths: numeric-browser.json. Changed controls and logo captures: supplement/ and logo-final/ where present. Earlier failed attempts remain in their original run folders.\n';
 fs.writeFileSync(`${qa}/FINAL.md`,text+checkText+changesText);
 fs.appendFileSync(`${root}/CLIENT.md`,`\n\n## Final local QA — 2026-09-08\n\nAll three variants have final 390/1440 route and interaction evidence in qa-final/FINAL.md and qa-final/final-results.json. This supersedes older pending status notes. Public URL remains null; forms/providers remain demos.\n`);
 fs.writeFileSync(`${root}/BUILD-STATUS.md`,text+checkText);
}
