import fs from 'node:fs/promises';
import { chromium } from '../../../templates/auto-best/node_modules/playwright/index.mjs';
const out=import.meta.dirname+'/evidence',base='http://127.0.0.1:6461';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const observations=[];
async function record(name,fn){try{const value=await fn();observations.push({name,...value});console.log(name,JSON.stringify(value));}catch(e){observations.push({name,error:e.message});console.log(name,e.message)}await fs.writeFile(out+'/interactions.json',JSON.stringify(observations,null,2));}
for(const width of [390,1440]){
 const page=await browser.newPage({viewport:{width,height:width===390?844:900},hasTouch:width===390,reducedMotion:'reduce'});
 page.setDefaultTimeout(8000);
 const go=async route=>{await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.waitForLoadState('networkidle',{timeout:5000}).catch(()=>{});};
 const shot=async name=>{await page.screenshot({path:`${out}/${width}-${name}.png`});};
 await record(`finance-${width}`,async()=>{await go('/listing-detail-v1/1');const c=page.locator('.dn-finance-calculator');const before=await c.locator('dd').allTextContents();await c.locator('input').fill('10000');await c.locator('select').selectOption('12');const after=await c.locator('dd').allTextContents();await c.scrollIntoViewIfNeeded();await shot('finance');await c.locator('input').fill('999999');await c.locator('select').focus();const clamped=await c.locator('input').inputValue();await c.locator('a').click();await page.waitForLoadState('networkidle');await shot('finance-handoff');return{before,after,clamped,url:page.url(),vehicleVisible:(await page.locator('main').innerText()).includes('Audi RS 6'),body:(await page.locator('main').innerText()).slice(0,1700)};});
 await record(`detail-return-${width}`,async()=>{await go('/listing-grid?make=BMW&sort=price-asc');const count=await page.locator('.dn-listing-results__grid > *').count();await page.locator('.dn-listing-results__grid a').first().click();await page.waitForLoadState('networkidle');const detail=page.url();const back=width===390?page.locator('.dn-detail-mobile-back'):page.locator('.dn-detail-title-card > a');await back.click();await page.waitForLoadState('networkidle');return{count,detail,returned:page.url(),returnedCount:await page.locator('.dn-listing-results__grid > *').count()};});
 await record(`gallery-${width}`,async()=>{await go('/listing-detail-v1/1');const marker=page.locator('.dn-detail-gallery__count');return{html:await marker.evaluate(e=>e.outerHTML),cursor:await marker.evaluate(e=>getComputedStyle(e).cursor),images:await page.locator('.dn-detail-gallery img').count(),buttons:await page.locator('.dn-detail-gallery button').count()};});
 await record(`blog-search-${width}`,async()=>{await go('/blog');await page.getByRole('searchbox').fill('внос');await page.getByRole('searchbox').press('Enter');await page.waitForLoadState('networkidle');const url=page.url();const before=await page.locator('.dn-blog-grid').innerText();await page.locator('.dn-blog-categories').getByRole('link',{name:'Внос',exact:true}).click();await page.waitForLoadState('networkidle');await shot('blog-filtered');return{url,filteredUrl:page.url(),before,after:await page.locator('.dn-blog-grid').innerText()};});
 await record(`video-${width}`,async()=>{await go('/');const play=page.locator('.dn-video-card__play').first();await play.click();await page.waitForTimeout(5000);await shot('video-open');const frame=page.locator('.dn-video-card iframe');const result={frameCount:await frame.count(),src:await frame.first().getAttribute('src'),frameUrls:page.frames().map(f=>f.url())};const close=page.locator('.dn-video-card').first().getByRole('button').filter({visible:true});result.buttons=await page.locator('.dn-video-card').first().locator('button:visible').allTextContents();const stop=page.locator('.dn-video-card').first().locator('button:visible').last();await stop.click();result.focusReturned=await play.evaluate(e=>e===document.activeElement);return result;});
 await record(`home-discovery-${width}`,async()=>{await go('/');const counts=[];for(const route of ['/listing-grid?make=Kia','/listing-grid?body=Sedan','/listing-grid?condition=new','/listing-grid?make=Audi']){await go(route);counts.push({route,count:await page.locator('.dn-listing-results__grid > *').count(),empty:await page.locator('.dn-listing-empty').isVisible()});}return{counts};});
 if(width===390){
  await record('mobile-menu',async()=>{await go('/');const trigger=page.getByRole('button',{name:'Меню',exact:true});await trigger.click();const dlg=page.locator('.dn-mobile-menu');await shot('menu');const initial=await page.evaluate(()=>document.activeElement?.getAttribute('aria-label'));const escaped=[];for(let i=0;i<19;i++){await page.keyboard.press('Tab');escaped.push(await dlg.evaluate(e=>e.contains(document.activeElement)));}const inert=await page.locator('main').evaluate(e=>!!e.closest('[inert]'));await page.keyboard.press('Escape');const restored=await trigger.evaluate(e=>e===document.activeElement);return{initial,tabContained:escaped.every(Boolean),inert,restored};});
  await record('home-mode-keyboard',async()=>{await go('/');const buy=page.getByRole('tab',{name:'Купи',exact:true});await buy.focus();await buy.press('ArrowRight');const selected=await page.getByRole('tab',{name:'Внос',exact:true}).getAttribute('aria-selected');await shot('home-import');return{selected};});
 }else{
  await record('desktop-menu',async()=>{await go('/');const link=page.getByRole('navigation',{name:'Основна навигация',exact:true}).getByRole('link',{name:'Автомобили',exact:true});await link.focus();await link.press('ArrowDown');await shot('mega');const expanded=await link.getAttribute('aria-expanded');const firstFocus=await page.evaluate(()=>document.activeElement?.textContent?.trim());await page.keyboard.press('Escape');return{expanded,firstFocus,closed:await link.getAttribute('aria-expanded'),focusReturned:await link.evaluate(e=>e===document.activeElement)};});
 }
 await page.close();
}
await browser.close();
