import fs from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const catalog=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));
const instructions={
  'auto-best': {install:'Use Node 22.12+ in the Node 22 line. Run `npm ci`.',checks:'`npm run validate` (architecture, assets, Svelte check, production build).',routes:['/','/listing-grid','/listing-detail-v1/1','/about-us','/contact','/blog'],detail:'The current copy passed validation: 73 native application/config files; 85 guarded and referenced assets; zero Svelte errors/warnings. Identity is centralized more than in the captured-page templates. Inventory and hero data still belong to the source dealer and must be replaced per client.'},
  modern: {install:'Use Node >=22.22.0 <23 and pnpm 11.4.0. Run `pnpm install --frozen-lockfile`, then `pnpm --filter @repo/database build` to generate the local Prisma client; this does not connect to a database. The existing `leadSite.staticDemoMode: true` supplies demo inventory. For the local public preview, set the following environment variables before the launch command. The three origins must be distinct. Ports 6466/6467 are reserved configuration here; no API or private app was started. Use appropriate distinct origins for a client copy.\n\n```powershell\n$env:SKIP_ENV_VALIDATION="true"\n$env:AUTOMARKET_PUBLIC_DATA_MODE="demo"\n$env:NEXT_PUBLIC_WEB_URL="http://127.0.0.1:6462"\n$env:NEXT_PUBLIC_API_URL="http://127.0.0.1:6466"\n$env:NEXT_PUBLIC_APP_URL="http://127.0.0.1:6467"\n```\n\nSKIP_ENV_VALIDATION is for this local review only. Hosted work requires its actual validated environment. No source credentials were copied.',checks:'`pnpm --filter web typecheck` passed. Use an appropriately configured `pnpm --filter web build` for a deployment; broader monorepo checks are documented in the source package.',routes:['/cars','/bg/cars','/bg/listing/bmw-x5-m50d-sofia-2020','/bg/contact','/bg/imports','/bg/sell','/bg/lease'],detail:'The full workspace was copied and hash-verified, dependencies were installed independently, and Prisma generation plus the web typecheck passed. The J: copy renders inventory, one detail and contact at both tested widths on 6462. It still has Next image-sizing/LCP and unconfigured development-toolbar warnings. Provider services and form delivery were not configured or certified. It is the least lightweight runtime here despite the compact UI.'},
  carwow: {install:'Use a Node version supported by the retained package, and run `npm ci`.',checks:'`npm run check` and `npm run build` for actual application changes.',routes:['/','/inventory','/inventory/mercedes-benz-gla-45-amg-405323','/contact','/sell-your-car','/financing'],detail:'Use the Cars startup helper. The historical `scripts/dev-local.mjs` intentionally hardcodes source port 6517. Do not use that wrapper from a new client. Desktop and mobile have separate compositions. Budget tiles, contact facts, chat identity and sample status must be reviewed in a skin.'},
  import: {install:'Run `npm ci` using the retained lockfile.',checks:'`npm run check` and `npm run build` for application changes.',routes:['/','/inventory','/inventory/21764342419542174','/contact','/sell-your-car','/financing'],detail:'Preserve the Auxero-derived route structure, the compact mobile shell and existing search/filter contracts. Central source data is in daynight.ts/daynight-listings.json, with additional template identity in routes and assets. This is related to showroom, not an independent design family.'},
  showroom: {install:'Run `npm ci` using the retained lockfile.',checks:'`npm run check` and `npm run build` for application changes.',routes:['/','/inventory','/inventory/11779989521200947','/contact','/sell-your-car','/financing'],detail:'The snapshot came from ELIQ 6404 and was initially copied under the audit key import-eliq, then renamed to the generic local key showroom. Historical screenshots use import-eliq. Keep the red/white stock-led desktop and mobile listing baseline; old ELIQ task ledgers do not govern new clients.'},
  autodeal: {install:'Node >=20; the server has no package dependencies. Run `node server.mjs` with an explicit PORT, or use the Cars helper.',checks:'`npm run build` verifies mirrored resources, i18n and syntax.',routes:['/','/home02','/home03','/home04','/home05','/home06','/home07','/home08','/home09','/home10','/listing-grid','/listing-detail-v1/1','/contact'],detail:'This is the full existing Node/static AutoDeal library, not the newer native auto-best. It retains 150 stored routes including locales/variants, and 479 local resources. All ten home layouts render locally. Some Bulgarian text is partial/mixed and source vehicle labels do not match their imagery. These are mandatory content corrections in a client skin.'},
  boxcar: {install:'Existing moved node_modules is retained for the local preview. A new copy uses `npm ci`.',checks:'`npm run check` and `npm run build`. Existing `scripts/flows.mjs` covers deeper interactions.',routes:['/','/listings/','/listing/ranger-white-2022/','/contact-us/','/about-us/','/compare/','/calculator/'],detail:'One local home only. Original menu labels Home 2-10 alias Home 1. Data is checked-in captured HTML/JSON with local interaction adapters, not a WordPress backend. Keep all real captured detail routes; verify forms and filter URLs after a skin. Mobile needs a compact filter/intro treatment in a future shared template task.'},
  rencar: {install:'Existing moved node_modules is retained for the local preview. A new copy uses `npm ci`.',checks:'`npm run check` and `npm run build`.',routes:['/','/index-2.html','/index-3.html','/index-4.html','/index-5.html','/car.html','/car-2.html','/car-single.html','/contact.html'],detail:'Five real homes, 45 compiled page components. Do not rerun scripts/prepare.mjs during a skin: it regenerates page components from captured source. Home 2 and Home 5 are the first dealer-adaptation candidates. Booking dates, driver age, daily prices and checkout need a shared conversion pass. Current mobile pages are tall and put the catalog below large hero/filter sections.'},
  motoria: {install:'Existing moved node_modules is retained for the local preview. A new copy uses `npm ci`.',checks:'`npm run check` and `npm run build`.',routes:['/','/inventory/','/listings/bmw-m5/','/pricing/','/contact-us/','/about-us/','/blog/'],detail:'The local name is Motoria, but the implementation reproduces Motors (Stylemix). One captured home and one vehicle detail; nine pricing styles are not nine home variants. Server-rendered snapshots retain legacy widgets; uncaptured destinations often leave to the source site. Vendor bars, external detail links and mismatched page skins need completion before a client offer.'},
  nusavo: {install:'Existing moved node_modules is retained for the local preview. A new copy uses `npm ci`.',checks:'`npm run check` and `npm run build`.',routes:['/','/car-listing/','/car-listing/urbango-hatchback/','/contact-us/','/about-us/','/cart/','/checkout/'],detail:'One home and 36 page components, including rental cart/account/checkout demo screens. Do not rerun scripts/generate.mjs during a skin. A remote CSS mask failed CORS in the initial audit and again while filtering the fleet. A quiet post-relocation homepage sample did not resolve this state-dependent issue. Prioritize for rental leads, or do one dealer adaptation before expecting branding-only sales demos.'}
};
for(const t of catalog.templates) {
  const dir=path.join(root,t.path),meta=path.join(dir,'.template'); await fs.mkdir(meta,{recursive:true});
  let manifest=null;try{manifest=JSON.parse(await fs.readFile(path.join(meta,'source-manifest.json'),'utf8'));}catch{}
  await fs.writeFile(path.join(meta,'template.json'),JSON.stringify({...t,sourceSnapshot:manifest?{source:manifest.source,head:manifest.git.head,branch:manifest.git.branch,includesDirtyFiles:!!manifest.git.status,files:manifest.files.length,bytes:manifest.bytes}:null,personalizationRequired:true,crmRegistration:'not-performed'},null,2));
  const i=instructions[t.key];
  const source=manifest?`${manifest.source}; ${manifest.git.head||'no Git SHA'}${manifest.git.status?' plus current uncommitted files':''}`:`Moved intact from J:/cars/${t.key}. See audits/2026-09-06/relocations.json.`;
  const doc=`# ${t.name}\n\nKey: \`${t.key}\` · version: \`${t.version}\` · family: \`${t.family}\`.\n\n${t.note}\n\n## Status\n\n${t.readiness}. Source branding/demo content is retained as a visual baseline. This is a candidate for personalization, not a finished generic config-driven template or a sendable lead demo.\n\n## Provenance\n\n${source}\n\nExisting license/asset notes remain with the source. No new multi-client rights determination was made. Source instructions and old project task ledgers are historical; J:/cars/AGENTS.md governs this copy.\n\n## Run\n\n${i.install}\n\nFrom J:/cars, on a free port:\n\n\`\`\`powershell\n./scripts/start-preview.ps1 -Template ${t.key} -Port ${t.libraryPort}\n\`\`\`\n\nSuggested library URL: http://127.0.0.1:${t.libraryPort}${t.entry}. The suggestion is not proof that a listener is running; see the audit runtime record. Original inspected source port: ${t.sourcePort||'none; inspected the new 6460 library runtime'}.\n\n${i.checks}\n\n## Real homepage choices\n\n${t.homes.map(h=>`- \`${h.id}\`: \`${h.route}\``).join('\n')}\n\nCopy the whole project to retain all variants. Select a primary entry after copying; retain alternate-home choice links when requested.\n\n## Personalization boundaries\n\n${t.brandFiles.map(f=>`- \`${f}\``).join('\n')}\n\nThese are current code/data ownership locations, not a promise that one config edits the whole app. Scan every retained route, metadata, contact value and identity-bearing asset after changes.\n\n${i.detail}\n\n## Representative QA routes\n\n${i.routes.map(r=>`- \`${r}\``).join('\n')}\n\nUse 390 and 1440 px, plus every offered home. Exercise navigation, filters, detail return, overlay dismissal and the main contact path. Existing source data and frontend feedback do not prove real form delivery or a working provider integration.\n`;
  await fs.writeFile(path.join(dir,'TEMPLATE.md'),doc);
  await fs.writeFile(path.join(dir,'AGENTS.md'),`# ${t.name} template instructions\n\nRead J:/cars/AGENTS.md, this TEMPLATE.md and .template/template.json first. This is a reusable source baseline. Preserve the current UI/UX. For a lead, clone into J:/cars/clients/<client>/${t.key} before changing identity, colors, assets or copy. Historic source-client instructions and task ledgers do not authorize work in this copy. Use the Cars startup helper with a free port rather than old source-specific launch commands. No sending, deployment or CRM state change is implied.\n`);
  const readme=path.join(dir,'README.md'),archived=path.join(meta,'source-readme.md');
  if(!(await fs.access(archived).then(()=>true).catch(()=>false)))await fs.copyFile(readme,archived).catch(()=>{});
  await fs.writeFile(readme,`# ${t.name}\n\nRead [TEMPLATE.md](./TEMPLATE.md) for current source lineage, run commands, real homepage variants, personalization files and limitations. This template belongs to the J:/cars library; the original source README is retained privately in .template/source-readme.md.\n\n${t.note}\n\nFor lead work, copy first using J:/cars/scripts/new-client.mjs. Preserve the template layout and change branding/content in the client copy.\n`);
}
const rows=catalog.templates.map(t=>`| [${t.name}](./${t.path}/TEMPLATE.md) | ${t.sourcePort||'full library'} | ${t.desktop.toFixed(1)} | ${t.mobile.toFixed(1)} | ${t.homes.length} | ${t.priority} |`).join('\n');
await fs.writeFile(path.join(root,'README.md'),`# Cars template library\n\nTen source baselines, stable names and independent client copies. Start with **Auto Best**, and use Modern or Carwow when a different sales direction helps. Shared polishing happens once in a master; client work stays focused on logo, colors, assets and verified copy.\n\nRead [the full browser audit](./audits/2026-09-06/REPORT.md), [the build workflow](./docs/WORKFLOW.md), [agent instructions](./AGENTS.md), or [the machine-readable catalog](./catalog.json).\n\n## Current catalog\n\nScores are comparative visual/UX judgement out of 10, not a production certification.\n\n| Template | Original port | Desktop | Mobile | Real homes | Recommended use |\n|---|---:|---:|---:|---:|---|\n${rows}\n\n## Available previews\n\n- [AutoDeal full library](http://127.0.0.1:6460/) — all ten homepages.\n- [Auto Best library copy](http://127.0.0.1:6461/) — independent of original 5173.\n- [Modern library copy](http://127.0.0.1:6462/cars) — public static demo mode.\n- [Carwow library copy](http://127.0.0.1:6463/), [Import library copy](http://127.0.0.1:6464/), [Showroom library copy](http://127.0.0.1:6465/inventory).\n- [Boxcar](http://127.0.0.1:6450/), [Rencar](http://127.0.0.1:6430/), [Nusavo](http://127.0.0.1:6420/), [Motors alias Motoria](http://127.0.0.1:6440/) — moved sources, original ports retained.\n\nAll ten local library previews were rendered during this setup. Runtime identities and verification scope are in the audit. The original M: previews remain separate and available.\n\n## Client work\n\n[Day & Night](./clients/dayandnight/CLIENT.md) has a [strict Rencar branding preview](./clients/dayandnight/rencar/README.md) at [port 6601](http://127.0.0.1:6601/), using the original five home layouts and Home menu. The initial custom rebuild was rejected and archived. [ELIQ](./clients/eliqauto/CLIENT.md) and [ASKO96](./clients/asko96/CLIENT.md) remain prospect folder scaffolds. No outreach has been sent.\n\nExample: “Build ASKO96 using auto-best, carwow and modern; keep their layouts and change branding, assets and copy.”\n\n\`\`\`powershell\nnode scripts/new-client.mjs --client asko96 --templates auto-best,carwow,modern --dry-run\n\`\`\`\n\nRemove --dry-run only when that build is requested. The helper preserves every real homepage variant, rejects occupied destinations and records source/version lineage. It creates source copies that still need personalization and QA.\n\nThe library intentionally preserves source-branded layouts for the next discussion. Captured-page templates still need shared brand-data extraction or dealer adaptation before every lead can be a quick config-only reskin.\n`);
