import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {gunzipSync} from 'node:zlib';
import {applyLeadBranding,assertLeadBranding,preserveTemplatePalettes,PUBLIC_ROOTS} from './publishing/lead-branding.mjs';
const root=path.resolve(import.meta.dirname,'..'),pack=JSON.parse(gunzipSync(fs.readFileSync(process.env.CARS_BRAND_TEST_MASTERS||path.join(root,'leads/varna/branding/generated-masters.json.gz'))));
const require=createRequire(process.env.CARS_BRAND_TEST_SHARP||path.join(root,'runtime/varna-tools/package.json')),sharp=require('sharp');
const hash=b=>createHash('sha256').update(b).digest('hex'),text=s=>Buffer.from(s),json=v=>text(JSON.stringify(v));
const nativeModern='// LEAD_SITE_CONFIG_START\nconst leadSite={\n accent: "#30343b",\n desktopAccent: "#4b5057",\n logoPath: "/dealer-brand/logo-on-light.webp",\n logoOnLight: "/dealer-brand/logo-on-light.webp",\n logoOnDark: "/dealer-brand/logo-on-dark.webp"\n};';
const nativeImport='export const dealerTheme = {\n accent: "#292c33",\n accentHover: "#17191e",\n accentContrast: "#ffffff"\n};';
function fixture(slug){const files=new Map([['modern/packages/marketplace/lead-site.ts',text(nativeModern.replace('#30343b','#c40101'))],['import/src/lib/config/dealer.ts',text(nativeImport.replace('#292c33','#c40101'))],['auto-best/src/lib/data/dealer-profile.json',json({business:{name:'Fixture dealer',phone:'+359123456789',accent:'#c40101',logo:'/branding/logo-on-light.png'}})],['business-facts.json',json({phone:'+359123456789',address:'Recorded address',accent:'#c40101'})],['stock.json',json([{id:'record-1',price:18000,currency:'EUR',image:'/vehicle/example.webp'}])],['app/lib/dealer.json',json({id:slug,name:'Fixture dealer',logo:{light:'/dealer-app/logo-light-old.webp',dark:'/dealer-app/logo-dark-old.webp',icon:'/dealer-app/icon.png'}})],['app/app/tokens.stylex.ts',text('export const tokens = { background: "#30343b", color: "#ffffff" };')]]);
 for(const [key,publicRoot]of Object.entries(PUBLIC_ROOTS)){files.set(publicRoot+'dealer-brand/logo-on-light.webp',text('old light image'));files.set(publicRoot+'dealer-brand/logo-on-dark.webp',text('old dark image'));files.set(key+'/src/logo-consumer.ts',text('export const light="/branding/logo-on-light.png", dark="/branding/logo-on-dark.png";'));}
 const manifest={slug,packaging:{version:'5'},templateSources:Object.fromEntries(Object.keys(PUBLIC_ROOTS).map(key=>[key,{repository:'darkapoparka/cars',path:'templates/'+key,revision:'1'.repeat(40)}]))};
 const readTemplate=(source,file,optional)=>source.path.endsWith('/modern')?nativeModern:source.path.endsWith('/import')?nativeImport:file==='app/tokens.stylex.ts'?'export const tokens = { background: "#30343b", color: "#ffffff" };':optional?null:(()=>{throw Error('Unexpected fixture template request');})();return {files,manifest,readTemplate};}
function fingerprint(files){return hash(JSON.stringify([...files].map(([p,b])=>[p,hash(b)])));}
async function branded(slug='dm-auto-varna'){const state=fixture(slug);state.contract=await applyLeadBranding(state.files,state.manifest,{master:pack.dealers[slug],generation:pack,sharp,readTemplate:state.readTemplate});return state;}
test('all ten real generated inputs decode into matching transparent light/dark pairs',async()=>{assert.equal(sharp.versions.sharp,'0.35.5');assert.equal(Object.keys(pack.dealers).length,10);for(const slug of Object.keys(pack.dealers)){const {files,manifest,contract}=await branded(slug);assertLeadBranding(files,manifest);assert.equal(contract.assets.length,60);const prefix='auto-best/static'+contract.publicBase+'/';const a=await sharp(files.get(prefix+'logo-on-light.webp')).ensureAlpha().raw().toBuffer({resolveWithObject:true}),b=await sharp(files.get(prefix+'logo-on-dark.webp')).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(a.info.width,512);assert.deepEqual(a.info,b.info);let transparent=0,opaque=0;for(let i=0;i<a.data.length;i+=4){assert.equal(a.data[i+3],b.data[i+3]);if(a.data[i+3]===0)transparent++;if(a.data[i+3]>230){opaque++;const dark=[...a.data.subarray(i,i+3)],light=[...b.data.subarray(i,i+3)];assert(Math.max(...dark)<=48 && Math.max(...dark)-Math.min(...dark)<=16,"Rendered near-black monochrome, including Lanczos edge overshoot");assert(Math.min(...light)>=250,"Rendered white monochrome");}}assert(transparent>100);assert(opaque>100);const mark=await sharp(files.get(prefix+'mark-on-light.webp')).metadata();assert.equal(mark.width,256);assert.equal(mark.height,256);const ico=files.get(prefix+'favicon.ico');assert.equal(ico.readUInt16LE(2),1);assert.equal(ico.readUInt16LE(4),3);assert.equal(JSON.parse(files.get('business-facts.json')).accent,'#c40101');assert(files.get('modern/packages/marketplace/lead-site.ts').toString().includes('#30343b'));}});
test('raw business facts, source profile, listings and amounts are unchanged',async()=>{const state=fixture('dm-auto-varna'),before=new Map(state.files);await applyLeadBranding(state.files,state.manifest,{master:pack.dealers['dm-auto-varna'],generation:pack,sharp,readTemplate:state.readTemplate});for(const name of ['business-facts.json','stock.json','auto-best/src/lib/data/dealer-profile.json'])assert.deepEqual(state.files.get(name),before.get(name));});
test('invalid creative input is atomic and cannot partly recolour a candidate',async()=>{const state=fixture('dm-auto-varna'),before=fingerprint(state.files);await assert.rejects(()=>applyLeadBranding(state.files,state.manifest,{master:{...pack.dealers['dm-auto-varna'],sha256:'0'.repeat(64)},generation:pack,sharp,readTemplate:state.readTemplate}),/hash mismatch/);assert.equal(fingerprint(state.files),before);});
test('a restored palette cannot be changed back to a dealer red',async()=>{const {files,manifest}=await branded();const p='modern/packages/marketplace/lead-site.ts';files.set(p,text(files.get(p).toString().replace('#30343b','#ff0000')));assert.throws(()=>assertLeadBranding(files,manifest),/palette override/);});
test('missing dark logo, changed logo bytes and absent contract each stop publication',async()=>{const {files,manifest,contract}=await branded();const name=contract.assets.find(r=>r.path.endsWith('logo-on-dark.webp')).path;const missing=new Map(files);missing.delete(name);assert.throws(()=>assertLeadBranding(missing,manifest),/missing or changed/);const changed=new Map(files);changed.set(name,text('not a logo'));assert.throws(()=>assertLeadBranding(changed,manifest),/missing or changed/);const absent=new Map(files);absent.delete('.cars-branding.json');assert.throws(()=>assertLeadBranding(absent,manifest),/Missing branding input/);});
test('an unapproved token colour is rejected before candidate mutation',async()=>{const state=fixture('dm-auto-varna');state.files.set('app/app/tokens.stylex.ts',text('export const tokens = { background: "#ff0000", color: "#ffffff" };'));const before=fingerprint(state.files);await assert.rejects(()=>applyLeadBranding(state.files,state.manifest,{master:pack.dealers['dm-auto-varna'],generation:pack,sharp,readTemplate:state.readTemplate}),/palette drift/);assert.equal(fingerprint(state.files),before);});
test('a second application is rejected rather than overwriting approval lineage',async()=>{const state=await branded();await assert.rejects(()=>applyLeadBranding(state.files,state.manifest,{master:pack.dealers['dm-auto-varna'],generation:pack,sharp,readTemplate:state.readTemplate}),/already exists/);});
test('new logo consumers are versioned while source facts retain original provenance',async()=>{const {files,contract}=await branded();const app=JSON.parse(files.get('app/lib/dealer.json'));assert.equal(app.logo.light,contract.publicBase+'/logo-on-light.webp');assert.equal(app.logo.dark,contract.publicBase+'/logo-on-dark.webp');assert.equal(app.logo.icon,contract.publicBase+'/app-icon.png');assert(files.get('modern/src/logo-consumer.ts').toString().includes(contract.publicBase));assert(!files.get('auto-best/src/lib/data/dealer-profile.json').toString().includes(contract.publicBase));});
