import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {specializeModernDemoDatabase,DATABASE_PATH,STATIC_DATABASE_MODULE,PRISMA_CONSUMERS,DEMO_BRIDGE_PATH} from './publishing/modern-demo-database.mjs';
const fixture=name=>fs.readFileSync(new URL('./fixtures/varna/'+name,import.meta.url));
const manifest={slug:'dm-auto-varna',candidate:{approved:false,nativeReleaseQualification:false}};
const input=()=>new Map([['modern/packages/database/package.json',Buffer.from(JSON.stringify({dependencies:{'@prisma/client':'7.4.2'},devDependencies:{prisma:'7.4.2'}}))],...Object.keys(PRISMA_CONSUMERS).map(p=>[p,fixture('modern-'+p.split('/').at(-1)+'.txt')]),[DATABASE_PATH,fixture('modern-database-index.ts.txt')],['modern/apps/web/public-runtime.ts',fixture('modern-public-runtime.ts.txt')],['modern/packages/marketplace/lead-site.ts',Buffer.from('// LEAD_SITE_CONFIG_START\nexport const leadSite: LeadSiteConfig = {\n  slug: "dm-auto-varna",\n  staticDemoMode: true,\n};\n// LEAD_SITE_CONFIG_END')],['modern/packages/security/index.ts',Buffer.from('existing security')],['modern/packages/marketplace-domain/testing/mock-data.ts',Buffer.from('dated stock')]]);
test('static-only specialization removes DB engine imports without changing security, stock or policy',()=>{const f=input(),before=new Map(f),r=specializeModernDemoDatabase(f,manifest);assert.equal(r.accidentalReadsAndWrites,'throw');for(const [p,b]of before)if(p!==DATABASE_PATH&&!Object.hasOwn(PRISMA_CONSUMERS,p))assert.equal(f.get(p),b);assert.match(f.get(DATABASE_PATH).toString(),/generated\/internal\/prismaNamespace/);assert.doesNotMatch(f.get(DATABASE_PATH).toString(),/PrismaNeon|webSocketConstructor|from "@neondatabase/);});
test('fails closed and atomically for live mode, changed source, wrong dealer and changed runtime policy',()=>{for(const mutate of [f=>f.set(DATABASE_PATH,Buffer.from('other database')),f=>f.set('modern/apps/web/public-runtime.ts',Buffer.from('other policy')),f=>f.set('modern/packages/marketplace/lead-site.ts',Buffer.from(String(f.get('modern/packages/marketplace/lead-site.ts')).replace('staticDemoMode: true','staticDemoMode: false')))]){const f=input();mutate(f);const before=[...f];assert.throws(()=>specializeModernDemoDatabase(f,manifest));assert.deepEqual([...f],before);}assert.throws(()=>specializeModernDemoDatabase(input(),{...manifest,slug:'other'}));assert.throws(()=>specializeModernDemoDatabase(input(),{...manifest,candidate:{approved:true}}));});
test('accidental database reads and writes both throw, never report success',()=>{const code=STATIC_DATABASE_MODULE.split('\n').filter(l=>!l.startsWith('import ')&&!l.startsWith('export type ')&&!l.startsWith('export * ')&&!l.startsWith('export { ')).join('\n').replaceAll('export const ','const ').replace('(): PrismaClient','()').replace('{} as PrismaClient','{}')+'\n globalThis.result={database,getDatabase};';const sandbox={};vm.runInNewContext(code,sandbox);assert.throws(()=>sandbox.result.getDatabase(),/unavailable/);assert.throws(()=>sandbox.result.database.marketplaceListing,/unavailable/);assert.throws(()=>{sandbox.result.database.foo='write';},/unavailable/);});

test('Prisma value imports use enum/type bridge, without importing a query compiler or weakening database failures',()=>{const f=input(),before=new Map(f);specializeModernDemoDatabase(f,manifest);for(const p of Object.keys(PRISMA_CONSUMERS)){assert.equal(String(f.get(p)).replace('from "./cars-demo-client"','from "./generated/client"'),String(before.get(p)));}assert.match(f.get(DEMO_BRIDGE_PATH).toString(),/generated\/internal\/prismaNamespace/);});
test('changed Prisma value consumer rejects atomically',()=>{const f=input();f.set(Object.keys(PRISMA_CONSUMERS)[0],Buffer.from('changed'));const before=[...f];assert.throws(()=>specializeModernDemoDatabase(f,manifest));assert.deepEqual([...f],before);});

test("requires the exact generated server namespace compiler",()=>{const f=input();f.set("modern/packages/database/package.json",Buffer.from(JSON.stringify({dependencies:{"@prisma/client":"8.0.0"}})));const before=[...f];assert.throws(()=>specializeModernDemoDatabase(f,manifest));assert.deepEqual([...f],before);});
