import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {safeIgnoreBuildCommand} from './publishing/ignored-build.mjs';
const root=process.env.TEMP || process.env.TMPDIR || '/tmp';
const fixture=fs.mkdtempSync(path.join(root,'ignore-fixture-'));
const empty=fs.mkdtempSync(path.join(root,'ignore-no-git-'));
const git=args=>execFileSync('git',args,{cwd:fixture,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
git(['init','-q']);git(['config','user.name','Cars build test']);git(['config','user.email','test@example.invalid']);
fs.mkdirSync(path.join(fixture,'docs'));fs.writeFileSync(path.join(fixture,'app.js'),'export const v=1;\n');
fs.writeFileSync(path.join(fixture,'docs/readme.md'),'one\n');git(['add','.']);git(['commit','-qm','fixture base']);const base=git(['rev-parse','HEAD']);
fs.writeFileSync(path.join(fixture,'docs/readme.md'),'two\n');git(['add','.']);git(['commit','-qm','docs only']);const docs=git(['rev-parse','HEAD']);
fs.writeFileSync(path.join(fixture,'app.js'),'export const v=2;\n');git(['add','.']);git(['commit','-qm','app change']);const code=git(['rev-parse','HEAD']);
const run=(p,c,cwd=fixture)=>spawnSync(process.env.CARS_TEST_SHELL || (process.platform==='win32'?path.resolve(execFileSync('git',['--exec-path'],{encoding:'utf8'}).trim(),'../../../usr/bin/sh.exe'):'sh'),['-c',safeIgnoreBuildCommand],{cwd,env:{...process.env,VERCEL_GIT_PREVIOUS_SHA:p,VERCEL_GIT_COMMIT_SHA:c},stdio:'ignore'}).status;
test('fits Vercel command length',()=>assert.ok(safeIgnoreBuildCommand.length<=256));
test('known docs-only changes skip',()=>assert.equal(run(base,docs),0));
test('application changes build',()=>assert.equal(run(docs,code),1));
test('missing comparison commits build',()=>assert.equal(run('',code),1));
test('invalid comparison commits build',()=>assert.equal(run('ffffffffffffffffffffffffffffffffffffffff',code),1));
test('archive without Git metadata builds instead of failing with 129',()=>assert.equal(run(base,code,empty),1));
process.on('exit',()=>{fs.rmSync(fixture,{recursive:true,force:true});fs.rmSync(empty,{recursive:true,force:true});});
