import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {git,writeJson,fingerprint,excluded,inside,resolveIdentity,validateManifest,sha256} from './lib/workflow.mjs';
import {verifyTemplate,promoteTemplate} from './template-release.mjs';
import {dealerGuidance} from './lib/dealer-guidance.mjs';
import {validateRegistry,registryViews,indexDeployments} from './index-deployments.mjs';
import {exportDealer,pushExport,packageDigest,validateReview} from './export-dealer.mjs';

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'cars-workflow-'));t.after(()=>{const resolved=fs.realpathSync(root);assert.ok(resolved.startsWith(fs.realpathSync(os.tmpdir())+path.sep));fs.rmSync(resolved,{recursive:true,force:true});});return root;}
function put(root,p,text){fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),text);}
function init(root){fs.mkdirSync(root,{recursive:true});git(root,['init','-b','main']);git(root,['config','user.name','Workflow fixture']);git(root,['config','user.email','fixture@example.invalid']);git(root,['config','core.autocrlf','false']);}
function commit(root){git(root,['add','.']);git(root,['commit','-m','fixture']);return git(root,['rev-parse','HEAD']);}
const manifest=(slug='demo')=>({schemaVersion:1,slug,repository:'fixture/cars-'+slug,defaultBranch:'main',variants:[{key:'auto-best',base:'',entry:'/'},{key:'import',base:'/variant-2',entry:'/variant-2/'},{key:'carwow',base:'/variant-3',entry:'/variant-3/'}],extraAssets:['assets'],packaging:{version:'1'}});

test('duplicate aliases, compact spellings and stable IDs resolve before cloning',t=>{const root=fixture(t);fs.mkdirSync(path.join(root,'clients/asko-96'),{recursive:true});writeJson(path.join(root,'docs/DEPLOYMENT-INVENTORY.json'),{aliases:{asko96:'asko-96'},dealers:[{slug:'asko-96',id:'dealer-1'}]});assert.equal(resolveIdentity(root,'asko96').slug,'asko-96');assert.equal(resolveIdentity(root,'asko--96').exists,true);assert.equal(resolveIdentity(root,'another','dealer-1').slug,'asko-96');assert.equal(resolveIdentity(root,'new').exists,false);assert.throws(()=>resolveIdentity(root,'../escape'));});
test('approved snapshot integrity handles CRLF but rejects content drift and release holds',t=>{const root=fixture(t),dir=path.join(root,'templates/import');put(root,'templates/import/code.ts','const value=1;\n');const digest=fingerprint(dir).digest;writeJson(path.join(root,'templates.lock.json'),{templates:{import:{status:'approved',commit:'a'.repeat(40),exportPolicy:'cars-source-v1',snapshotPath:'templates/import',digest}}});put(root,'templates/import/code.ts','const value=1;\r\n');assert.equal(verifyTemplate(root,'import').digest,digest);put(root,'templates/import/code.ts','const value=2;\n');assert.throws(()=>verifyTemplate(root,'import'),/drift/);assert.throws(()=>verifyTemplate(root,'modern'),/No release lock/);for(const p of ['.git/config','.env.local','node_modules/a','src/credentials.json','public/server.key'])assert.equal(excluded(p),true);assert.equal(excluded('LICENSE'),false);assert.equal(excluded('provenance/source.md'),false);assert.throws(()=>inside(root,'../outside'));});
test('manifest preserves both trios and rejects a fourth design or route mismatch',()=>{const m=manifest();assert.equal(validateManifest(m),m);const standard=structuredClone(m);standard.variants[1]={key:'modern',base:'/variant-2',entry:'/variant-2/cars'};validateManifest(standard);assert.throws(()=>validateManifest({...m,variants:[...m.variants,{key:'modern'}]}));assert.throws(()=>validateManifest({...m,extraAssets:['../private']}));});
test('portable instructions and registry retain evidence and actual Import routes',t=>{const root=fixture(t),m=manifest();for(const v of m.variants)put(root,'clients/demo/'+v.key+'/package.json','{}');writeJson(path.join(root,'clients/demo/dealer.json'),m);writeJson(path.join(root,'docs/DEPLOYMENT-INVENTORY.json'),{schemaVersion:2,aliases:{},dealers:[{slug:'demo',localPath:'clients/demo',variants:[],delivery:{state:'READY',url:'https://example.invalid'},evidence:{ownerReview:{state:'unknown'},browser:{state:'unknown'}},extraPreserved:'yes'}]});const registry=indexDeployments(root);validateRegistry(registry,root);assert.equal(registry.dealers[0].extraPreserved,'yes');assert.equal(registry.dealers[0].evidence.browser.state,'unknown');assert.match(registryViews(registry).deployments,/import \/variant-2\//);const text=dealerGuidance({slug:'demo',variants:m.variants,workflowCommit:'a'.repeat(40)});assert.doesNotMatch(text,/[A-Z]:[\\/]/);assert.match(text,/pnpm|npm/);assert.match(text,/publishing mirror/);assert.throws(()=>validateRegistry({...registry,dealers:[registry.dealers[0],registry.dealers[0]]}),/Duplicate/);});
test('export retains remote ancestry, refuses unexplained mirror changes and rejects remote races',t=>{
 const area=fixture(t),root=path.join(area,'cars'),remote=path.join(area,'remote');init(root);init(remote);put(remote,'app.txt','publishing-only fix\n');const remoteCommit=commit(remote);git(root,['config',`url.${remote.replaceAll('\\','/')}.insteadOf`,'https://github.com/fixture/cars-demo.git']);
 const m=manifest();writeJson(path.join(root,'clients/demo/dealer.json'),m);put(root,'source.txt','source\n');const sourceCommit=commit(root);const pkg=path.join(area,'package');writeJson(path.join(pkg,'dealer.json'),m);writeJson(path.join(pkg,'.cars-package.json'),{sourceCommit,packagingVersion:'1'});put(pkg,'app.txt','reviewed canonical fix\n');put(pkg,'assets/logo.svg','<svg/>');put(pkg,'.env.secret','not exported');const payload=packageDigest(pkg).files.filter(f=>f.path!=='.cars-package.json');writeJson(path.join(pkg,'.cars-package.json'),{sourceCommit,packagingVersion:'1',payload,payloadDigest:sha256(JSON.stringify(payload))});const originalIndex=fs.readFileSync(path.join(root,'.git/index'));const proposal=exportDealer({root,slug:'demo',packageDir:pkg,targetBranch:'codex/pilot'});assert.equal(proposal.parent,remoteCommit);assert.ok(proposal.changes.includes('app.txt'));assert.throws(()=>exportDealer({root,slug:'demo',packageDir:pkg,write:true}),/reconciliation/);
 const reviewFile=path.join(area,'review.json');writeJson(reviewFile,{remoteCommit,candidateDigest:proposal.candidateDigest,changes:proposal.changes.map(p=>({path:p,resolution:'canonical-source',reason:'Fixture explicitly reconciles this payload.'}))});const result=exportDealer({root,slug:'demo',packageDir:pkg,reviewFile,write:true,targetBranch:'codex/pilot'});assert.equal(git(root,['rev-parse',result.commit+'^']),remoteCommit);assert.deepEqual(fs.readFileSync(path.join(root,'.git/index')),originalIndex);assert.ok(!git(root,['ls-tree','-r','--name-only',result.commit]).includes('.env.secret'));
 const receiptFile=path.join(result.proposalDirectory,'export.json');pushExport({root,receiptFile});assert.equal(git(remote,['rev-parse','refs/heads/codex/pilot']),result.commit);assert.equal(git(remote,['rev-parse','main']),remoteCommit);
 const next=exportDealer({root,slug:'demo',packageDir:pkg,write:true,targetBranch:'codex/pilot'});put(remote,'another.txt','new owner change');commit(remote);assert.throws(()=>pushExport({root,receiptFile:path.join(next.proposalDirectory,'export.json')}),/Remote advanced/);
});

test('template promotion refuses dirty snapshots and pins the exact fetched release without altering clients',t=>{
 const area=fixture(t),root=path.join(area,'cars'),upstream=path.join(area,'upstream');init(root);init(upstream);
 put(root,'templates/import/code.ts','before\n');put(root,'templates/import/AGENTS.md','old wrapper\n');put(root,'clients/keep/source.txt','owner work\n');
 const before=fingerprint(path.join(root,'templates/import')).digest;
 writeJson(path.join(root,'templates.lock.json'),{schemaVersion:1,templates:{import:{status:'reconciliation-required',repository:'fixture/cars-template-import',snapshotPath:'templates/import',digest:before,exportPolicy:'cars-source-v1'}}});
 commit(root);put(upstream,'code.ts','after\n');put(upstream,'LICENSE','retained license\n');put(upstream,'.env','secret fixture');const release=commit(upstream);
 git(upstream,['remote','add','origin','https://github.com/fixture/cars-template-import.git']);git(upstream,['config','url.'+upstream.replaceAll('\\','/')+'.insteadOf','https://github.com/fixture/cars-template-import.git']);
 put(root,'templates/import/code.ts','owner edit\n');assert.throws(()=>promoteTemplate({root,key:'import',sourceRepo:upstream,commit:release}),/unexpected edits/);
 put(root,'templates/import/code.ts','before\n');const proposal=promoteTemplate({root,key:'import',sourceRepo:upstream,commit:release});assert.ok(proposal.changes.some(c=>c.path==='code.ts'));assert.ok(!proposal.changes.some(c=>c.path==='.env'));
 const evidence=path.join(area,'qa.json');writeJson(evidence,{repository:'fixture/cars-template-import',commit:release,approved:true,verifiedAt:'2026-09-12',checks:[{command:'fixture content comparison',status:'passed'}],standalone:{mobile:true,desktop:true},runtime:{node:'24'}});
 promoteTemplate({root,key:'import',sourceRepo:upstream,commit:release,evidence,write:true});assert.equal(verifyTemplate(root,'import').commit,release);assert.equal(fs.readFileSync(path.join(root,'clients/keep/source.txt'),'utf8'),'owner work\n');assert.equal(fs.existsSync(path.join(root,'templates/import/.env')),false);
});
