import fs from 'node:fs/promises';import {execFile,spawn} from 'node:child_process';import {promisify} from 'node:util';import {chromium} from 'file:///J:/cars/templates/boxcar/node_modules/playwright/index.mjs';
const exec=promisify(execFile),c=process.argv[2],port={autolife:6643,priselci:6648,'ivo-auto':6653}[c],base=`http://127.0.0.1:${port}`,out=`J:/cars/clients/${c}/qa-final`,runtime='J:/cars/audits/2026-09-08/verify/runtime.ps1';let owned,browser;const proof=[];
async function launch(){return new Promise((resolve,reject)=>{const proc=spawn('powershell.exe',['-NoProfile','-File',runtime,'-Client',c,'-Template','carwow','-Port',String(port)],{stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>reject(Error('Runtime launch timed out: '+output)),30000);proc.stdout.on('data',chunk=>{output+=chunk;try{const result=JSON.parse(output);clearTimeout(timer);proc.stdout.destroy();proc.stderr.destroy();proc.unref();resolve(result);}catch{}});proc.on('error',reject);});} try{owned=await launch();for(let n=0;n<45;n++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,1000));}browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [390,1440]){const p=await browser.newPage({viewport:{width,height:900}});p.setDefaultTimeout(15000);p.setDefaultNavigationTimeout(45000);const errors=[];p.on('pageerror',e=>errors.push(e.message));for(const route of ['/','/inventory?price=under-10000','/inventory?price=under-20000']){await p.goto(base+route,{waitUntil:'networkidle'});await p.waitForTimeout(2200);const row={width,route,errors:[...errors]};if(route==='/'){row.visible=await p.locator(width===390?'.mobile-home':'.daynight-home-shell').isVisible();row.logo=await p.locator(width===390?'.mh-hero__logo':'img').first().getAttribute('src');}else{const hrefs=await p.locator('a[href^="/inventory/"]').filter({visible:true}).evaluateAll(es=>[...new Set(es.map(e=>e.getAttribute('href')))]);const all=JSON.parse(await fs.readFile(`${out}/results.json`)).find(x=>x.template==='carwow');const sample=hrefs.filter(x=>x!=='/inventory/map'&&x!=='/inventory/compare');row.hrefs=hrefs;row.count=sample.length;row.expected=route.includes('20000')?13:{autolife:8,priselci:13,'ivo-auto':7}[c];}row.pass=!errors.length&&(route==='/'?row.visible:row.count===row.expected);await p.screenshot({timeout:12000,path:`${out}/${c}/carwow/final-${width}-${proof.length}.png`});proof.push(row);}await p.close();}
await fs.writeFile(`${out}/focused.json`,JSON.stringify(proof,null,2));console.log(c,JSON.stringify(proof));
if(proof.every(x=>x.pass)){const r=JSON.parse(await fs.readFile(`${out}/results.json`)),cw=r.find(x=>x.template==='carwow');for(const row of cw.routes.filter(x=>x.route.includes('price=under-'))){const verified=proof.find(x=>x.width===row.width&&x.route===row.route);row.originalHarnessCount=row.budgetCount;row.budgetCount=verified.count;row.pass=true;row.focusedEvidence='../focused.json';}cw.pass=cw.routes.every(x=>x.pass)&&cw.interactions.every(x=>x.pass);cw.focusedProof='focused.json';await fs.writeFile(`${out}/results.json`,JSON.stringify(r,null,2));await fs.writeFile(`${out}/${c}/carwow/result.json`,JSON.stringify(cw,null,2));}
}finally{await browser?.close();if(owned)await exec('powershell.exe',['-NoProfile','-File',runtime,'-StopPid',String(owned.PID),'-Port',String(port)],{timeout:15000});}



