import fs from 'node:fs/promises';
const jobs=JSON.parse(await fs.readFile('J:/cars/audits/2026-09-07/varna-leads/build-tasks.json')).tasks;
for(const slug of ['automarket-varna','elit-auto-import','legend-auto']){
const root=`J:/cars/clients/${slug}`, job=jobs.find(j=>j.slug===slug), facts=JSON.parse(await fs.readFile(root+'/business-facts.json')), stock=JSON.parse(await fs.readFile(root+'/stock.json'));
const results=JSON.parse(await fs.readFile(root+'/qa-final/results.json'));
const checks=await fs.readFile(root+'/qa-final/build-status.txt','utf8').catch(()=> 'pending');
const lines=[];
for(const [key,port]of [['auto-best',job.ports.autoBest],['modern',job.ports.modern],['carwow',job.ports.carwow]]){
const r=results.find(r=>r.template===key), pass=!!r?.pass;
const build=key==='auto-best'||(key==='modern'?/typecheck=0/.test(checks)&&/\bbuild=0/.test(checks):/carwow-check=0/.test(checks)&&/carwow-build=0/.test(checks));
const p=root+'/'+key+'/.client/project.json',m=JSON.parse(await fs.readFile(p));
m.state=pass&&build?'local-qa-passed':'personalized-validation-pending';m.selectedHome='main';m.offeredHomes=m.availableHomes;m.publicUrl=null;
m.qa={desktop:pass,mobile:pass,identity:true,contactPath:pass,evidence:key==='auto-best'&&slug!=='legend-auto'?`J:/cars/audits/2026-09-08/verify/${slug}/auto-best/result.json`:`../qa-final/${slug}/${key}/result.json`,frameworkChecks:build,...(key==='carwow'?{buildScope:'Build passed before final static and contact-copy corrections; final Svelte check and targeted browser proof are recorded separately.'}:{}),checkedAt:new Date().toISOString(),limits:['Local demo only; no provider or form delivery verified.','Stock is a dated source-backed sample.']};
m.preview={url:`http://127.0.0.1:${port}${key==='modern'?'/cars':'/'}`,state:'stopped-after-verification',...(slug==='legend-auto'?{origins:{api:'http://127.0.0.1:6674',app:'http://127.0.0.1:6675'}}:{})};m.personalization={...(m.personalization||{}),businessFacts:'../business-facts.json',stock:'../stock.json',stockCount:stock.length,sourceTemplateVersion:'2026.09.06-refresh-1'};await fs.writeFile(p,JSON.stringify(m,null,2)+'\n');
lines.push(`| ${key} | ${build?'pass':'pending/fail'} | ${pass?'pass':'pending/fail'} | ${r?.routes?.length||0} | ${m.preview.url} |`);
}
let final=`# ${facts.name} — Fast Skin final verification\n\nMaster version 2026.09.06-refresh-1; Auto Best /, Modern /cars, Carwow /. Independent copies preserve source layouts and interactions. No CRM, deployment, commit or outreach.\n\n| Template | Framework/build | 390/1440 browser | Route states | Assigned local entry |\n|---|---|---|---|---|\n${lines.join('\n')}\n\nAuto Best framework validation is reused because its source is unchanged; browser evidence is from 2026-09-08, including a fresh LEGEND run on safe port 6671. Fresh Modern and Carwow logs are here. Screenshots were visually inspected for rendered main content and header identity; small original logos remain a source-quality limit.\n\nFinal corrections: unconfigured Modern social tiles hidden; Carwow chat launcher uses client logo, financing phone and detail map use dealer configuration. LEGEND Modern directory now contains its real unverified dealer and captured vehicles instead of missing synthetic inventory; feature values retain original text in the required bilingual shape and duplicate city keys were removed. LEGEND Carwow disclaimer CSS was merged into its existing style block. Legacy public proposal HTML was preserved in provenance and replaced by home/contact redirects; Automarket/ELIT build logs predate this static-only correction.\n\nActive public-source identity scan found no prior dealer name/contact remnants; matches are limited to historical Modern test fixtures. Autofixer reports are retained for edited Svelte components.\n\nLimits: ${stock.length} dated sampled vehicles, no live stock feed; forms/chat/finance remain demonstrations with no delivery or approval verified. Generic template vehicle cutouts remain decorative. Public deployment and outreach are not done. Admin-only legacy demo map is outside public Fast Skin scope.\n\n${slug==='legend-auto'?'Safe review ports explicitly assigned: 6671 Auto Best, 6672 Modern, 6673 Carwow; Modern configuration origins 6674/6675. Previous 6666–6668 ports were replaced with parent authorization.\n':''}`;
if(slug!=='legend-auto')final=final.replace(/ LEGEND Modern directory[\s\S]*?LEGEND Carwow disclaimer CSS was merged into its existing style block\./,'').replace('Auto Best framework validation is reused because its source is unchanged; browser evidence is from 2026-09-08, including a fresh LEGEND run on safe port 6671.','Auto Best framework validation and 2026-09-08 browser evidence are reused because its source is unchanged.');
final=final.replace('Automarket/ELIT build logs predate this static-only correction.',slug==='legend-auto'?'Proposal redirects were included in the retry build; the manifest correction followed it.':'The Carwow build log predates this static-only correction.');
await fs.writeFile(root+'/qa-final/FINAL.md',final);
let client=await fs.readFile(root+'/CLIENT.md','utf8');if(slug==='legend-auto')client=`# LEGEND AUTO\n\nProspect Fast Skin; no dealer approval or sale implied. Source: https://legendauto1.mobile.bg/ and local research captures. Phone 0899 877 305; бул. Цар Освободител 289, срещу МАКАО, Варна. Distinct from Avangard despite street-number overlap. Published hours: Monday–Saturday 09:00–17:30; Sunday closed.\n\n${stock.length} source-backed representative vehicles with original dealer photos and logo. Availability requires reconfirmation; no live stock integration. Exclusions and source inconsistencies are recorded in business-facts.json. No verified social channels, email, finance, buyback or import service claims added.\n\nThree independent templates, version 2026.09.06-refresh-1; Auto Best primary.\n`;
client=client.replace(/\n## Final verification 2026-09-08[\s\S]*$/,'');client+='\n## Final verification 2026-09-08\n\nSee qa-final/FINAL.md for exact framework and browser outcomes, final corrections and limitations. Source UI retained. Previews stopped after verification. No public preview, CRM registration or outreach.\n';await fs.writeFile(root+'/CLIENT.md',client);
}
