import fs from 'node:fs/promises';
const root='J:/cars';
const jobs=JSON.parse(await fs.readFile(`${root}/audits/2026-09-07/varna-leads/build-tasks.json`)).tasks;
const records=[];
for(const j of jobs){
 const dir=`${root}/clients/${j.slug}/qa-final`;
 const rows=JSON.parse(await fs.readFile(`${dir}/results.json`));
 const report=await fs.readFile(`${dir}/FINAL.md`,'utf8');
 if(!report.trim())throw Error(`Missing final review: ${j.slug}`);
 for(const template of ['auto-best','modern','carwow']){
  const r=rows.find(x=>x.template===template&&x.client===j.slug);
  if(!r?.pass||r.routes.length<8||r.interactions.length!==2)throw Error(`Not verified: ${j.slug}/${template}`);
  const metadata=JSON.parse(await fs.readFile(`${root}/clients/${j.slug}/${template}/.client/project.json`));
  if(['desktop','mobile','identity','contactPath'].some(key=>metadata.qa?.[key]!==true))throw Error(`Final metadata not accepted: ${j.slug}/${template}`);
  records.push({client:j.slug,name:j.name,template,port:r.port,routeChecks:r.routes.length,interactionChecks:r.interactions.length,pass:r.pass,evidence:`${dir}/results.json`,report:`${dir}/FINAL.md`,state:metadata.state,qa:metadata.qa});
 }
}
if(records.length!==30)throw Error('Expected exactly 30 variants');
await fs.writeFile(`${root}/audits/2026-09-08/verify/final-results.json`,JSON.stringify(records,null,2)+'\n');
const count=records.reduce((n,r)=>n+r.routeChecks,0),interactions=records.reduce((n,r)=>n+r.interactionChecks,0);
let body=`# Varna client demos — final local verification\n\n2026-09-08. **30/30 variants verified for local demo review** across 10 dealerships. Each has one Auto Best, Modern and Carwow project from template version 2026.09.06-refresh-1.\n\n${count} route/viewport checks and ${interactions} main-flow interaction checks at 390px and 1440px. The current client reports link framework/build logs, rendered screenshots, contact checks and any narrower caveats. This is local demo acceptance, not production or message-delivery certification.\n\n| Dealer | Auto Best | Modern | Carwow | Evidence |\n| --- | --- | --- | --- | --- |\n`;
for(const j of jobs){const r=records.filter(x=>x.client===j.slug);body+=`| ${j.name} | Pass · ${r[0].port} | Pass · ${r[1].port} | Pass · ${r[2].port} | [Client report](../../../clients/${j.slug}/qa-final/FINAL.md) |\n`;}
body+=`\n## Coverage and fixes\n\nChecked entry/home, inventory, a real vehicle detail, contact and about/import routes; search/filter, navigation, mobile menu dismissal and focus, gallery where offered, and enquiry/contact destinations. Screenshots were visually inspected instead of trusting DOM text or HTTP status alone.\n\nRepairs include stale Modern sample-directory references and invalid data shapes, duplicate dictionary keys, empty-team prerender configuration, stock-derived search choices/budget content, correct parsing of non-breaking spaces in numeric prices/mileages, readable client logos, inherited chat-brand media, verified financing phone/map links, unconfigured social placeholders, and stale manifests/static proposal pages. Original proposal/concept artifacts are preserved outside the served site. Some earlier successful builds are reused; later scoped logo, copy or static-asset changes have framework checks and rendered evidence as recorded in the individual client reports. This does not certify a freshly built deployable artifact for every final source snapshot.\n\nThe initial sweep remains in this audit folder. Final evidence lives under each client qa-final folder. Initial Vite dependency-optimization issues, smooth-scroll capture timing and a test-induced React attribute mismatch were investigated separately from product defects; final reports identify any retained runtime caveats.\n\n## Local review\n\nThe four owner review previews are retained: [Excellent Auto Best](http://127.0.0.1:6621/), [Excellent Modern](http://127.0.0.1:6622/cars), [Excellent Carwow](http://127.0.0.1:6623/), and [Champion Auto Best](http://127.0.0.1:6631/). Other QA runtimes are stopped after verification. Ports in the table are assigned review addresses, not a claim that all 30 servers run simultaneously. Legend uses safe ports 6671/6672/6673, replacing browser-blocked 6666/6667/6668.\n\nInventory/photos and prices are the dated source snapshots recorded in the client briefs; availability must be confirmed with the dealer. Forms, chat, private accounts, live import feeds and external delivery retain their documented demo limits. Excellent Modern has a recorded lightbox keyboard-focus restoration gap; its image navigation and dismissal work, and menu focus checks pass. Source-derived sample admin/team/partner surfaces are not proof of real staff, customers or partnerships. No public deployment, outreach, commit, push or CRM registration occurred.\n\nShared templates were not overwritten. Reusable defects discovered here should be incorporated into a separately reviewed template refresh; these independent client copies retain their own fixes.\n`;
await fs.writeFile(`${root}/audits/2026-09-08/verify/REPORT.md`,body);
console.log({projects:records.length,routeChecks:count,interactionChecks:interactions});
