import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/elit-auto-import';const f=JSON.parse(await fs.readFile(root+'/business-facts.json'));const stock=JSON.parse(await fs.readFile(root+'/stock.json'));const edit=async(p,fn)=>{p=root+'/'+p;await fs.writeFile(p,fn(await fs.readFile(p,'utf8')));};
await edit('carwow/src/lib/components/detail/desktop/DesktopDetailLocationMap.svelte',s=>s.replace(/const mapUrl =\s*'[^']*';/,'const mapUrl = daynightSite.mapUrl;'));
await fs.writeFile(root+'/carwow/src/lib/data/daynight-videos.ts','export const youtubeChannelUrl = "";\nexport const homeVideos: {id:string;title:string;duration:string;thumbnail:string;url:string}[] = [];\n');
await edit('carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte',s=>s.replace('<section class="home-videos"','{#if homeVideos.length}\n<section class="home-videos"').replace('</section>','</section>\n{/if}'));
async function walk(dir,cb){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())await walk(p,cb);else if(/\.(svelte|tsx?|css|html)$/.test(p)&&!/[.](test|spec)[.]/.test(p)){const s=await fs.readFile(p,'utf8');const n=cb(s,p);if(s!==n)await fs.writeFile(p,n)}}}
await walk(root+'/carwow/src',(s,p)=>s.replace(/\/brand\/daynight-logo[\w.-]*\.png/g,f.logo).replace(/\/assets\/daynight\/(?!.*(?:icon|cutout))[^'"`\s)]+\.(?:jpg|png|webp)/g,m=>m.includes('inventory')?stock[0].images[0]:f.showroom).replace(/https:\/\/www\.google\.com\/maps\/search\/\?api=1&query=[^'"`\s]+/g,f.mapsUrl).replaceAll('Кристиан Кирилов','автокъщата').replaceAll('Пловдив','Варна').replaceAll('Спартак Ауто','ELIT AUTO').replaceAll('Околовръстен път 86','Прилеп 74А').replaceAll('#d71920','#30343b').replaceAll('#a50f15','#17191d').replaceAll('#f5c542','#c7cbd0').replaceAll('#fee2e2','#eef0f2').replaceAll('#fff5f5','#f7f8f9'));
await walk(root+'/modern/apps/web',(s,p)=>s.replace(/\/(?:images\/sell\/day-night-sell-centered-hero-v2\.webp|day-night-contact-hero-v1\.png|lead-import-hero-v1\.png|images\/lease\/day-night-financing-hero-v1\.webp)/g,f.showroom));
for(const p of ['auto-best/src/lib/components/company/AboutHero.svelte','auto-best/src/lib/components/company/ContactIntent.svelte'])await edit(p,s=>s.replace('{#each socialLinks as','{#each socialLinks.filter(link => link.href) as'));
await edit('auto-best/src/lib/components/layout/Header.svelte',s=>s.replace(/(<a \{\.\.\.\{ href: brand\.(instagramUrl|youtubeUrl|facebookUrl) \}\}[^\n]+<\/a>)/g,'{#if brand.$2}$1{/if}'));
// Updated explicit media inventory: preserve all original asset guard checks and exact client asset counts.
const auto=root+'/auto-best';const ref=new Set();await walk(auto+'/src',s=>{for(const m of s.matchAll(/\/(?:assets\/[A-Za-z0-9._@%+~/-]+\.(?:avif|eot|gif|ico|jpe?g|mp4|png|svg|ttf|webm|webp|woff2?)|favicon\.ico)/gi))ref.add(m[0]);return s});const removed=[];async function prune(d){for(const e of await fs.readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())await prune(p);else {const rel='/'+path.relative(auto+'/static',p).replaceAll('\\','/');if(!ref.has(rel)&&rel!=='/favicon.ico'){if(!path.resolve(p).startsWith(path.resolve(auto+'/static')+path.sep))throw Error('outside');await fs.unlink(p);removed.push(rel);}}}}await prune(auto+'/static');await edit('auto-best/scripts/check-assets.mjs',s=>s.replace(/const guardedMediaCount = \d+;/,`const guardedMediaCount = ${ref.size};`));await fs.writeFile(root+'/asset-guard-change.json',JSON.stringify({note:'Client personalization changed the exact asset inventory. Original missing/unreferenced/retired-runtime guards preserved. Only unreferenced files in this newly cloned client static directory removed.',count:ref.size,removed},null,2));
console.log('Media and identity pass complete; Auto exact assets:',ref.size);
