import fs from 'node:fs/promises';import path from 'node:path';
const root='J:/cars/clients/elit-auto-import';let stock=JSON.parse(await fs.readFile(root+'/stock.json'));stock=stock.filter(v=>v.id!=='11731496419950309');await fs.writeFile(root+'/stock.json',JSON.stringify(stock,null,2));const facts=JSON.parse(await fs.readFile(root+'/business-facts.json'));facts.stockCount=stock.length;facts.excluded.push({title:'Subaru Forester 2.5',url:'https://elitautoimport.mobile.bg/obiava-11731496419950309-subaru-forester-2-5',reason:'Description is Скоростна кутия Cvt; gearbox-only advert, not whole car.'});await fs.writeFile(root+'/business-facts.json',JSON.stringify(facts,null,2));
const replacements=[['Day &amp; Night Auto Group',facts.name],['Day & Night Auto Group',facts.name],['DAY NIGHT AUTO GROUP',facts.name],['Day Night Auto Group',facts.name],['Day & Night',facts.shortName],['Day Night Auto',facts.shortName],['Ден и Нощ Ауто Груп',facts.name],['daynight.mobile.bg','elitautoimport.mobile.bg'],['daynightautogroup.bg','elitautoimport.mobile.bg'],['087 982 4625',facts.phoneDisplay],['0877 733 110',facts.phoneDisplay],['0877733110','0887777887'],['0879824625','0887777887'],['+359879824625','+359887777887'],['+359877733110','+359887777887'],['София','Варна'],['Sofia','Varna'],['Студентски град','м-т Пчелина'],['Индустриална зона','м-т Пчелина'],['ул. „Атанас Манчев“ 18','ул. „Прилеп“ 74А'],['ул. Атанас Манчев 18','ул. Прилеп 74А'],['улица Атанас Манчев 18','улица Прилеп 74А'],['Понеделник - Събота: 9:00 - 18:00',facts.hoursNote],['Делнични дни: 9:00 - 18:00 · Неделя: по уговорка',facts.hoursNote],['Собствен лизинг','Условия за покупка'],['собствен лизинг','условия за покупка'],['проверени автомобили','автомобили по обяви'],['Проверени автомобили','Автомобили по обяви']];
const changes=[];async function walk(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.git'].includes(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())await walk(f);else if(/\.(svelte|tsx?|css|html|svg|json)$/.test(f)&&!/[.](test|spec)[.]/.test(f)&&!f.includes('lock')){let s=await fs.readFile(f,'utf8'),n=s;for(const [a,b]of replacements)n=n.replaceAll(a,b);n=n.replace(/https:\/\/(?:www\.)?(?:instagram\.com\/dayandnight_autogroup\/?|facebook\.com\/deninoshtautogroup\/?|youtube\.com\/@kristiankirilov1355\/videos)/g,facts.stockUrl);if(n!==s){await fs.writeFile(f,n);changes.push(f)}}}}
for(const variant of ['auto-best','carwow'])await walk(root+'/'+variant+'/src');for(const folder of ['apps/web','packages/marketplace','packages/marketplace-ui','packages/marketplace-domain','packages/seo','packages/internationalization'])await walk(root+'/modern/'+folder);
for(const variant of ['auto-best','carwow','modern']){const pub=root+'/'+variant+(variant==='modern'?'/apps/web/public':'/static');await fs.mkdir(pub+'/assets/elit',{recursive:true});for(const v of stock)for(const image of v.images)await fs.copyFile(root+'/assets/'+path.basename(image),pub+image);for(const name of ['logo.png','cover.png'])await fs.copyFile(root+'/assets/'+name,pub+'/assets/elit/'+name);}
const edit=async(f,fn)=>{const p=root+'/'+f;await fs.writeFile(p,fn(await fs.readFile(p,'utf8')));};
await edit('auto-best/src/lib/config/brand.ts',s=>s.replace(/youtubeUrl: '[^']*'/,`youtubeUrl: ''`).replace(/instagramUrl: '[^']*'/,`instagramUrl: ''`).replace(/facebookUrl: '[^']*'/,`facebookUrl: ''`).replace(/logo: '[^']*'/,`logo: '${facts.logo}'`));
await edit('auto-best/src/lib/data/inventory.ts',s=>s.replace('  image: string;','  image: string;\n  gallery: string[];\n  description: string;\n  sourceUrl: string;').replace(/export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`export const featuredVehicles: Vehicle[] = ${JSON.stringify(stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,description:v.description+' '+v.mileageNote,sourceUrl:v.sourceUrl,category:v.category,body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:v.mileageLabel,mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:['4x4','Навигация','Парктроник','Подгряване на седалки'].filter(x=>v.features.some(f=>f.includes(x==='Подгряване на седалки'?'Подгряване':x))),condition:'used',priceEur:v.priceEur,href:'/listing-detail-v1/'+(i+1)})),null,2)};`));
await edit('auto-best/src/lib/data/listing.ts',s=>s.replace(/makes: \[[^\n]+/,`makes: ['', ...new Set(featuredVehicles.map(v => v.make))],`).replace(/bodies: \[[^\n]+/,`bodies: ['', ...new Set(featuredVehicles.map(v => v.body))],`).replace(/fuels: \[[^\n]+/,`fuels: ['', ...new Set(featuredVehicles.map(v => v.fuel))],`).replace(/transmissions: \[[^\n]+/,`transmissions: ['', 'Автоматик', 'Ръчна'],`).replace(/years: \[[^\n]+/,`years: ['', '2010', '2013', '2014', '2015', '2016', '2017', '2021'],`).replace(/prices: \[[^\n]+/,`prices: ['', '10000', '15000', '20000', '25000', '30000'],`));
await edit('auto-best/src/lib/components/company/ShowroomMap.svelte',s=>s.replace("  import { showroomCoordinates } from '$data/company';",'').replace(/const mapEmbedUrl = [^;]+;/,`const mapEmbedUrl = ${JSON.stringify(facts.mapsEmbedUrl)};`));
await edit('auto-best/src/routes/listing-detail-v1/[id]/+page.svelte',s=>s.replace("  const phoneLinkAttributes",'  let galleryIndex = $state(0);\n  const phoneLinkAttributes').replace('src={data.vehicle.image}','src={data.vehicle.gallery[galleryIndex % data.vehicle.gallery.length]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<button type="button" class="dn-detail-gallery__count" aria-label="Следваща снимка" onclick={() => galleryIndex += 1}>{galleryIndex % data.vehicle.gallery.length + 1} / {data.vehicle.gallery.length}</button>').replace(/\{data.vehicle.title\} е част от актуалната селекция[\s\S]*?екипа за потвърдени данни за състоянието, наличността и следващите стъпки\./,'{data.vehicle.description}').replace('Поискайте информация\n                  </a>','Поискайте информация\n                  </a>\n                  <a href={data.vehicle.sourceUrl} target="_blank" rel="noreferrer">Оригинална обява и пълни данни</a>'));
await edit('auto-best/src/app.css',s=>s.replace('--dn-red: #c40101','--dn-red: #30343b').replace('--dn-red-hover: #a90000','--dn-red-hover: #17191d'));
// Keep sections, replace unsupported services with confirmed service topics.
await edit('auto-best/src/lib/data/company.ts',s=>s.replaceAll('Условия за покупка','Доставка в страната').replaceAll('Лизинг','Доставка').replaceAll('Обсъдете лизинг','Обсъдете доставка').replaceAll('Условия според избрания автомобил.','Доставка със собствен транспорт — уточнете условията.').replaceAll('Оценка за бартер','Проверка в сервиз').replaceAll('Бартер и оценка','Проверка в сервиз').replaceAll("label: 'Бартер'","label: 'Проверка'").replaceAll('Предложете своя автомобил за индивидуална оценка.','Възможност за проверка в сервиз по Ваш избор.').replaceAll('Разкажете ни за автомобила, който искате да предложите, и поискайте индивидуална оценка.','Уточнете възможността за проверка в избран от Вас сервиз.'));
// Media ownership: replace source dealer photos; decorative vehicle cutouts remain template artwork.
await (async()=>{const dir=root+'/auto-best/src';async function media(d){for(const e of await fs.readdir(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())await media(f);else if(/\.(svelte|ts|css)$/.test(f)){let s=await fs.readFile(f,'utf8');s=s.replace(/\/assets\/images\/lead\/day-night-(?!cutout)[\w.-]+\.(?:webp|png|jpg)/g,m=>m.includes('logo')?facts.logo:facts.showroom);await fs.writeFile(f,s)}}}await media(dir)})();
await edit('auto-best/src/lib/data/videos.ts',s=>s.replace(/export const featuredVideos:[\s\S]*/,`export const featuredVideos: readonly FeaturedVideo[] = [];\n`));
await edit('auto-best/src/lib/components/home/VideoSection.svelte',s=>s.replace('<section class="dn-videos"','{#if featuredVideos.length}\n<section class="dn-videos"').replace('</section>','</section>\n{/if}').replace('Избрани автомобилни видеа с Кристиан Кирилов.','Видеа от автокъщата.'));
await edit('carwow/src/lib/data/daynight-site.ts',s=>s.replace(/logoLight: '[^']*'/,`logoLight: '${facts.logo}'`).replace(/logoDark: '[^']*'/,`logoDark: '${facts.logo}'`).replace(/inventoryCount: \d+/,`inventoryCount: ${stock.length}`).replace(/mapUrl:\s*'[^']*'/,`mapUrl: ${JSON.stringify(facts.mapsUrl)}`).replace(/heroSubtitle: '[^']*'/,`heroSubtitle: 'Внос от Европа, САЩ и Япония. Автомобили във Варна.'`));
await edit('carwow/src/lib/data/daynight-current-inventory.ts',s=>s.slice(0,s.indexOf('export const currentDayNightListings'))+`export const currentDayNightListings: CurrentDayNightListing[] = ${JSON.stringify(stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:v.priceEur+' €',priceBgn:(v.priceEur*1.95583).toFixed(2)+' лв.',status:'По обява',date:v.date,mileage:v.mileageLabel,color:v.color,fuel:v.rawFuel,power:v.powerHp+' к.с.',transmission:v.transmission==='Автоматик'?'Автоматична':'Ръчна',body:v.category,features:v.features.filter(Boolean),image:v.images[0]})),null,2)};\n`);
await fs.writeFile(root+'/carwow/src/lib/data/elit-stock.ts',`export const elitStock = ${JSON.stringify(stock,null,2)};\n`);
await edit('carwow/src/lib/data/daynight-vehicles.ts',s=>"import { elitStock } from './elit-stock';\n"+s.replace('const listingToVehicle = (listing: CurrentDayNightListing): Car => {','const listingToVehicle = (listing: CurrentDayNightListing): Car => {\n const source = elitStock.find(v => v.id === listing.id)!;').replace('gallery: [listing.image]','gallery: source.images').replace(/monthly: `[^`]+`/,'monthly: \'Условия по запитване\'').replace(/description: `[^`]+`/,'description: source.description + " " + source.mileageNote').replace('`DN-','`ELIT-'));
await edit('carwow/src/lib/data/daynight-reviews.ts',s=>s.replace(/export const daynightReviews = \[[\s\S]*?\] satisfies DayNightReview\[\];/,`export const daynightReviews: DayNightReview[] = [];`).replace('`${daynightReviewCount} отзива`',"'Няма потвърдени отзиви'"));
const cfg={accent:facts.accent,address:facts.address,city:facts.city,contactUrl:facts.phoneHref,country:facts.country,countryCode:'BG',currency:'EUR',email:'',heroPath:facts.showroom,locale:'bg-BG',logoPath:facts.logo,mapsEmbedUrl:facts.mapsEmbedUrl,mapsUrl:facts.mapsUrl,name:facts.name,phoneDisplay:facts.phoneDisplay,phoneHref:facts.phoneHref,shortName:facts.shortName,slug:'elit-auto-import',socialLinks:{},staticDemoMode:true,tagline:'Внос от Европа, САЩ и Япония. Автомобили във Варна.'};await edit('modern/packages/marketplace/lead-site.ts',s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${JSON.stringify(cfg,null,2)};`));
const listings=stock.map((v,i)=>({id:'elit-'+v.id,slug:'elit-'+v.id,category:'car',dealerOrgId:'dealer-elit-auto',status:'active',title:v.title,description:v.description+' '+v.mileageNote+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:facts.city,region:'м-т Пчелина',country:facts.country},features:[],spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Coupe:'coupe',Sedan:'sedan'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',enginePowerHp:v.powerHp,colorExterior:v.color},seller:{id:'dealer-elit-auto',type:'dealer',displayName:facts.name,verificationStatus:'unverified',city:facts.city},publishedAt:new Date(Date.UTC(2026,8,7,10,0,-i)).toISOString(),promoted:false}));await edit('modern/packages/marketplace-domain/testing/mock-data.ts',s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${JSON.stringify(listings,null,2)};`));
for(const [src,dest]of [['logo.png','lead-logo.png'],['cover.png','lead-hero.jpg']])await fs.copyFile(root+'/assets/'+src,root+'/modern/apps/web/public/'+dest);
await fs.writeFile(root+'/personalization.json',JSON.stringify({changedIdentityFiles:changes,stockCount:stock.length,scope:'Actual template data/media/copy boundaries; layout preserved.'},null,2));console.log('Personalized three variants:',stock.length,'vehicles');
