import fs from 'node:fs/promises';import path from 'node:path';
const root=import.meta.dirname,f=JSON.parse(await fs.readFile(`${root}/business-facts.json`)),stock=JSON.parse(await fs.readFile(`${root}/stock.json`));
const read=p=>fs.readFile(path.join(root,p),'utf8');const write=(p,s)=>fs.writeFile(path.join(root,p),s);const json=JSON.stringify;
const changes=[];
async function edit(p,fn){const old=await read(p),s=fn(old);if(old!==s){await write(p,s);changes.push(p);}}
async function walk(dir){let out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isSymbolicLink()||['node_modules','.next','.svelte-kit','.git','.vercel','generated'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
const replacements=[['Day &amp; Night Auto Group',f.name],['Day & Night Auto Group',f.name],['DAY NIGHT AUTO GROUP',f.name],['Day Night Auto Group',f.name],['Day &amp; Night',f.name],['Day & Night',f.name],['Day Night Auto',f.name],['Ден и Нощ Ауто Груп',f.name],['087 982 4625',f.phoneDisplay],['0877 733 110',f.phoneDisplay],['0877733110',f.phone],['0879824625',f.phone],['+359877733110','+359899877305'],['+359879824625','+359899877305'],['daynight.mobile.bg','legendauto1.mobile.bg'],['daynightautogroup.bg','legendauto1.mobile.bg'],['ул. „Атанас Манчев“ 18, Студентски град',f.address],['Студентски град, ул. Атанас Манчев 18',f.address],['ул. Атанас Манчев 18',f.address],['Студентски град','бул. Цар Освободител 289'],['Studentski grad','Tsar Osvoboditel 289'],['София','Варна'],['Sofia','Varna'],['собствен лизинг','условия за покупка'],['Собствен лизинг','Условия за покупка'],['Внос по заявка','Запитване за автомобил'],['Внос по поръчка','Избор на автомобил'],['внос по заявка','запитване за автомобил'],['внос по поръчка','избор на автомобил']];
for(const variant of ['auto-best','carwow','modern']){
const dirs=variant==='modern'?['apps/web','packages/marketplace','packages/marketplace-domain','packages/marketplace-ui','packages/seo']:['src'];
for(const dir of dirs)for(const file of await walk(path.join(root,variant,dir))){if(!/\.(svelte|tsx?|css|html|json|svg)$/.test(file)||/\.(test|spec)\./.test(file))continue;await edit(path.relative(root,file),s=>{for(const [a,b]of replacements)s=s.replaceAll(a,b);return s;});}
const dest=path.join(root,variant,variant==='modern'?'apps/web/public/assets/legend-auto':'static/assets/legend-auto');await fs.mkdir(dest,{recursive:true});for(const name of await fs.readdir(`${root}/assets`))if(/\.(png|webp)$/.test(name))await fs.copyFile(`${root}/assets/${name}`,`${dest}/${name}`);
}
// Auto Best: existing typed identity and inventory boundaries.
await write('auto-best/src/lib/config/brand.ts',`export const brand = ${json({name:f.name,shortName:f.name,city:f.city,addressLine:f.address,address:`${f.address}, ${f.city}`,phone:f.phoneDisplay,phoneHref:f.phoneHref,appointment:f.hours,logo:f.logo,youtubeUrl:'',facebookUrl:'',instagramUrl:'',mapsUrl:f.mapsUrl,mapsEmbedUrl:f.mapsEmbedUrl},null,2)} as const;\n`);
const equipment=v=>[['4x4','4x4'],['Навигация','Навигация'],['Парктроник','Парктроник'],['Подгряване на седалките','Подгряване на седалки'],['Безключово палене','Безключов достъп']].filter(([s])=>v.features.some(x=>x.includes(s))).map(([,t])=>t);
await edit('auto-best/src/lib/data/inventory.ts',s=>s.replace('  image: string;','  image: string;\n  gallery: string[];\n  description: string;\n  sourceUrl: string;').replace(/export const featuredVehicles: Vehicle\[\] = \[[\s\S]*?\n\];/,`export const featuredVehicles: Vehicle[] = ${json(stock.map((v,i)=>({id:i+1,image:v.images[0],gallery:v.images,description:v.description,sourceUrl:v.sourceUrl,category:v.bodyBg,body:v.body,make:v.make,title:v.title,year:String(v.year),yearNumber:v.year,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,mileageKm:v.mileageKm,fuel:v.fuel,transmission:v.transmission,equipment:equipment(v),condition:'used',priceEur:v.priceEur,href:`/listing-detail-v1/${i+1}`})),null,2)};`));
await edit('auto-best/src/lib/data/listing.ts',s=>{for(const [key,values] of Object.entries({makes:['',...new Set(stock.map(v=>v.make))],bodies:['',...new Set(stock.map(v=>v.body))],fuels:['',...new Set(stock.map(v=>v.fuel))],transmissions:['','Автоматик','Ръчна'],years:['',...new Set(stock.map(v=>String(v.year)))],prices:['','3000','5000','10000','15000','20000','30000','40000'],mileages:['','50000','100000','150000','200000','300000']}))s=s.replace(new RegExp(`${key}: \\[[^\\]]*\\]`),`${key}: ${json(values)}`);return s;});
await edit('auto-best/src/lib/components/company/ShowroomMap.svelte',s=>s.replace("  import { showroomCoordinates } from '$data/company';",'').replace(/const mapEmbedUrl = .*?;/,`const mapEmbedUrl = brand.mapsEmbedUrl;`));
await edit('auto-best/src/lib/data/company.ts',s=>s.replace(/export const showroomCoordinates = \{[\s\S]*?\} as const;/,'').replace(/export const companyServices: CompanyService\[\] = \[[\s\S]*?\n\];/,`export const companyServices: CompanyService[] = ${json([{index:'01',icon:'inspection',title:'Оглед във Варна',description:'Обадете се за наличност и удобен час.',href:'/contact?topic=inspection',cta:'Уговорете оглед'},{index:'02',icon:'import',title:'Транспорт в страната',description:'В обявите е посочен транспорт до всяка точка на страната. Уточнете условията.',href:'/contact',cta:'Попитайте за транспорт'},{index:'03',icon:'leasing',title:'Условия за покупка',description:'Обсъдете конкретната цена и документите за автомобила.',href:'/contact',cta:'Свържете се с нас'},{index:'04',icon:'trade-in',title:'Избор на автомобил',description:'Сравнете публикуваните автомобили и техните характеристики.',href:'/listing-grid',cta:'Вижте автомобилите'}],null,2)};`));
// Keep gallery geometry; make the existing image indicators operate on real photos.
await edit('auto-best/src/routes/listing-detail-v1/[id]/+page.svelte',s=>s.replace('  const phoneLinkAttributes',"  let photoIndex = $state(0);\n  const phoneLinkAttributes").replace('src={data.vehicle.image}','src={data.vehicle.gallery[photoIndex % data.vehicle.gallery.length]}').replace('<div class="dn-detail-gallery__count" aria-hidden="true">\n                  <span></span><span></span><span></span>\n                </div>','<div class="dn-detail-gallery__count" aria-label="Снимки на автомобила">\n                  {#each data.vehicle.gallery as photo, index (photo)}<button type="button" aria-label={`Снимка ${index + 1}`} aria-pressed={photoIndex === index} onclick={() => photoIndex = index}>{index + 1}</button>{/each}\n                </div>').replace(/\{data.vehicle.title\} е част от актуалната селекция[\s\S]*?следващите стъпки\./,'{data.vehicle.description}').replace('                  <a class="dn-detail-inline-action"','                  <a href={data.vehicle.sourceUrl} target="_blank" rel="noreferrer">Оригинална обява в Mobile.bg</a>\n                  <a class="dn-detail-inline-action"'));
// Social links are rendered only when verified; no inherited social profiles.
for(const rel of ['company/AboutHero.svelte','company/ContactIntent.svelte'])await edit(`auto-best/src/lib/components/${rel}`,s=>s.replaceAll('{#each socialProfiles as profile (profile.name)}','{#each socialProfiles.filter(profile => profile.href) as profile (profile.name)}').replaceAll('{#each socialPlatforms as platform (platform.name)}','{#each socialPlatforms.filter(platform => platform.href) as platform (platform.name)}').replaceAll('Последвайте ни','LEGEND AUTO').replaceAll('Социални мрежи','Контакт по телефона'));
await edit('auto-best/src/lib/components/layout/Header.svelte',s=>s.replace(/(\s*<a \{\.\.\.\{ href: brand\.(instagram|youtube|facebook)Url \}\}[^\n]+<\/a>)/g,'{#if brand.$2Url}$1{/if}'));
// Media section keeps its source grid and card styles, now linking genuine stock photos.
await edit('auto-best/src/lib/components/home/VideoSection.svelte',s=>{const styles=s.slice(s.indexOf('<style>'));return `<script lang="ts">\n import { featuredVehicles } from '$data/inventory';\n import Icon from '$components/ui/Icon.svelte';\n</script>\n<section class="dn-videos" aria-labelledby="videos-title"><div class="container"><div class="dn-videos__panel"><div class="dn-videos__heading dn-home-section-heading"><h2 id="videos-title" class="dn-home-section-title">От нашите обяви</h2><p>Оригинални снимки на автомобили от LEGEND AUTO.</p><a class="dn-videos__channel dn-home-section-action" href="/listing-grid">Всички автомобили <Icon name="arrow-right" size={16}/></a></div><div class="dn-videos__grid">{#each featuredVehicles.slice(0,3) as vehicle (vehicle.id)}<article class="dn-video-card"><div class="dn-video-card__media"><a class="dn-video-card__play" href={vehicle.href}><img src={vehicle.image} alt={vehicle.title} width="720" height="404" loading="lazy"/></a></div><div class="dn-video-card__content"><h3>{vehicle.title}</h3><div class="dn-video-card__actions"><a href={vehicle.href}>Снимки и подробности <Icon name="arrow-right" size={16}/></a></div></div></article>{/each}</div></div></div></section>\n${styles}`;});
await edit('auto-best/src/lib/data/videos.ts',s=>s.replace(/export const featuredVideos:[\s\S]*/, 'export const featuredVideos: readonly FeaturedVideo[] = [];\n'));
// Carwow uses the same stock with the existing mapper and public routes.
await edit('carwow/src/lib/data/daynight-current-inventory.ts',s=>s.slice(0,s.indexOf('export const currentDayNightListings')).replace('image: string;','image: string;\n gallery: string[];\n description: string;')+`export const currentDayNightListings = ${json(stock.map(v=>({id:v.id,title:v.title,sourceUrl:v.sourceUrl,priceEur:`${v.priceEur.toLocaleString('bg-BG')} €`,priceBgn:`${(v.priceEur*1.95583).toFixed(2)} лв.`,status:'Публикувана обява',date:v.date,mileage:`${v.mileageKm.toLocaleString('bg-BG')} км`,color:v.color,fuel:v.fuel,power:v.powerHp?`${v.powerHp} к.с.`:'Не е посочена',transmission:v.transmission,body:v.bodyBg,features:v.features,image:v.images[0],gallery:v.images,description:v.description})),null,2)} satisfies CurrentDayNightListing[];\n`);
await edit('carwow/src/lib/data/daynight-vehicles.ts',s=>s.replace('gallery: [listing.image]','gallery: listing.gallery').replace(/monthly: `[^`]+`/,'monthly: \'Условия по запитване\'').replace(/description: `[^`]+`/,'description: listing.description').replace("lot: `DN-","lot: `LA-").replace("doors: body === 'Купе' ? 3 : 5","doors: listing.features.some(feature => /4\\(5\\) Врати/.test(feature)) ? 5 : 0"));
await edit('carwow/src/lib/data/daynight-site.ts',s=>s.replace(/mapUrl:[\s\S]*?,\s*mapLabel:/,`mapUrl: ${json(f.mapsUrl)},\n mapLabel:`).replace(/inventoryCount: \d+/,`inventoryCount: ${stock.length}`).replace(/logoLight: '[^']+'/,`logoLight: '${f.logo}'`).replace(/logoDark: '[^']+'/,`logoDark: '${f.logo}'`).replace(/heroSubtitle: '[^']+'/,"heroSubtitle: 'Автомобили във Варна · бул. Цар Освободител 289, срещу МАКАО'"));
const infoCards=[{name:'Автомобили',label:'Публикувани предложения',text:'Разгледайте автомобилите на LEGEND AUTO. Потвърдете наличността преди посещение.'},{name:'Оглед',label:'Предварителна уговорка',text:'Обадете се на 0899 877 305 за автомобила и удобен час за оглед.'},{name:'Транспорт',label:'До всяка точка на страната',text:'Транспортът е посочен в обявите на LEGEND AUTO. Уточнете цената и условията по телефона.'}].map((v,i)=>({...v,id:`info-${i}`,avatar:f.logo}));
await edit('carwow/src/lib/data/daynight-reviews.ts',s=>s.slice(0,s.indexOf('export const daynightReviews'))+`export const daynightReviews = ${json(infoCards,null,2)} satisfies DayNightReview[];\nexport const daynightReviewCount = daynightReviews.length;\nexport const daynightReviewCountLabel = 'Информация за покупката';\nexport const daynightReviewLinkLabel = 'Полезна информация';\n`);
await edit('carwow/src/lib/components/home/desktop/DesktopHomeReviews.svelte',s=>s.replace(/const reviews: Review\[\] = \[[\s\S]*?\n\t\];/,`const reviews: Review[] = ${json(infoCards.map(v=>({id:v.id,description:v.text,avatar:v.avatar,name:v.name,meta:v.label})),null,2)};`).replace(/const starIds = \[[^\]]*\] as const;/,'const starIds: string[] = [];'));
await edit('carwow/src/lib/data/daynight-videos.ts',()=>`export const youtubeChannelUrl = 'https://legendauto1.mobile.bg/';\nexport const homeVideos = ${json(stock.slice(0,3).map(v=>({id:v.id,title:v.title,duration:'',thumbnail:v.images[0],url:v.sourceUrl})),null,2)} as const;\n`);
await edit('carwow/src/lib/components/home/desktop/DesktopHomeVideos.svelte',s=>s.replaceAll('LEGEND AUTO в YouTube','От нашите обяви').replaceAll('Всички видеа','Всички обяви').replace(/LEGEND AUTO в <img[^>]+\/>/,'От нашите обяви').replace(/<iframe[\s\S]*?<\/iframe>/,'<a href={video.url} target="_blank" rel="noreferrer"><img src={video.thumbnail} alt={video.title} width="480" height="270" loading="lazy" /></a>').replace('.home-video__image iframe','.home-video__image img').replace('min-height: 200px; border: 0;','min-height: 200px; border: 0; object-fit: cover;'));
// Modern retains the whole monorepo and static demo provider.
const config={...f,countryCode:'BG',currency:'EUR',contactUrl:f.phoneHref,heroPath:stock[0].images[0],locale:'bg-BG',logoPath:f.logo,slug:'legend-auto',staticDemoMode:true,tagline:'Автомобили във Варна. Огледи с предварителна уговорка.'};
const allowed=['accent','address','city','contactUrl','country','countryCode','currency','email','heroPath','locale','logoPath','mapsEmbedUrl','mapsUrl','name','phoneDisplay','phoneHref','shortName','slug','socialLinks','staticDemoMode','tagline'];
await edit('modern/packages/marketplace/lead-site.ts',s=>s.replace(/export const leadSite: LeadSiteConfig = \{[\s\S]*?\n\};/,`export const leadSite: LeadSiteConfig = ${json(Object.fromEntries(allowed.map(k=>[k,config[k]])),null,2)};`));
const listings=stock.map((v,i)=>({id:`legend-${v.id}`,slug:`legend-${v.id}`,category:'car',dealerOrgId:'dealer-legend-auto',status:'active',title:v.title,description:v.description+' '+v.vat+'. Оригинална обява: '+v.sourceUrl,price:{amount:v.priceEur,currency:'EUR'},priceType:'fixed',images:v.images.map(url=>({url,alt:v.title})),badges:['used'],location:{city:f.city,region:f.address,country:f.country},features:v.features,spec:{make:v.make,model:v.model,year:v.year,bodyType:({SUV:'suv',Hatchback:'hatchback',Wagon:'wagon',Coupe:'coupe',Sedan:'sedan'})[v.body],fuelType:({'Дизел':'diesel','Бензин':'gasoline','Хибрид':'hybrid','Електрически':'electric'})[v.fuel],transmission:v.transmission==='Автоматик'?'automatic':'manual',mileageValue:v.mileageKm,mileageUnit:'km',...(v.powerHp?{enginePowerHp:v.powerHp}:{}),colorExterior:v.color},seller:{id:'dealer-legend-auto',type:'dealer',displayName:f.name,verificationStatus:'unverified',city:f.city},publishedAt:new Date(Date.UTC(2026,8,7,0,0,-i)).toISOString(),promoted:false}));
await edit('modern/packages/marketplace-domain/testing/mock-data.ts',s=>s.replace(/export const mockListings: VehicleListing\[\] = \[[\s\S]*?\n\];/,`export const mockListings: VehicleListing[] = ${json(listings,null,2)};`));
await fs.writeFile(`${root}/personalization-changes.json`,json(changes,null,2));console.log(`${changes.length} files personalized, ${stock.length} vehicles per variant`);
