import fs from 'node:fs/promises';import crypto from 'node:crypto';
const root=import.meta.dirname;const selected=JSON.parse(await fs.readFile(`${root}/research/selected.json`));
const excluded=selected.filter(c=>/Suzuki Celerio|Peugeot 308/.test(c.title));
const stock=[];const media=[];
for(const [i,c] of selected.filter(c=>!excluded.includes(c)).entries()){
const p=c.parts.find(p=>p.cls==='params').text;const info=c.parts.find(p=>p.cls==='info').text;
const year=Number(p.match(/\b(20\d{2}|19\d{2})\b/)[0]);const mileageKm=Number(p.match(/г\.\s*([\d ]+)\s*км/)[1].replaceAll(' ',''));
const rawFuel=p.match(/Електрически|Хибриден|Дизелов|Бензинов/)[0];const fuel=({'Хибриден':'Хибрид','Дизелов':'Дизел','Бензинов':'Бензин'})[rawFuel]||rawFuel;
const bodyBg=p.match(/(Джип|Хечбек|Комби|Седан|Купе|Ван)$/)[0];const body=({Джип:'SUV',Хечбек:'Hatchback',Комби:'Wagon',Седан:'Sedan',Купе:'Coupe',Ван:'Minivan'})[bodyBg];
const color=p.split('км')[1].split(rawFuel)[0].trim();const transmission=p.includes('Автоматична')?'Автоматик':'Ръчна';
const priceEur=Number(c.parts[0].text.match(/([\d ]+)\s*€/)[1].replaceAll(' ',''));const powerHp=Number(p.match(/(\d+) к\.с\./)?.[1])||null;
const features=(info.split('Особености - ')[1]||'').split(', ').filter(Boolean);const unique=[...new Map(c.gallery.map(u=>[u.split('/').at(-1),u])).values()].slice(0,5);const images=[];
for(const [j,url] of unique.entries()){const file=`vehicle-${String(i+1).padStart(2,'0')}-${j+1}.webp`;const res=await fetch(url);if(!res.ok)throw Error(`${res.status} ${url}`);const bytes=Buffer.from(await res.arrayBuffer());await fs.writeFile(`${root}/assets/${file}`,bytes);images.push(`/assets/legend-auto/${file}`);media.push({file,sourceUrl:url,listing:c.url,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}
stock.push({id:c.url.match(/obiava-(\d+)/)[1],title:c.title,make:c.title.split(' ')[0],model:c.title.split(' ')[1],year,date:p.split(' г.')[0],mileageKm,priceEur,fuel,transmission,powerHp,color,body,bodyBg,features,images,sourceUrl:c.url,vat:'Не се начислява ДДС',capturedAt:new Date().toISOString(),description:`${c.title}. ${year} г., ${mileageKm.toLocaleString('bg-BG')} км, ${fuel.toLowerCase()}, ${transmission.toLowerCase()} скоростна кутия. Публикувана оферта от LEGEND AUTO. Потвърдете наличността и характеристиките преди оглед.`});console.log(`${stock.length}: ${c.title} (${images.length} photos)`);
}
const query=encodeURIComponent('LEGEND AUTO, бул. Цар Освободител 289, Варна');
const facts={name:'LEGEND AUTO',shortName:'LEGEND AUTO',legalNameAsAdvertised:'ЛЕДЖЕНТ АУТО ЕООД',city:'Варна',country:'България',address:'бул. Цар Освободител 289, срещу МАКАО',phone:'0899877305',phoneDisplay:'0899 877 305',phoneHref:'tel:+359899877305',email:'',hours:'Понеделник – събота: 09:00–17:30 · Неделя: почивен ден',hoursSource:'https://legendauto1.mobile.bg/about',hoursNote:'Contact page has no structured hours; About page supplies explicit schedule. Confirm before visit.',sourceUrl:'https://legendauto1.mobile.bg/',contactUrl:'https://legendauto1.mobile.bg/contacts',socialLinks:{},socialNote:'No matched official social links were found on the dealer profile or targeted phone/name search.',accent:'#c42136',logo:'/assets/legend-auto/logo-original.png',logoSource:'https://cdn2.focus.bg/mobile/images/houseslogos/h14769822911961758.pic',logoNote:'Original low-resolution marketplace logo retained unchanged; red lettering on a light background. No invented logo.',mapsUrl:`https://www.google.com/maps/search/?api=1&query=${query}`,mapsEmbedUrl:`https://maps.google.com/maps?q=${query}&output=embed`,services:['Продажба на автомобили','Оглед с предварителна уговорка','Транспорт до всяка точка на страната (според обявите)'],unverifiedServices:['Собствен лизинг','Изкупуване и бартер','Внос по поръчка'],identityNote:'Distinct legendauto1 profile and 0899877305 phone; not Avangard despite shared street number.',capturedAt:new Date().toISOString(),sampleSize:stock.length,advertCount:33,excluded:excluded.map(c=>({title:c.title,url:c.url,reason:c.title.startsWith('Suzuki')?'Title says automatic but specification says manual.':'Advert lists 2000 hp, inconsistent with model; omitted pending dealer clarification.'}))};
await fs.writeFile(`${root}/stock.json`,JSON.stringify(stock,null,2));await fs.writeFile(`${root}/business-facts.json`,JSON.stringify(facts,null,2));await fs.writeFile(`${root}/assets/provenance.json`,JSON.stringify({capturedAt:facts.capturedAt,logo:{file:'logo-original.png',sourceUrl:facts.logoSource,unchanged:true},vehicles:media,notes:['Original source watermarks retained.','Dealer stock snapshot, not an automatic inventory feed.','Existing template decorative cutouts remain decorative, not advertised stock.']},null,2));
